### ISSUE TITLE
Static end-to-end test for maps integration

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#1004]
# Context
*Early* proof that the proposed end-to-end Akvo Maps + Akvo Lumen integration architecture actually works would be desirable.

# Problem or idea
We have assumed, so far, that the architecture we have designed to serve more advanced maps in Akvo Lumen will work when all the component pieces are put together. Rather than assume, we should create a static fixture, of sorts, which proves the entire pipeline works as expected.

# Solution or next step
Lumen client calls Lumen backend endpoint to send MapConfig to Windshaft which returns map tiles to the client. Demonstrate this pipeline with fixed data/fixed logic.

**Comment by dlebrero** [comment]
Expected headers: X-DB-HOST, X-DB-USER, X-DB-PASSWORD, X-DB-PORT

**Comment by peeb** [comment]
Thanks Dan ^^

**Comment by dlebrero** [comment]
Added X-DB-LAST-UPDATE header for the Lumen Backend to control the cache.

It can be any number, but:

* It cannot be bigger than System.currentTimeMillis
* It must be monotonically increasing

Last update in the DB still looks like the best candidate.

**Comment by kardan** [comment]
Does the client need to know the database name for Winshaft to know what db to use? Thinking about https://github.com/akvo/akvo-lumen/blob/a37d286a980f3bb4f62afd5f2c4eab0155bd37fb/client/src/components/demo/AkvoMapsDemo.jsx#L9 which is used to render at https://github.com/akvo/akvo-lumen/blob/a37d286a980f3bb4f62afd5f2c4eab0155bd37fb/client/src/components/demo/AkvoMapsDemo.jsx#L95.

**Comment by peeb** [comment]
Yes it does ^^ @kardan

**Comment by dlebrero** [comment]
@peeb @kardan I thought about removing it from the url and add it as yet another header in the POST request, as it is something that cannot be changed after the map has been created. It will also leak less details to the client, so a little bit more decoupled.

Should we go for a X-DB-NAME header? By the way, this is the last header that we add before reconsidering the Windshaft interface.

**Comment by kardan** [comment]
I'm not sure "leaking" the database name to the client is a critical thing, but It does feel a bit odd. If we add X-DB-NAME header, will that be used from the client when getting tiles? If so I guess we could if we want encrypt the value while it's in the clients hands. But then, I'm not really sure if this is something to stress over before we have maps that work :-)

**Comment by dlebrero** [comment]
We have removed the db name from the url as part of https://github.com/akvo/akvo-maps/issues/18. 

From version d5bb0ba0 of the Windshaft docker image, it will expect a X-DB-NAME header on the POST request to create the map. After that, the client just needs to send the layer group id.

@kardan Do you want me to create a new issue on Lumen to update the Windshaft version? Or do you want to add this comment into some issue?
