### ISSUE TITLE
Encrypt db credentials when making a new request for a map

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#1005]
# Context
We agreed on the idea of sending the DB credentials to Windshaft as part of the `POST` request, in the form of HTTP header fields. We think this is a valid approach since the 2 processes (JVM and Node) are in a private network. We can increase the security by encrypting those credentials using symmetric encryption (shared secret).

# Problem or idea
The increased usage of externally hosted solutions (e.g. error reporting on sentry.io) leads to think that we could potentially _leak_ private information. We want to avoid this potential problem by encrypting sensitive information that travels across processes.

# Solution or next step
* Using symmetric encryption (via a share secret, e.g. Kubernetes secrets) we can encrypt/decrypt the HTTP headers containing sensitive information

**Comment by dlebrero** [comment]
Maps will expect the initialisation vector as the header X-ENCRYPT-INIT-VECTOR.

The encryption key will be the same as the one used to encrypt the credentials in the DB

**Comment by dlebrero** [comment]
We decided not to do this as the communication between the Backend and  Windshaft is through localhost
