### ISSUE TITLE
Add an 'unlimited' pricing tier to resource tracking

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1010]
# Context

We are now tracking resource usage against Standard and Pro tiers.
Some instances are used internally and are not 'for sale', for instance trial, demo, test, hub instances. 

# Problem or idea
We should add an additional tier that we don't sell. It should not have any limit on the number of visualisations and external datasets.

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
- [ ] Add new tier which is unlimited
- [ ] Extend script to support it
