### ISSUE TITLE
Add information button to fields in the vis. editor

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1016]
# Context

I've just had a Lumen training with Banzoumana and he said that visualisation editor, especially for bar charts, is difficult to understand. Especially the 'sub-bucket' field got him very confused until I explained it to him.

# Problem or idea
Banzoumana suggested adding information buttons to some fields in the visualisation editor, which would contain some basic overview of how this or that field should be used. 
I think we have 'i' buttons in RSR project editor as well, so he suggested to introduce something similar in Lumen.

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
@nadiagorchakova I also find the bar chart editor a bit confusing. I commented on why I think so here: https://github.com/akvo/akvo-lumen/issues/1026

**Comment by jonase** [comment]
> As a side note I find the bar chart editor a bit confusing.
>
> I would suggest to default to aggregation method Count, and the selection for the “bucket column” would come first. Only if you pick an aggregation different from Count do you need to select a metric column. This would mean that the bar config editor would very similar to the pie chart editor. With one additional option (except the sub-bucket stuff): “Aggregation”. If you pick aggregation other than count, then you would see the metric column options.
>
> Conceptually, one way to see why the current setup is fishy, is that if you select the count aggregation the metric column selection is arbitrary. Whatever you select you get the same chart but you still have to select one
>
> Would like to hear you opinions on this

**Comment by nadiagorchakova** [comment]
I think we have two different issues here :-)

**Comment by janagombitova** [comment]
I think we can close this issue for now as we have just redesigned the visualisation editor and will gather feedback for further improvements that will be handled in separate issues.
