### ISSUE TITLE
'Built with Akvo Lumen' tag in visualisations and dashboards

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1022]
# Context
Currently, 'Built with Akvo Lumen' tag appears in the right bottom corner of visualisations and dashboards

# Problem or idea
As @Lynngre and @LarsSjogreen pointed out, in embedded visualisations and dashboards the tag can appear misplaced - too far removed from the actual visualisation(s).

# Solution or next step
As we are in the process of re-designing dashboard canvas, maybe it's something we could include into the re-design effort, @loicsans what do you think?

**Comment by loicsans** [comment]
The "built with Akvo Lumen" feature only makes sense if the page you are looking at is not hosted on the akvo lumen domain. Question is, are we going to let people host lumen dashboards  on any domains?

**Comment by Lynngre** [comment]
I also forwarded an email to Loic (as I saw that the original comment had been removed), but will copy my response here just for info:

'We’ll definitely need visualisations on domains other than Lumen’s when sharing & even on ‘CNAME’ url’s (domains) running on Lumen (such as https://visualisations.wandelenvoorwater.nl which would be https://wandelenvoorwater.akvolumen.org for us - this is just an example).

Below is what I sent to Nadia in June which really relates directly to Groundtruth 2.0’s use & also all Akvo Sites use.

Hope that gives some more background info for https://github.com/akvo/akvo-lumen/issues/1022
'
