### ISSUE TITLE
Link 'Built with Akvo Lumen' tag to Lumen product page on akvo.org

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1023]
# Context

For publicity purposes, Lars suggested to link 'Built with Akvo Lumen' tag that appears in visualisations and dashboards to the new Akvo Lumen product page on akvo.org (the page is still under construction, so a url will follow later).

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Completed
