### ISSUE TITLE
Dropdown in the pivot table filter keeps jumping lower down

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1035]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-69545-from-nikki-at-akvo-dot-org
Created by: Nikki

Message:
[AKVOLUMEN] Support request #69,545 from nikki@akvo.org      

User email: nikki@akvo.org  

Request Info
Device:  Personal computer
Browser:  Safari 10.1.1
OS:  OS X 10.12.5
IP Address:  116.212.237.86
URL:  http://lumensupport.akvo.org/form  

1- What do you need help with?
I have a bug  

2- What is the name of your instance? (xx.akvolumen.org)
seap.akvolumen.org  

3- What is the name of your dataset, visualisation or dashboard?
Visualisations (Pivot table) called Surveys Collected  

4- What did you expect to happen?
to be able to scroll through the list of questions for filtering  

5- What actually happened?
everytime I tried to scroll within the filter list, the page jumped lower down the list again  

Tell us more about your request
Hey guys, So I was trying to select one of the first questions in the survey to filter out some responses. However everytime I opened the list of lists, the page would navigate to about mid list, as I tried to scroll up and select the question I wanted, the page would jump down to it's previous location. I've been able to filter on a different question, so this isn't a an urgent issue, but would be great if some could have a look into it please :)  

Download attachment
Scrolling in datafilter.gif (https://s3-eu-west-1.amazonaws.com/cdn.supporthero.io/ticket/747/scrolling-in-datafilter.gif)

**Comment by janagombitova** [comment]
Issue is resolved
