### ISSUE TITLE
Improvements to Lumen Collections UI

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1036]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/ui-unexpected-slash-counterintuitive-behaviour
Created by: Lynn

Message:
As a user I login and access my saved/created ‘collection’. In the example the collection is named ‘Lynn’.

Once I have browsed to the collection page (in this case the Collection named ‘Lynn’), as a user I want to import new datasets, create visualisations &amp; add dashboards via the option in the collection header. (Noting that the options to add these via ‘+Dataset’, ‘+Visualisation’, ‘+Dashboard’ is displayed inline with the collection name to the left ‘Lynn’). As these are displayed alongside &amp; seemingly within the collection area, as a user I assume that when I utilise any of these options they will appear within my collection ‘Lynn’.

However, what happens is that when I select to add one of these, I am:

A) not made aware of the fact that anything is processing/happening/erroring
B) once the import or creation has been completed I am returned back to the relevant collection’s page/area, left scratching my head as to where to find my imported dataset or visualisation &amp; if it imported/was created at all.

Once I go hunting for it I find that it has been imported or created or failed with an error under ‘Library’ instead.

Summary:

I find it counterintuitive that when I attempt to import a new dataset, create a visualisation or add a dashboard from within a collection, that I then have to find it under ‘Library’ &amp; then ‘add to collection: Lynn’ to get it to where it should have been created in the first place.

I suggest that a user is asked whether to create the resource within ‘this current collection’ when importing/creating it.

Let me know if you need more information/clarity.

With thanks

**Comment by Kiarii** [comment]
this sounds like a bug, the design idea was that a user could directly add assets to their collection
