### ISSUE TITLE
Password-protected dashboard links

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1046]
# Context

To ensure protection of sensitive data, a few partners are asking for a functionality to set passwords on publicly shared dashboards. It's also in line with GDPR legislation that we need to help partners protect their sensitive data.

# Problem or idea

When a dashboard is shared publicly via the 'share' option, anyone who obtains the link can view it. That is not safe enough as some survey data might contain personal data of respondents like religion, sexual orientation etc. If this data (or visualisations) that can identify certain people or communities gets into the wrong hands, the respondents might be in danger or persecution. There are other cases of possible dashboard data mishandling too. 

# Solution or next step
Currently, the dashboard sharing window looks like that:
<img width="986" alt="screen shot 2018-04-19 at 11 17 38" src="https://user-images.githubusercontent.com/21127166/38982885-51c8c480-43c3-11e8-8602-0deb57441e13.png">
It should be enhanced with password setting functionality.
@Kiarii, if you have time, would be helpful to hear your opinion on best UX practices for that.

**Comment by nadiagorchakova** [comment]
yes!

**Comment by Kiarii** [comment]
I think this shd be done similarly to the visualization's pwd protection; https://invis.io/46F1NKMEV#/262731142_2a-_Share_Dialog_Def for the sake of some consistency

**Comment by nadiagorchakova** [comment]
thanks @Kiarii! this is helpful

**Comment by kardan** [comment]
### Backend Todo
- [ ] Implement/api/shares/ :PUT endpoint that takes {"password": "the-password}
- [ ] Remove Tardis from the share db table
- [ ] Migrate share table to have a password column 
- [ ] Store password hashed on shares table 
- [ ] Add auth logic on /shares/<id> GET to if needed look for a {"X-Password" "the-password"} header.
