### ISSUE TITLE
Better feedback for failed derive column transformations

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1049]
# Context
Users can derive columns with javascript formulae 
 
# Problem or idea
We provide the user feedback on when their formula is invalid javascript, but aside from that there is no feedback for syntactically correct javascript that generates errors or exceptions whenever it is run.

For example, the formula `row["multiple_choice"].split("|").includes("A")` will trigger the failure case for any possible row because the backend doesn't support the `includes` array method - but the user has no way to discover the cause of the problem aside from guessing, intuition and trial-and-error.

# Solution or next step
We should think about ways to help the user discover the causes of errors - this might be access to an error log for power users, or something more intuitive for general users.

Perhaps we should treat formulae that trigger the failure case for every row in the dataset as a special case, and show the user more information when this happens

**Comment by janagombitova** [comment]
I prefer we handle this specific case at a time as right now the specification is a bit too vague to base  further work on and the split column transformation is now handled in a more user friendly way. Closing the issue for now.
