### ISSUE TITLE
Geolocation of photos missing from Flow import

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1050]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/geolocation-of-photos-missing-from-flow-import
Created by: Joy

Message:
The current Flow import does not get in the photo geolocation. 
This is important data as it helps map accuracy of collected data, also enabling operations such as computation of distances between place of survey and location of photographs.

**Comment by nadiagorchakova** [comment]
dataset: greencoffee.akvoflow.org—>Baseline—>M&E Baseline. There is only 1 photo question towards the end.
@jonase could you have a look pls? I'm not sure what technical limitations are there

**Comment by jonase** [comment]
The flow-api captures the photo's geo-location (if available) which means we have this information when importing flow data into lumen. 

The question is how to represent this in Lumen. We could have two (or three) columns for each photo question type: `(url, geoloc)` or `(url, lat, long)`. 

But as usual I'm hesitant to go down this route of splitting columns for flow questions. OTOH, if we're not going to represent flow data types in Lumen I'm not sure we have many other options.

One other option is cascades approach (with json strings) but then the user would have to create a derived column for the simple use case of displaying an image on the map.

**Comment by nadiagorchakova** [comment]
Why are you hesitant about splitting columns for flow questions, @jonase ?

**Comment by janagombitova** [comment]
Just to add a bit of use case context to make the decision on how to implement easier: 

Today photo geotags are used to check the location of the photo in comparison to the location of the data point. Either this is done using the maps or by calculating the distance between the two points. Most of our users use the map option as they are not familiar with how to calculate the distance. 

So the main opportunity here is: **How can we bring in and provide the photo metadata so it is easy to use?**

Second opportunity looming in the dark (that should be handled in a separate issue but might affect the decision we make here) is **How can we make it easy to check the location of a photo in comparison to the location of its data point?**

**Comment by janagombitova** [comment]
Geert requested this too in the name of a parter Ecosia: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-316808-from-geert-at-akvo-dot-org

The request is to be able to add a layer on the map that shows the location of photos.
