### ISSUE TITLE
New dataset modal is not cleared when browser back button clicked

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1052]
# Context
Steps to reproduce:

1) View a visualisation
2) return to the library view
3) open the "new dataset" modal
4) hit the browser back button

# Problem or idea
The browser returns to the previously viewed visualisation, but the "new dataset" modal fails to clear and is overlayed on the visualisation view, resulting in a broken layout.

# Solution or next step
We should clear the "new dataset" modal on browser navigation change

**Comment by kardan** [comment]
Is this still valid?

**Comment by nadiagorchakova** [comment]
I cannot reproduce it anymore. Not sure if anything was changed there.

**Comment by kardan** [comment]
@nadiagorchakova thanks for checking
