### ISSUE TITLE
Display Lumen version number in the UI

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1054]
# Context

Thomas asks us to display Lumen version number somewhere in the UI.
This is to adhere to best open source practices.

# Problem or idea
In which part of the UI to display it?
Flow has it in a footer:

<img width="1238" alt="screen shot 2017-09-06 at 14 25 53" src="https://user-images.githubusercontent.com/21127166/30112213-c20ce01e-9310-11e7-9e2b-b4508dd6c307.png">

Since we don't have a footer in Lumen we need to find some other nice spot for it. @Kiarii maybe you'll have an opinion about it?

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
It's not trivial to show the version number.

**Comment by janagombitova** [comment]
Why is the most important question here. We have different ways of releasing in Flow and in Lumen and will need to find a best way forward with the connected two. I am closing this issue for now
