### ISSUE TITLE
Text to Number transform - pick_a_default_value if it fails

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1056]
# Context

When you switch between different data types, there is an option to choose "pick_a_default_value" if transformation fails.

# Problem or idea
When I choose "pick_a_default_value" and set default value to zero, nothing happens when I'm trying to apply the transformation. The operation appears as complete as side panel is closed but I don't see the column data type changing.

<img width="1232" alt="screen shot 2017-09-07 at 16 50 06" src="https://user-images.githubusercontent.com/21127166/30170592-d777ff62-93ef-11e7-81e4-2598d5061f5c.png">

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
There is two things going on here. 
1. There is a missing doc string.
2. On the backend we're trying to insert a string in a number column.

**Comment by jonase** [comment]
According to the "spec" the default value for a to-number transform should be a number. If it's currently set as a string I think the bug should be considered to be at the client side.

https://github.com/akvo/akvo-lumen/blob/develop/doc/spec/transformations.md#corechange-datatype

**Comment by kardan** [comment]
Thanks, I was thinking that the backend code looked odd if we only expected strings.

**Comment by kardan** [comment]
So to recap the client side needs some love. Since we send strings and not number to backend. Unless I'm doing something totally wrong, it's not possible to type a default date.
