### ISSUE TITLE
Deleting a dataset does not result in deletion of a related pivot table

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1065]
# Context

When cleaning up the demo instance, I noticed that deleting a dataset does not result in automatic deletion of a pivot table, which was created from this dataset. 

# Problem or idea
The problem is that: (1) the pivot table was mentioned in a warning when deleting a dataset, however, its icon still remains in the library. (2) when clicking on this pivot table I get to 'select visualisation type' page, which means that it was deleted after all.
So as a result, I have to delete this pivot table individually.

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
@nadiagorchakova I was not able to reproduce this issue

**Comment by nadiagorchakova** [comment]
@jonase Here's a gif

![dataset deletion pivot table](https://user-images.githubusercontent.com/21127166/30417431-0575b3ce-9930-11e7-84de-2f0e3df154df.gif)

**Comment by nadiagorchakova** [comment]
It happens when I'm cleaning *old* datasets, if it makes any difference..
