### ISSUE TITLE
Sharing of an existing dashboard

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1066]
# Context
When I open an existing (finished) dashboard, the share button is disabled. 

# Problem or idea
I have to click on save first before I'd be able to share an old existing dashboard.
It's a bit counter-intuitive as I haven't changed anything in this existing dashboard, I just want to share my finished work.

# Solution or next step
It's related to our recent improvement to disable sharing before saving a visualisaiton or dashboard.
That was done to prevent generation of broken links. In this case, however, a link to an existing dashboard should not broken, so I think the share button should be enabled right away. What do you think @gabemart @loicsans ?

**Comment by jonase** [comment]
I think this should be considered a regression. I'll look into it

**Comment by jonase** [comment]
https://github.com/akvo/akvo-lumen/issues/988
