### ISSUE TITLE
Displaying multiple columns in pivot table

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1070]
# Context
We received some feedback on Lumen from a US partner Lifewater (contact person Ethel).
Currently there is a way to pick only one column from a source dataset to be displayed as a column in a pivot table

# Problem or idea
Just one column is sometimes not enough to get a summary you want. Being able to add multiple columns would aid data analysis.
I imagine having multiple columns in pivot table would look something like that (this is an example from Excel):

<img width="827" alt="screen shot 2017-09-18 at 12 20 01" src="https://user-images.githubusercontent.com/21127166/30537897-e1bf5ac2-9c6b-11e7-942f-211bb7dd9e6f.png">

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
To expand on the context of this issue: 

Pivot tables are the data behind the graph. Often Lumen is not the end goal. Lumen visuals are then taken and placed in a report and then the pivot table is based next to the visualisation to show the data it is based on. 


Secondly, every visualisation in Lumen aggregated, but sometimes you just want to show a piece of the dataset. So not a pivot table but a smaller slice of the data table and share it. 

Here is an example shared by our colleagues in the West Africa hub

![Screen Shot 2019-05-07 at 15 32 17](https://user-images.githubusercontent.com/12456965/57303314-5bb23600-70dd-11e9-891c-3aabb4b13cf4.png)

**Comment by janagombitova** [comment]
I would like to keep this one open, so we do not forget about it and actually implement
