### ISSUE TITLE
Ability to add a secondary Y axis to a bar graph

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1071]
# Context
We received some feedback on Lumen from a US partner Lifewater (contact person Ethel).
Their data analysis needs include a possibility to monitor progress over time using more than one variable in one graph.

# Problem or idea
The most suitable way to do that is probably to add a secondary Y axis to a bar graph, which we don't support yet.
The result would look something like that:

<img width="578" alt="screen shot 2017-09-18 at 12 30 30" src="https://user-images.githubusercontent.com/21127166/30538270-80d87c00-9c6d-11e7-85f2-9634e65e4e26.png">

Lifewater even did a hand drawing with their own example, but here you also have multiple lines, which is a separate issue.

<img width="501" alt="screen shot 2017-09-14 at 15 07 12" src="https://user-images.githubusercontent.com/21127166/30538299-a88a81bc-9c6d-11e7-93a4-d32fc3496e4b.png">

# Solution or next step
How could we solve it?

**Comment by LarsSjogreen** [comment]
Maybe we just shouldn't. Dual axis charts are quite often seen as an anti-pattern in the data-viz community. Or as they say: "friends don’t let friends use dual Y axis charts."

Here's a blog post explaining why it's a bad idea.
https://blog.datawrapper.de/dualaxis/?utm_source=The+Den+Bulletin&utm_campaign=f90fa170c9-EMAIL_CAMPAIGN_2018_05_11&utm_medium=email&utm_term=0_01a9377b12-f90fa170c9-149983937

**Comment by janagombitova** [comment]
Considering our users are not data scientists or experts in handling data and our goal is to make data as understandable as possible I agree with @LarsSjogreen that rather than making things even more complicated, we should simplify. Perhaps an idea is to add a support article with examples on best practices on how to visualise such cases, as done in the blog.

**Comment by janagombitova** [comment]
I agree with the goal to strive for simple and understandable graphs as our users and those reading these are not experts in data. Thus closing the issue. It can always we reopened if our focus changes or if we receive more similar feedback from the field.
