### ISSUE TITLE
Flow import should mark id's as unique

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#1076]
# Context
We are about to implement dataset merging in Lumen, where you can add columns from one dataset to another. One of the main use cases is for the user to be able to merge Flow registration data into a monitoring dataset.

The following are facts about Flow datasets in Lumen
* A dataset imported from a flow registration form has unique values in the `Identifier` column. This is the "datapoint id". Every row is the registration of a separate data point
* A dataset imported from a flow monitoring form has a corresponding `Identifier` column but this column is not unique because every row is a monitoring of a specific data point

As a first iteration we're going to merge columns from a registration form into a monitoring form. To be able to ensure the "correctness" of the result (that the result is still a "monitoring dataset") the `Identifier` in the registration form needs to be a foreign key (otherwise we would either have to aggregate the incoming columns or make the resulting dataset something that could no longer be considered a monitoring dataset.)

# Solution or next step
Mark `Identifier` columns as primary keys in registration forms at Flow import time.

**Comment by kardan** [comment]
@tangrammer you know if this is done?

**Comment by tangrammer** [comment]
@kardan  don't know 🤔.... would you like me to confirm?
