### ISSUE TITLE
Use Windshaft for rendering maps

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1077]
# Context
We have decided and done ground to switch to Windshaft for maps. At the moment we have Windshaft running in the Lumen pod next to lumen. This enables us to use it more or less as a library. 

# Problem or idea
We need to reach feature parity with the current map solution but using Windshaft as a tiler.

# Solution or next step
We have a static test for rendering maps using Windshaft, we should take this a step further and do a test with client, backend and Windshaft. 

ref:
- [#1004](https://github.com/akvo/akvo-lumen/issues/1004)
- [#1061](https://github.com/akvo/akvo-lumen/issues/1061)
- [#963](https://github.com/akvo/akvo-lumen/issues/963)
- [#901](https://github.com/akvo/akvo-lumen/issues/901)

plan:
We'll add the new map under the current one in the visualisation editor. This way we can build up a pair of maps with one visualisation editor and verify that they behave in a similar fashion. 
Things to do (WIP):
- [x] Communicate to windshaft over correct host (localhost in production)
- [x] Use dynamic url for POST to Windshaft
- [x] Use correct headers for POST to Windshaft
- [x] Build simple SQL case
- [x] Investigate how to render legends if not all data is available in the client. Will probably need to populate the pointColorMapping before returning from /api/visualisations/maps. 
- [x] Feature parity for legend positioning and overflow
- [x] Pop up support
- [x] Image popup support
- [x] Bugfix - points filtered out via dataset editor still have popup from utfgrid
- [x] ~~Zoom map? (map bounding box currently works, but potentially we should save the zoom and pan from the editor view /g)~~ not going to do this
- [x] Rate-limit client requests to backend (in progress)
- [x] Be smarter about when to rerender map (e.g. we don't need to refresh legend when poup changes)
- [x] Refactor / clean up backend code (especially around public)
- [x] Validate map specs on the backend. (D)
- [x] Bugfix - filtered-out values should not appear in the pointColorMapping
- [x] Make public maps work (new maps needs windshaft ref). This will require the public endpoint to depend on config.
- [x] Fix issue where public maps client tries to use the "rows" from a dataset. 
- [x] Remove the double maps and only show one
- [x] New version of akvo-maps does not use tenantDB in the url, we should sync up with the platform team and follow the release of akvo-maps
- [x] Only do backend requests if we have a "sensible" visualisation spec
- [x] Show lat / long dropdonwn for old maps and geom column dropdown for v2 and new map?
- [x] Fix bug where inputs disabled when lat/long absent but geom present in viz editor - g
- [x] Handle cases where too many values in pointColorMapping - for now, just show everything and let the legend scroll
- [x] Fix map updating in dashboard editor
- [x] Quote strings so we're not open to  sql injection
- [ ] Keep rows that exactly matches number also allows nil values
- [ ] Streamline number format (we only use doubles) returned from "group by" sql calls in the map editor
- [ ] When a "remove exact value" filter is applied, and that filters matches at least one row, any rows with nil values for that column are not rendered as points by windshaft (but weirdly, they do appear in the pointColorMapping if that column is chosen as the "color by" column). This is slightly different to the bug above. If the filter doesn't match at least one value, nil value rows are not filtered out.
- [ ] Removing data filters does not re-render the map

**Comment by kardan** [comment]
We'll add the new map under the current one in the visualisation editor. This way we can build up a pair of maps with one visualisation editor and verify that they behave in a similar fashion. 
Things to do (WIP):
- [ ] Communicate to windshaft over correct host (localhost in production)
- [ ] Use dynamic url for POST to Windshaft
- [ ] Use correct headers for POST to Windshaft
- [ ] Build actual SQL
- [ ] Pop up support
..

**Comment by kardan** [comment]
@jonase suggested to investigate https://github.com/jkk/honeysql (sql/format) for sql generation.

**Comment by gabemart** [comment]
* Be smarter about when the client makes a POST to the backend for a new layerGroupId
* Think about changing the current `pointColorMapping` system - separating the default colours from user-selected colors
* Agree on what new information the backend should send to the client (e.g. map bounds, labels, color mapping, unique values)
* Backend could return something like:
````
{
  layerGroupId: $id,
  metadata: {
    boundingBox: [[0,0], [0,0]]
  },
}
````

**Comment by kardan** [comment]
Moved todo list to the issue description.
