### ISSUE TITLE
Numerical shorthandling long numerical values 

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#1081]
# Context
Need to consider how and when to shorten long numerical values to declutter visualizations, legends, where specific values are not necessary to view at once but may be pulled via a pop-up e.g. 
- 1 234 567 to 1.2M
- 1234 to 1.2k
- some form of shortening for long decimal numbers would also apply

**Comment by janagombitova** [comment]
Shortening is in place. Exceptions should be handled in specific issues with the example
