### ISSUE TITLE
Renaming in maps editor

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1087]
# Context
As shared by Thomas. 

Renaming in maps - two actions when one should be enough - When renaming a map layer it takes two actions to save. One to click the check mark and one to click save. One should be sufficient.

Also giving a name or renaming a layer in map has different UI than other title elements in Lumen.

<img width="1265" alt="screen shot 2017-09-27 at 16 37 24" src="https://user-images.githubusercontent.com/21127166/30919590-22895bb0-a3a2-11e7-81e5-0cfba6b1efd1.png">

**Comment by finnfiddle** [comment]
@nadiagorchakova I dont think the layer names can be so easily separated from the rest of the map - ie saved independently. If the user has other changes then those will get saved as well. we could do it theoretically but its going to not be a very elegant solution I think. it seems that this is more an issue of there not being autosave - or not?

**Comment by nadiagorchakova** [comment]
I think what Thomas meant here is that you need to use the ... button in order to give a name to an Untitled map layer or to rename it. The logic for naming or renaming the map itself or other visualisations types in Lumen is different - you just need to click on the 'Untitled' and start typing. I think I agree with him that it's not very intuitive.

Does it make more sense now...?

![naming of map layers](https://user-images.githubusercontent.com/21127166/37293978-1e287aec-2615-11e8-82bf-a09c9ab42dcd.gif)

**Comment by finnfiddle** [comment]
@nadiagorchakova but then how do you get to editing the layer? Because currently if you click the layer name it takes you the the layer editor

**Comment by nadiagorchakova** [comment]
hm hm, good point @finnfiddle 
I'll ask @Kiarii to have a look and share his opinion

**Comment by Kiarii** [comment]
nb: the *map title* on the other hand is only an **editable element**, the *layer name* element is both **editable and clickable** - it cannot have these two properties simultaneously.. (so much for the double split experiment)  

one option how we could achieve a uniformity is by separating the clickability and editability properties of the *layer name* as follows: 
- user clicks add new layer
- new layer has a default name "untitled layer x"
- "untitled layer x" is only **clickable** 
- user clicks on "untitled layer x" 
- they navigate to the "untitled layer x" editing page where
- "untitled layer x" becomes an **editable** element     

Of course, this also comes with its own setbacks: to rename a layer, the user has to open it.. to rename multiple layers, the user has to go back and forth.. one might also wonder why a layer has an edit action **delete** and not another **edit** and so on..

**Comment by loicsans** [comment]
+1 @Kiarii

**Comment by finnfiddle** [comment]
@Kiarii the benefit of doing this seems quite marginal. I agree that - if we need to have 2 steps clicking and then editing - we might as well move the layer title editing to its actual screen instead of doing it on the layer list screen. Because then we edit everything about the layer in the same place. But I guess we're not really solving the original problem that Thomas reported which is removing the extra step.  @nadiagorchakova maybe its a better idea to invest time in the autosaving rather?

**Comment by Kiarii** [comment]
the current workflow could be simplified by adding a [edit] icon on the layer row and having in view (so that on clicking it, the layer name field is shown and the cursor placed therein) to cut it down to a single step - there might be a confusion though of which this edit refers to: a) layer name edit or b) layer data/theme/etc edit

**Comment by nadiagorchakova** [comment]
@finnfiddle to prioritise this a bit, let's indeed do the autosaving step first.
Just to confirm, it will replace this button, right? 
<img width="378" alt="screen shot 2018-03-13 at 12 26 55" src="https://user-images.githubusercontent.com/21127166/37339132-e9dfb9c6-26b9-11e8-9b6d-de2aa436e1b7.png">

and thanks @Kiarii for your thoughtful input!

**Comment by finnfiddle** [comment]
yes thanks @Kiarii. @nadiagorchakova it will replace the other button - the "Save" button bottom left. Autosave isnt mentioned in this issue but it was mentioned on another task I just worked on - maybe that was a bit unclear what I was talking about: https://github.com/akvo/akvo-lumen/issues/825

**Comment by nadiagorchakova** [comment]
If the autosave will apply when you're inside layer editor as well, and when you're working with other visualisations types, e.g. bar charts - then I'm 100% in favour.
Some users did complain already that they managed to navigate away without saving and loosing all their work..
