### ISSUE TITLE
Improve development stack based on Docker and docker-compose

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#1098]
# Context

A great improvement has been done with an _easy_ command `docker-compose up`, however there are some differences when running this containerized development setup between macOS and Linux.

One of the main issues is the permissions assigned to new files created within the container on an exposed host folder using `--volumes`.

# Problem or idea

On Linux dev host:
````
# Create a new file inside a container inside an exposed folder from the host
# Try to remove/touch/edit the file as a host user

[ivan@utila tmp]$ docker run --rm --volume "$(pwd)":/code clojure:lein-2.7.1 touch /code/new-file.txt
[ivan@utila tmp]$ ls -l new-file.txt 
-rw-r--r-- 1 root root 0 Oct  8 14:17 new-file.txt
[ivan@utila tmp]$ rm -rf new-file.txt 
rm: cannot remove 'new-file.txt': Operation not permitted
````
The new file is created as is `root` was the owner and group leading to problems on the host machine (we don't need to use `sudo` to deal with files)

The same happens with usual `target` folder or any other file created inside the container, e.g. the `backend` folder:

````
[ivan@utila backend]$ ls -laht
total 72K
-rw-r--r--  1 root root    5 Oct  8 14:13 .nrepl-port
-rw-r--r--  1 root root   15 Oct  8 14:13 .lein-env
drwxr-xr-x  8 ivan ivan 4.0K Oct  8 13:54 .
drwxr-xr-x  3 root root 4.0K Oct  8 13:53 target
[...]
````

This is a known issue, the workaround is to setup a user inside the container with the same user id (`id -u`) and group id (`id -g`) as the host user.

*NOTE:* Docker has the ability to run as _any_ user via `docker run -u`, but this doesn't work because of leiningen and how maven cache works.

# Solution or next step
* Create a user in the container [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) and execute the `lein <command>` as the newly created user
* Inspiration:
  * https://github.com/markmandel/wrapping-clojure-tooling-in-containers
  * https://github.com/iperdomo/tmate.clj/blob/master/startup.sh

**Comment by kardan** [comment]
What's the status on this?

**Comment by iperdomo** [comment]
@kardan done
