### ISSUE TITLE
Resource usage doesn't show in some instances

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1124]
# Context

I wanted to check Lumen usage stats, but don't see the actual numbers when I click on the 'Resources' button

<img width="967" alt="screen shot 2017-10-25 at 15 31 56" src="https://user-images.githubusercontent.com/21127166/32001395-f23c01b6-b999-11e7-923f-130209cbcf45.png">

<img width="483" alt="screen shot 2017-10-25 at 15 35 06" src="https://user-images.githubusercontent.com/21127166/32001433-1b2ee7fa-b99a-11e7-9afb-15f34a8e4f54.png">

Some instances do show resource usage though. So if it's a bug it seems to strike at random.

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
It's because some tiers don't have a plan attached to them. We need to add one & also review how we ended up in this situation.
