### ISSUE TITLE
Update Flow imports

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1143]
# Context

We currently pull latitude/longitude from the Flow Datapoint table (called `SurveyedLocale`) into every imported form (both registration- and monitoring forms)

# Problem or idea

In the case of Flow data cleaning the location information is sometimes not updated and if new submissions are added as part of data cleaning the datapoint is also not always updated accordingly.

With recent improvements in Lumen we can make a number of improvements to the Flow import.

1. Rely on the form responses for location information. This means the location will often only be available in the registration form but with the new "merge datasets" feature in lumen the user can merge the location into monitoring forms if desired

2. We currently import location data into two separate columns (latitude/longitude) but the new maps has introduced a `geopoint` data type that we should take advantage of.
 
# Solution or next step

Removing the latitude/longitude (and instead adding a `location` column) will change the import in backward incompatible ways which would break updating previously imported forms. There are a few ways we could address this:

1. Analyze current usage of the update feature to see if flow forms are being regularly updated in non-demo tenants. If not (or if there are very few cases) it would be possible to accept the breakage

2. Bump the flow import version to `3` and make sure old datasets are updated with the old approach. The tradeoff being more complex import code.

(description from @jonase )

**Comment by jonase** [comment]
1) and 2) from `Problem or idea` section implemented. But currently not backward compatible in terms of the update feature (meaning "old" imports can't currently be updated, a reimport is required)
