### ISSUE TITLE
Map markers get cropped

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1157]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-81887-from-thomas-at-akvo-dot-org

Message:
[AKVOLUMEN] Support request #81,887 from thomas@akvo.org

Request Info
Device:  Personal computer
Browser:  Safari 11.0.1
OS:  OS X 10.11.6
URL:  https://gt20.akvolumen.org/visualisation/59d773ae-582d-4199-b2bb-5ff914e53733

1- What do you need help with?
I have a bug

2- What is the name of your instance? (xx.akvolumen.org)
gt20.akvolumen.org

3- What is the name of your dataset, visualisation or dashboard?
Fosfatnivå - Flen Blitz oktober 2017

4- What did you expect to happen?
Map markers to be round

5- What actually happened?
At some zoom levels the markers are cut off

6- What is your full name?
Thomas Bjelkeman

7- Which Akvo Hub do you usually work with?
Europe

Tell us more about your request
When you zoom in and out, markers that span tiles seem to get cut off. I have one that seems to be reproducible. The picture attached is a sample of this.
This is not a big issue, but a small visual bug.

Download attachment
gt20_cut-zoom2.png (https://s3-eu-west-1.amazonaws.com/cdn.supporthero.io/ticket/747/gt20cutzoom2.png)

![gt20_cut-zoom2](https://user-images.githubusercontent.com/21127166/32726773-77fca758-c87a-11e7-8385-a373162de8da.png)
![gt20_cut-zoom3](https://user-images.githubusercontent.com/21127166/32726774-781ad80e-c87a-11e7-9adb-880e415b7049.png)

**Comment by gabemart** [comment]
I suspect we need to increase the `buffer-size` property - I think this can be passed to windshaft as cartoCSS

**Comment by gabemart** [comment]
I did some testing and even setting the buffer-size to a low value (I used 8) is enough to prevent this problem. I *think* that because our current max point size is 13, the worst-case is that pixels end 6 pixels up on another tile, so 8 seems enough.

the appropriate place to do this seems to be on the top level of mapconfig
