### ISSUE TITLE
Import and view raster data as a map layer

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#1161]
# Context
We want to be able import raster data (e.g. Worldpop population estimates) and use it as one of the layers in a map.

# Problem or idea
Raster data is a way of encoding large dense datasets. In this attempt we're going to import a raster dataset (only [GeoTIFF](http://geotiff.maptools.org/faq.html)) and use it a a layer in a map.

# Solution or next step
* This effort only includes the import of raster dataset, and use it as a layer in a map. Does not include a larger effort on use the dataset for analysis.
* This _dataset_ doesn't follow the _tidy data_ approach of columns and rows, so it won't be imported like other datasets
* We're going to use `raster2pgsql` to import the raster file
* The raster dataset will be part of the user library
* Some transformations (e.g. reprojection) needs to happen to be usable in a map

**Comment by nadiagorchakova** [comment]
I think the issue can be closed now that we have initial support for raster data
