### ISSUE TITLE
Reverse Geocoding transformation

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#1162]
# Context
[Reverse Geocoding](https://en.wikipedia.org/wiki/Reverse_geocoding):

> Reverse geocoding is the process of back (reverse) coding of a point location (latitude, longitude) to a readable address or place name. This permits the identification of nearby street addresses, places, and/or areal subdivisions such as neighbourhoods, county, state, or country.

# Problem or idea

Reverse Geocoding in Lumen will be implemented as a transformation on a `geopoint` column resulting in a new text column with the "name" of the location.

The first implementation will use the "world" shapefile provided by http://www.fao.org/geonetwork. This shapefile will reach admin boundary level 2. Future enhancement could be to use a user supplied dataset with a `geoshape` column and extract a column value from that dataset.

**Comment by nadiagorchakova** [comment]
Kiarii asked to leave a comment about potential application of this feature.
There are two cases I know of:
- creating a pivot table which sums up certain data for each admin division
- looking into the future, a few partners expressed a need to be able to filter on admin divisions on the dashboard. Kiarii, this is what Charles and Lars. H built for partners as a custom solution and there is a demand now to have it in Lumen.
