### ISSUE TITLE
The placement of embedded graph is off

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1163]
# Context
Lynn and Thomas reported that embedded graphs appear misplaced on the website.
Embedded graphs are used in ground truth 2.0 program in Sweden (citizen observatories). 

# Problem or idea
The website: https://vattenfokus.akvotest.org/flen-vattenblitz-resultat/

Example of embedded visualisation:
<img width="1279" alt="screen shot 2017-11-15 at 09 28 14" src="https://user-images.githubusercontent.com/21127166/32826096-6435ffa8-c9e7-11e7-9a44-99f24eb4becb.png">

The iframe code Lynn used:
<iframe src="https://gt20.akvolumen.org/s/vVL32GKGZpQ" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" width="100%" height="500"></iframe>

# Solution or next step

**Comment by peeb** [comment]
![screenshot from 2017-11-22 20-16-56](https://user-images.githubusercontent.com/155294/33148045-2df029ec-cfc2-11e7-850f-d16cfcc8e995.png)

Looks a bit nicer ^^
