### ISSUE TITLE
Continue with the lumen tests using Puppeteer

### ISSUE THREAD

**Issue by baztan106483** [akvo/akvo-lumen#1169]
# Context
We want to automatize tests that are made to check if Lumen operates correctly
# Problem or idea
- Maps are one of the hardest visualization type because it needs to transform the dataset
- It is interesting to create a dataset directly from Akvo-Flow

# Solution or next step
We use Puppeteer to make these tests run automatically

**Comment by janagombitova** [comment]
@kardan What is the status of this issue?
