### ISSUE TITLE
Not possible to delete library item with long title

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1170]
# Context

Import of one of the Flow forms failed and as a result its title lengthened (to incorporate the error message that import failed).

![deleting an item with long title](https://user-images.githubusercontent.com/21127166/33204030-679a6fb8-d102-11e7-9752-4e379aaec56f.gif)
 

# Problem or idea
There is no way to delete this item now as three dots are unavailable due to overlapping titles.

# Solution or next step
@Kiarii maybe you would have an idea how to improve user experience here?

**Comment by Kiarii** [comment]
First thoughts:
- The overlap of the asset bounding boxes is technical: we need at least to have a max width but can have adjusting height to accommodate longer asset titles, metadata <s> or error messages in this case</s>. 

## About the failure: 
If there was a failure in creating an asset, then that asset should not in any way be 'created' or added to the library. 
- A notification shd suffice to inform the user of the failure, and further
- Get rid of the seeming paradox: an uncreated asset appearing as an asset
- And thus to rid of the extra task of selecting and deleting it
- Primarily the asset card should not be used as an error message holder

To take it a step further, the failure notification can have a [Retry] action with which the user can bring up the dataset creation dialog to make appropriate changes - this might however be too far fetched  

Am available to align with whoever will be resolving this..

**Comment by nadiagorchakova** [comment]
we should take it up after we are done with maps contractual obligations!

**Comment by janagombitova** [comment]
Removing failed datasets is handled in a separate issue and when an item in the library has a long name, handling this in a more user friendly way has been implemented. So this issue can be closed
