### ISSUE TITLE
Add data-test-id attribute to some elements in Lumen code

### ISSUE THREAD

**Issue by baztan106483** [akvo/akvo-lumen#1171]
# Context
We are using Puppeteer to simulate users of Lumen and now we want to do the tests in a new tenant:
https://lumencitest.akvotest.org

# Problem or idea
We need the data-test-id attribute to identify the HTML elements when we are doing the tests. We need a pull request of this properties to do the tests in the tenant we want, not locally.

**Comment by janagombitova** [comment]
@kardan Can you check the status of this issue?
