### ISSUE TITLE
Undo fail

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1175]
# Context

At the training in Liberia we were working with a rather large dataset:
https://liberia.akvolumen.org/dataset/5a180433-a122-4656-b4ee-ae06f47d682d

More than 30 transformations were applied to the dataset with the last one being merge transformation.

# Problem or idea

It looks like the last transformation caused all the rows to disappear (might have been a user mistake).
The problem is that it is not possible to undo the last action anymore, which makes this dataset useless and all the visualisations dependent on it - empty.

<img width="518" alt="screen shot 2017-11-29 at 13 07 38" src="https://user-images.githubusercontent.com/21127166/33376628-56ba07fa-d506-11e7-97a3-4744740f7ca0.png">

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment]
The issue was reported by a couple of other people:

this is the one from Nikki:  https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-88234-from-nikki-at-akvo-dot-org

And this is the one from Geert:  https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-89997-from-geerts-at-freedom-dot-nl

In Geert's case deletion of a merged dataset could be a potential reason too:
"I deleted the single merged column and then the dataset. Then it didn’t want to play along anymore
"

**Comment by nadiagorchakova** [comment]
@kardan looks like it's becoming a big issue. could you look into it?

**Comment by kardan** [comment]
With added logging I can observe:
```
09:43:27.974 [XNIO-5 task-1] INFO  akvo.lumen.transformation.engine - Unsuccessful undo of dataset: 59e7d22b-355f-4304-bae1-c9c88d3f6fe7
09:43:27.975 [XNIO-5 task-1] INFO  akvo.lumen.transformation.engine - Failed to transform: Error: cached plan must not change result type
```

https://github.com/pgjdbc/pgjdbc/pull/451

**Comment by kardan** [comment]
## More ref: 
- https://www.postgresql.org/message-id/200711090250.lA92ojX11076%40momjian.us
- https://jdbc.postgresql.org/documentation/94/server-prepare.html

## Statements:
- Apparently using "DISCARD ALL" within a transaction is a no no. 
- No prepared statement cache in the pool (https://github.com/brettwooldridge/HikariCP#statement-cache)
- Setting prepareThreshold=0 in the JdbcUrl (Postgres JDBC driver) do look promising. 

## Questions:
- What consequences does it have to make this change?

```Clojure
(defn pool
  "Created a Hikari connection pool."
  [tenant]
  (let [cfg (HikariConfig.)]
    (.setJdbcUrl cfg (str (:db_uri tenant)
                          "&prepareThreshold=0"))
    (.setPoolName cfg (:label tenant))
    (.setMinimumIdle cfg 2)
    {:datasource (HikariDataSource. cfg)}))
```

**Comment by kardan** [comment]
Investigating using "DEALLOCATE ALL" in transforms that affect the form of the table

**Comment by kardan** [comment]
Created a hot fix for this issue, but since we're working on deployments moving to Travis we need to do some work before we apply the fix
