### ISSUE TITLE
Map point coloring is broken for unique values containing two or more adjacent whitespace

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1177]
# Context
The map editor allows the coloring of geopoints by the unique values of some other column

# Problem or idea
When a unique value is a string containing two or more adjacent whitespace characters, the mapping of unique value to colour doesn't work, and the color shown in the legend isn't the color actually applied to the points for that value

To reproduce, just appling a color coding column to a map where that column contains at least one value that contains two spaces next to each other

# Solution or next step
I haven't looked into the bug yet, but I would guess that whitespace is being collapsed at some point in our processing pipeline, and at some point the uncollapsed string is being compared to the collapsed string and is failing to match

**Comment by nadiagorchakova** [comment]
![cc_lumen](https://user-images.githubusercontent.com/21127166/33440084-f432a772-d5e6-11e7-9a2d-743d36a7a89a.gif)

We experienced something similar at the training today.

The intention was to visualise seasonality with 0 - 12 standing for no. of months when water is not avaliable. We wanted to mark 10 - 12 in different shades of red as this is an acute case.
