### ISSUE TITLE
Points on the chart go outside the plot area

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1178]
# Context
At the Liberia training we practiced creating different types of charts, including line charts and scatter plots.

# Problem or idea
Some of the dots appear outside of the plot area, which is perceived by data analysts as a negative value.

<img width="800" alt="screen shot 2017-11-30 at 13 06 27" src="https://user-images.githubusercontent.com/21127166/33432438-cf4c4e2a-d5cf-11e7-891e-f38129d949d3.png">

As you can see from the source dataset, Population column has no negative values:

<img width="1274" alt="screen shot 2017-11-30 at 13 16 00" src="https://user-images.githubusercontent.com/21127166/33432655-be329c74-d5d0-11e7-8ffc-e341ca6693e2.png">

# Solution or next step

If data points are not negative, they should not appear in the negative area outside of the plot.

**Comment by janagombitova** [comment]
![screen shot 2019-01-07 at 11 55 59](https://user-images.githubusercontent.com/12456965/50764534-3e767380-1273-11e9-98dc-dca4a3cd0348.png)
We handle negative numbers in a more elegant way
