### ISSUE TITLE
Data import from url failed

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1189]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-85241-from-thomas-at-akvo-dot-org
Assignee: Camille Clerx

Message:
[AKVOLUMEN] Support request #85,241  
    
       
Request Info  
Device:  Personal computer  
Browser:  Safari 11.0.1  
OS:  OS X 10.11.6  
URL:  http://lumensupport.akvo.org/form  
 
 
 1- What do you need help with?  
I have a bug  
 
 2- What is the name of your instance? (xx.akvolumen.org)  
https://gt20.akvolumen.org/  
 
 3- What is the name of your dataset, visualisation or dashboard?  
Dataset "Headers"  
 
 4- What did you expect to happen?  
I should be able to update an imported via URL dataset.  
 
 5- What actually happened?  
Failed to update "Headers": Column mismatch  
 
 7- Which Akvo Hub do you usually work with?  
Europe  
 
 Tell us more about your request  
Importing a dataset via URL (which worked previously) and then attempting to Update the dataset, results in an error. Failed to update "Headers": Column mismatch 
Example dataset that fails, since a recent update of Lumen (Header test with older data): 
https://gt20.akvolumen.org/dataset/5a2933f2-9e3d-45ca-9783-414e0399429e 
Example dataset that works (based on the same URL) (FlenBlitzOct17 v2) 
https://gt20.akvolumen.org/dataset/59d76f17-a66a-4993-9413-b9b139ea8606 
A simple look at the imported CSV file indicates that it has at least one trailing space in a column name. And Daniel thought that this new feature may have caused this problem. 
"We improved derived column experience a bit by automatically removing leading and trailing whitespace in column names at import. We had a few cases reported that working with derived column formulas was hampered by ‘invisible’ whitespace’." 
For example column "Total number of participants ". 
The import URL is: https://api.thewaterhub.org/exportv2/export_all_excel.php?&amp;gid=38438&amp;_ga=2.210007957.1036526505.1512553674-1217766220.1512553674

**Comment by nadiagorchakova** [comment]
@peeb @kardan could you please look into it and suggest a possible solution?
The instance is currently being used by Ground Truth 2.0 project

**Comment by peeb** [comment]
:+1: @nadiagorchakova

**Comment by kardan** [comment]
### 5a2933f2-9e3d-45ca-9783-414e0399429e
No columns with trailing spaces

### 59d76f17-a66a-4993-9413-b9b139ea8606
``` clojure
({"sort" nil,
  "type" "text",
  "title" "Total number of participants ",
  "hidden" false,
  "direction" nil,
  "columnName" "c15"}
 {"sort" nil,
  "type" "text",
  "title" "Taste ",
  "hidden" false,
  "direction" nil,
  "columnName" "c98"}
 {"sort" nil,
  "type" "text",
  "title" "Borehole/Well flowrate   ",
  "hidden" false,
  "direction" nil,
  "columnName" "c100"})
```

When I tried the import url
https://api.thewaterhub.org/exportv2/export_all_excel.php?&amp;gid=38438&amp;_ga=2.210007957.1036526505.1512553674-1217766220.1512553674
returned.
```
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 95 bytes) in /home/api.thewaterhub.org/public_html/exportv2/PHPExcel/Worksheet.php on line 1218
```

We should make sure the update don't fail just because of the source is failing.

**Comment by kardan** [comment]
@bjelkeman were you able to update the last dataset now?

**Comment by peeb** [comment]
@kardan Might it be an idea to trim whitespace from headers in *existing datasets* when doing an update? This seems to me to be an adequate solution to this issue, unless I'm missing some nuance.

Since all headers are now trimmed on a new import anyway, it might make sense to normalize the existing dataset during the update?

**Comment by peeb** [comment]
Proceeding with the above ^^ after discussion with @kardan
