### ISSUE TITLE
Load all column metadata on first library load

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1197]
# Context
Currently, there are exactly 2 possible states for datasets in the client `library` store. They don't have names, so I'll make up some names.

### 1) Not-loaded
In which the client has a representation of `id`, `name`, `reason`, `status`, `modified`, `created` and `type`.

### 2) Fully-loaded
In which the client has a representation of the above, plus 3 additional properties: `transformations`, `columns`, and `rows`.

# Problem or idea
We need the columns for a dataset much more often than we need the transformations or the rows.

The rows are much larger than the list of columns, and much more sensitive/private.

Currently, every time we fetch the list of columns (e.g. to populate a dropdown in a menu) we fetch the rows as well, which can easily be 1000x as much data.

# Solution or next step
I propose we move the column list from state#2 to state#1 - i.e. we always load the column metadata for every dataset as soon as we load the library.

### Advantages
* Radically simplify client code (never need to send a request just to show a dropdown)
* Don't fetch the rows unless really needed, saving data and avoiding downloading potentially sensitive data when it's not needed
* Fewer requests to the backend (better on unreliable connections)

### Disadvantages
* More data to download on first run - could be a problem if there are many hundreds or thousands of datasets

**Comment by kardan** [comment]
Sounds good to me
