### ISSUE TITLE
Add unit tests for dataset merging

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#1199]
# Context
It is important that backend features are adequately tested.

# Problem or idea
Currently there are no unit tests for important backend subsystems, such as merging datasets. Since such features are complex, unit tests can add confidence.

# Solution or next step
Add unit tests for dataset merging feature.

**Comment by tangrammer** [comment]
closing now, test located here: https://github.com/akvo/akvo-lumen/blob/develop/backend/test/akvo/lumen/lib/transformation_test.clj#L573
