### ISSUE TITLE
Dataset data structure

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#12]
```json
{
  "id": "2Px3VGXSSwKm22b4CmGF",
  "name": "Dataset name",
  "source": {
    "type": "DATA_FILE",
    "name": "file_name.csv",
    "mimeType": "text/csv"
  },
  "periodicUpdate": null,
  "created": 1234434234,
  "modified": 12334325213,
  "headers": [
    {
      "title": "Column 1",
      "type": "NUMBER",
    }, 
    {
      "title": "Column 2",
      "type": "STRING",
    }, 
    {
      "title": "Column 3",
      "type": "DATE",
      "format": "dd-mm-yyyy"
    }
  ],
  "rows": [
    [1, "foo", 1454036337],
    [2, "bar", 1454036370],
    [3, "baz", 1454036402]
  ]
}
```

* `id`: I'm not sure if we will use numeric id's instead of alphanumeric. We should not expect a specific type/format.
* `name`: The name of the dataset
* `source.type`: The type of the data source. Initially one of `DATA_FILE` or `LINK`
  * `DATA_FILE`: `source.mimeType` initially the only supported file type is `'text/csv'`. `source.name` is the name of the file on disk
  * `LINK`: `source.url` will be the link url. We also need a `source.mimeType` for this. Could possibly be derived from response headers.
* `periodicUpdate`: Perhaps initially something as simple as `null | 'DAILY' | 'WEEKLY' | 'MONTHLY'`. Some `source.type`'s does not support periodic updates (for example `DATA_FILE`).
* `headers`& `rows`. This is where it gets tricky with lots of tradeoffs and options. This initial suggestion is "row oriented" but it might make just as much sense to make it column oriented, for exemple

```
{ 
  ...
  "columns": [
    {
      "title": "Column 1",
      "type": "NUMBER",
      "values": [1, 2, 3]
    },
    {
      "title": "Column 2",
      "type": "STRING",
      "values" ["foo", "bar", "baz"]
    },
    {
      "title": "Column 3",
      "type": "DATE",
      "format": "dd-mm-yyyy",
      "values": [1454036337, 1454036370, 1454036402]
    }
  ],
  ... 
}
```

ping @gabemart for comments / feedback / suggestions .

**Comment by iperdomo** [comment]
cc/ @kardan

**Comment by mtwestra** [comment]
@jonas @kardan @gabemart @iperdomo  Should we be looking at the datamodel of datagraft, if we are thinking of integrating with that?

**Comment by iperdomo** [comment]
@mtwestra we're going to get inspiration from datagraft. Definitely we're going to check their data model, but we'll need to see how much integration is possible, e.g.

* Their UI is an angular application, and we're using React
* I would like to define the steps in the pipeline as _data_. I need to double check but i think transformations are stored as code in datagraft.

**Comment by iperdomo** [comment]
Confirmed, transformations are just clojure code
https://github.com/dapaas/grafterizer-backend/blob/master/database-container/init-database.sql#L87-L92

**Comment by kardan** [comment]
I think the column based approach is best. I like the decoupling of "schema" and data. Especially if we get the user to define the column name / type. For certain data sources like the periodicUpdate links I guess we want to reuse the schema. One can also see the schema generation just like a transformation. And transformations in this context is another thing we need to discuss and might affect how we structure the dataset.

**Comment by kardan** [comment]
Small thing. It's something with the use of "headers" that feels odd. E.g.
´´´javascript
headers": [
    {
      "title": "Column 1",
      "type": "NUMBER",
    }, ]
```
What we are defining here is that the column type is "STRING" and the column header is "Column 1". Would it not make more sense with something like:
```javascript
:schema [{:header "Column 1" :type "NUMBER"}]  // alt a
:columns [{:header "Column 1" :type "NUMBER"}] // alt b
:data [[1, "foo"...] [2, "bar"]]
```

**Comment by kardan** [comment]
@jonase @iperdomo close this?

**Comment by jonase** [comment]
I would like to keep this open for now when we start implementing transformations on the client side.
