### ISSUE TITLE
Saving transformations - Support request #86,196 from Thomas

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1200]
Created via Reamaze:

Link: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-86196-from-thomas-at-akvo-dot-org

Message:
[AKVOLUMEN] Support request #86,196 from Thomas    
      
User email: thomas@akvo.org  
 
Request Info  
Device:  Personal computer  
Browser:  Safari 11.0.2  
OS:  OS X 10.12.6  
URL:  https://www.google.se/  
 
 
 1- What do you need help with?  
I would like to request a feature  
 
 2- Who will be using this feature?  
Creating dashboards  
 
 3- How do you want to use it?  
Saving transformations so one can easily pick from saved transformations would be very useful.  
 
 4- Why do you need to have it?  
Now transformations have to be copied and pasted between external documents and Lumen, which is cumbersome.  
   
 6- Which Akvo Hub do you usually work with?  
Europe  
 
 Tell us more about your request  
You probably have this on the list of things to do.

**Comment by kardan** [comment]
At the moment we have transformations and the "transformation log". We don't have transformation recipes. I know there have been talks about making a list of transformations as a first class thing. A related problem I know comes up from time to time is the possibility to edit a previous transformation. I think the transformation area is a thing that needs a proper review. There is multiple things that interact, things like how to identify columns when applying a list of transformation to a different dataset. Also if you are able to edit a previous transformation you run into the possibility that a later transformation depends on a previous one.

**Comment by nadiagorchakova** [comment]
I got a few other similar suggestions from Anabelle and Luuk: 
- to copy the transformation log and apply it to another identical dataset located in the same instance. The reasoning behind this request is that partners are often dealing with identical Flow datasets, just coming from different country offices. When you have to apply 50 similar transformations to a few datasets, it becomes quite time consuming.

**Comment by janagombitova** [comment]
Notes: We need to reconsider the value of this request in the light of our work done to simplify transformations. Most of the transformations users do are now handled in a user friendly way (Extract multiple values, split column) and more improvements are to come. Thus we need to check if this request is relevant in the new world

**Comment by janagombitova** [comment]
Based on comments above, closing this issue. If relevant in the future we will reopen it again
