### ISSUE TITLE
Axis labels don't clear up in scatter plot

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1214]
# Context

When I decide to switch a dataset while inside the Scatter plot editor, the axis labels do not clear up.
Also, I cannot choose a column anymore - the visualisation is unresponsive. 

![ezgif com-gif-maker 29](https://user-images.githubusercontent.com/21127166/34413913-a0993552-ebe6-11e7-92b8-c331a8da1136.gif)

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
No longer an issue. Fix is in production
