### ISSUE TITLE
Add custom keycloak login theme

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#1221]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by peeb** [comment]
Production version of this issue is here: https://github.com/akvo/akvo-platform/issues/5

**Comment by peeb** [comment]
# Notes

In the interests of maintainability going forward, I opted to extend/inherit the default Keycloak theme. This is done by creating a folder structure under `keycloak/theme/akvo`, in particular the `login` folder is worth taking a look at.

The theme is configured by the `theme.properties` file. Of interest is the `styles` directive. The value of this is critical as it must inherit the necessary style files otherwise the theme will not work. This is poorly documented in the Keycloak docs, unfortunately. 

```
styles=lib/patternfly/css/patternfly.css lib/zocial/zocial.css css/login.css css/custom.css css/logo.css
```

Here, only the last *two* files are created by us - everything else is part of the original keycloak theme. Since there is no mechanism to inherit or extend CSS files in Keycloak, you need to manually specify a list of them in the `styles` directive. The templates DO inherit. However, in our theme, we're not overriding any templates, we're just using the default Keycloak ones.

Therefore, our theme is a theme.properties directive file and a set of custom css files and images to use.

Worth noting is that the `css/login.css` file comes from the *keycloak* theme, not from our own theme. Unfortunately in the other theming areas like "account" and "admin" the css file can have various names - like "styles.css" or "account.css". This must be discovered by looking at the themes directory in the keycloak codebase.

In order for our new akvo theme to be set as default, the following command must be passed to `jboss-cli.sh`:

```
/subsystem=keycloak-server/theme=defaults/:write-attribute(name=default,value=akvo)
```

@dlebrero knows the most about JBoss configuration, FYI.

In our setup, this command is passed in in `Dockerfile`.

This work should hopefully provide a good basis for further tweaks of the themes via `theme.properties` and custom CSS overrides.

**Comment by dlebrero** [comment]
Thanks a lot Paul. All changes to be done as https://github.com/akvo/akvo-keycloak/issues/1
