### ISSUE TITLE
Styling dataset can be the same as shape dataset (advanced maps)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1236]
# Context

In the current iteration of advanced maps, we allow to select a 'styling dataset', which has to have a geopoint column:

<img width="1270" alt="screen shot 2018-01-19 at 15 02 40" src="https://user-images.githubusercontent.com/21127166/35154261-ddcc8d8a-fd29-11e7-9152-703525380658.png">

The idea here is that a user would want to use a survey as a styling dataset, which contains geopoint column. For instance, a user could visualise the average depth of water well across different districts.

# Problem or idea

It is possible that a shape dataset could contain an indicator or styling too. Obviously, a shape file doesn't have a geopoint column, only WKT column indicating shapes.
For example, this dataset from the UN contains data on shapes of admin units of Ethiopia, as well as population statistics for each admin unit:

https://lumen.akvotest.org/dataset/5a61f6e9-1de5-4b24-add6-4610334c2d81  

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment]
Joy approached me about this issue today.
In his words:

"so the shapefiles right now is dependant on other datasets for any kind of visualisation.

But in a lot of real-world scenarios, the shapefiles themselves contain data column.

Those may be numeric or text. So we need to visualise shapefiles as a data layer itself rather that it just acting as a container"

**Comment by janagombitova** [comment]
We had two issues for the same change (#2172). Keeping this one as the core issue
