### ISSUE TITLE
Cascading updates in 'related' datasets

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1247]
# Context

The issue was initiated by Joy. He writes:

"Assume 2 datasets dependant on each other say due to merging.
One dataset is a smaller size than other and hence the API is able to pull the data quicker.

    Registration form (with a couple of questions)
    Monitoring form , the heavier dataset

I’m merging a column from the monitoring set to the registration set

The registration form updates faster, but does not find the required rows in the monitoring set which are not there because of the longer time it takes to update.

This may lead to funky results.

Couple of possible solutions:
a. We can use “masking” so that updating can only be triggered one dataset at a time.
b. Updating a dataset triggers an update for all interdependent datasets before interdependent actions are executed."

# Problem or idea
What is the cause?

# Solution or next step

I think it would be best to consider cascading updates so that updating a dataset triggers an update for 'related' or dependent datasets. The first iteration of dataset updates didn't take it into account.

**Comment by Kiarii** [comment]
would it be technically possible to 'hold-off' visualization's auto-updating until dataset updating - to a single form data or to all form data - is complete? It might also be wise to consider how the user is notified of these events: 
* dataset update process
* dataset update outcome - success
* visualization update process;
* visualization update outcome

**Comment by nadiagorchakova** [comment]
we had a quick talk with @kardan about possible dependencies between datasets, updates and how it could possibly go wrong and decided to have a story mapping session about it after we release. Are you in @Kiarii ?

**Comment by Kiarii** [comment]
yes please..

**Comment by kardan** [comment]
Beside the cases we talked about there is also the case when someone manipulates the merged dataset in an incompatible way which makes things like undo fail. Other cases might be when someone update the merged in dataset directly. Then we also find ourselves trying to deal with two dataset out of sync. 

Maybe the issue is that we will always be in a situation where datasets is out of sync, but with merge and undo it's not a happy story :-(

**Comment by kardan** [comment]
I was probably not very clear earlier. But in general two different datasets are never "in sync". If we pull them from the Flow API it will not happen in a synchronised way, even if we do it as one job from the Lumen side. 

Expanding on the out "out of syncness", there is multiple ways to make the dataset that is merged into a parent into a state where it's not mergeable anymore. Things like transforming the dataset via normal work, updating the "merged in" dataset but not the parent (were we only want to undo). Etc.

**Comment by nadiagorchakova** [comment]
Kiarii and I had an interesting talk with @janagombitova on Flow data and when it can get out of sync in Lumen.

Maybe the biggest discovery was that Flow users **almost never delete questions in Flow surveys**. They are actually not allowed to do so in Flow unless they manually delete all collected data for this question first. That is not what people prefer to do normally.

**Other findings:**
- most often change in Flow is to a question name, e.g. to correct a typo - this will cause an update to fail in Lumen. I think it's directly related to this issue: https://github.com/akvo/akvo-lumen/issues/1281
- another change than can happen is change of question type in Flow. For instance, from free text to numeric to make it more restrictive. We did some tests with Jana - after this change in Flow (Flow API cache time is 1h), update will fail in Lumen. Do we want this update to go through in the future? Considering that it might potentially screw up some visualsations in Lumen... Something to look into.

These all is about the case when only one Flow dataset goes out of sync. We haven't started looking into merged datasets and dependecies between multiple datasets yet...

Link to mural board with user journey maps and some ideas: https://app.mural.ly/t/akvo8194/m/akvo8194/1520428940097/d1b07531a38dede66f2183602fe0e4c07b3096a8

@kardan @Kiarii  @finnfiddle @gabemart shall we find some time to recap and decide what to do next?
