### ISSUE TITLE
Deleting a layer doesn't update the map

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1248]
# Context

I experienced the issue in prod environment:

![deleting a layer](https://user-images.githubusercontent.com/21127166/35571951-c87e9a24-05d3-11e8-94d2-ad51a27aac6e.gif)

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
cant reproduce - possibly fixed in https://github.com/akvo/akvo-lumen/issues/1215
