### ISSUE TITLE
Introduce a spinner when data is loading

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1250]
# Context

Especially in countries with bad connectivity, users need visual feedback when something is loading.
When they see a white screen for a minute or two, they start doubting whether Lumen is still working and start to take actions, like re-loading the page, etc.

# Problem or idea
Perhaps we could introduce a spinner in parts of the UI where we know loading can take some time?

# Solution or next step

Something like that?

![image](https://user-images.githubusercontent.com/21127166/35620605-ea37939c-0681-11e8-9702-672ad0b12a69.png)

**Comment by finnfiddle** [comment]
@nadiagorchakova this is a bit broad - are there specific places in the app that are especially bad?

**Comment by nadiagorchakova** [comment]
I witnessed slow loading with large datasets (dataset editor), maps and even visualisations (where people saw a blank screen in the place of visualization preview
