### ISSUE TITLE
A new icon for raster data

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1265]
# Context

We don't have a suitable icon yet to display raster data in the library.
Imported raster data is shown as a dataset in the library, even though it's not. When you click on it, you get a raster image:

<img width="1280" alt="screen shot 2018-02-07 at 15 02 52" src="https://user-images.githubusercontent.com/21127166/35920391-05d081ae-0c18-11e8-8ccb-f2c6985961ab.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Is this issue already handled?

**Comment by finnfiddle** [comment]
@janagombitova I believe so yes 
<img width="280" alt="screen shot 2018-07-05 at 12 20 37 pm" src="https://user-images.githubusercontent.com/4628721/42314515-e1a55200-804d-11e8-89d9-cf7e4b6e5ebd.png">

**Comment by janagombitova** [comment]
Great. The we can close the issue
