### ISSUE TITLE
Enable eastwood linting

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#1276]
# Context
[eastwood](https://github.com/jonase/eastwood) is a Clojure code [linting](https://en.wikipedia.org/wiki/Lint_(software)) tool. Usually catches some easy to miss errors (wrong doc-strings, expressions that always evaluate to true|false, etc)

# Problem or idea
We used to run eastwood for checking our Clojure code at some point. The version 0.2.5+ supports Clojure 1.9.0 (the previous versions used to report lots of false positives)

# Solution or next step
Fix the current issues and enable eastwood as part of the build

**Comment by janagombitova** [comment]
@kardan what is the status of this issue?

**Comment by kardan** [comment]
We're running Eastwood as part of your build process, hence closing the issue
