### ISSUE TITLE
Transformation undo running perpetually

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1287]
# Context

Saw the issue in a couple of production instances:
- Karolina reported the issue happening in wcaro.akvolumen.org
- I have it in my own instance nadia.akvolumen.org

In both cases datasets are quite large > 20.000 rows.

# Problem or idea
Transformation undo gets stuck - 'in progress' forever:

<img width="321" alt="screen shot 2018-02-20 at 14 12 18" src="https://user-images.githubusercontent.com/21127166/36426284-dc391bee-1649-11e8-9e3b-5d17f892b9cb.png">

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
I have checked datasets on the wcaro.akvolumen.org instance. In most of the cases Undo worked as it should. I have one case where I got a 502. 

Here are the details: 
Dataset: https://wcaro.akvolumen.org/dataset/5a9d8082-270b-459a-b8dc-3ae939ff3735
![screen shot 2018-11-16 at 10 34 42](https://user-images.githubusercontent.com/12456965/48613537-4f4deb80-e98c-11e8-8c01-205a1fefe3d2.png)

**Comment by janagombitova** [comment]
Steps to take to reproduce: 

1. Run a simple transformation on the column, Is the facility functional? like changing to uppercase. 
2. Then Undo
3. In console you will see the error. 
4. Refresh page. 
5. Check that the transformation was actually undone on the column and removed from the log

**Comment by tangrammer** [comment]
@janagombitova could you give me access to this tenant? 🙏
