### ISSUE TITLE
Rework allowed JavaScript

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1296]
# Context
This came up when a user tried to make a derived column from a column name that included the word "function". In this case:
```javascript
row["Is the facility functional?"] = "yes" ? "1" : "0"
```
I do guess the user wants to use double equals, but that beside the point.
```javascript
row["Is the facility functional?"] == "yes" ? "1" : "0"
```

# Problem or idea
The problem is that we disallow the word "function" because of the security implications it would have to allow users to create functions. 
https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/transformation/derive.clj#L37

We want to take great precautions, protect us from call to the JVM but also race conditions with recursions and similar problems. 

# Solution or next step
There is a way to get an AST back from Nashorn:

```
(require '[clojure.pprint :refer [pprint]])
(require '[cheshire.core :as json])
(import
  [javax.script ScriptEngineManager ScriptEngine Invocable ScriptContext Bindings SimpleScriptContext]
  [jdk.nashorn.api.scripting NashornScriptEngineFactory ClassFilter ScriptUtils])

;; Setup
(def script-engine-manager (ScriptEngineManager. ))
(def nashorn-engine (.getEngineByName script-engine-manager "JavaScript"))
(def ctx (SimpleScriptContext.))

;; Load parser into the js context
(.eval nashorn-engine "load('nashorn:parser.js');", ctx)

;; Tenary
(clojure.pprint/pprint
  (json/decode 
    (.eval nashorn-engine "JSON.stringify(parse('true == true ? true : false') )", ctx))) 
;; =>
{"type" "Program",
 "body"
 [{"type" "ExpressionStatement",
   "expression"
   {"type" "ConditionalExpression",
    "test"
    {"type" "BinaryExpression",
     "operator" "==",
     "left" {"type" "Literal", "value" true},
     "right" {"type" "Literal", "value" true}},
    "consequent" {"type" "Literal", "value" true},
    "alternate" {"type" "Literal", "value" false}}}]}

;; Tenary with variable assignment
(clojure.pprint/pprint
  (json/decode 
    (.eval nashorn-engine "JSON.stringify(parse('var n = 1; true == true ? n : 0; ') )", ctx)))
;; =>
{"type" "Program",
 "body"
 [{"type" "VariableDeclaration",
   "declarations"
   [{"type" "VariableDeclarator",
     "id" {"type" "Identifier", "name" "n"},
     "init" {"type" "Literal", "value" 1}}]}
  {"type" "ExpressionStatement",
   "expression"
   {"type" "ConditionalExpression",
    "test"
    {"type" "BinaryExpression",
     "operator" "==",
     "left" {"type" "Literal", "value" true},
     "right" {"type" "Literal", "value" true}},
    "consequent" {"type" "Identifier", "name" "n"},
    "alternate" {"type" "Literal", "value" 0}}}]}

;;  function
(pprint
  (json/decode 
    (.eval nashorn-engine "JSON.stringify(parse('var f = function (x) {x};') )", ctx))) 
;; =>
{"type" "Program",
 "body"
 [{"type" "VariableDeclaration",
   "declarations"
   [{"type" "VariableDeclarator",
     "id" {"type" "Identifier", "name" "f"},
     "init"
     {"type" "FunctionExpression",
      "id" nil,
      "params" [{"type" "Identifier", "name" "x"}],
      "defaults" [],
      "rest" nil,
      "body"
      {"type" "BlockStatement",
       "body"
       [{"type" "ExpressionStatement",
         "expression" {"type" "Identifier", "name" "x"}}]},
      "generator" false,
      "expression" false}}]}]}

;; Arrow function
(clojure.pprint/pprint
  (json/decode 
    (.eval nashorn-engine "JSON.stringify(parse('var func = (x) => x + x; func(2);') )", ctx)))
;; =>
{"type" "Program",
 "body"
 [{"type" "VariableDeclaration",
   "declarations"
   [{"type" "VariableDeclarator",
     "id" {"type" "Identifier", "name" "func"},
     "init"
     {"type" "BinaryExpression",
      "operator" "=>",
      "left" {"type" "Identifier", "name" "x"},
      "right"
      {"type" "BinaryExpression",
       "operator" "+",
       "left" {"type" "Identifier", "name" "x"},
       "right" {"type" "Identifier", "name" "x"}}}}]}
  {"type" "ExpressionStatement",
   "expression"
   {"type" "CallExpression",
    "callee" {"type" "Identifier", "name" "func"},
    "arguments" [{"type" "Literal", "value" 2}]}}]}

**Comment by kardan** [comment]
Turns out people have derived columns using things like Date.now(). If I'm not mistaken that one would render an empty column but one could imagine someone having Date().toString(), but we need to do a full query of existing derived operations to know exactly.

**Comment by tangrammer** [comment]
trying/exploring https://github.com/javadelight/delight-nashorn-sandbox/ as foundation to communicate with nashorn

**Comment by tangrammer** [comment]
@kardan how many memory should we allow js-engine to use? and/or MaxCPUTime?
https://github.com/javadelight/delight-nashorn-sandbox#usage

and braces?
https://github.com/javadelight/delight-nashorn-sandbox/blob/ca1f8ce333d06a1a0a09494bf529f8382eb9417d/src/main/java/delight/nashornsandbox/NashornSandbox.java#L204-L248

**Comment by tangrammer** [comment]
after reading all docs (that I've found ;)  )related to executing js in lumen-backend, it seems that all problems described in https://github.com/akvo/akvo-product-design/issues/192#issuecomment-261248979 are covered in https://github.com/javadelight/delight-nashorn-sandbox

**Comment by tangrammer** [comment]
+ topics in WIP
+ adding specs https://github.com/akvo/akvo-lumen/compare/specs#diff-11f30678676d2439da0b11f8238f747e
+ decoupling js-execution&error-handling from clj-execution&error-handling from db-execution&error-handling. This decoupling is tricky thus result depends on the ::t.engine/error-strategy to choose an execution impl. (eg: “leave-empty” or “delete-row” let us to execute in parallel js and sql without finishing any of them [of course always inside a tx] but “fail” force impl to wait until js-execution has finished without errors before calling db-updates)
+ improve performance with updating bunch of rows (~ 8000 aprox) in each update db call. Code still waiting for some sort of http://clojuredocs.org/clojure.core/split-at
+ extracting js-engine details to its own ns https://github.com/akvo/akvo-lumen/compare/specs#diff-397b6ce33d7447d4ab2a757db9f893de
+ replacing js engine details with  https://github.com/akvo/akvo-lumen/compare/issue/1296-js-engine#diff-447779b93863a0b103d1697460471585
+ refactoring current PR in several ones to merge functionality carefully

**Comment by tangrammer** [comment]
results of https://github.com/akvo/akvo-lumen/commit/5ebaff6cf8b931378277ee67213ebae8ff679847
``` 
2018-05-10T09:36:05,624 [nREPL-worker-1] INFO  a.l.transformation.derive.js-engine - :js-engine: 10.2907
2018-05-10T09:36:06,039 [nREPL-worker-1] INFO  a.l.transformation.derive.js-engine - :js-engine: 3.7215
2018-05-10T09:36:06,382 [nREPL-worker-1] INFO  akvo.lumen.transformation.derive - :row-transform-fn: 345.9125
2018-05-10T09:36:07,511 [nREPL-worker-1] INFO  akvo.lumen.transformation.derive - :all-data: 1127.2222
2018-05-10T09:36:07,514 [nREPL-worker-1] INFO  akvo.lumen.transformation.derive - :js-execution-seq: 0.8638
2018-05-10T09:36:07,517 [nREPL-worker-1] INFO  akvo.lumen.transformation.derive - :add-column: 1.1428
2018-05-10T09:36:16,255 [nREPL-worker-1] INFO  akvo.lumen.transformation.derive - :set-db-values: 8736.123
2018-05-10T09:36:16,258 [nREPL-worker-1] INFO  akvo.lumen.transformation.derive - :derive: 10222.7533
```
100K rows  => 10222.7533 msecs :)

**Comment by kardan** [comment]
Nice!

**Comment by tangrammer** [comment]
https://github.com/akvo/akvo-lumen/commit/a7209d69a71889121b9308d50a83958f349489f8

`100K => 9606.0721 msecs` 

```
14:21:50.515 [nREPL-worker-36] INFO  akvo.lumen.import - :iterate-do-import: 55516.8967
14:21:52.655 [nREPL-worker-36] ERROR akvo.lumen.transformation-test - :rows-to-process 100068
14:21:52.729 [nREPL-worker-36] INFO  a.l.transformation.derive.js-engine - :js-engine: 64.7071
14:21:54.453 [nREPL-worker-36] INFO  a.l.transformation.derive.js-engine - :js-engine: 5.0999
14:21:54.741 [nREPL-worker-36] INFO  akvo.lumen.transformation.derive - :add-column: 0.9407
14:22:02.824 [nREPL-worker-36] INFO  akvo.lumen.transformation.derive - :Set-vals: 8081.3889
14:22:02.827 [nREPL-worker-36] ERROR akvo.lumen.transformation.derive - :rows-processed 100068
14:22:02.830 [nREPL-worker-36] INFO  akvo.lumen.transformation.derive - :derive: 9606.0721

```
