### ISSUE TITLE
Usability problem when a map has too many points

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1305]
# Context

Akvo often supports partners with nation-wide water point mapping. This results in a map with *a lot* of points on it. It would look something like that:

<img width="1275" alt="screen shot 2018-02-26 at 15 27 32" src="https://user-images.githubusercontent.com/21127166/36675550-9e040284-1b09-11e8-8143-fc163202cc60.png">

# Problem or idea

It's very difficult to make sense of such a map. As an M&E manager or Project Officer, what do I do with this information? (Unless what a user wants to show is simply the multitude of points on the map. Which is also the case sometimes...)

# Solution or next step
@finnfiddle suggested heat maps as a possible solution. 
Clustering of points could be another option too - Flow maps do that afaik

**Comment by finnfiddle** [comment]
I attempted this one but realized half way its mostly a backend job. maybe better idea if someone else tackles it
