### ISSUE TITLE
Renamed column - legend for geoshape not updated

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1309]
# Context
I renamed a dataset column after I built a map that uses this dataset. I had to rename the column as the original name was too long for the available space in the legend.

My expectation was that when I rename a column, the map legend that is using it will update as well.

# Problem or idea

The map legend was not updated. As you can see on the screenshot below, the dropdown on the left shows the new name, while the legend still shows the old.

<img width="1274" alt="screen shot 2018-02-28 at 11 21 32" src="https://user-images.githubusercontent.com/21127166/36783142-718bffc2-1c7b-11e8-9656-bce328e3514d.png">

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
not reproducible
