### ISSUE TITLE
In Liberia instance Resources window is empty

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1315]
# Context

Liberia instance has activity but it's not recorded in resource usage page:

<img width="626" alt="screen shot 2018-03-01 at 15 03 34" src="https://user-images.githubusercontent.com/21127166/36850523-583e2c88-1d67-11e8-9553-0a9d9c4d5a82.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Issue no longer exists as it is solved
