### ISSUE TITLE
Option to change the order of map layers

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1328]
# Context
We now support multiple layers in Lumen maps.
When creating a map you need to be careful which layer to set up first, as coloured geo-shapes, for example, can partially obscure a layer with datapoints.

# Problem or idea
Would be nice to have an option to decide which layer to bring forward or backward, in other words, toggle between layers.

# Solution or next step
How could we solve it?

**Comment by gabemart** [comment]
Discussion from milestone planning: for now, let's have a simple "up arrow/down arrow" system. 

Ultimately, a drag-and-drop list might be more user friendly.

**Comment by nadiagorchakova** [comment]
released
