### ISSUE TITLE
Display min/man values on geo-shape legend

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1329]
# Context
Geo-shape legend shows a color scale but without indication of what min/max values are exactly.
<img width="248" alt="screen shot 2018-03-12 at 13 55 02" src="https://user-images.githubusercontent.com/21127166/37284786-2d282a96-25fd-11e8-9cc0-eea0bff73b2c.png">

# Problem or idea
It would be helpful to know what those min/max values are. Analysing the map based on intensity of colour alone can be difficult.  

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Still relevant
