### ISSUE TITLE
Turn off column name or layer name in map legend

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1333]
# Context

Feedback from Thomas:

In the Legend on a map, we now get a name for the Layer. I also get a name for the column displayed. But if I only have one layer to display, this becomes a bit redundant. It would be good to be able to turn off the column name or the layer name.

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
![screen shot 2019-01-07 at 12 13 56](https://user-images.githubusercontent.com/12456965/50765287-c1003280-1275-11e9-9a9c-2b5ca7b1ad1f.png)
Indeed, having both is quite redundant. It would be different if one layer held more data variables, but it is usually one layer = one variable, having double naming is not helpful or useful. In some cases users remove the layer name and keep on a space there to avoid the redundancy
