### ISSUE TITLE
How large files do we allow for cases when the resumed library is used

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1356]
# Context
Thought that we had a 50mb limit on files.

# Problem or idea
Looks like larger files are allowed. At least when it comes to raster. A thought is that the resumed does not honor client-max-body-size (obviously) and will allow files of any size.

# Solution or next step
We should at least know the situation.

**Comment by nadiagorchakova** [comment]
Ivan says it's 100mb for raster.

**Comment by iperdomo** [comment]
The resumed library has a `max-file-size` setting that we're currently set to 100 MB.
https://github.com/akvo/akvo-lumen/blob/v0.24.0/backend/resources/akvo/lumen/system.edn#L102

There was an issue in the resumed library that didn't honor that max size. Already solved 
https://github.com/akvo/resumed/issues/6

`[org.akvo/resumed "1.27.7406c5e5be3ccd6d9e1f99d29f05ab1251682de7"]`
