### ISSUE TITLE
WKT in shape file exists but map creation fails.

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1359]
# Context

Molo encountered some problems while using shape file with Ugandan sub counties in Lumen.

Shape file in Lumen: https://lumen.akvotest.org/dataset/5ab8ee6a-67fb-4408-bbd2-9afdca63512f
Original data: https://drive.google.com/drive/u/0/folders/0B8E_9GJMK5liR3lrTUFIUUJXQjA

I converted shape file to csv with WKT using QGIS

# Problem or idea
The shape dataset containg geoshapes loads to Lumen without any errors:

<img width="1280" alt="screen shot 2018-03-26 at 15 02 39" src="https://user-images.githubusercontent.com/21127166/37907906-b968c5c4-3106-11e8-970f-c3dc14247741.png">

However, when I want to use it in a map, I get something like that:

<img width="1277" alt="screen shot 2018-03-26 at 15 03 45" src="https://user-images.githubusercontent.com/21127166/37907972-dfc56a10-3106-11e8-9702-5ac2c15104f7.png">

Even if I manually zoom in to Uganda, I still don't see any shapes displayed there.

# Solution or next step
@kardan @iperdomo do you have a clue what might be going on?

**Comment by iperdomo** [comment]
We don't do any transformation of the shapefile and we expect it's using a specified projection (http://epsg.io/4326)

See: https://github.com/akvo/akvo-lumen/blob/v0.24.0/backend/src/akvo/lumen/import/common.clj#L79-L80

This shapefile is using a different projection (https://epsg.io/32636) so the numbers don't _match_

````
$ cat Uganda_Subcounties2010.prj
PROJCS["WGS_1984_UTM_Zone_36N",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",200000.0],PARAMETER["Central_Meridian",33.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]
````

An example of the projection data of another _working_ file

````
$ cat CIV_G2015_4.prj 
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]
````

**Comment by nadiagorchakova** [comment]
Hey @iperdomo , I picked projection WGS 84 when saving the file from QGIS:

<img width="1275" alt="screen shot 2018-03-27 at 10 11 53" src="https://user-images.githubusercontent.com/21127166/37955012-a63cab18-31a7-11e8-9e69-3a26b77dee65.png">

It looks like it's the same as specified here: http://epsg.io/4326

Is it correct? If yes, what else could be the reason?

**Comment by iperdomo** [comment]
@nadiagorchakova i don't really know QGIS :/ so i can't tell why the re-projection didn't happen

**Comment by tangrammer** [comment]
Relates to #1364
