### ISSUE TITLE
more elaborate error message when dataset update fails

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1361]
# Context

As we discussed with Kiarii, Daniel and Finn, Flow users are allowed to change question data type in a Flow form. For instance, they can change free text to number to restrict the kind of responses they are getting. In this case dataset update through Lumen will fail.

# Problem or idea
When we fail the dataset update, we give a rather generic error message:

<img width="595" alt="screen shot 2018-03-26 at 15 29 00" src="https://user-images.githubusercontent.com/21127166/37909149-737279b2-310a-11e8-9616-8e5b76bd04ec.png">

As a result, users do not know what action to take next and might think it's a bug in Lumen. 
It would be better to give more specific error - which column was the reason for the update failure and why. 

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
@tangrammer came with the idea to Enhance the error message to hold: dataset name - which tranformation is causing the update to fail - reason for failure. 

For example: "Failed to update dataset "Sparkx (Ghana)": transformation X references a column that doesn't exist in the dataset"

This will give Salim more information to act upon.

**Comment by janagombitova** [comment]
Closing this issue. I assume we will improve the errors on a case by case basis.
