### ISSUE TITLE
option to add metadata to raster layer legend

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1362]
# Context

I got the following feedback at Lumen maps webinar:

Raster layer legend shows min and max values for the colour range, however, it's not always clear to an outsider what these numbers mean exactly.

<img width="883" alt="screen shot 2018-03-26 at 15 51 22" src="https://user-images.githubusercontent.com/21127166/37910366-a3117f58-310d-11e8-9a7f-2e945ee3a118.png">

# Problem or idea
Would it be at all possible to extract this data from raster file and display it in the legend? Or do we just get numbers in a grid without any attributes on what this numbers mean? @iperdomo @gabemart 
In the example above, it's probably 'people' we're talking about, but we just see a number.

# Solution or next step
How could we solve it?

**Comment by iperdomo** [comment]
Raster meaning is usually shared in a different medium. 

If you take a look at http://www.worldpop.org.uk/data/summary/?doi=10.5258/SOTON/WP00033 (the estimated population density for Burina Faso) the explanation of what each _pixel_ means comes in the dataset _metadata_

>DATASET: Alpha version 2010 and 2014 estimates of numbers of people per grid square, with national totals adjusted to match UN population division estimates (http://esa.un.org/wpp/). 
>REGION: Africa 
>SPATIAL RESOLUTION: 0.00833333 decimal degrees (approx 100m at the equator) 
>PROJECTION: Geographic, WGS84 
>UNITS: Estimated persons per grid square 
>MAPPING APPROACH: Land cover based, as described in: Linard, C., Gilbert, M., Snow, R.W., Noor, A.M. and Tatem, A.J., 2012, Population distribution, settlement patterns and accessibility across Africa in 2010, PLoS ONE, 7(2): e31743. 
>FORMAT: Geotiff (zipped using 7-zip (open access tool): www.7-zip.org) 
>FILENAMES: Example - AGO10adjv4.tif = Angola (AGO) population count map for 2010 (10) adjusted to match UN national estimates (adj), version 4 (v4). Population maps are updated to new versions when improved census or other input data become available. 
>DATE OF PRODUCTION: January 2013 
>
>Dataset construction details and input data are provided here: www.afripop.org and here: http://www.plosone.org/article/info:doi/10.1371/journal.pone.0031743 

If we get the info about the specific `.tif` file we just get _numbers_
````
$ gdalinfo BFA10adjv3.tif
Driver: GTiff/GeoTIFF
Files: BFA10adjv3.tif
       BFA10adjv3.tif.aux.xml
Size is 9510, 6819
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-5.519091642688500,15.083266411176101)
Pixel Size = (0.000833300000000,-0.000833300000000)
Metadata:
  AREA_OR_POINT=Area
  DataType=Generic
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  -5.5190916,  15.0832664) (  5d31' 8.73"W, 15d 4'59.76"N)
Lower Left  (  -5.5190916,   9.4009937) (  5d31' 8.73"W,  9d24' 3.58"N)
Upper Right (   2.4055914,  15.0832664) (  2d24'20.13"E, 15d 4'59.76"N)
Lower Right (   2.4055914,   9.4009937) (  2d24'20.13"E,  9d24' 3.58"N)
Center      (  -1.5567501,  12.2421301) (  1d33'24.30"W, 12d14'31.67"N)
Band 1 Block=128x128 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=512.446 
  Minimum=0.000, Maximum=512.446, Mean=0.485, StdDev=3.667
  NoData Value=-3.40282299999999995e+38
  Metadata:
    STATISTICS_COVARIANCES=13.4459083470104
    STATISTICS_MAXIMUM=512.44641113281
    STATISTICS_MEAN=0.48497704824117
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=3.6668662843101
````

So without a richer dataset/raster metadata it is difficult so show a meaningful legend.

**Comment by nadiagorchakova** [comment]
I see, thanks for investigating Ivan. 
So, if raster metadata is usually shared through a different medium, perhaps it would make sense to allow users add annotations to a map to explain what's going on there. 
Another option would be to let users edit the legend to add metadata directly there. However, it sounds like it's way more complicated to implement.

**Comment by iperdomo** [comment]
@nadiagorchakova i think this needs to be solved by a proper _metadata_ handling at raster/dataset level

IMHO our current support for raster is not targeting _data analysis_ just maps.By rendering colors we just give a sense of magnitude (less, more). We should remove the values to avoid confusion (or should be optional)

**Comment by nadiagorchakova** [comment]
Perhaps I misunderstood. Raster files/datasets carry some metadata after all, Lumen just doesn't read it at the moment, right? 

Indeed, we're not targeting data analysis in raster maps yet, as we don't have a good feel for what our partners/or solutions need there. 

You're saying: "We should remove the values to avoid confusion (or should be optional)" - Do you mean the values in the raster legend? I think they are still valuable if your title the raster layer as 'population density, ppl per km' or smth like that.

**Comment by iperdomo** [comment]
> Perhaps I misunderstood. Raster files/datasets carry some metadata after all, Lumen just doesn't read it at the moment, right?

No, you have it right. There are some values encoded in the TIF file, but is not metadata about the meaning of each pixel. At least not something you can then append to a legend in a map.

> You're saying: "We should remove the values to avoid confusion (or should be optional)" - Do you mean the values in the raster legend? I think they are still valuable if your title the raster layer as 'population density, ppl per km' or smth like that.

For knowing that a number represent "ppl per km" you need to know the metadata of the raster. Not included in the tif file itself.

**Comment by nadiagorchakova** [comment]
Ok, all clear for now. 
Yes, people would need to know the metadata of the raster. My assumption is that they know where they got it from and that they have an idea what it's about. But it's just an assumption.
