### ISSUE TITLE
use categorical data in geo shape layer styling

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1363]
# Context

Annabelle suggested the following enhancement to geo shape styling.

Based on her experience, a user might want to colour geo shapes on a map according to her own logic. For instance, she knows after doing the analysis that counties 1, 2 and 3 are not meeting the standards on water quality. So she wants to colour counties 1, 2 and 3 in red and the rest - in green. 

In this case, we would probably need to display unique values from 'County' column in shape file and use colour picker to manually apply colours to county shapes. 

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
In essence, this issue relates to #2168 where the shapes are styled based on a variable, meeting the criteria and not meeting the criteria but the 'randomness' is not something we aim to support. We aim to allow styling shapes based on text columns. Thus this issue can be closed
