### ISSUE TITLE
Cannot highlight block of text in a text box (dashboards)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1366]
# Context

Andrew Molo shared with me an issue he encountered in a Lumen training.

In Lumen dashboards, we support adding text boxes, where partners often add some narrative about the charts and their findings in general.

# Problem or idea
It's not possible to highlight a block of text in a text box. Sometimes you want to highlight a block of text to delete it at once, for instance. What one expects to be a highlighting action, just moves the text box around on the dashboard:

![ezgif com-gif-maker 40](https://user-images.githubusercontent.com/21127166/38027243-523ace26-328f-11e8-9c85-a674e1c66677.gif)

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Issue is resolved with the new text editor implemented in 2018
