### ISSUE TITLE
It shouldn't be possible to right-click and save image from a map pop-up

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1369]
# Context
Had a chat with @Lynngre about our compliance with GDPR.
She advised to disallow saving an image from a map pop-up window. The reason is that partners need an explicit consent from their respondents to allow distributing their images, which they might not have. 
Currently, it's possible to save an image by right-clicking on it:

<img width="583" alt="screen shot 2018-04-03 at 15 05 24" src="https://user-images.githubusercontent.com/21127166/38251283-5529d692-3751-11e8-8906-e775ad4c069e.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by gabemart** [comment]
@nadia currently the thumbnail image is a link to the full-size image. I would imagine that if partner want to disable "save as" functionality, they would also want to remove the link to the full-size image?

We can prevent the context menu from appearing, but we should be clear that this doesn't actually prevent anyone redistributing the image, it just makes it a bit less convenient. Any method we use to display the image will let someone save and redistribute the image.

**Comment by nadiagorchakova** [comment]
@gabemart I think you mentioned a different nadia in your comment above... so I wasn't notified about it.
good point. yes, as a next step we should also check if we could remove a link to the image.

**Comment by finnfiddle** [comment]
@nadiagorchakova  I think if the user can see the image in the browser then it already has been distributed. there is nothing stopping someone downloading it at this stage. we can only make it a bit less convenient as @gabemart says

**Comment by Lynngre** [comment]
Someone should check with the Flow team about how these links stored on Amazon are changing. The last I heard, it may be updated so that only if someone is logged into their Flow dashboard, will the url be available openly.

**Comment by nadiagorchakova** [comment]
@janagombitova

**Comment by nadiagorchakova** [comment]
Tested the issue in production -  one cannot see any link to the full size image anymore. The context menu is also suppressed. Seems like this task has been completed already. I will close the issue.
