### ISSUE TITLE
Consent to our terms of use first time a user logs in

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1370]
# Context
@Lynngre and I had a chat about our compliance with GDPR.
We'll need a user to explicitly consent to our terms of use when they log in to the system **for the first time**. The consent form should contain a link to our terms of use.
@iperdomo I would guess it might have to do with Keycloak as well?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Handled with Auth0
