### ISSUE TITLE
Update API endpoint

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1377]
# Context
Users can add Data sets that are more or less a reference to a source (Flow and Link). These datasets can be updated manually in the UI. This means that Lumen will go fetch the dataset, and then apply transformations added by the user to get a new dataset which has new updates data while previous work to transform the dataset is kept.

# Problem or idea
At the moment issuing an update is a manual process. The manual update has always been version one of the update feature. Lumen have users that require the update to happen daily. Hence this becomes a chore that takes a lot of effort. Building a full update scheduling system into Lumen is a non-trivial task requiring UI work and an available scheduler. 

# Solution or next step
An intermediate solution would be to allow an external user to hit an endpoint to update.

1. Request (with valid access token from Keycloak) -> akvo-lumen.org/api/dataset/update 
2. Lumen would update the dataset and return when the update process is done.

Keeping this endpoint synchronous would allow the external script to know when the update is done. As context, the way we do it in the client is via async calls where we return a token which the client can use to pool the backend with.

**Comment by kardan** [comment]
We already have an update endpoint which can be called with a valid token.

**Comment by nadiagorchakova** [comment]
@kardan does it mean that Joy can already trigger that update endpoint for his daily updates? Or what is the latest status of discussion with Keycloak guys?

**Comment by kardan** [comment]
Today in Lumen there is an endpoint that the Lumen client uses. With a valid token from Keycloak it's possible to request an update on a specific dataset. A valid token can be requested with user credentials.

**Comment by kardan** [comment]
Hitting the update button in the UI for a random FLOW dataset will cause the following request:
```
Request URL: https://lumen.akvotest.org/api/datasets/5afa9dc2-697d-4939-a0fd-5b1ccb133183/update
Request Method: POST
Status Code: 200 
content-type: application/json; charset=utf-8
date: Thu, 21 Jun 2018 09:35:59 GMT
server: nginx/1.11.10
status: 200
via: 1.1 google
:authority: lumen.akvotest.org
:method: POST
:path: /api/datasets/5afa9dc2-697d-4939-a0fd-5b1ccb133183/update
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,sv;q=0.8
authorization: Bearer ey ... w
cache-control: no-cache
content-length: 1245
content-type: application/json
origin: https://lumen.akvotest.org
pragma: no-cache
referer: https://lumen.akvotest.org/library
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36
{"refreshToken":"ey..."}
```
The response was:
```
{"updateId":"5b2b717f-8e31-4716-9de7-87edcef92938"}
```
Then the updateId can be used to query for the progress of the import via a GET to
https://lumen.akvotest.org/api/job_executions/5b2b717f-8e31-4716-9de7-87edcef92938

{"jobExecutionId":"5b2b717f-8e31-4716-9de7-87edcef92938","status":"PENDING","kind":"AKVO_FLOW","reason":null}
...
{"jobExecutionId":"5b2b717f-8e31-4716-9de7-87edcef92938","status":"OK","datasetId":"5afa9dc2-697d-4939-a0fd-5b1ccb133183"}

...
GET https://lumen.akvotest.org/api/datasets/5afa9dc2-697d-4939-a0fd-5b1ccb133183 will return the dataset

**Comment by dedenbangkit** [comment]
it works! thank you @kardan

**Comment by dedenbangkit** [comment]
I've tried to trigger the update endpoint, It returns 200 with this value:
```
{'updateId': '5c995be9-5c8a-4ecf-b0a2-bd7be7e16405'}
```
But the response of JobExecution endpoint loop is failed when we use Akvo Flow dataset, response:
```
{'jobExecutionId': '5c995be9-5c8a-4ecf-b0a2-bd7be7e16405', 'status': 'FAILED', 'kind': 'AKVO_FLOW', 'reason': 'Null cause from instance: angkorsalad'}
```
Code:
```
def refreshData():
    tokens = requests.post(tokenURI, rtData).json();
    return tokens['refresh_token']

def getAccessToken():
    account = {
        'client_id':'curl',
        'refresh_token': refreshData(),
        'grant_type':'refresh_token'
    }
    try:
        account = requests.post(tokenURI, account).json();
    except:
        logging.error('FAILED: TOKEN ACCESS UNKNOWN')
        return False
    return account

refresh_token = account["refresh_token"]
access_token = account["access_token"]

def getResponse(url,rtype):
    header = {
        'authorization':'Bearer ' + access_token,
        'accept':'*/*',
        'content-type':'application/json',
        'user-agent':'python-requests/2.14.2'
    }
    params = {'refresh_token' : refresh_token}
    if rtype == "post":
        response = requests.post(url, headers=header, params=params).json()
    else:
        response = requests.get(url, headers=header, params=params).json()
    return response
```

**Comment by tangrammer** [comment]
Sentry issue: [LUMEN-BACKEND-PRODUCTION-56](https://sentry.io/organizations/akvo-foundation/issues/888752221/?project=157354&referrer=github_plugin)

**Comment by tangrammer** [comment]
@dedenbangkit following sentry issue there was an auth problem around your last attempt 
`{\"error\":\"invalid_grant\",\"error_description\":\"Invalid refresh token\"}", :trace-redirects []}` 
🤔

**Comment by dedenbangkit** [comment]
@tangrammer I'm not sure why, but for the other GET requests from Lumen API works well with this method (eg. getting Lumen datasets columns and rows to download it as excel / csv). Currently we use selenium driver running in our local machine, but we don't know how to run it in Kubernetes without X display server.

Np: I don't have access to Sentry issue.

**Comment by dedenbangkit** [comment]
Hi Lumen Dev, is there any other alternative to have trigger update without using selenium? Dan (Lebrero) has concerned with the code, he fear that the code is going to be extremely brittle. 
But our partner need to have this trigger update soon.

link: [https://github.com/akvo/akvo-tech-consultancy/tree/master/lumen-api/lumen-trigger-selenium](https://github.com/akvo/akvo-tech-consultancy/tree/master/lumen-api/lumen-trigger-selenium)

**Comment by tangrammer** [comment]
Hi @dedenbangkit !
As far as I know :)  currently, there is no other update alternative 
Regarding that "extremely brittle" code aspect, maybe we could set up a new entrypoint to update all updatable datasets in one call (eg: `api/datasets/batch-update` ) but, we should still need to check the job_execution_id for that "big" process, or maybe, just sending an email with the final result should work... 
what do you think  @janagombitova, @dlebrero & @kardan about it?

PS: @dedenbangkit I'm not keen on selenium+keycloak, but looking at that `loginUrl` line https://github.com/akvo/akvo-tech-consultancy/blob/master/lumen-api/lumen-trigger-selenium/app.py#L15  and comparing with my live url `https://login.akvo.org/auth/realms/akvo/protocol/openid-connect/auth?client_id=akvo-lumen&redirect_uri=https%3A%2F%2Fdemo.akvolumen.org%2F&state=b41327af-210a-47f1-9cdf-c9d1887e5ce0&nonce=c0a194e3-e829-44b4-892a-aee6dc6dec31&response_mode=fragment&response_type=code&scope=openid` it seems that there is a few values that are not send in your code 🤔 ... not sure but maybe related with the problem

**Comment by tangrammer** [comment]
Following  [RFC 6749 OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-5.2) 

> invalid_grant
> The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

**Comment by dedenbangkit** [comment]
> Hi @dedenbangkit !
> As far as I know :) currently, there is no other update alternative
> Regarding that "extremely brittle" code aspect, maybe we could set up a new entrypoint to update all updatable datasets in one call (eg: `api/datasets/batch-update` ) but, we should still need to check the job_execution_id for that "big" process, or maybe, just sending an email with the final result should work...
> what do you think @janagombitova, @dlebrero & @kardan about it?
> 
> PS: @dedenbangkit I'm not keen on selenium+keycloak, but looking at that `loginUrl` line https://github.com/akvo/akvo-tech-consultancy/blob/master/lumen-api/lumen-trigger-selenium/app.py#L15 and comparing with my live url `https://login.akvo.org/auth/realms/akvo/protocol/openid-connect/auth?client_id=akvo-lumen&redirect_uri=https%3A%2F%2Fdemo.akvolumen.org%2F&state=b41327af-210a-47f1-9cdf-c9d1887e5ce0&nonce=c0a194e3-e829-44b4-892a-aee6dc6dec31&response_mode=fragment&response_type=code&scope=openid` it seems that there is a few values that are not send in your code 🤔 ... not sure but maybe related with the problem

Sure, the endpoint is this line: https://github.com/akvo/akvo-tech-consultancy/blob/2e008f74cb55641484678753a1ae57df0344a23f/lumen-api/lumen-trigger-selenium/app.py#L60

```python3
lumenInstance = 'https://'+instanceName+'.akvolumen.org'
loginUrl = 'https://login.akvo.org/auth/realms/akvo/protocol/openid-connect/auth?client_id=akvo-lumen&redirect_uri='
loginUrl = loginUrl + lumenInstance
```

_PS: The job was run on my personal instance (AWS) everyday for almost 2 weeks, Joy just ask to stop this cron today because the data collection is complete. But there is a possibility in the future for this kind of job. Hopefully next time I can pull the trigger with POST API and it runs in Akvo infrastructure (Kubernetes) instead of my personal box._

**Comment by tangrammer** [comment]
After talking with @dlebrero, closing this issue thus lumen wants to move the update process as a real-time process approach, so no more explicit update calls in the future
