### ISSUE TITLE
Slow-loading dashboards

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1378]
# Context
We've already introduced a spinner on vis previews and dataset editor, for cases when pages take a long time to load - https://github.com/akvo/akvo-lumen/issues/1250

@LarsSjogreen has created a dashboard that takes about 15 secs to load on a reasonably good connection:
https://lumen.akvotest.org/s/qfb-O4GDfE4

# Problem or idea
When a dashboard takes 15 secs to load on a rather fast stable connection, it might take much longer in less connected part of the world. A user might think there is a problem with the website if there is no visual feedback for a long period of time.

# Solution or next step
Render dashboard more progressively?
Add a spinner for each visualisation on a dashboard?
Maybe @finnfiddle or @gabemart would have some ideas

**Comment by iperdomo** [comment]
That request is 2.5MB compressed data, that expanded are 16MB
````
curl https://lumen.akvotest.org/share/qfb-O4GDfE4 > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.0M    0 16.0M    0     0  1049k      0 --:--:--  0:00:15 --:--:-- 3926k
````

**Comment by finnfiddle** [comment]
I think when aggregations are done on the backend this will speed things up a lot because less data will be sent over the wire. here you can see the 2.5 MB request: https://lumen.akvotest.org/share/qfb-O4GDfE4 - its just all the data for all the charts in the dashboard.
