### ISSUE TITLE
Begin using new visualisation library

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1381]
# Context
We have decided to [switch to a new viz lib](https://github.com/akvo/akvo-lumen/issues/1365) and to perform aggregations on the backend and only send aggregated data to the client. 

This issue will cover implementing those decisions, building on the work already done.

We have decided to tackle visualisations one-by-one.

This probably means a PR for each visualisation type that adds the appropriate backend aggregation and "switches on" that visualisation in the client using the new lib.

This approach is intended to break this large task down into more manageable chunks, and to make finding bugs and handling feedback for each new visualisation type more manageable. 

- [ ] line/area chart
  - [x] Date x-axis vs number x-axis
  - [x] Minor styling/positioning points
  - [x] keys warning on Collection
  - [x] Down-sampling
- [ ] scatter chart
- [ ] pie/donut chart
- [ ] bar chart

**Comment by gabemart** [comment]
# Line Charts

Here are some potential issues with line charts:

## Date x-axis vs number x-axis
Right now we assume x-axis will always be a date-type. On text there is at least one line chart that has a number-type x-axis. 

With new charts, if you try to use a number column for the x-axis, the tick labels will display incorrectly because we are using functions that cast the value to a date

To make the new line chart work with number-type x-axis, the client would need to know explicitly know if the x-axis was a date or number type (perhaps backend could include this in `metadata` response) and we would need to handle things a bit differently for number types

The other option would be to decide that line and area charts are only for date-types on the x-axis, and enforce this in the editor (although that raises the question of what happens to any existing line or area charts with a numeric x-axis that already exist in production)

## Minor styling/positioning points
Y-axis tick labels aren't vertically centered on their tick marks
![image](https://user-images.githubusercontent.com/2589977/39529098-c9e75b98-4e1d-11e8-9ca1-d9b85875732e.png)

---

The x-axis label isn't horizontally centered on the x-axis
![image](https://user-images.githubusercontent.com/2589977/39529245-1c626ab6-4e1e-11e8-9bf2-aa61f8b4e625.png)

---

At large widths, there might be a bit too much negative space at the sides (although this is subjective)
![image](https://user-images.githubusercontent.com/2589977/39530121-30806898-4e20-11e8-8005-194118aff6a0.png)


---

**Comment by gabemart** [comment]
@finnfiddle and I have been talking about performance with large numbers of points. We are experimenting with using random sampling on the backend when the total number of points in the line chart would be very large (e.g. 5k or 10k).

**Comment by nadiagorchakova** [comment]
done :)
