### ISSUE TITLE
Charts to visualise progress

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1396]
# Context

Comment from Joy:
"With international aid becoming increasingly target-based , we need a way to visualise it.
Say I have 10 regions and my sampling plan has come up with data collection targets for each zone"

# Problem or idea
Visualising something like this is currently not possible.

# Solution or next step

Joy suggested to review [this chart type](https://www.wikiwand.com/en/Bullet_graph) as an example:
Also other examples [here](https://powerbi.microsoft.com/en-us/blog/actual-vs-budget-which-chart-is-effective/).
Important to consider: Data on targets will not come from raw field data. It means that it should probably come as a meta data in the visualisation layer. 
The field data will then be compared against the set standards. For example, raw data will say 42 trainings completed. And the target is 60(meta data).
Thoughts or ideas? @finnfiddle @Kiarii

**Comment by nadiagorchakova** [comment]
Also Leonie from SNV shared the following chart example:

![image001](https://user-images.githubusercontent.com/21127166/40359940-aea54e6a-5dc4-11e8-8566-93bc1f3b49b7.png)

**Comment by finnfiddle** [comment]
@janagombitova this is a task that needs a planning session

**Comment by janagombitova** [comment]
To flesh out the issue even more and add more info here are some more details

# Context 
With Flow+Lumen we aim to make it as easy as possible to go from no data to data-based decisions for those working in international development and aid. This goal not only means to make it easy to analyse and visualise data but that Flow+Lumen should support development aid specific needs around data as field-based data collection, working in areas with a lower internet connection, supporting reporting requirements. 

## Current status quo
When it comes to the Understand phase, data is analysed in international aid more and more in regards to a specific target (expected result). Lumen makes it easy to analyse and visualise data, but there is no simple way to do it in regards to a result that is often defined before data is collected. 

# Opportunity 

As Nadia mentioned in the opening description of this issue, international aid is becoming increasingly target-based. Targets are set in the beginning of a programme/project based on their Theory of Change (what is it that they assume to achieve) and Monitoring framework (how will the programme/project measure they are heading towards this change). During the duration of the programme/project data is captured, (sometimes) aggregated and then compared towards the target. 

## Why do we have this issue? What are we trying to solve? 


## The idea 
## How will this benefit users? 
## How will this benefit Akvo? 
# Next steps 
* the next steps is to discuss the problem with the team to map out the workflow to find out if we have enough information or not (I suggest to involve Irene, Joy, Geert in the research or even in the session to get input on the current workflows) 
* go back to users to get the missing details 
* user test ideas (mock-ups)

**Comment by janagombitova** [comment]
I am reopening this issue as a partner (interested in further using Lumen to monitor their projects) has requested the option to visualise outcome data towards a target/goal. The issue describes a large opportunity especially if we think about all the different visualisation options we provide in Lumen and all their different customisations. 

But, what if we start small and think of a specific (yet generic) use case of visualising one variable (one column) towards a set target? That way we can support one use case and see if users pick up the functionality and what other requests stream in. 

When speaking with Irene about her partner, they have a common need to visualise **numeric data towards a target**. So they have outcome = column structure where after summing up all the values in that column they want to see how far off are they from the target. The aggeration method can very -they might sum or calculate the average etc. 

Something like this: 
<img width="636" alt="Screenshot 2021-05-04 at 15 36 19" src="https://user-images.githubusercontent.com/12456965/117011935-a972d080-acee-11eb-9c99-c063f60b299f.png">
<img width="625" alt="Screenshot 2021-05-04 at 15 36 04" src="https://user-images.githubusercontent.com/12456965/117011940-aaa3fd80-acee-11eb-883e-2df197acd9d3.png">

These are examples of **progress doughnut charts**. They have become a very popular way to show progress as they are easy to understand and the user can quickly see the status of things. Furthermore, they are limited to just displaying one metric that possibly can make them a smaller thing to implement that we can learn quickly from.

**Comment by janagombitova** [comment]
Today we discussed this idea and here are the notes from the call: 
* To limit the implementation to a bare minimum so we can learn as we go, we go for only NUM columns for now (other cases we can handle in the next iterations - like counting all submissions or handling TEXT and OPTION columns)  
* What about cases where you go over the target? Full circle and percentage to show the % that is more than 100% 
* Show the percentage and actual value 
* Colour can be defined by the user but just the colour for the column value. The background should either be by default grey or always a lighter shade of the selected colour 
* Estimate a week of work
