### ISSUE TITLE
Resources in admin console - incorrect count

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1397]
# Context

In Admin console we have Resources screen, where one can see number of visualisations and external datasets.

<img width="576" alt="screen shot 2018-05-01 at 14 00 26" src="https://user-images.githubusercontent.com/21127166/39472192-07d17b0e-4d48-11e8-8eb3-4faf62cb7bcf.png">

# Problem or idea
Number of external datasets specified in the Resources screen doesn't tally with the actual number of datasets in the library.
In the case of gt20 instance, Resources screen says there are 20 (external) datasets in the instance, while the library itself shows the total of only 4 datasets. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/21127166/39472304-b86b83f6-4d48-11e8-8ac0-5516e18ecb07.gif)

# Solution or next step
Resources screen should show the actual number o resources present in the library at the moment.

**Comment by kardan** [comment]
The UI for this has changed a bit but still seems to be something odd going on.

![screenshot 2019-02-27 at 09 10 20](https://user-images.githubusercontent.com/31837/53475177-9d848780-3a6f-11e9-8aa1-42475e220d42.png)
![screenshot 2019-02-27 at 09 10 29](https://user-images.githubusercontent.com/31837/53475183-a1180e80-3a6f-11e9-9efd-34306d2ab15b.png)
