### ISSUE TITLE
Hover area is not equal to hit area in the Lumen library

### ISSUE THREAD

**Issue by LarsSjogreen** [akvo/akvo-lumen#1401]
# Context
When you hover over a visualization, a data source or a dashboard in the library, the background changes color, indicating something. However, the gray area contains three different hit areas, the checkbox, the link/navigation to the actual thing and the dot menu. It also contains an area (marked with blue in the illustration below) that is not active at all. The only UI hint that signals that you are on something active is that the mouse pointer turns into a finger.

# Solution or next step
I suggest that the hit area for navigating to the "thing" is stretched to cover the whole button/block and that an extra hover style is added to the checkbox and the dot menu to signal that they have a different behaviour.

(There might be a larger redesign of the Library in the planning. In that case, I assume that things like this will be addressed.)

# Ilustration of the hit areas and the area with hover response but with no behaviour:
![image](https://user-images.githubusercontent.com/18190715/39568004-0a662f34-4ec1-11e8-8668-bb51213298fa.png)

**Comment by janagombitova** [comment]
Looks good to me from the users's point of view 👍
