### ISSUE TITLE
Delete datasets in pending mode

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1408]
# Context
Users end up with datasets that are in pending mode

# Problem or idea
There are issues when importing them and they stay in pending mode. 

# Solution or next step
We need to make sure we don't introduce bugs in a long-running import. Think We can delete in data_source and let the Postgres cascading to its thing to stay safe - maybe.

- [x] Delete pending datasets
- [x] Delete pending rasters
- [x] Review if we can do a better cleanup
- [x] Remove import bug

**Comment by janagombitova** [comment]
@kardan are you still working on this one or has everything been already handled?

**Comment by tangrammer** [comment]
@kardan it seems that we can't remove failing imported dataset 

<img width="634" alt="screen shot 2018-11-07 at 12 16 27" src="https://user-images.githubusercontent.com/731829/48128512-ff35a180-e286-11e8-80d8-74007b124c76.png">

looking at code detail impls, client library view calls `GET /api/library` and backend then execute [this SQL](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/dataset.sql#L1-L37) that returns different "things", the problem arises when we try to [delete the dataset based on the id ](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/dataset.clj#L86) received by [client-side](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/endpoint/dataset.clj#L25), but this id is not a dataset-id anymore

**Comment by kardan** [comment]
I wonder if this relates to https://github.com/akvo/akvo-lumen/issues/1408

**Comment by tangrammer** [comment]
do you mean #1449 ?  thus #1408 is this one 🤔

**Comment by tangrammer** [comment]
@kardan  @janagombitova are you ok if I start with this issue in the meanwhile i get feedback/review from #1744 ?

**Comment by tangrammer** [comment]
<img width="547" alt="screen shot 2019-03-05 at 16 27 11" src="https://user-images.githubusercontent.com/731829/53816398-c91ddb00-3f63-11e9-9820-c907d71511c4.png">

same problem here 

in this case `DELETE  http://t1.lumen.local:3030/api/job_executions/5c7e8f64-4fb2-4b37-906d-4da43760da27` is not even a declared endpoint

**Comment by kardan** [comment]
@tangrammer I think the DELETE methods are on the different entites (viz, dataset, dashboard).

**Comment by muloem** [comment]
@tangrammer is this fully resolved? If so maybe we can close it

**Comment by tangrammer** [comment]
nope
