### ISSUE TITLE
Start colour in raster map preview different from chosen

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1416]
# Context
In Theme tab in map layer it's possible to pick a custom start and end colour of the raster.

# Problem or idea
When I picked a start colour different from default, the map preview on the right showed a wrong colour.
Looks like it's showing the previous colour choice.

![raster colours](https://user-images.githubusercontent.com/21127166/39925585-89e6c02c-552c-11e8-8a8b-ba7dae41181d.gif)

# Solution or next step
How could we solve it?

**Comment by gabemart** [comment]
The problem of the baselayer not updating is related to the same state propagation issue
