### ISSUE TITLE
The product link should lead to an information page

### ISSUE THREAD

**Issue by LarsSjogreen** [akvo/akvo-lumen#1442]
# Context/problem
We brand the Lumen dashboards, but for someone interested in the tool and knowing more about it, it takes an effort to actually find the right place to read about it.

![image](https://user-images.githubusercontent.com/18190715/40720002-9aa593c8-6415-11e8-8e9a-6a861c7545a1.png)

![image](https://user-images.githubusercontent.com/18190715/40720135-05b13410-6416-11e8-9d9a-f590a5779686.png)

# Solution or next step
The "Built with Akvo Lumen" tag in the dashboards should be a link leading to a web page. This one for example: https://akvo.org/products/akvo-lumen/#overview

**Comment by janagombitova** [comment]
👍
