### ISSUE TITLE
Standardised mock dataset for testing

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1450]
# Context
When we do feature development or manual or automated testing on Lumen, we can't use real user datasets as it would be a privacy violation.

We need mock datasets for this kind of testing.

# Problem or idea
It's easy to generate simple mock datasets with random data, but they're not very useful for testing:

These simple datasets aren't very close to our real user datasets:

* Random numbers are usually uniformly distributed. Distributions in real life are rarely uniform
* This also applies to geopoints
* They lack "naughty" values - missing values, garbled strings, typos, really long strings, strings with unusual characters, numeric values outside the expected range, etc
* For any given row, the values each column usually aren't correlated in any way (e.g. Column B value is lower when Column A valuer is higher)
* They usually don't contain FLOW specific structures like multiple option columns

Why would it be better to have a standardised mock dataset that closely resembled a real Flow dataset?

* Some bugs caught sooner - anecdotally, we currently use fairly simple datasets during feature development (I certainly do), then do enhanced testing on more complex datasets when a feature is "done". Bugs caught at this stage (or worse, only after deploying to production) take more time to fix and are worse for the user. 

* In the same way as previous point, we are likely missing out on some non-bug enhancements by not building features around realistic datasets. When we develop using a simple dataset, it is unavoidable that we to some extent optimise user experience for the simple dataset.

* Reproducing bugs between developers and other team members would be much easier if it the bug could be reproduced on the standard test dataset everyone was familiar too and had access to. It would also avoid the situation where a developer has to be given access to a production instance just to view or reproduce a bug.

* Testing visualisations in particular is hard when using simple, uniformly distributed random data. Visualisations are often used as a tool for exploring or presenting correlations and relationships between variables. If there are no correlations or relationships between values in different columns, this is harder

# What a good standard dataset would look like

This is work-in-progress, and it would be great to have input from other team members on this, particularly team members who do a lot of work with FLOW datasets

What I can think of so far:

* Wide range of column types - text, number, date, geopoint but also things like instance ID or Identifier, if possible
* **Columns**
  * Loads of columns
  * Some column names replicating the "99999999|SOME COLUMN NAME" pattern
  * Some very long column names
  * Some column names containing javascript keywords (e.g. `function`)
  * Columns which are mostly blank
  * Columns which are entirely blank
* **Text Columns**
  * Text column representations of multiple option questions
  * Text columns with typos - eg "Yes", "yes", "yse", "ye s"
  * ["Naughty" strings](https://github.com/minimaxir/big-list-of-naughty-strings)
  * Text values from different character sets
  * Text columns which are all actually numbers (`"12.5"` vs `12.5`)
  * Text columns which are *almost* all actually numbers ("5", "7", "9", "12z", "14")
* **Number Columns**
  * Numbers within a range
  * ...with a non-uniform distribution (e.g. standard distribution)
  * ...but with some numbers way outside of that range (e.g. 1, 3, 3, 4, 5, -9992929332, 7)
  * Number columns which actually represent time (e.g. year)
* **Date Columns**
  * Dates within a range
  * ... but with outliers
  * Dates that follow a regular or semi-regular interval (e.g. about once a day, month, year etc)
  * ...With some really big or really small intervals (once every ten seconds, once every ten years)
  * Dates with different timezones/utc offsets ?
* **Geopoint Columns**
  * Geopoints within a rough boundary (doesn't have to be exact, but points that are in a roughly country or city-sized area are much closer to real usage than points that are uniformly distributed over the globe)
  * Geopoints which are extreme outliers
* **Relationship between Columns ideas (examples to be added)**
  * A number column where the value gets smaller as a geopoint column goes further south
  * A number column where the value is different based on a text column 
  * A number column where the value gets lower as a date column gets further into the future

# How to do this?

There are lots of mock-data-generating tools and services.

In my opinion, tools like [mockaroo](https://mockaroo.com/) are a bit too limited for building a really robust standard dataset.

We may be able to build on the work Juan has been doing with clojure.spec to generate column values

We may be able to use some simple scripting for some data generation

We could also use a combination of approaches

What matters is the output (i.e. the standard dataset itself). Having said that, it would be nice to be able to make changes - in an ideal case, whenever we discovered a bug that could not be replicated in the standard dataset, we could update the standard dataset so that it could be replicated :)

**Comment by finnfiddle** [comment]
@gabemart hey did you start on this already? maybe I could pick up where you left off. Is there a branch for it?

**Comment by tangrammer** [comment]
I'd like to work in this issue too :) if we finally decide that it is worth it ...

**Comment by janagombitova** [comment]
@tangrammer and @kardan is this issue completed or is there still more to be done? Can we close it?

**Comment by tangrammer** [comment]
@janagombitova I'd prefer to keep this issue **still** opened. 
although we can currently generate simple mock datasets with current work done, we could improve the quality or complexity of data generated adding more effort on this area
