### ISSUE TITLE
Abbreviate millions in y axis

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1471]
# Context

In the new vis version we should be abbreviating large numbers like millions in the same way we do in the old version.

New:
<img width="802" alt="screen shot 2018-06-18 at 14 06 22" src="https://user-images.githubusercontent.com/21127166/41534975-d552354a-7300-11e8-85e8-123b9c541f44.png">

Old:
<img width="826" alt="screen shot 2018-06-18 at 14 07 18" src="https://user-images.githubusercontent.com/21127166/41535011-fbdec67e-7300-11e8-844c-7357a12be142.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by gabemart** [comment]
After some testing I think it makes sense to abbreviate anything over 10k
