### ISSUE TITLE
Bar names appear cut off in new vis version

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1472]
# Context
In this graph, bar names appear cut off and do not show in full on hover:

<img width="820" alt="screen shot 2018-06-18 at 14 48 59" src="https://user-images.githubusercontent.com/21127166/41536755-c6a16b32-7306-11e8-8ae6-31ec40d7b4e7.png">

Link: 
https://dark-demo.akvolumen.org/visualisation/58db05b3-ed9d-4cae-b800-2debea83410d

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by gabemart** [comment]
closed via #1478
