### ISSUE TITLE
bar y-axis labels font size too small

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#1490]
The new code to adjust the font-size on long axis labels is a bit too aggressive, and can result in labels which are too small to read:

![image](https://user-images.githubusercontent.com/2589977/41668774-0c8fbca0-74a8-11e8-95f8-2155b63ac891.png)

In my opinion we should change a couple of things -

* I think we need a min font size
* Even though it makes good use of space, in practise I think it looks weird when the x and y axis labels are different font sizes. I think we should use one font size for both (i..e the smaller of the two values)
* I think we need the same adjustments for line and scatter - currently only bar chart labels are adjusted

**Comment by finnfiddle** [comment]
ok sounds reasonable to me. the labelling is not perfect yet by any means - it needs some care

**Comment by gabemart** [comment]
I totally agree, it is a complex issue that needs a fuller solution
