### ISSUE TITLE
Switch between interactive and print mode in visualisations

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1494]
# Context
As part of the work to implement a new vis library, we explored a possibility to support print mode for visualisations.
@gabemart explained that we now have support for activating different settings when in print or interactive mode. However, there is more work to be done on the UI and probably backend level.

# Problem or idea

# Solution or next step
We determined that only certain of the charts have differences between print and interactive modes: Pie, Stack Bar.
Pie has been the one that has been requested the most so we will first implement a "Show Labels" option for it.

**Comment by finnfiddle** [comment]
## TODO

- [ ] Pie "Show Labels" option
- [ ] Print styles
- [ ] Download charts/dashboards as images

**Comment by finnfiddle** [comment]
@janagombitova maybe we can split the image exports subtask out into its own ticket so my branch doesnt get left behind while we're deciding how to implement it?

**Comment by janagombitova** [comment]
@finnfiddle sounds like a plan! How about using this existing one: https://github.com/akvo/akvo-lumen/issues/952

**Comment by nadiagorchakova** [comment]
Hi @finnfiddle, we just discussed with @janagombitova that the visual of the pie chart in 'print mode' that you shared above does not display any numeric values. As we discussed in the story mapping session together, Jerome, our user, wants to see the numeric values associated with each pie chart slice.

**Comment by finnfiddle** [comment]
<img width="464" alt="screen shot 2018-07-05 at 11 56 03 am" src="https://user-images.githubusercontent.com/4628721/42313103-993311d6-804a-11e8-948e-5b061fafc515.png">
here you go @nadiagorchakova @janagombitova

**Comment by janagombitova** [comment]
Nice, i like how you took away the edit side panel from the print view, cool 👍
