### ISSUE TITLE
Colour-code dots on scatter plot using categorical variable

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1512]
Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-126018-from-andrew-at-akvo-dot-org
Assignee: Unassigned

Message:
[AKVOLUMEN] Support request #126,018 from   

Request Info
Device:  Personal computer
Browser:  Firefox 60.0
OS:  OS X 10.13
URL:  https://footballforwater.akvolumen.org/  

1- What do you need help with?
I would like to request a feature  

2- Who will be using this feature?
Everyone  

3- How do you want to use it?
Able to add a categorical variable in a Scatter plot.  

4- Why do you need to have it?
Add more information to existing scatter plot.  

5- What is your full name?
Molo  

6- Which Akvo Hub do you usually work with?
East Africa  

Tell us more about your request
For example in the Scatter plot attached, I'd like to be able to color code the dots using a categorical variable, e.g A question type like "Type of School with the categories  "Private" &amp; "Public" 
Then thereafter, I color code with blue dots denoting Public Schools and Green Dots denoting private schools. 

Download attachment
plot.png (https://s3-eu-west-1.amazonaws.com/cdn.supporthero.io/ticket/747/plot.png)

**Comment by janagombitova** [comment]
Released today
