### ISSUE TITLE
Combining columns where one of the columns has empty values

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1517]
# Context

A partner reported a case where the combined column returns empty value when one of the columns contains empty values.

Steps to reproduce:
- Find two columns one of each contains empty cells. Example:

<img width="401" alt="screen shot 2018-06-29 at 16 00 14" src="https://user-images.githubusercontent.com/21127166/42096412-8d6b17a2-7bb5-11e8-85e7-9a2935a5997f.png">

- Do the 'Combine columns' transformation
- The resulting column will be empty. Example:

<img width="202" alt="screen shot 2018-06-29 at 16 01 46" src="https://user-images.githubusercontent.com/21127166/42096487-c0dacfe2-7bb5-11e8-943e-ba61a28f5cad.png">

# Problem or idea

The user expectation is the following:
When one of the columns has empty value and the other has value 'test' in it, the combined column should show 'test'.

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
issue tested against https://lumen.akvotest.org/dataset/5b74000f-163d-47d0-8438-977874d7b833
**working fine!**
