### ISSUE TITLE
Provide better error messages for failed imports

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1518]
# Context
When doing Flow import you can run into errors, these errors are provided in a very raw format.

# Problem or idea
clj-http: status 502 is not a great message to user.

# Solution or next step
For common things like a 502 error we could provide a better message.

**Comment by kardan** [comment]
![image](https://user-images.githubusercontent.com/31837/42154631-92de4c76-7de6-11e8-897a-c40e878b291c.png)

**Comment by janagombitova** [comment]
@tangrammer when looking at #1361 can you take a look at this one too?
