### ISSUE TITLE
Delete datasets and visualisations

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#153]
* Backend 
  * [x] `DELETE /api/datasets/<id>`
  * [x] `DELETE /api/visualisations/<id>`
  * [x] We want to do cascading deletes on the backend so we don't end up with dangling foreign keys in the database. 
  * [x] For visualisations this means that we can't embed the `datasetId` in the spec jsonb [as we currently do](https://github.com/akvo/akvo-lumen/blob/develop/backend/resources/org/akvo/dash/migrations_tenants/003-visualisation.up.sql#L4). 
* Client
  * [x] The [mockups](https://drive.google.com/file/d/0B4C2-GDdmwzKOFJSVVllckJtVXc/view) for deleting datasets are available
  * [x] Will require a context menu similar to the one we use in transformations
  * [x] We'll probably want to somehow have the user confirm deletions. Especially since deleting a dataset you'll also delete the visualisations that depend on it. @Kiarii thoughts?

**Comment by Kiarii** [comment]
made delete dialog for datasets with child visualizations; see _general mockups_ (0.71)
