### ISSUE TITLE
Blank screen + error 'n is undefined'

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1530]
# Context

I experienced this strange behavior more that three times, but somehow it's usually tricky to reproduce it.

# Problem or idea
<img width="1276" alt="screen shot 2018-07-05 at 11 22 35" src="https://user-images.githubusercontent.com/21127166/42314639-c21a3386-8045-11e8-97da-7916560cfb71.png">

At the point when I switch between different screens a blank screen suddenly appears.
When I press the back button on my browser, the url address changes, but I still see the same blank screen. Refreshing the page helps though.

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
In the description Nadia's says "tricky to reproduce it" and I was not able to nor have we received any issues via support or users experiencing the same. Thus closing the issue
