### ISSUE TITLE
Pie chart legend cut off

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1545]
# Context
It gets cutoff if it is just one long word
https://dark-lumen.akvotest.org/s/sw8_Rw15FB0

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
is this really an issue? I think it is unlikely to have a legend title which is just one really long word. What do you think @janagombitova?

**Comment by janagombitova** [comment]
I agree. I think this was just one extreme example and the user can always so and edit the column title to adjust the really long word. Closing the issue
