### ISSUE TITLE
It shouldn't be possible to add a 'failed import' to a collection 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1546]
# Context

Currently, it seems to be possible to add a failed import to a collection.

<img width="1047" alt="screen shot 2018-07-11 at 09 38 03" src="https://user-images.githubusercontent.com/21127166/42557366-a0ae88a2-84ee-11e8-80d0-d8fbb16a8610.png">

# Problem or idea
I think it doesn't make sense to add a failed import to a collection.
The only useful action would be to delete it.

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment]
Probably, 'Update' shouldn't be in the dropdown menu for failed imports either, as it gives 'undefined' error anyway

**Comment by tangrammer** [comment]
tested with https://dark-lumen.akvotest.org/library/collections/9fd07166-e83a-4ac9-a094-9964cd17b351
<img width="626" alt="screen shot 2018-08-30 at 18 59 15" src="https://user-images.githubusercontent.com/731829/44866976-f1601080-ac86-11e8-9195-d06f5f1ea188.png">
