### ISSUE TITLE
Pie chart label appears cut off when displayed on dashboard

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1560]
# Context
The label of a pie chart appears cut off when shared in a dashboard

<img width="529" alt="screen shot 2018-07-13 at 16 15 18" src="https://user-images.githubusercontent.com/21127166/42696285-083a3b54-86b8-11e8-8205-d56d5b45b6f6.png">

I manage to get the full label in when I manually resize the frame.

# Problem or idea
What is the cause?

# Solution or next step
I think the label should be more responsive to the size of the frame.
Maybe truncate it if it's way too long and display full text on hover?

**Comment by nadiagorchakova** [comment]
label gets cut off also when shown in legend:

<img width="630" alt="screen shot 2018-07-13 at 16 28 06" src="https://user-images.githubusercontent.com/21127166/42697315-0cab9bf8-86bb-11e8-9dde-9e0c7a67ed7c.png">

**Comment by janagombitova** [comment]
I could not reproduce this anymore with the example pie chart
