### ISSUE TITLE
Dataset filters are a bit hidden

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1570]
# Context
When Jerome opens an existing vis in editor view, the Dataset filter section is collapsed:

<img width="1150" alt="screen shot 2018-07-18 at 17 09 40" src="https://user-images.githubusercontent.com/21127166/42890584-7b58317e-8aad-11e8-941e-12ec24312b82.png">

Only when Jerome clicks on it does he realise that the vis represents a filtered slice of data:

<img width="1198" alt="screen shot 2018-07-18 at 17 15 08" src="https://user-images.githubusercontent.com/21127166/42890898-4b8c226a-8aae-11e8-83d4-46c26339f196.png">

# Problem or idea
When Jerome checks out an existing visualisation, there is no indication that it has a dataset filter applied to it. I think it might be misleading in certain situations.

# Solution or next step
Perhaps it would make sense to have dataset filter disclosed by default for transparency reasons. Or use other ways to make it more prominent.

**Comment by janagombitova** [comment]
Closing this issue as we have changed the design of the visualisation editor. And we have not received further input regarding this issue. If needed it will be reopened in the future
