### ISSUE TITLE
Better support Caddisfly data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1571]
# Context
*Why do we add this issue?*

With this issue we enabled showing Caddisfly data in the Flow data set as a json string: https://github.com/akvo/akvo-lumen/issues/946 This implementation was intentionally basic to give us a starting point to support Caddisfly data. 

With the aim to have a better integration between Caddisfly - Flow - Lumen we need to also simplify this implementation to remove the need for Jerome to have to transform the column to get the values out of the sting in a way he can work with the data.

# Problem or idea
*What is the cause?*

Current implementation show Caddisfly answers as a json string and Jerome can use the derived column to extract the value from the test result and then use it further in a visualisation. This is not the most user friendly approach. Furthermore as the data is coming from our own product the we should be able to show it is a user readable way. 

# Solution or next step
*How could we solve it?*

Flow data exports create separate columns for the Cadidsfly tests. We can follow how Flow exports the Caddisfly data to ensure we handle Caddisfly in a unified way across both products. 

Here is an example of a Flow data export (the data in the sheet is all mock data): 
[Example of Caddisfly columns.xlsx](https://github.com/akvo/akvo-lumen/files/2210059/Example.of.Caddisfly.columns.xlsx)

**Comment by tangrammer** [comment]
Uploaded file to GDrive
https://drive.google.com/file/d/1Pq0ECN9vsrLW026sFbFb054aWRIrGW6u/view?usp=sharing

**Comment by tangrammer** [comment]
(WIP) More on Caddisfly data types here 
https://docs.google.com/spreadsheets/d/1y9XFjrvmmsHZ1z8nSqonAXy5VLao8xgylOE7H9J6GW8/edit#gid=0

**Comment by tangrammer** [comment]
Syncing with @nhternup regarding Caddisfly https://docs.google.com/spreadsheets/d/1y9XFjrvmmsHZ1z8nSqonAXy5VLao8xgylOE7H9J6GW8/edit#gid=0

**Comment by tangrammer** [comment]
Syncing with Joy Ghosh
https://docs.google.com/spreadsheets/d/1uauiqtoD8vkqXWMkCp8bAsS3_vciR-Pu8b70T5Zd_Lc/edit#gid=1307281381

**Comment by tangrammer** [comment]
Syncing with Emmanuel Mulo
https://github.com/akvo/akvo-flow/blob/develop/GAE/src/org/waterforpeople/mapping/dataexport/GraphicalSurveySummaryExporter.java#L879-L963

**Comment by janagombitova** [comment]
Here is a brief summary of the decisions made so far around this issue (high level and from the users perspective) and how it will be implemented. For more details, especially on the technical implementation check the PR linked. 

# Creating Caddisfly columns at import
The initial idea was that at the time of importing the Flow dataset with Caddisfly data Lumen will automatically convert the current one column per question for Caddisfly data set up to multiple columns per question depending on the Caddisfly test (as done by Flow services at data export). 

The positive value of this approach for Salim is that he does not need to take any extra steps in handling Caddisfly data. He just needs to ignore what he does not need. 

We have, however, decided that this approach bring two negative consequences to Salim: 
- Salim ends up with even more columns in his data set which is hard to manage in Lumen's current UI 
- Salim ends up with odd columns names, that are long and hard to view in the current Lumen set up. 

Both of these issues are not only Caddisfly issues, but overall Lumen UX problems that need a more holistic solution. 

# Extract Caddisfly data UI option 

## Initial implementation 
So, instead of converting automatically all caddisfly questions to columns, we have created a **new transformation type - Extract Caddisfly data**. After Salim imports his Flow dataset he will see the Caddisfly columns as today, one column per question with data showing as a json string. For the Caddisfly questions where he wants to work with the results, he will find this transformation in the column header menu. This option will remove the current Caddisfly column and create new columns at the end of the data set. 

Even though this approach gives Salim one extra step to take to work with Caddisfly data, it does not give him redundant columns he will not use. 

This is the initial implementation.

## Handling existing data sets 
We have many datasets already imported in Lumen with Caddisfly data. The question was how to handle these once we release the functionality. We can update all data sets automatically or have Salim update the ones he needs. We have agreed to leave the update to Salim to avoid too many unneeded calls via the Flow API. 

## Handling changes to the Caddisfly file 
All test types live in a file that has a set structure. This file is updated often with new tests added and sometimes some tests are removed from the file. The concern is how to handle versioning of the content of the file to ensure Flow and Lumen know which version of the file the data set is based on. Currently there is no versioning in place. 

If Flow has data that does not match an existing test type, it is ignored. We agreed that Lumen to handle this, needs to - for now - implement a warning to the user to explain that the test type is unknown. 

# Advance transformations 
We have also considered to give Salim more advance editing options via the transformation side bar as: he selects which Caddisfly column he wants and then which value he wants to extract and how should that be handled (column name, data type, what to do with exceptions) because we learned in the research that not all result values in a Caddisfly answer are useful. 

We will not pursue this opportunity yet because: 
- if not all values in the Caddisfly answers are useful to users, why do we store them --> this needs to be researched on Caddisfly's end for all test types and what values are stored 
- we do not want the UI to know too much about Caddisfly, but want to have a more generic approach to data structures where a column holds more columns 
- we want to learn if our initial approach is valuable or not and how.

**Comment by tangrammer** [comment]
@janagombitova I've created a new issue to keep working separately in the ["multidimensional column" topic](https://github.com/akvo/akvo-lumen/issues/1571#issuecomment-412770502)
