### ISSUE TITLE
Enhance text editor for dashboards 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1576]
# Context
*Why do we add this issue?*

Dashboards as collections of different visualisations are a way to share the insights from the data. As data still needs to be interpreted Jerome adds text to his dashboard visualisations to explain what the dashboards show, the story of the project or describes different individual graphs. 

Example (pubic data): https://seap.akvolumen.org/s/53fGgdM9fXE
<img width="1268" alt="screen shot 2018-07-24 at 08 41 56" src="https://user-images.githubusercontent.com/12456965/43121287-8bd05170-8f1d-11e8-878d-f3578683b1dc.png">

The text he adds ranges from simple text descriptions, to captions under the graphs, small headers, lists, etc. 

# Problem or idea
*What is the cause?*

Current text editor allows Jerome to add simple plain text. He cannot make it bold, or add a bulleted list and then only way for him to differentiate the text he has written is to use all caps. 

To strengthen the dashboards and make them visually more appealing we want to give Jerome the possibility to edit the text he adds to enrich the message he wants to convey with the dashboards. 

# Solution or next step
*How could we solve it?*

How can we add the options to edit text so Jerome? Are there open source editors we can use?

**Comment by finnfiddle** [comment]
I plan to implement this by just replacing the textareas on the dashboard editor with rich text editors instead

something like this:

<img width="1440" alt="screen shot 2018-08-20 at 2 44 17 pm" src="https://user-images.githubusercontent.com/4628721/44339010-77f73f80-a488-11e8-8d2a-465133eaf065.png">

**Comment by janagombitova** [comment]
@finnfiddle I gave the changes a quick look on test and here are some things I found: 

On smaller screens once you add a new text element the alignment is off. 
<img width="404" alt="screen shot 2018-08-23 at 10 41 30" src="https://user-images.githubusercontent.com/12456965/44514721-28e81f00-a6c1-11e8-918b-7a71b8d23e14.png">

The text input field is small to see the entire text and I could not enlarge the box. I could only enlarge it once I clicked on the canvas and it took me quite some brain power to figure that out. It would be nice if the text field automagically adjusted to the size of the text. 
![text](https://user-images.githubusercontent.com/12456965/44514894-7f555d80-a6c1-11e8-8144-e8246c099ee9.gif)

Numbers and bullet points show differently in editor and in preview (here is an example dashboard: https://lumen.akvotest.org/s/KEXrD8fLbig) 
<img width="1172" alt="screen shot 2018-08-23 at 10 48 55" src="https://user-images.githubusercontent.com/12456965/44515230-3fdb4100-a6c2-11e8-8634-1cac65c807a4.png">
<img width="1173" alt="screen shot 2018-08-23 at 10 49 06" src="https://user-images.githubusercontent.com/12456965/44515234-410c6e00-a6c2-11e8-98b4-807a7950d6a1.png">

**Comment by janagombitova** [comment]
@finnfiddle I went through the feature once more in the afternoon today and here is a summary of my findings, so you can ignore the comment above. 

All my tests are based on the dashboard 'jana 23 aug test' (https://lumen.akvotest.org/s/KEXrD8fLbig) on https://lumen.akvotest.org/dashboard/5b7e72da-31e9-4733-abba-ef7fb77db45a

# Adding a new text element
After I added a new text element the box is quite small and sad. Can you adjust it so it is more visible on where you are to type and more it more present?
<img width="1080" alt="screen shot 2018-08-23 at 17 27 53" src="https://user-images.githubusercontent.com/12456965/44535338-0aeae080-a6fa-11e8-8396-570840073532.png">

So it looks maybe like this? 
<img width="1079" alt="screen shot 2018-08-23 at 17 30 06" src="https://user-images.githubusercontent.com/12456965/44535407-3a015200-a6fa-11e8-8eab-807b5723d7df.png">


# Extra white space under the text
I have created two small text boxes without adjusting the height of the box, only the width of the second one. When I viewed the ready dashboard via the shared link it seems as if there is an extra white space under the text. This makes it look weird. 

<img width="1253" alt="screen shot 2018-08-23 at 17 17 43" src="https://user-images.githubusercontent.com/12456965/44534774-d3c7ff80-a6f8-11e8-914e-ec1802564e2a.png">
<img width="940" alt="screen shot 2018-08-23 at 17 17 54" src="https://user-images.githubusercontent.com/12456965/44534778-d4f92c80-a6f8-11e8-8a02-6b00ad36408f.png">


# Cannot select text type
The dropdown with the header 1, header 2, etc is hidden behind the text box. 

<img width="749" alt="screen shot 2018-08-23 at 17 21 17" src="https://user-images.githubusercontent.com/12456965/44534864-070a8e80-a6f9-11e8-9cc9-b652c905c607.png">

# Numbers and bullet points show differently in editor and in preview
It seems numbers and bullets do not show when viewing the dashboard. 

https://user-images.githubusercontent.com/12456965/44515230-3fdb4100-a6c2-11e8-8634-1cac65c807a4.png
https://user-images.githubusercontent.com/12456965/44515234-410c6e00-a6c2-11e8-98b4-807a7950d6a1.png


# No visible difference between underlined and linked 
If I underline a piece of text or link it, visible there is not difference. Linked with a different colour? 
<img width="1068" alt="screen shot 2018-08-23 at 17 34 00" src="https://user-images.githubusercontent.com/12456965/44535695-e2afb180-a6fa-11e8-9d9d-9f6d9bee1405.png">


# Bold does not show
Bolded out text does not show in the live dashboards 
<img width="1075" alt="screen shot 2018-08-23 at 17 35 34" src="https://user-images.githubusercontent.com/12456965/44535743-01ae4380-a6fb-11e8-8c18-6cdd4b56bce1.png">
<img width="1080" alt="screen shot 2018-08-23 at 17 35 42" src="https://user-images.githubusercontent.com/12456965/44535747-04109d80-a6fb-11e8-91a8-721971e7e969.png">


# Extra question 
This should be a different issue, but what do you think of where the `Add new text element` button is located? I found it quite annoying once my dashboard was longer that I had to scroll up all the time to add another text element.

**Comment by janagombitova** [comment]
@finnfiddle I tested again today on dark and found some more things that need attention: 

# New text element box 
After I added a new text element the box is quite small and sad. 
<img width="1080" alt="screen shot 2018-08-23 at 17 27 53" src="https://user-images.githubusercontent.com/12456965/44535338-0aeae080-a6fa-11e8-8396-570840073532.png">

Can you adjust it so it is more visible on where you are to type, there is no overlap in the different elements and more it more present? Perhaps so all the items are in one row? So it looks maybe like this? 
<img width="1079" alt="screen shot 2018-08-23 at 17 30 06" src="https://user-images.githubusercontent.com/12456965/44535407-3a015200-a6fa-11e8-8eab-807b5723d7df.png">

# Multiple level lists don't show when shared 
If a list has more levels, they do not show well once the dashboard is shared. 

<img width="1242" alt="screen shot 2018-08-29 at 13 42 24" src="https://user-images.githubusercontent.com/12456965/44785532-884aa100-ab91-11e8-9ae2-e97740f95a50.png">
<img width="1252" alt="screen shot 2018-08-29 at 13 42 40" src="https://user-images.githubusercontent.com/12456965/44785542-8da7eb80-ab91-11e8-8944-acd75c640ae7.png">
