### ISSUE TITLE
Dashboard scroll bar covering right side border-radius corners of boxes.

### ISSUE THREAD

**Issue by LarsSjogreen** [akvo/akvo-lumen#1594]
# Context
[**Minor cosmetic issue.**]
The dashboards look very nice with the new boxes with rounded corners. It's a pity that they are hidden behind the scroll bar on the right side of the screen. It looks a bit cut off. An extra few pixels of margin on the right side, pushing them in, would probably make it look nicer.

![image](https://user-images.githubusercontent.com/18190715/44033410-976f286a-9f0a-11e8-8384-b9890cb22b1a.png)

**Comment by janagombitova** [comment]
@LarsSjogreen can you specify which browser you were using, as I do not see the scroll bars on Chrome. Thanks

**Comment by LarsSjogreen** [comment]
Edge and Chrome (Windows). It probably depends on if you view a dashboard that is tall enough to scroll.

(Maybe the MacOS ui is different, but in other operating systems, viewports with scrollable content is denoted by showing a scroll bar. In that case, use Browser stack to see scroll bars.)
