### ISSUE TITLE
Add Device ID when importing Flow data 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1595]
# Context
Why do we add this issue?
Flow dataset holds multiple meta data columns: Identifier, Display Name, Device ID, Submission date, Submitter, Duration. This meta data is used to better understand the submission and how the data collection went. Jerome analysis submissions per submitter or device, looks at the duration to check for outliers to then follow up with the submitter. 

When users import data from Flow to Lumen they expect to have the same dataset available. 

# Problem or idea
What is the cause?

Currently when we import Flow data, the column **Device ID** is not shown in the data set. Sometimes analysis is also done to see the submissions per device than per submitter. 

# Solution or next step
How could we solve it?

Add Device ID column and data at Flow import.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-139862-from-ilyasse-at-akvo-dot-org

**Comment by tangrammer** [comment]
@janagombitova 
 Device ID is   "deviceIdentifier" ?

currently we have a stored column called "identifier" 
example values from uat1 instance when importing dataset ...

`"deviceIdentifier"  => "102938",`
`  "identifier" "4139-k07c-bjw2",`

**Comment by tangrammer** [comment]
@janagombitova forget the question, rereading the issue description there is no other possible thing that could be the device ID :) 
I was double checking too much 😂

**Comment by tangrammer** [comment]
tested against `test` env
https://dark-lumen.akvotest.org/dataset/5b85047c-449f-4235-a6c2-b2fc80e23007
