### ISSUE TITLE
Day and night mode on dashboards and visualisations 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1600]
# Context

When we look at how to Lumen dashboards and visualisations are being used currently, they are: 
- embedded into websites 
- saved and downloaded to be added to reports and presentations 
- shown on a screen

We currently support fully and well the 1st use case. For the 2nd one we are working on a solution and you can say that the 3rd case has been supported from the launch of the dashboard and visualisation sharing link feature. 

# Problem 
If you put a Lumen dashboard or visualisation on a screen to showcase the insights, the dashboard or visualisation consists of a chart (or series of charts) some text on a white background. If shown on a large screen to vast white background shines at you making it harder to read and interpret what is shown and is a strain to the eyes. 

# Opportunity
The idea is to enable the so called **night mode** where Kadjo sees the dashboard or visualisation on a dark black background. 

Night mode inverts page colours, showing white text on a black background.  

# Solution or next step
We should consider: 
- first if this is something interesting for Lumen's visualisations and dashboards
- if yes should this be a permanent setting you set for a visualisation or a dashboard or a switch on the shared visualisation and dashboard the viewer can turn on and off if he wants 

@finnfiddle and @Kiarii what are your thoughts

**Comment by Kiarii** [comment]
I think optimizing the colors for best viewing is a priority for lumen since we are in the business of making visualizations. That said I think we can start with a subtle approach: toning down the white background for visualizations so it is not a 100% white. If we can achieve a good result it means that users creating or sharing visualizations do not need to switch modes. A secondary issue may occur with mode management if different modes are desired for the same visualization when this is shared in different color/print/screen environments

**Comment by finnfiddle** [comment]
I was thinking about it @Kiarii and I was thinking if we are just going to be changing the background color why dont we make it an option so that users can choose the color they want for the background instead of us predefining two modes/colors?

**Comment by Kiarii** [comment]
@finnfiddle I see your point, in my thinking toning down the color would be done in the code; and not provided as a toggle setting for the users..

**Comment by Kiarii** [comment]
@finnfiddle I have asked @loicsans to respond to this one..

**Comment by loicsans** [comment]
For the sake of keeping things simple, we can try to apply a layer covering the whole dashboard with a black background and opacity apply to be at 5% to start with. The idea is to not degrade the contrast between all elements
