### ISSUE TITLE
Lookup potential filter match values

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1602]
# Context

When you are busy creating a filter when editing a visualization - the last step of the process is problematic because you need to know in advance exactly which value you will use. There is no ability to search through the existing values.

# Idea

I propose looking up potential values when the user types in the "Filter match value" input.

# Solution or next step

Implement a lookup input that shows you potential values in a dropdown when you start typing.

**Comment by finnfiddle** [comment]
<img width="1440" alt="screen shot 2018-10-29 at 9 55 33 am" src="https://user-images.githubusercontent.com/4628721/47636394-cef05380-db60-11e8-9213-e3ed7f360388.png">
See screenshot - the value field for the new filter - the potential values are obscured - you need to know in advance what possible values you can enter. It would be more user friendly if they could select from available values with a dropdown or something

**Comment by tangrammer** [comment]
@janagombitova  @finnfiddle so ... let's say that we have a dataset with 1000 rows
and ... the user selects filter-by "first_name(text)" ... client side makes an API call to get the 1000 first_name values ... then client-side paint a select (multiple?) list so the user could select the value to match in this filter 

are you ok with this process having 1K rows? what would happen if our dataset grows to 10K?
how should we offer these feature to the user? 🤔

**Comment by janagombitova** [comment]
With this issue https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-176908-from-deden-at-akvo-dot-org Deden pointed out another thing we need to consider and improve in a better way once we dive into filters: how to handle more than one filter? 'And' and 'or' rules and how do they work with each other. 

<img width="1273" alt="screen shot 2019-01-16 at 09 27 46" src="https://user-images.githubusercontent.com/12456965/51236325-24731a00-1972-11e9-9400-7510e0b96fb8.png">
