### ISSUE TITLE
Extracting Caddisfly images 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1627]
# Context
*Why do we add this issue?*

We currently have a prototype running on dark-lumen.akvotest.org that is the 1st implementation of handling Caddisfly data. This implementation introduces multiple as a data value for columns that hold more than one value in them. In the prototype it is Caddisfly data, but in the future this can also be cascade question responses, or multiple option responses or geoshapes.

In the prototype Salim selects a Transformation option Extract multiple values and in the dropdown he selects which column he wants to work with. The dropdown only shows applicable columns (currently only Caddisfly). Depending on what Caddisfly test data we are handling options present on what he can extract to separate columns: image, one result value, another result value.

On https://dark-lumen.akvotest.org there is a data set called Caddisfly tests that you can use.

# Problem or idea
*What is the cause?*

When Salim extracts the **Caddisfly image** he gets a column with the text string. This is useless as it is not a url pointing to the image and Salim cannot do much with the string. In Flow Caddisfly images render as images. 

<img width="1257" alt="screen shot 2018-08-29 at 14 19 06" src="https://user-images.githubusercontent.com/12456965/44790194-fe093980-ab9e-11e8-9400-3b79eadbc652.png">
<img width="1254" alt="screen shot 2018-08-29 at 13 57 38" src="https://user-images.githubusercontent.com/12456965/44790196-ff3a6680-ab9e-11e8-84ae-5a46d309daca.png">

# Solution or next step
*How could we solve it?*

Is it possible to extract the caddisfly image in such a way that is shows the image if used in a map pop up for example?

**Comment by tangrammer** [comment]
tested against https://dark-lumen.akvotest.org/dataset/5b869259-74bc-4cfb-9e4f-4bb853eadbec
<img width="1057" alt="screen shot 2018-08-31 at 09 09 41" src="https://user-images.githubusercontent.com/731829/44897932-b1884000-acfd-11e8-91b1-4cf433392805.png">

**Comment by tangrammer** [comment]
Hi @janagombitova 
if you look at https://dark-lumen.akvotest.org/dataset/5b869259-74bc-4cfb-9e4f-4bb853eadbec the value for the second row (the only with geo value) and the column "New Nitrogen Image" is https://akvoflow-uat1.s3.amazonaws.com/images/null 
so the map visualisation can't render the `null` image

**Comment by tangrammer** [comment]
I did a derivation to have the first row "New Nitrogen Image" valid value in  all rows to demonstrate that the problem is just a data problem 
attached image result...
<img width="871" alt="screen shot 2018-09-03 at 19 09 14" src="https://user-images.githubusercontent.com/731829/44997234-2503a900-afad-11e8-9ca3-dde24f225a8f.png">

**Comment by janagombitova** [comment]
Then I was too hasty when testing and did not check the details and all the data. Sorry about that. 

Wonderful! 👍 This looks perfect.
