### ISSUE TITLE
Cannot have text above visualisation in dashboard 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1650]
# Context
*Why do we add this issue?*

When creating a dashboard Salim arranges the elements in different ways. He can have a map at full width, then two chart under the map next to each other, then a text box at full with, then a few visualisations next to each other. It is flexible. 

Salim expects that how the dashboard looks in his editor is the same how the dashboard will look shared (if the screen is wide enough) 

# Problem or idea
*What is the cause?*

If Salim have two visualisations next to each other and wants to add a text above the visualisation, he can arrange everything well in the editor, but in the shared link the layout changes. 

Here is a gif with a pivot table: 
https://user-images.githubusercontent.com/12456965/45078510-86806080-b0f0-11e8-8d58-cb7e8f3d446a.gif

Here are two images with visualisations
<img width="1192" alt="screen shot 2018-09-12 at 09 26 57" src="https://user-images.githubusercontent.com/12456965/45408924-061cab00-b66e-11e8-8623-eea7d633fe02.png">
<img width="1195" alt="screen shot 2018-09-12 at 09 27 10" src="https://user-images.githubusercontent.com/12456965/45408927-087f0500-b66e-11e8-9621-bb34fd10c518.png">

# Solution or next step
*How could we solve it?*

@finnfiddle Does this comment: https://github.com/akvo/akvo-lumen/pull/1646#issue-213531795 mean that it is not possible to have a dashboard where I lay out two visualisations (or more) next to each other and want to have a text box above it? 

It is possible in the editor, but once you view it via the shared link, the layout shifts. 

If this is indeed the case: 
- Can we change it to make it possible? 
- If we cannot change it, we should make it visible already in the editor that it will not work as users expect the dashboard shared via the link to looks the same as in the editor, if the screen is wide enough.

**Comment by finnfiddle** [comment]
@janagombitova this one is problematic - we need to discuss
