### ISSUE TITLE
Interactivity for dense line charts

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1654]
# Context 
However, this is not this case in line charts that are created from more data points, are more dense. In this case if when one hovers a mouse in the line chart, values are not shown. 

# Opportunity 

Salim can create line charts. If there are not so many values on the chart, he sees data points that build the chart. These points are clickable and show the value on x and y axis. 

Example interactive: https://akvointernal.akvolumen.org/s/R16WCkReUL8
Example not interactive: https://gt20-belgium.akvolumen.org/s/lxRVwXPGjM8

# Next steps 
Can interactivity also be included in line charts? 

# Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-146602-from-andrew-at-akvo-dot-org

**Comment by finnfiddle** [comment]
@janagombitova I dont really have ideas how to resolve this. Do you have any? I will look around a bit to see what solutions others have found
