### ISSUE TITLE
Hovering over charts shows different colour in shared visuals and dashboards 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1667]
# Problem or idea
*What is the cause?* 

When a user hovers over a chart we show *sometimes* a little point that has a colour that does not match the colour in the chart. I assume this should reflect the colour in the chart.

![screen shot 2018-09-19 at 10 05 46](https://user-images.githubusercontent.com/12456965/45751669-58803d80-bc13-11e8-8c1c-e1a5f53fcb89.png)

Check bar charts in this public dashboard: https://marsfood.akvolumen.org/s/WXn-RJIyY3U

# Solution or next step
*How could we solve it?*

**Comment by finnfiddle** [comment]
@janagombitova I cant reproduce locally and I cant log in to this tenant to see the original visualisations. Can I either get access to this tenant or some concrete steps to reproduce it?

**Comment by janagombitova** [comment]
@finnfiddle I have just sent you an invite to the tentant

**Comment by janagombitova** [comment]
Resolved. Just checked the dashboard where we found the issue and all is well now.
