### ISSUE TITLE
Bar chart value labels do not fit in the bar

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1682]
# Problem or idea
*What is the cause?*

If Salim selects to show the value label on bar charts and the bar is not high enough, the label overlaps on the x axis or the bar bucket name. In such cases, when the value does not fit in we need to find a better solution. 

<img width="835" alt="screen shot 2018-09-28 at 14 05 14" src="https://user-images.githubusercontent.com/12456965/46214488-99770100-c33b-11e8-854a-76ec4457501b.png">

<img width="840" alt="screen shot 2018-09-28 at 14 05 36" src="https://user-images.githubusercontent.com/12456965/46214578-c3c8be80-c33b-11e8-9ac5-06bc89e348a2.png">

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
I suggest just hiding the labels for the small bars @janagombitova
