### ISSUE TITLE
Don't allow deletion of datasets that is used in a merge transformation

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1689]
# Context
For datasets used in viz there is a warning when trying to delete. For dataset used in merge transformations there is not.

# Problem or idea
The problem is that deleting a dataset gives no warnings but can cause a lot of work useless.

# Solution or next step
We should either warn of not allow dependent datasets to be deleted.

---------------------

**Comment by kardan** [comment]
Possible options:
A: Don't allow deletion of datasets that are used in transformations
B: Warn that datasets have dependents but allow deletion of only the single dataset
C: Warn that datasets have dependents and delete everything that is dependent (other datasets & viz)
D: Do what we do today. Allow deletion and fails. But make sure the user can remove failing transforms to not get stuck
E: ?

**Comment by tangrammer** [comment]
@kardan after playing a bit with the transformation-merge-datasets, I think we also need to take care of  the source columns dataset consistency, thus if  we e.g remove a column that participates in merge operation then "updating" dataset should fail 🤔

**Comment by tangrammer** [comment]
this code is WIP
`select DISTINCT ON (dataset_id) dataset_id, id, version, transformations from dataset_version order by dataset_id, version desc`

**Comment by kardan** [comment]
I'm not sure what I think. In one way it's odd if there is two users involved. Can the merger block the original author at the point? @janagombitova

**Comment by janagombitova** [comment]
After our talk last week about this issue we agreed to also **not allow to delete a dataset that is used in a merge**? Should we create a separate issue for this change?

**Comment by tangrammer** [comment]
@janagombitova not necessary another issue, I just started ensuring update operations to protect the database from inconsistencies .... working now in "not allow to delete a dataset that is used in a merge"

**Comment by janagombitova** [comment]
And then the next step would be to also not allow to delete the column from the data set used in merge, right? @tangrammer

**Comment by tangrammer** [comment]
yep!
