### ISSUE TITLE
Add dashboard title to download

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1694]
# Context
*Why do we add this issue?*

With https://github.com/akvo/akvo-lumen/issues/952 we now enable to download visualisations and dashboards as pngs or pdfs. This is a great improvement as many of the visualisations and dashboards are not only used as live online ways to showcase insights but are also added to presentations and reports. 

# Problem or idea
*What is the cause?*

Right now you export what shows in the editor, so no name.

![testing issues](https://user-images.githubusercontent.com/12456965/46660807-2c276380-cbb8-11e8-88e4-a7be1ff21175.png)

When sharing the dashboard via the url the name shows as a title and I can expect users will want that in the exports too. Often the dashboard name serves indeed as a title and then the next item in the dashboard is text explaining the visualisations below. 

# Solution or next step
*How could we solve it?*
Would it be possible to show also the **name/title** of the dashboards in the export?

**Comment by janagombitova** [comment]
Besides adding the dashboard title to the export file, can you also remove: 
- the small pointer under each visualisation with which you change the visualisation's size in the editor
- the placeholder for 'x' in the top right corner of each visualisation? 

These two items are of no use in the export and removing them will clean up how the file looks.

**Comment by kardan** [comment]
A very crude title was added. But to separate different work, we will push the feature as is out and then iterate look and feel.

**Comment by janagombitova** [comment]
I would suggest we close this issue and handle 2nd round of improvements in a new one once we collect feedback. What do you think @kardan ?

**Comment by kardan** [comment]
Agree!
