### ISSUE TITLE
Speed up builds

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#1710]
# Context
The build time in CI has increased dramatically. We're adding more components and we're building everything from scratch on every build

# Problem or idea
We have Docker images that do not change too often and we can build them separately and just use them as part of the docker-compose system.

# Solution or next step

- Move development Docker images to https://github.com/akvo/akvo-dockerfiles
- Use the built images in the docker-compose system

**Comment by kardan** [comment]
Should we close https://github.com/akvo/akvo-lumen/issues/1270 ?

**Comment by iperdomo** [comment]
@kardan yes
