### ISSUE TITLE
Logging in and out makes exports fail

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1717]
I am trying to test the exports in production and I am getting an export, but it is all greyed out and says `Failed to load library. Please refresh the page and check you are authorised to access the tenant` (the same as you get when you try to log into a lumen tenant without logging out via keycloak first, instead of just opening a new window. 

I have two accounts I use to access the demo Lumen instance: jana@akvo.org and support@akvolumen.org. 

I log into demo.akvolumen.org with jana@akvo.org and export a map. All works well. Now I log out via the use tab (Keyloack) and log in with support@akvolumen.org. When trying to export being logged in with support@akvolumen.org I have access to the tenant as I can access everything else on it, but the exports do not work. I have tried using a private Firefox window with no other tabs opened. 

Now for instances where I do not even have access with my personal account I cannot test the exports as they fail even when I am only logged in with the support account on private browsers.

**Comment by janagombitova** [comment]
Here is a gif of the steps I took and what I see: 

![2 accounts](https://user-images.githubusercontent.com/12456965/47363052-29f3f780-d6d6-11e8-80ce-a6259ece394f.gif)

**Comment by kardan** [comment]
I have tried but not been able to replicate the issue. A bit baffled by the issue at the moment :-(

**Comment by janagombitova** [comment]
Is there a chance this is an isolated case? We can leave the issue open but pause the reserach till we find another case that is not on my machine.

**Comment by tangrammer** [comment]
@janagombitova @kardan 
I tried to reproduce locally the error, but I couldn't 🤔 
My feeling is that we have some kind of cache around here 

Jana, could you repeat the test and paste here the request headers of token and exports API calls that are called when we click the `export` button? 

I attach 2 images of the thing I'm interested in ... 
<img width="953" alt="screen shot 2018-10-25 at 11 34 12" src="https://user-images.githubusercontent.com/731829/47491005-25505000-d84a-11e8-8753-7b22381a716b.png">
<img width="956" alt="screen shot 2018-10-25 at 11 34 03" src="https://user-images.githubusercontent.com/731829/47491007-271a1380-d84a-11e8-8c71-9c84815986bb.png">

**Comment by janagombitova** [comment]
@tangrammer here are the screen shots that I have taked after being logged in with the user that gets the failed authenticated exports and clicking on the export button. I hope this is what you were looking for, if not, let me know. 

## Token
![screen shot 2018-10-25 at 13 39 01](https://user-images.githubusercontent.com/12456965/47497864-baa81000-d85b-11e8-803c-2b31e48ab086.png)
![screen shot 2018-10-25 at 13 39 17](https://user-images.githubusercontent.com/12456965/47497866-bc71d380-d85b-11e8-9447-8422d1fde575.png)

## Exports 
![screen shot 2018-10-25 at 13 39 39](https://user-images.githubusercontent.com/12456965/47497871-c562a500-d85b-11e8-9638-dfebbf0bdf60.png)
![screen shot 2018-10-25 at 13 40 02](https://user-images.githubusercontent.com/12456965/47497874-c85d9580-d85b-11e8-8bac-beaa2b3d5bab.png)
![screen shot 2018-10-25 at 13 40 20](https://user-images.githubusercontent.com/12456965/47497877-ca275900-d85b-11e8-802c-11e5619774b5.png)

**Comment by janagombitova** [comment]
Hi @tangrammer I copied over the token and export headers as you said. You can find them here: https://docs.google.com/document/d/1HJMZtBiUPApKTbpJMsrWIVcf0iIKfcEOhgl6sBjRMKw/edit#

**Comment by tangrammer** [comment]
After debugging carefully the logs in dark production, we don't have any auth problems there :) 
but seems we have again the *big* odd problem behind this issue 
<img width="1131" alt="screen shot 2018-10-29 at 11 18 40" src="https://user-images.githubusercontent.com/731829/47643661-6c04b980-db6c-11e8-8045-c2400ad3cabc.png">
"Error: Protocol error (Runtime.callFunctionOn): Target closed." from exporter service

Once that we reach this problem, the exporter service doesn't process properly the export action. So it stops and client returns the "Failed to load library ... "

**Comment by janagombitova** [comment]
I cannot reproduce the error anymore! 👍

**Comment by tangrammer** [comment]
yupie!
