### ISSUE TITLE
Exporting maps not working 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1723]
When trying to export this map: https://westafrica.akvolumen.org/visualisation/5bc8b4cc-f189-42ad-bfe5-53b95e42edf4?show-export=1 or this one: https://westafrica.akvolumen.org/visualisation/5bc4bc07-a7f3-41d1-8530-843fbeb7f5e2 and I get a 500 error in console and the export fails

<img width="1274" alt="screen shot 2018-10-24 at 14 53 31" src="https://user-images.githubusercontent.com/12456965/47431757-f7610200-d79c-11e8-8483-d607103aa880.png">
<img width="1272" alt="screen shot 2018-10-24 at 14 57 47" src="https://user-images.githubusercontent.com/12456965/47431892-37c08000-d79d-11e8-8766-156d228d2743.png">
<img width="1273" alt="screen shot 2018-10-24 at 14 57 56" src="https://user-images.githubusercontent.com/12456965/47431898-38f1ad00-d79d-11e8-9922-81baf1815a07.png">

**Comment by tangrammer** [comment]
I could reproduce the issue locally using this character `’` in the visualisation title name 

according to https://stackoverflow.com/a/46105399/1074389
it *seems* that ...

> That TypeError gets thrown by node when making an outgoing HTTP request if there is any string in the request headers option object contains a character outside the [basic ASCII range](https://github.com/nodejs/node/blob/v4.8.4/lib/_http_common.js#L278-L292).

**Comment by janagombitova** [comment]
Works fine following my test
