### ISSUE TITLE
Cannot go back to Lumen when in user's profile page 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1728]
# Problem or idea
*What is the cause?*

When a user goes to her profile she lands in the akvo user management service (Keycloak). She often goes here to change the language or to just see her user profile. Once she wants to go back to Lumen, there is no way. She needs to retype the instance url. 

![no-button-back-to-lumen-portal](https://user-images.githubusercontent.com/12456965/47548607-d9f57a80-d8f9-11e8-9faa-2016967513d7.gif)

# Solution or next step
*How could we solve it?*

**Comment by kardan** [comment]
Since we're planning to move from Keycloak I'm closing this issue
