### ISSUE TITLE
User email invites not being sent 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1742]
# Context

To add a new user to Lumen you invite her. She then receives an email invitation with a link she needs to click on and only then she can access Lumen. 

# Problem
No emails are being sent to the invited users causing them not being able to access Lumen. 

# Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-160982-from-eric-at-akvo-dot-org

1.pdf (https://s3.eu-west-1.amazonaws.com/cdn.supporthero.io/ticket/747/1.pdf)

**Comment by kardan** [comment]
Other findings:
We have references to email-host which I think was when we tried to send email via our webserver and not an external web API. Thinks like: 
https://github.com/akvo/akvo-lumen/blob/develop/ci/k8s/deployment.yaml.template#L71
https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/config.clj#L27
https://github.com/akvo/akvo-lumen/blob/develop/backend/resources/akvo/lumen/config.edn#L125
But it's never used in any of the emailers at https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/component/emailer.clj

**Comment by kardan** [comment]
Been able to send myself email with the credentials so don't think it's something wrong with the service we use.

**Comment by janagombitova** [comment]
Issue resolved. All works well
