### ISSUE TITLE
React is running in production mode, but dead code elimination has not been applied. Re

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1756]
# Context
Why do we add this issue?
https://sentry.io/akvo-foundation/test/issues/755044390/?referrer=slack

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
issue is back

**Comment by kardan** [comment]
Looks like this is solved in both production and on test, hence closing
