### ISSUE TITLE
Marging aligment on shared dashboards

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#1770]
# Context
Visual difference between left vs right margin on Firefox (Linux)
![2018-11-14_1917x499_scrot](https://user-images.githubusercontent.com/178474/48470157-f72eb200-e7f0-11e8-9d9a-f6488c77cf6c.png)

OS: Arch Linux (4.19.1-arch1-1-ARCH)
Browser: Firefox 63.0.1 (64-bit)

# Problem or idea
It seems that the right margin is not honored

# Solution or next step
Test in more browsers than just Chrome :wink:

**Comment by janagombitova** [comment]
looks good
