### ISSUE TITLE
Bubble Chart

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1787]
# Context

See #1734 for more info.

**Comment by janagombitova** [comment]
![screen shot 2018-11-29 at 10 45 09](https://user-images.githubusercontent.com/12456965/49213218-0ce0d180-f3c4-11e8-94ad-97c6ab27d797.png)

After testing bubbles today and talking with Finn we agreed to make the following improvements: 
- fix sharing 
- once Salim selects the Bucket, bubbles show right away based on 'count' (as with bar charts) 
- once Salim selects the Metric he can also select the Aggregation method

**Comment by janagombitova** [comment]
Hey @finnfiddle I tested it out sharing and changing aggregation work now well. It makes more sense now as well with the Aggregations available ;) 

But I get a lot of errors when I just select the bucket column, see that my aggregation is count but the bubbles are not generated. 

Check this one out: https://dark-lumen.akvotest.org/visualisation/5c000056-d720-4cfd-8e95-1f86971b8b81

![bubble](https://user-images.githubusercontent.com/12456965/49230858-f56c0d80-f3f0-11e8-972c-ff4032054b3d.gif)
<img width="1249" alt="screen shot 2018-11-29 at 16 08 20" src="https://user-images.githubusercontent.com/12456965/49230899-0a48a100-f3f1-11e8-863c-213e43a34362.png">
