### ISSUE TITLE
Dataset name should be mandatory

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#179]
When importing a CSV file, you can leave the _Dataset name_ text box empty and continue with the process. Leading to an _Unamed_ dataset.
![2016-05-27-065259_1366x768_scrot](https://cloud.githubusercontent.com/assets/178474/15598191/e44c6bb2-23d7-11e6-8d4f-d2a613640c2d.png)
![2016-05-27-065308_1366x768_scrot](https://cloud.githubusercontent.com/assets/178474/15598192/e907e5be-23d7-11e6-9732-5c057138fb79.png)

**Comment by gabemart** [comment]
Closed via #185
