### ISSUE TITLE
Extracting multiple gives a 404

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1808]
This dataset: https://sierraleone.akvolumen.org/dataset/5bf97378-76c0-418c-86c1-392f12e78ad5 holds multiple `multiple` type columns. When trying to extract the data, Lumen gives a 404. 

After trying to update the dataset (what usually helped to mitigate this problem) I get a 400 error. 

![screen shot 2018-11-26 at 08 33 19](https://user-images.githubusercontent.com/12456965/48999579-5973a500-f157-11e8-9a2e-43bd650678fa.png)

**Comment by tangrammer** [comment]
I've set up a PR for that
I couldn't reproduce the issue with flow survey locally nor in the production environment. So my suspicions are that flow question type wasn't properly set to `caddisfly` type in flow.

The PR affects only to update operation, so clicking update will fix this odd scenario
