### ISSUE TITLE
Improve UX for adding entities to dashboard

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#183]
It can be confusing to add an entity to a dashboard when it is added to a position that is not visible in the viewport.
- [ ] In this case we should automatically scroll the dashboard editor such that the new item is visible
- [x] Additionally, I think we should add some indication of a new entity more generally - for example, give new entities a green background that fades out in 1 second

**Comment by janagombitova** [comment]
This issue has been resolved. Once a new visualisation is added we scroll to the bottom of the dashboard where it was added. Same applies for text areas.
