### ISSUE TITLE
Make it an easy task to see what's running where

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1834]
# Context
We deploy to production by merging to master and then switching the dark environment to light (production) is a manual step. 

# Problem or idea
For anyone not doing the actual switching (might be the switcher a few days in the future) it's not easy to get a grip on what's running where.

# Solution or next step
A. We could expose the build SHA to the web app and render it somewhere. 
B. We could have a script that gathers all info
C. We could have a visual representation on a page somewhere?

# Ref
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Comment by kardan** [comment]
We have access to the commit sha in the K8s deployment and in the exporter we already use this value (for Sentry). https://github.com/akvo/akvo-lumen/blob/develop/ci/k8s/deployment.yaml.template#L66

**Comment by kardan** [comment]
Let's not work on this until we done the Reitit work.

**Comment by kardan** [comment]
First step can be to expose the build sha to the /env endpoint.

**Comment by janagombitova** [comment]
@kardan is this issue related to #2336?

**Comment by kardan** [comment]
@janagombitova not really what I was thinking about. But it's in the same spirit. I opened a PR for what I was thinking about https://github.com/akvo/akvo-lumen/pull/2338. An even better thing would be that we had some web UI where we could see what's running where. But I think we got other things to work on :-)

**Comment by kardan** [comment]
New keys lumenDeploymentColor, lumenDeploymentEnvironment & lumenDeploymentVersion now available on /env endpoint (available in in test https://lumen.akvotest.org/env).
