### ISSUE TITLE
client request error handling

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1838]
# Context
Why do we add this issue?
If a request to the api fails we currently dont handle it - it just throws an error. Eg: https://sentry.io/akvo-foundation/test/issues/794513526/?referrer=slack

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?
Handle the errors

**Comment by kardan** [comment]
We should review if the backend is responding with valuable error messages. If not maybe we could?

**Comment by janagombitova** [comment]
Hi @finnfiddle and @kardan, what is the status of this issue? Is it completed, tested and can be closed or is there is more to be done?
