### ISSUE TITLE
Pivot tables improved design

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1857]
# Context
*Why do we add this issue?*

We are currently working on adding new visualisations to Lumen (4 dimensional scatter plots, bubble charts and polar areas) and improving the existing ones. There is one visualisation type that is used frequently and we have not improved since its 1st iteration are **pivot tables**

# Problem or idea
*What is the cause?*

From the feedback we received from our users, they appreciate the flexibity and visual appeal of the charts, but feel that pivot tables lack behind and asked us if we can "Akvotise the pivot tables" to make them look more appealing. 

![screen shot 2018-12-12 at 14 08 36](https://user-images.githubusercontent.com/12456965/49871920-cfdefb00-fe17-11e8-8801-3aac837f1087.png)

# Solution or next step
How could we solve it?
@loicsans and @Kiarii can you give this a look?

**Comment by Kiarii** [comment]
My take on this one is that we can only simplify the table to make it easier for Salim to scan and read its content. https://medium.com/mission-log/design-better-data-tables-430a30a00d8c

"When deciding how to style the graphic elements of a table, the goal should always be to reduce the table’s footprint without losing structural fidelity. One of the ways you can accomplish this is by using as little “ink” as possible — that is, whenever possible, choose not to style an element."

Adding colors, would be a no go; given that in contrast to visualizations, actual data is read or scanned while with visualizations, colors are the primary way of figuring out its content
