### ISSUE TITLE
Switching visualisation types gives blank page 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1862]
# Context 
Salim creates a visualisation and wants to explore which visualisation type 'works' better to convey the insights he just found. So he switches to a different visualisation type and assumes it either generated a new visualisation or some of the variables that he defined are preset for him to further continue. 

# Problem or idea
When switching from one type to another Salim gets a white blank page. These are the connections that do not work: 

- from bar to bubble
- from polar to bubble
- from scatter to bubble 
- from scatter to bar

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
closing because already has been fixed in https://github.com/akvo/akvo-lumen/pull/1861

**Comment by janagombitova** [comment]
@finnfiddle I was not aware this was merged. Can you confirm all works well on dark-test or test. I am not sure on which of the two the fix is running currently. Thanks
