### ISSUE TITLE
Improvements to library selecting functionality

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1870]
# Context

While trying to delete many items in the library I noticed some things that could be improved:

# Problem or idea

1. When you select multiple you can't then delete them at once
2. You can't select all from a certain day
3. When you click delete and it prompts you "are you sure?" - you cant hit the ENTER button to accept

# Solution or next step

1. Add a delete button in the bottom bar when selecting multiple
2. Add a button "Select all" next to the day title
3. listen for enter button press when prompting - are you sure

@loicsans  @janagombitova @kardan what do you think?

**Comment by janagombitova** [comment]
I agree. It is a good idea. Can you also connect with @Kiarii and/or @loicsans on it?
