### ISSUE TITLE
Simplify error message when merging datasets 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1879]
# Context
When something goes wrong we inform Salim with error notifications. These are simple to understand and informative (if possible) for him to take action. 

The case relevant to this issue is when: 
1. Salim merged two datasets 
2. Salim deleted a column that is merged 
3. Salim tries to update the data set with the merged in column 

In this situation we show him this error: 
![screen shot 2018-12-20 at 10 53 29](https://user-images.githubusercontent.com/12456965/50277920-0c2cdf80-0446-11e9-991d-2cf0da0690fd.png)

# Problem 
This error message has typos, is confusing, long and holds too technical info. It should say what happened, and why this happened. We do not need to add the dataset IDs as these are invisible to Salim. 

# Created via Reamaze:

Link: /admin/conversations/error-message-dataset-update

**Comment by janagombitova** [comment]
### Option A:
Update failed. This dataset has merged columns that no longer exist in their dataset, [name]

### Option B: 
Update failed. Columns merged from [dataset name] no longer exist. 

### Option C: 
Update failed. Merged in columns no longer exist in their dataset, [name]. 

@tangrammer and @finnfiddle and @kardan What do you think?

**Comment by tangrammer** [comment]
@janagombitova 
we have a few messages related with merging dataset ops. Could you verify/correct those that should be improved?

- **on delete dataset:**
"This dataset is used in merge tranformations with other datasets: {:id \"5ccfe81e-a9f8-4006-96ea-c5ea0d4c5bc8\", :title \"name\"}
  - BTW: Client side doesn't show the message yet :!
- **on delete column used in merge-dataset op**:
"Failed to transform. Following datasets have merge operations based on this column {:id \"5ccfe81e-a9f8-4006-96ea-c5ea0d4c5bc8\", :title \"name\"}
  - Client side doesn't show the message yet either :!
- **on update dataset**:
  - **with dependent datasets already removed** 
"This version of the dataset isn't consistent thus it has merge transformations with datasets which were already removed. Dataset diff: [:diff #{\"5ccff9e0-6119-4379-9519-8bc165386c4e\"}]"
  - **with dependent columns from datasets already removed** 
"This version of the dataset isn't consistent thus it has merge transformations with datasets columns which were already removed from their datasets: {:diff #{\"c3\"}, :dataset-id \"5ccffa74-5498-4274-944d-8ebb9c368339\"}"

**Comment by janagombitova** [comment]
Hi @tangrammer I would overall not show the IDs as users do not know they exist and thus cannot use them as references. Here are some suggestions on how to structure the text:  

- **on delete dataset:** - does this show when the user is trying to delete a dataset? If yes then I would suggest: Cannot delete dataset. It is used in merge transformations in dataset, [name]. 
-**on delete column used in merge** - does this show when a user is trying to delete a column? If yes then I would suggest: Cannot delete column. It is used in merge transformations in dataset, [name]
- **on update dataset:**
   - **with dependent datasets already removed** - Update failed. This dataset has merged columns from a dataset that no longer exists. 
   - **with dependent columns from datasets already removed** - Update failed. This dataset has merged columns that no longer exist in their dataset, [name]

**Comment by tangrammer** [comment]
<img width="1099" alt="Screen Shot 2019-05-08 at 20 44 28" src="https://user-images.githubusercontent.com/731829/57401890-ab285d00-71d6-11e9-9cbf-8fb3b0b41a6e.png">
<img width="849" alt="Screen Shot 2019-05-08 at 21 17 11" src="https://user-images.githubusercontent.com/731829/57401893-ae234d80-71d6-11e9-8d6d-26b18045be41.png">

**Comment by janagombitova** [comment]
@tangrammer can we make one more change? Can you remove the [ ] brackets? That was me trying to indicate that the name should go there, but I was not clear that is should we without the brackets. Thank you

**Comment by tangrammer** [comment]
<img width="826" alt="Screen Shot 2019-05-14 at 09 39 51" src="https://user-images.githubusercontent.com/731829/57679677-3a48d100-762c-11e9-8270-37cfd53375e3.png">
<img width="864" alt="Screen Shot 2019-05-14 at 09 39 18" src="https://user-images.githubusercontent.com/731829/57679678-3a48d100-762c-11e9-80fc-bab2cda944f6.png">
