### ISSUE TITLE
Investigate the possibility of using Undertow adapter with Immutant web

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#188]
- https://lists.jboss.org/pipermail/keycloak-user/2016-May/006430.html
- https://transcripts.jboss.org/channel/irc.freenode.org/%23immutant/2016/%23immutant.2016-05-27.log.html

**Comment by iperdomo** [comment]
A sample code of authenticating an Undertow webserver with Keycloak can be found at:

https://github.com/iperdomo/undertow-keycloak

**Comment by finnfiddle** [comment]
@iperdomo do you know is this still an issue?

**Comment by iperdomo** [comment]
@finnfiddle is still an _open_ issue, it depends on the need of doing it. Moving to an Undertow adapter means moving to server side sessions.

I'll schedule a conversation with @kardan and @dlebrero about it

**Comment by finnfiddle** [comment]
@iperdomo ok theres no urgency Im just trying to see if there are old issues that can be closed

**Comment by dlebrero** [comment]
https://github.com/dlebrero/akvo-lumen/commit/b19c476f90884ab71878e22b4e18d2374bcc4891

**Comment by dlebrero** [comment]
We will use Istio once it is production ready
