### ISSUE TITLE
Multi-series line & area chart

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1886]
This issue is a copy of: https://github.com/akvo/akvo-product-design/issues/261

Multi-series line charts are most often used to compare how two or more variables change over time.
It's a graph that is commonly used in time-series analysis.

A multi-series line chart would look something like that:

<img width="540" alt="screen shot 2017-04-21 at 17 48 51" src="https://cloud.githubusercontent.com/assets/21127166/25285533/d5ce3a3e-26ba-11e7-9634-168047c28b52.png">

And here's an example of multi-series area chart:

<img width="482" alt="screen shot 2017-04-21 at 18 05 48" src="https://cloud.githubusercontent.com/assets/21127166/25286265/76558870-26bd-11e7-95b3-9bdf6dfcfddc.png">

In Lumen, we already have Line charts and Area charts, but so far, they only support single series. 

As to use cases, Flow monitoring data, for instance, could be best visualised using multi-series and area charts.

**Comment by Kiarii** [comment]
I think this is similar to the issue #2131 the main difference being  i) the chart type and ii) the use of monitoring data to show change over time.. my suggestion is to consider this in a storymapping whence we can derive a workflow that can maintain some uniformity for both use cases while providing necessary options in each..

**Comment by janagombitova** [comment]
Molo and Mert shared a dataset where they are looking at making such visualisations. When looking at how they build the chart the main use case is selecting multiple columns for the y-axis using the same aggregation method. This is similar to how we implemented multiple series for bar charts. 

<img width="1177" alt="Screen Shot 2020-08-05 at 20 03 49" src="https://user-images.githubusercontent.com/12456965/89447848-f96c3900-d756-11ea-8392-9f1afdd09cea.png">
*This is just a piece of the dataset to protect personal data**
