### ISSUE TITLE
Sharing individual visualisations from public dashboards

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1889]
This issue is a copy of its original: https://github.com/akvo/akvo-product-design/issues/270
Created via Reamaze by Lynn:

As a visitor to a public dashboard, such as https://demo.akvolumen.org/s/tgdAOXjc8Ws <https://demo.akvolumen.org/s/tgdAOXjc8Ws> , I notice that the graph/visualisation G4AW VN - Fertilizer, exactly relates to research I am doing into how fertilisers affect the agricultural soil quality.
I need a share option on only that specific visualisation so that only the relevant visualisation can be shared to my social media followers on Twitter and Facebook or displayed on my own website within the content related to my research on the subject.
Of course if the dashboard is not public, this option should not be available to me, and if the dashboard is public the Lumen user should decide whether the option to ‘share’ is available.

A use case for this would be one of Lars Heemskerk’s West Africa Akvo Sites where data is currently visualised via a plugin, as well as the GT2.0 Swedish demo case where it would be useful for a visitor to the FreshWaterWatch Lumen integration page may want to share a visualisation.

**Comment by kardan** [comment]
My initial thought on this is that it sounds a bit odd that someone without access to the underlying Lumen instance would be able to create new shares (even if it's shared before in another context). What would, for example, happen if it's shared publicly. External user shares one viz on his/hers site. Then the original dashboard creator adds a password or just wants to hide the Dashboard from sharing. 

There are spins on this; one could argue that we could make all viz that are part of a shared Dashboard publicly available by themselves. Not sure if there is a use case for this or not.
