### ISSUE TITLE
Bar visualisation client UI doesn't call aggregation backend API

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#1900]
# Context
Some bar visualization options aren't sent to the backend via /aggregation API
Detected ones so far:
+ sub-bucket column value
+ truncateSize
+ sort
+ adding/removing filters don’t aggregate either

# Problem or idea
client bug

# Solution or next step

**Comment by janagombitova** [comment]
Hi @finnfiddle and @tangrammer, what is the status of this issue? Is it completed, tested and can be closed or is there still more to be done?
