### ISSUE TITLE
Changing scatter size column gets blank page

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#1901]
# Context
<img width="694" alt="screen shot 2019-01-09 at 17 07 45" src="https://user-images.githubusercontent.com/731829/50911954-3c5a1380-1431-11e9-92e3-d6b0dd71f751.png">

# Problem or idea
Selecting a size column breaks the UI (blank page)

# Solution or next step
...

**Comment by finnfiddle** [comment]
@tangrammer I cant reproduce - is it still reproducible on your side?

**Comment by tangrammer** [comment]
@finnfiddle yep, still happening here. Try to unselect the size value to force the problem

**Comment by finnfiddle** [comment]
this should be fixed in https://github.com/akvo/akvo-lumen/pull/1952

**Comment by janagombitova** [comment]
no blank pages on dark test. looking good
