### ISSUE TITLE
cypress tests failing intermittently

### ISSUE THREAD

**Issue by finnfiddle** [akvo/akvo-lumen#1969]
# Context
Why do we add this issue?
https://dashboard.cypress.io/#/projects/wazc6q/runs/2192/specs
# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Builds are all green. Is that sufficient enough to conclude this issue is resolved and we can close it? @finnfiddle and/or @kardan?

**Comment by finnfiddle** [comment]
I would say yes
