### ISSUE TITLE
Deleting anything gives an error but works 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1971]
# Context
Why do we add this issue?
To not confuse users that something did not work even though it did. 

# Problem or idea
What is the cause?

When deleting a visualisation (any kind) or a dataset from the Library I get the red error message saying it failed to delete. But the visualisation or dataset is gone from the library what makes it confusing. 

![screen shot 2019-02-13 at 16 16 15](https://user-images.githubusercontent.com/12456965/52721820-c9e9cf80-2faa-11e9-8d82-e1d896e00bd0.png)

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Is there more to be done here? I checked on production and it works well

**Comment by kardan** [comment]
Nah, the fix was merged with the last release
