### ISSUE TITLE
Legend position simplify dropdown

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1990]
# Context
Why do we add this issue?
Child of #1855 

# Problem or idea
What is the cause?

<img width="337" alt="screen shot 2019-02-19 at 14 00 07" src="https://user-images.githubusercontent.com/12456965/53016777-b0cf9b80-344e-11e9-9273-44c9a223a506.png">

I noticed in the dropdown there are 5 options: Auto, Right, Left, Botton, Top. But by default auto is Right. Can you instead of showing auto, show the legend position dropdown directly with Right selected as the default option?

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
if the screen has a portrait layout then the default is Right otherwise if it has a portrait layout then the default is Bottom if Im not mistaken. Thats why we have an Auto option. @janagombitova

**Comment by janagombitova** [comment]
Ohhh interesting. I did not know that. Closing the issue then
