### ISSUE TITLE
Horizontal percentage stacked bars 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1997]
# Context
Why do we add this issue?

Child #1395 

# Problem or idea
What is the cause?

Showing percentage labels and the values and percentage when hovering over the buckets works well now on the dark test, but it does not work when I flip the bar chart to the horizontal layout. If I flip back to vertical it works fine again.

![screen shot 2019-02-20 at 11 17 49](https://user-images.githubusercontent.com/12456965/53084469-32800180-3501-11e9-85d2-ea69a2fb542d.png)

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
A lot of percentages are NaN and others are not making sense in horizontal mode, still an issue.

**Comment by finnfiddle** [comment]
I cant reproduce locally have you got a link?

**Comment by kardan** [comment]
https://lumen.akvotest.org/visualisation/5c51b12a-fb6b-495f-a9fb-174fbc5db636

**Comment by janagombitova** [comment]
We missed one tiny detail. The labels do not show. https://lumen.akvotest.org/visualisation/5c875c00-6fdb-4aab-86af-bdc1b16b4c38
