### ISSUE TITLE
Inconsistency data stored through PUT api/visualisation/:id

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2057]
# Context
There is no validation in `spec` attribute  body payload on `PUT /api/visualisation/:id` , and current `client` side is sending any spec when we switched visualisation-type  using the horizontal scroller 
<img width="402" alt="Screen Shot 2019-04-02 at 15 38 56" src="https://user-images.githubusercontent.com/731829/55407004-7da81e00-555d-11e9-9b1c-fb5bbfc1cd7a.png">

As a result of both worlds, we're storing wrong specs in the `visualisation.spec` table

Example of `area-type-spec` with `pie` visualisation-type:
```clojure
{:name "Untitled visualisation",
                 :visualisationType "pie",
                 :type "visualisation",
                 :created 1554194706677,
                 :modified 1554200128582,
                 :datasetId "5ca2635b-d3be-4ab1-9ec8-8a8f1ad9a08a",
                 :author author,
                 :spec
                 {:showLegend true,
                  :metricColumnX "c5",
                  :metricAggregation "q1",
                  :filters [],
                  :axisLabelYFromUser true,
                  :legendPosition "left",
                  :bucketColumn nil,
                  :showLabels true,
                  :metricColumnY "c4",
                  :axisLabelX "jor",
                  :legendTitle nil,
                  :axisLabelXFromUser true,
                  :axisLabelY "Temperature - q1",
                  :version 1,
                  :sort nil},
                 :status "OK",
                 :id "5ca32112-43c1-4c91-9ca3-a79278906660"}
```

# Solution or next step
`Backend` should add specs to conform on these endpoints 
`Client` should not send wrong spec to the backend

It seems that `client` has some work done in this aspect thus `client` only calls `/api/aggregation/uuid/vis-type?query=xxxx` whith proper spec data. So not called when we switched visualisation-type  using the horizontal scroller

**Comment by tangrammer** [comment]
@finnfiddle could you take a look at the `client` part of this issue?

**Comment by finnfiddle** [comment]
@tangrammer yes sure

**Comment by tangrammer** [comment]
#2063 depends on this issue too

**Comment by janagombitova** [comment]
This was merged to develop on 22 April. I am closing the issue under the assumption that it is done. If not, @tangrammer please reopen it. Thanks
