### ISSUE TITLE
Add column name to Column mismatch error 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2094]
# Context
When something goes wrong we inform Salim with error notifications. We aim to make them simple to understand and informative (if possible) for him to take action. 

# Problem or idea

![Screen Shot 2019-04-23 at 16 19 50](https://user-images.githubusercontent.com/12456965/56589094-e0cd2380-65e4-11e9-9c06-883705c5f8cd.png)

However, in the case of error **Column mismatch** the error message is not informative enough, as Salim does not know which column(s) is not matching causing him to have to check every single column in his original sheet and in Lumen what can be a pain if there are many columns in the dataset. 

# Solution or next step

When handling this issue for a user (via support) @tangrammer added the column name to the logs: https://github.com/akvo/akvo-lumen/commit/3eb7f59f446a44baa757ed1905b99212ef32c6f8 

- Can we add to the error message box the column name(s) that are the ones Salim needs to check and change in order for the update to work? 
- Is there any other extra information we can give Salim to know what action to take (as the reason for mismatching, point to a transformation that is causing the update to fail)? 

This change can be handled with #1879 as it also improves error messaging but for merged datasets.

**Comment by janagombitova** [comment]
Nice. Works well and tells you more to be able to find where the issue lies. Well done

**Comment by janagombitova** [comment]
I guess we can close this issue, right? @tangrammer

**Comment by tangrammer** [comment]
sure!
