### ISSUE TITLE
Points do not show on map (imported dataset via Google sheet link)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2097]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?
Our colleague reported an issue that her map does not how the points anymore. She created a dataset in Lumen via importing the data via Google Sheet and used the transformation to create geopoints. She then created a map and all worked fine. After updating the dataset the points stopped showing on the map. 

Here is an example map: 
https://footballforwater.akvolumen.org/visualisation/5c9a19ef-9942-4367-bae5-d70432b09dc6

Here is the issue I get in Console after opening the map: 

![Screen Shot 2019-04-25 at 10.03.21.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/9c35e228-6e21-4f07-b91a-69818e57d1b0)

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
So it seems all maps on the Lumen instance do not show points, where on other instances there is no issue.

**Comment by tangrammer** [comment]
https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=akvo-lumen&authuser=1&minLogLevel=0&expandAll=false&timestamp=2019-04-25T14%3A01%3A49.408000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.pod_id%3D%22lumen-blue-66cc699d85-7wql5%22%0Aresource.labels.zone%3D%22europe-west1-d%22%0Aresource.labels.project_id%3D%22akvo-lumen%22%0Aresource.labels.cluster_name%3D%22test%22%0Aresource.labels.container_name%3D%22lumen-backend%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.instance_id%3D%226615060407602635879%22%0Atimestamp%3D%222019-04-25T13%3A59%3A44.595761157Z%22%0AinsertId%3D%221huf70sg3bmccw0%22&scrollTimestamp=2019-04-25T13%3A59%3A44.595768223Z




ERROR: permission denied for relation ds_424e74a5_bbd4_4536_9ea6_e40bf2562d40

**Comment by janagombitova** [comment]
Some urls to compare results: 

Not working maps (no datapoints showing): 
https://footballforwater.akvolumen.org/visualisation/5c9a19ef-9942-4367-bae5-d70432b09dc6
https://footballforwater.akvolumen.org/visualisation/5c9b479f-f050-4dc0-a51b-b329d588fa63
https://footballforwater.akvolumen.org/visualisation/5b2a19b2-00b6-4b45-baf2-b581149a43d1
https://footballforwater.akvolumen.org/visualisation/5c6feedc-022c-42f3-a896-d909cd8d88e8

Working maps (showing data points): 
https://snv.akvolumen.org/visualisation/5cc1c6e0-9ce5-47f9-8cff-5bd386faa473
https://snv.akvolumen.org/visualisation/5c6877ed-2206-4c94-b0ca-5e4f78b652bd
https://sierraleone.akvolumen.org/visualisation/5c070be2-dcce-45b5-a87b-7d510c13805c
https://sierraleone.akvolumen.org/visualisation/5c7e4b5c-43b4-4fa3-a7f0-2d4c64034f01

**Comment by janagombitova** [comment]
Issue resolved
