### ISSUE TITLE
Update caddisfly json schema version

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2100]
# Context
https://s3-eu-west-1.amazonaws.com/akvoflow-public/caddisfly-tests-v2.json

# Problem or idea
Flow has updated to this `v2` version but lumen still is not sync

# Solution or next step
Adapt v2 to the same v1 structure so we just update the URL file and keep same functionality

**Comment by tangrammer** [comment]
These tests in v1 don't exist in v2 ... 

```
[{:name "Water - Colorimetry - Caddisfly - Fluoride (0 - 2 mg/l F)",
  :uuid "f0f3c1dd-89af-49f1-83e7-bcc31c3006cf",
  :brand "Caddisfly",
  :hasImage true,
  :results [{:id 1, :name "Fluoride", :unit "mg/l"}]}
 {:name
  "Water - Colorimetry - Caddisfly - Free Chlorine (0 - 3 mg/l Cl2)",
  :uuid "a2413119-38eb-4959-92ee-cc169fdbb0fc",
  :brand "Caddisfly",
  :hasImage true,
  :results [{:id 1, :name "Free Chlorine", :unit "mg/l"}]}
 {:name
  "Water - Colorimetry - Caddisfly - Free Chlorine (0 - 1 mg/l Cl2)",
  :uuid "c3535e72-ff77-4225-9f4a-41d3288780c6",
  :brand "Caddisfly",
  :hasImage true,
  :results [{:id 1, :name "Free Chlorine", :unit "mg/l"}]}
 {:name "Water - Colorimetry - Caddisfly - Chromium",
  :uuid "d488672f-9a4c-4aa4-82eb-8a95c40d0296",
  :brand "Caddisfly",
  :hasImage true,
  :results [{:id 1, :name "Chromium", :unit "mg/l"}]}]
```

**Comment by janagombitova** [comment]
After a quick testing check, I noticed one odd thing. If I extract also the image the url is added to all rows even though the data is only in a few. 

https://lumen.akvotest.org/dataset/5cc0772c-08de-4bc6-bdfe-f07110c9d5bf

<img width="801" alt="Screen Shot 2019-04-26 at 14 38 19" src="https://user-images.githubusercontent.com/12456965/56808185-2716c280-6831-11e9-94c4-0ff09f0d8f3f.png">

**Comment by janagombitova** [comment]
Works well. Issue with images noted as #2104
