### ISSUE TITLE
Null cause error when importing Flow dataset

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2105]
# Context

Issue reported via support: https://flowhelp.reamaze.com/admin/conversations/akvolumen-support-request-number-208690-from-eric-at-akvo-dot-org

# Problem or idea
![Screen Shot 2019-04-26 at 16.15.00.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/b0bc485f-ccc0-4067-8808-e470628bd534)

When importing one specific dataset from Flow to Lumen I get the error Null cause. The dataset is on americas.akvoflow.org -> Akvo - Mariana > Test folder 1 >Boricua >Registration 

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
![Screen Shot 2019-04-29 at 09 24 13](https://user-images.githubusercontent.com/12456965/56881458-c241af00-6a60-11e9-9c31-265e62cfbe38.png)

Here is the error I see in the console

**Comment by tangrammer** [comment]
the problem appears here 
https://api.akvotest.org/flow/orgs/americas/form_instances?survey_id=237070018&form_id=254970003&page_size=300

500 Response from flow

```
{:cached nil, :request-time 432, :repeatable? false, :protocol-version {:name HTTP, :major 1, :minor 1}, :instance americas, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x29eb9a45 org.apache.http.impl.client.InternalHttpClient@29eb9a45], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase Server Error, :headers {Access-Control-Allow-Headers Accept,Accept-Encoding,Accept-Language,Authorization,Connection,DNT,Host,Origin,Referer,User-Agent, Server openresty, Via 1.1 google, Content-Type text/html; charset=ISO-8859-1, Access-Control-Allow-Origin *, Content-Length 21, Alt-Svc clear, Connection close, Access-Control-Allow-Methods GET, OPTIONS, Date Mon, 29 Apr 2019 08:14:08 GMT, Access-Control-Allow-Credentials true}, :orig-content-encoding nil, :status 500, :length 21, :body Internal Server Error, :trace-redirects []}
```

**Comment by tangrammer** [comment]
@janagombitova maybe it's time to close this issue

**Comment by janagombitova** [comment]
ok.
