### ISSUE TITLE
Explore using 'Extract multiple values' for Flow geoshape questions

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2125]
# Context
Why do we add this issue?

# Problem or idea
**What is the status quo?**

How we handle Flow **geoshape questions** data in Lumen is not optimal at the moment.

Flow geoshape data is 'special' as one answer holds more values. In the Flow data export, all the geoshape data is shown in the question column as a JSON string. It holds the `properties` that represent the length, point count and area, and the `type` of geoshape (points, line, polygon) and the `coordinates`. 

Here is an example of how the sting looks like: 

```
{
    "features": [
        {
            "type": "Feature",
            "properties": {
                "length": "21162.78",
                "pointCount": "3",
                "area": "15505886.51"
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [
                            21.8968471,
                            48.758165
                        ],
                        [
                            21.86427623033524,
                            48.72222222749574
                        ],
                        [
                            21.92736010998488,
                            48.67512625804887
                        ],
                        [
                            21.8968471,
                            48.758165
                        ]
                    ]
                ]
            }
        }
    ],
    "type": "FeatureCollection"
}
```

When currently in Lumen, the data does not show. So Salim not only has no way to use geoshape data in Lumen maps (another issue) but he cannot analyse the data under `properties` as length, pointCount or area. 

![Screen Shot 2019-05-06 at 12 17 57](https://user-images.githubusercontent.com/12456965/57219647-08ff4e00-6ff9-11e9-9444-407006111876.png)
*Example: UAT1 > 1.9.20 > Not monitored > all questions*

# Solution or next step
*How could we solve it?*

The idea is to see if we can use the same approach to geoshape data as we have done with  Caddisfly. A while back we implemented the new transformation action: Extract multiple values that currently works for Caddisfly questions. Caddisfly data is unique because one answer usually holds more than one properly (a value and an image or more than one values). Not all values are always needed in analysis so the transformation gives Salim the chance to extract only what he needs. 

See the original issue here: https://github.com/akvo/akvo-lumen/issues/1619

Since its implementation, we have seen a significant decrease in the use of derived columns with javascript, support requestion on how to handle Caddisfly data and an increase in the use of this transformation prooving the value of the change. 

*If this change is successful, what might we observe?*
Geoshapes are used mostly in agriculture projects and thus not widely used across our partners yet but growing. This change can help us support the growth towards agri projects and make not only demoing how to handle agri project data, but give us a stronger market position with this still unique functionality. 

If we handle this data type in a simpler way we should see a decrease in the Flow geoshape data exports, as Salim will rather analyse the data in Lumen because of the benefit of simple visualisation creating and direct connection to Flow (new data streaming can be handled almost right away). 

Benefits of this change will, however, be dependent on making it possible to use Flow geoshape data on Lumen maps. https://github.com/akvo/akvo-lumen/issues/1355

**Comment by tangrammer** [comment]
<img width="789" alt="Screen Shot 2019-05-15 at 17 35 10" src="https://user-images.githubusercontent.com/731829/57788824-0c50b300-7738-11e9-9f13-437d7ef21f6d.png">

First version: 

- [x] storing geoshapes
- [x] visualising geoshapes in lumen dataset view

**Comment by tangrammer** [comment]
@kardan  @janagombitova a couple of things to think about:
I'm not keen on the couple  Postgres ❤️ postgis  
but here are my impressions:
- if we store the polygon data of a geoshape in a [postgres geometry column](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/postgres.clj#L70) it seems that we can't store the `features` described above in this issue. (thus this `geometry` type is designed to be functional/performant in geom ops )
- so to store these json features, we should have a new hidden text-column associated to the geoshape-column ... This design would follow a very different pattern of store a flow thing into 2 places at the same time (so I imagine at this stage that it should be a fair amount of work to have a stable version )

**Comment by kardan** [comment]
Initial thoughts on the "FeatureCollection" (would be interesting to know if there is other types):

I think we need to store this as two columns (shape and metadata). The only alternative as I see it would be to create an extraction transformation where you can extract one thing, either shape or metadata. But adding a transformation step and letting the user import something "unusable" is not really wanted unless it has benefits for us moving to a solution. 

On making a hidden column, I could also imagine that we just create two visible columns, one geometry and one json with the metadata values. If you want to use a specific value like "area" the user would just extract the value to it's own column. That way we can use the same "simple" column pickers in the viz editor. Storing these values in a hidden json column and expecting the keys to be accessible as columns by the user sounds like a troublesome path.

**Comment by kardan** [comment]
& if it's always these 3 metadata fields, maybe create one column for each directly?

**Comment by janagombitova** [comment]
The end goal is to be able to use geoshapes on the map and to be able to analyse the metadata. it is important to highlight, I am not sure I did in the initial description, that a geoshape question in Flow can give a polygon, or a line or points. Considering the metadata are always three fields I like the idea of just extracting the data directly at import. So one Flow geoshape question would be 4 columns. We should add something to the name to show that these columns are from the shape.

**Comment by tangrammer** [comment]
@kardan @janagombitova thanks for the feedback! :)

**Comment by janagombitova** [comment]
Pushed to production today!
