### ISSUE TITLE
Support Flow repeated question groups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2127]
# Context
This issue https://github.com/akvo/akvo-lumen/issues/529 has given a start to this topic but only a little bit has been touched upon in the issue as it derailed to also redesigning the data grid. 

## Why do we add this issue?
We are working on connecting Flow and Lumen and in this process, we have decided that we need to first handle the current gaps between Flow and Lumen. Lumen needs to be able to handle all Flow data types and data structures. Initially, Lumen was built not knowing too much about Flow, but with the change to move towards one product, Lumen needs to handle all 'special' Flow data types in a simple and user-friendly way. 

# Problem or idea

## What are repeated question groups? 

Repeated question groups are our alternative to table questions. Often a group of questions needs to be asked multiple times when filling in the questionnaire. For example, if you want to ask the same questions to each member of a household, you will add the questions to one question group and click on the repeat option. This way you do not need to pre-define in the survey the questions for each member of the household, as that is an impossible task. 

Repeated question groups are, simply said, a group of questions (of any kind) that the respondent can fill in more than once. 

## Repeated question group data 
Using repeated question groups results in one submission holding more than one answer to one or more questions. The number of repetitions can differ per submission. 

When handling repeated question group data in a table with Flow exports we learned a lot (see this issue: https://github.com/akvo/akvo-product-design/issues/227) on what way of presenting data works and what does not work for our users: 

### 1) All data in one sheet with the repetitions in separate rows
![Screen Shot 2019-05-13 at 11 05 22](https://user-images.githubusercontent.com/12456965/57609378-09ef2d00-756f-11e9-8aee-7ea54c3c1478.png)

This data structure, where all data was in one sheet and the repetitions were in separate rows has proven not useful to our users. They complained about the empty cells, it was hard to see which column is repeated, complexity in having to analyse data that was not repeated this way. Thus we changed the export options in Flow to explore other solutions. 

This structure is still supported in Flow's Data analysis exports as we aimed to keep all the data in one sheet. However, we still receive requests on changing this structure to either have separate sheets or columns. 

### 2) Repeated group data split into a separate sheet with data point metadata copied over
![Screen Shot 2019-05-13 at 11 07 21](https://user-images.githubusercontent.com/12456965/57609514-53d81300-756f-11e9-8979-1dd74c3952e3.png)

This way of presenting data in the table has proven to work better for our users. They have one data sheet holding data for all the questions that are not repeated. This sheet ensures one row = one submission. The following sheet holds one repeated group. (If s survey has more repeated groups, it will have a sheet for each group). The repeated group sheet, the data is shown as a table with repetitions in separate rows. This way Salim can analyse the data column by column, aggregate variables and analyse it as any other data table what is how he is used to without having to take any other manual steps. 

This structure is supported today in Flow's Data cleaning exports.

### 3) Repeated group data added into extra columns

When researching what structure is the best to work with we came across the option to show the repetitions in columns (Question1 - 1 | Question2 - 1 | Question3 - 1 | Q1 - 2 | Q3 - 2 | Q3 - 2 | … OR Question1 - 1 | Question1 - 2 | Question2 - 1 |...). Positive thing is that this is a common data analysis format for handling such data and it respects the rule where one row = one submission. On the other hand with large datasets, this approach adds more columns to the dataset making it not easy to analyse. Plus not having the data in rows makes aggregation harder. 

### Conclusion 
It is hard to find a good structure for RQG data, but the multiple sheet/table approach has proved to work the best.

Our users are used to working with data tables. They view the data in columns to check for outliers, frequencies, etc and then in rows to understand the submission. 

But they are not advanced in analysis to handle more complex table structures. The data structure for repeated groups, most appreciated so far, is in separate sheets. In separate columns would be choice n2 to keep the rule one row = one submission, but our users might not know how to analyse and visualise this data structure as the variables are split across columns. 

## What is the current status quo? 

When importing data directly from Flow currently, Lumen does not understand the concept of repeated question groups and if a question group is repeatedly answered, in Lumen only the 1st repetition is imported. So to handle this situation, partners export the Flow dataset and import the data to Lumen as a .csv file losing the magic of the direct connection to Flow. 

## If this change is successful what might we observe? 
- Stroger market position as an easy to use data platform as we found a simple way to handle a complex Flow data structure
- Decrease in dataset import via .csv file uploads 
- Increase in using Lumen 

# Solution or next step
## How could we solve it?

We need to figure out how to support Flow's RQG data in Lumen's data grid. I know we still doubt the value of the grid especially when having large datasets (rows and columns), but users are familiar with this structure. They might not spend too much time on the grid and go right to visualisations, but the grid is still a valuable way of representing data. If we want to provide an alternative, that should be handled in a separate issue and at a later stage in time.

**Comment by Kiarii** [comment]
for the first iteration, we could go by what we have in flow exports, i.e. splitting RQG, this would however require us to split all question groups for an intuitive UX.. on the analysis side, the requirement is for repeat aggregation incl. Number of repeats, average, minimum, maximum, and so on. There is also a need to link data across forms e.g. for farmers, layering or filtering e.g. analysing income by gender.. 
My proposal is that we link up and storymap this together as there are a number of details we would need to agree on..

**Comment by iperdomo** [comment]
We can consider a Repeatable Question Group (RQG) a _new dataset_ with a parent/child relationship to the form instance.

When we export data to Excel using different sheets, the user needs to use the `Identifier` column to _manually_ match the repetitions to a particular form instance. (NOTE: I'm not suggesting this is wrong).

There are other ways to represent parent/child relationships, e.g MS Access follow this pattern:
![7122](https://user-images.githubusercontent.com/178474/80934900-8c997980-8dca-11ea-8e0e-ba2b5e476976.jpg)

Source: https://social.microsoft.com/Forums/getfile/7122/

### Random notes

* In MS Access the user is able to edit the child rows directly, e.g. modifying a value or adding an entirely new row. In Lumen the user modifies the data by applying transformations, some of them are defined as actions in the header of the column, so it will be tricky to place them in the header of expanded table
* Our datasets are flat 2 dimensional arrays. A RQG adds a new dimension that **most** be aggregated into a single value in the main dataset.
  * Example: A RQG can be contain something like `name`, `age`, `literacy`. Because we don't know how many repetitions per instance do we have, the value we want/need in the main dataset an _aggregation_ of a variable: `AVG(age)`,`MIN(age)`, `MAX(age)`, `COUNT('can-read')/COUNT(*)` or a _derived score_.

**Comment by janagombitova** [comment]
Today we spoke about how to implement RQGs in Lumen. Here are my brief notes: 
* For background: A dataset in Lumen is defined and designed as a tidy dataset http://vita.had.co.nz/papers/tidy-data.pdf, where a column is a variable and a row is an observation and a dataset should as much as possible not have replicating data - https://en.wikipedia.org/wiki/Third_normal_form
* If we look at structure right now a form = dataset but forms are organised by question groups out of which some question groups can be repeated 
* RQGs are in principle another separate table - more natural, more conform with the database rules that we want to follow
* But if we split off (as a separate dataset, or separate tab in one dataset) the repeated groups, should we not do the same for all groups from the user point of view? 
* Start with **MVP** 
   * After importing a dataset that holds repeated group(s) we create a separate dataset for the repeated group(s) so Salim ends up with 2 or more datasets 
   * The dataset name is shared in the UI, so the "main dataset" has the user-defined name and the repeated group dataset is `user-defined dataset name - Group 3 - group name` for example
   * The MVP will be behind a feature flag, we can test it with a few users (and possibly confuse only a few) and learn as quickly as possible 
* **Ideal state** is where one form = one dataset from the user's point of view
   * This dataset is then split by each group
   * How does this affect transformations, merging, creating visuals?
   * Is this something users can and will work with? 
   * While working on the MVP we should test with users the ideal state

**Comment by tangrammer** [comment]
Add feature flag issue https://github.com/akvo/akvo-lumen/issues/2676

**Comment by janagombitova** [comment]
Today we spoke again about how we can implement the minimum that is useful and can be tested in a week and had Geert to share his experiences with working with RQGs. All notes (on previous user research as well) can be found here: https://drive.google.com/drive/u/1/folders/1KBFaAwCWE-diYakTTWfNEWzCBGFy4tVq

Some of the main insights that invalidate our initial ideas are: 
* data is analysed across the dataset - so within the RQG but also in correlation with data outside of the group 
* the Flow data cleaning export structure is fine 
* ordinary question groups act as a way to see where I am but if I had the split off (in one tab each group) I would not want that. They have one shared structure so it is not needed, it would be confusing and it would create more actions for me to undertake 
* the end product is a visualisation where I want to be able to work with data from the main sheet and a repeat group (the dataset is today a middle step that I use to prepare my data to visualise) 

Based on Geert's input and the notes from talks with Ilyasse and Molo, we decided to start: 
* We’re going to support Repeteable Question Groups by storing a vector of values inside a cell
* By default we support JavaScript transformations on those columns (clunky but works)
* We’re going to support aggregating one variable (column) at visualization definition 

More here: https://gist.github.com/iperdomo/059db992435d40d8cecd285fc64b6fb9

**Comment by tangrammer** [comment]
any preference for naming this new property in the visualisation spec?

**Comment by muloem** [comment]
> * the end product is a visualisation where I want to be able to work with data from the main sheet and a repeat group (the dataset is today a middle step that I use to prepare my data to visualise)

When relating data from a column in a non-RQG and a column in a RQG, we will support aggregating values coming from the RQG column such that the resulting visualization is based on a dataset in the third normal form. 

For example in the table below lets say the Family name is in a non-RQG and we want to visualize that against an aggregated form of the age which is part of a RQG.

| Family Name | Members | Age | 
|--------------|-----------|-----|
|Kintu               | Mother      | 66  | 
|               | Father      | 58  | 
| | Daughter 1 |27|
| Kamau | Mother | 63|
|               | Father      | 68  | 
| | Son |33|

We provide the user the possibility to aggregate the age column such that the underlying visualization is based on the following table

| Family Name | Average Age | 
|--------------|--------|
|Kintu               | AVG(66, 58, 27)|
| Kamau           | AVG(63, 68, 33)|

### How will this affect the different visualization types?

In general (just as is the case with current visualizations based on aggregations) we can only support aggregation of columns with numeric data.

#### Bar charts
Bar charts visualize discrete values against measured values. In this case, the measured values would be the aggregated values and the discrete value, would be the one coming from the non-RQG.  So for example from the table above, we would plot family name as a discrete value and the average age in the family as the measured value. 

#### Line charts

#### Pie chart and donut chart

**Comment by janagombitova** [comment]
> In general (just as is the case with current visualizations based on aggregations) we can only support aggregation of columns with numeric data.

I agree. But I just want to make sure we will also support the simple cases when I want to just analyse the RQG data? Like the example of crop types. Crop type is a text value in an RQG column and I want to plot the crop type as the bucket column in the bar chart with the aggregation count. In this case, the charts behave the same way as in any other dataset, right?

**Comment by janagombitova** [comment]
@muloem  and @Kiarii  did you guys also l look at the affects of our MVP approach in visualizations if i was to work only with data from the RQG?

For example if my RQG is about crops the farmer produces, I want to visualize all the different crops (bar chart where the bucket column holds all the different text values - crops, metric column is not defined, aggregation remains on count, or this could be a bubble or polar chart too)

**Comment by muloem** [comment]
@janagombitova yes this is also part of the considerations but we were focused on the first issue which is working with data between non-RQG and RQG. But the document will be updated with this info as well 👍

**Comment by muloem** [comment]
I believe we talked about it but I think we should definitely consider the possibility of adding "Aggretate Data" as a transformation that only applies to numeric data in RQG.  This transformation would create a new column that contains the aggregated RQG data.  This new column could then be used to perform visualizations that require further aggregations. e.g. an aggregated "Total Household Income" can then be used to plot income distribution in farming households.  @janagombitova @Kiarii what do you think? if its something to proceed with then we can create a separate issue for it

**Comment by tangrammer** [comment]
@muloem I believe Geert didn't mention to need the aggregated values as new columns but to have the option in the viz charts to aggregate the RQ

**Comment by Kiarii** [comment]
I was talking to Carmen today about how you approach a dataset, sometimes you come to a dataset with a task in mind, sometimes you want to find interesting patterns by being able to explore the data - i.e. in this case for instance being able to aggregate RQG data on the fly (during analysis) than having to create a separate col aggregations in order to explore the data.. so imo, there is a bit of both

**Comment by janagombitova** [comment]
We need to not forget that Geert was just one source of information to get us started. We should keep the implementation for this week to what we agreed on, push the change out to a few users to test and then move forward based on their feedback. We might see there is a need for an `Aggregate data transformation` or to `extract the RQG to a separate data set` or something else. Let's push what we have to users and learn from them.

**Comment by janagombitova** [comment]
Today we agreed that the MVP for this Friday is: 
* get all the data in Lumen, thus all the repetitions in Lumen in one cell 
* users can then use the Derive column transformations to make new columns with something they can use in visualisations from the repeated columns. 
* we will create examples for the Derive column cookbook to use. 

We will decide on the next steps based on the input we get from the research after the MVP is out.

**Comment by janagombitova** [comment]
Here is the video from today’s stand up on the new design for the dataset in Lumen to support RQGs: https://peak.akvo.org/flumen-supporting-rqgs-designs-27-may-2020/

**Comment by janagombitova** [comment]
Today we discussed the next steps for RQGs. The recording can be found here: 



## We agreed to handle now:
* follow the designs: https://projects.invisionapp.com/share/JHXDE589BYT#/screens/417456348_0-0_DG_-_Metadata. 
* implement the sidebar group navigation (without search and per question navigation) #2705 
* once selecting a RQG show the data as a grid, columns and rows "unpacked" 
* all changes will go under the current feature flag (per instance enabled)
* we will enable the feature flag for a few instances to control the testing and releasing to users in an informed way

## To research/handle later
* How to handle transformation columns? Should new columns transformed from RQG data show in the RQG view and from all other groups in a "shared" `Transformations` group view, or in each separate group based on the column they come from? 
* Visualising and transforming data based only on RQG should work with the new view, but what should Lumen do: 
   * if I select a column from the RQG and a different group in my visualisation? or should we not allow that and handle analysing this combination of data by having users bring in other group data in the RQG as another column? 
   * if I select a RQG in a merge transformation?

**Comment by tangrammer** [comment]
@janagombitova  Could we assert that question type inside a RQG could be of any possible Flow question type?

**Comment by janagombitova** [comment]
@tangrammer yes. All question types can be part of a RQG. So in Lumen words, all data types - text, number, geopoint, multiple. Anything and everything.

**Comment by tangrammer** [comment]
Could we have a flow form with a RQG that contains one column of each flow type? I think it will be very useful in dev/test phase

**Comment by tangrammer** [comment]
some info around unpacking RQG text column https://gist.github.com/tangrammer/0852f53a846c254a4ccbcf41e151b4b4

**Comment by iperdomo** [comment]
Follow up of this comment https://github.com/akvo/akvo-lumen/issues/2127#issuecomment-640659912

* Having all the a repeated question group data packed in a single cell was a nice *experiment* but it's conceptually broken
  * This change is behind a feature flag and only enabled in one instance
  * We have shown the solution to some users and the feedback was not very positive. The most confusing part was how to know what are my available "columns"
* We all agree that a RQG is another "dimension", a dataset inside another dataset, so we should treat it as such
* There is complexity in unpacking/packing, transformations, question types that are avoided by treating the RQG as a dataset
*  The user should not be aware of this internal structure, for the user is another tab/section *inside* the dataset

## Moving forward
* Client side changes will happen behind a feature flag. Moving the column headers to the side-bar (@tangrammer @marvinkome)
* A plan on how to deal with the internal structure of RQG as a dataset (@iperdomo @tangrammer)

**Comment by valllllll2000** [comment]
For testing you can use: in uat1 `Lumen Testing/Lumen RQG Testing / Repeated All Questions`

**Comment by tangrammer** [comment]
Agreeing with @marvinkome to set up a new backend entrypoint to retrieve dataset columns and rows based by groupId
`GET /api/datasets/<dataset_UUID>/group/<group_UUID>` 

example response 

```json
{
  "updated": 1591871348434,
  "columns": [
    {
      "groupId": null,
      "key": false,
      "groupName": null,
      "sort": null,
      "direction": null,
      "metadata": null,
      "title": "daniel",
      "type": "text",
      "multipleType": null,
      "hidden": false,
      "multipleId": null,
      "columnName": "c1"
    },
    {
      "groupId": null,
      "key": false,
      "groupName": null,
      "sort": null,
      "direction": null,
      "metadata": null,
      "title": "sweden",
      "type": "text",
      "multipleType": null,
      "hidden": false,
      "multipleId": null,
      "columnName": "c2"
    }
  ],
  "created": 1591871348391,
  "modified": 1591889136678,
  "rows": [
    [
      "jonas",
      "finland"
    ]
  ],
  "groupId": "712873781237823",
  "datasetId": "5ee20774-fee7-4c0e-91c3-3cdab5e53410"
}
```

**Comment by iperdomo** [comment]
If you're getting a particular group, why the column has a `groupId`? is not  *implicit* in the top level object?
```js
{
  "updated": 1591871348434,
  "columns": [
    {
      "groupId": null,    // <<--- this one
      "key": false,
      "groupName": null,
      "sort": null,
      "direction": null,
      "metadata": null,
      "title": "daniel",
      "type": "text",
      "multipleType": null,
      "hidden": false,
      "multipleId": null,
      "columnName": "c1"
    },
  // rest of colums
  "groupId": "712873781237823",
  "datasetId": "5ee20774-fee7-4c0e-91c3-3cdab5e53410"
}
```

**Comment by iperdomo** [comment]
Current ideas on how to deal with RQG as Dataset:

https://gist.github.com/iperdomo/06725216071d995e3b4ad2c63c98571b#rqg-as-dataset

**Comment by tangrammer** [comment]
@iperdomo in relation to https://github.com/akvo/akvo-lumen/issues/2127#issuecomment-643921195 
I'd choose option 1 thus requires less work and doesn't "directly relate" to other boundaries like visualizations and transformations

"directly relate" means here that IMO, the SQL work to do in vizs and txs is going to be more or less the same if that "table" is generated with any of your proposal approaches

**Comment by marvinkome** [comment]
https://github.com/akvo/akvo-lumen/issues/2127#issuecomment-643191877 based on this how would we get the data for the metadata column group? It's groupId` is `null`

**Comment by iperdomo** [comment]
@marvinkome has a good point on the _Metadata_ group. This is an _artificial question group_ that contains the common columns of every dataset. We can use `/dataset/<id>/group/metadata`

**Comment by tangrammer** [comment]
yep we need to define metadata and transformations group calls https://github.com/akvo/akvo-lumen/pull/2716#issue-434386661

**Comment by marvinkome** [comment]
On the client-side, we've decided to change the structure to be groups based

```{
  "datasets": {
    "wioib02g-sdboigbw": {
      "groups": {
          "metadata": {
            "groupId": "902gjgwn",
            "groupName": "Metadata",
            "rows": [],
            "columns": []
          },
          "c409420g": {
            "groupId": "c409420g",
            "groupName": "Question Group",
            "rows": [],
            "columns": []
          }
        }
    }
  }
```

Where the metadata and transformations will also be groups

**Comment by tangrammer** [comment]
added backend API support to work with groups https://github.com/akvo/akvo-lumen/pull/2716

not fully ready but usable in development so @marvinkome could keep working on client side :)

**Comment by iperdomo** [comment]
@tangrammer my findings attempting to use multiple `IN` clauses

https://gist.github.com/iperdomo/a988097ea20d23da25d33b21dec72433

It *works* but it means that we're going to read MxN times the same kind (`QuestionAnswerStore`).

**Comment by iperdomo** [comment]
After some back and forth, together we realized that we can adhere to the current import process implementation by using _namespaced columns_ (@tangrammer's idea)

We have a `DataseImporter` protocol, as example:

```clojure
  (reify
    Closeable
    (close [this])

    DatasetImporter
    (columns [this]
      [{:id :a :type \"text\" :title \"A\"}
       {:id :b :type \"number\" :title \"B\"}
       {:id :c :type \"date\" :title \"C\"}])
    (records [this]
      [{:a \"foo\"
        :b 42
        :c (Instant/now)}
       {:a \"bar\"
        :b 3.14
        :c (Instant/now)}
```
The contract is to have 2 methods `columns` and  `records`. The idea separate the return values for this methods using the group id as a _namespace_.

Example with namespaced columns

```clojure
(reify
    Closeable
    (close [this])

    DatasetImporter
    (columns [this]
      [{:id :g123/a :type \"text\" :title \"A\"}
       {:id :g456/a :type \"number\" :title \"B\"}
       {:id :g123/c :type \"date\" :title \"C\"}])
    (records [this]
      [{:g123/a \"foo\"
        :g456/b 42
        :g123/c (Instant/now)}
       {:g123/a \"bar\"
        :g456/a 3.14
        :g123/c (Instant/now)}
```
By using namespaced column ids we avoid collisions and we have now a way to know how many dataset tables do we need to create. In the above example, one per different group.

The idea is to evolve trying to concentrate the changes in fewer places as possible. 

@tangrammer the current idea is to use this setup just in the case we find at least one RQG, right? The contract with the protocol doesn't restrict to add *more* data to the column definition.

**Comment by tangrammer** [comment]
> the current idea is to use this setup just in the case we find at least one RQG, right?
IMO we could use this approach always, in case we don't have RQG we'll have only one namespace for all

BTW: to keep in mind ... perhaps we will need to evolve a bit the way we store/use column definition too. in import/update process seems to be valid the column namespace approach, but in db or transformation references we should need the group name as this extra identifier ... and here we need to know wich are the json options to serialise the fully qualified namespace (thinking very aloud :) )

**Comment by tangrammer** [comment]
Agreed with @marvinkome on how to proceed with the work to be done at client side
instead of trying to have a "clean" dataset UI view design that covers both views (with/without feature flag) with lot of conditional logic inside and expecting that this feature-flag-ui-dataset-view is not going to live lot of time in production, we decided to duplicate UI components with the hope that once finished the work we just need to remove the original dataset view logic.  

The drawback is that if we need to fix a prod issue during the feature-flag life we'll have to fix it twice

**Comment by iperdomo** [comment]
Notes on a pairing design session with @tangrammer 

Let's zoom out and describe some _domain_ concepts, based on [Tidy Data](https://vita.had.co.nz/papers/tidy-data.pdf)
> A dataset is a collection of values, usually either numbers (if quantitative) or strings (if
qualitative). Values are organised in two ways. Every value belongs to a **variable** and an
**observation**.


So far in Lumen we had a mapping one-to-one between a dataset and a _data table_ holding the values for variables (columns) and observations (rows).

Internally we have some more structure (tables holding metadata) to support atomic updates, e.g. we want to support serving a visualization while the update/transformation process is happening. For that, we introduced the concept of a `dataset_version`. We create a new `dataset_version` after a successful import/transformation.

![lumen-db-structure](https://user-images.githubusercontent.com/178474/84925952-f8117f00-b0ca-11ea-8884-9e67e021b4fb.png)

* `datastet` has the name and other top level attributes
* `dataset_version` has the column definitons and transformations, and logical references to physical tables via `table_name` and `imported_table_name` fields

When serving data to the client we join the metadata tables for the structure and the `ds_<uuid>` for the data.

This model has served well until now that we want to support datasets with data at *multiple levels*.

### RQG is a different *'observational unit'*

> Datasets often involve values collected at multiple levels, on different types of observational
units. During tidying, each type of observational unit should be stored in its own table.

We can consider repeatable question groups (RQG) a collection of values at different *observational unit* for the same dataset. Logically for the user is **one** dataset, but internally we need to store the data in **many** tables.

![data-multiple-levels](https://user-images.githubusercontent.com/178474/84927059-97834180-b0cc-11ea-8fad-e9c12f77f642.png)

We want to introduce this changes gradually and *evolve* with the current data model.

As of now, one `dataset` had only **one** `dataset_version` (with a `table_name` referencing the *data table*). With the new model one `dataset` will have **one or more** `dataset_version` referencing the *main* group (non-repeatable) and `n` other tables (where `n` is the number of RQG).

![many-dataset-version](https://user-images.githubusercontent.com/178474/84928754-33ae4800-b0cf-11ea-8bf5-c3287062c4dd.png)

This idea was described as one of the options in a previous document:
https://gist.github.com/iperdomo/06725216071d995e3b4ad2c63c98571b#one-dataset-multiple-dataset_version

### Implementation details

We want to start introducing small changes, gradually moving towards the new model:
* We want to add metadata about the version of the `DatasetImporter` used. This will be added to the `spec` of the `data_source`
* Right now we have a unique constraint on `(dataset_id, version)` [code](https://github.com/akvo/akvo-lumen/blob/promote-20200616-143330/backend/resources/akvo/lumen/migrations/tenants/005-dataset-version.up.sql#L14). In the new model we'll have more than one combination `dataset_id,version` as we may have more than one table. We need to change the unique constraint to `(dataset_id, version, columns)` or `(dataset_id, version, table_name)`.
* We need to split the column definition by question groups. The *main* non-repeatable and the repeatables. Each `dataset_version` has its `columns` definition.
* To know with `dataset_version` belongs to which group, we can query the `columns` JSON blob.
  * To speed things up, we may want to add an index on the expression used for the query

**Comment by janagombitova** [comment]
# Analysing data from a RQG data group

Today we discussed the research Jana did on RQGs and how we can support analysing them so users still can easily have an overview of the data, what they are doing and what is happening without too much cognitive effort. All notes here: https://docs.google.com/document/d/1jfowv5S3_-3vV4zH6zN5JkoHLQrJGYxzpUFsAKoaeWU/edit#

* If we allow to bring in non-RQG data into the RQG data group we end up with duplicated data and that is not a best practice, plus it can be hard for the user to keep track of why one column (with location for example) is in the first data group and also in the repeated data group 
* If we bring a RQG column into the non-RQG data group, user has to aggregate the data and thus creating a new column - aggregated - so the data is not copied over, it is aggregated and “something else”
* Ideally on visualisation level Lumen tells the user - now you are visualising a RQG data column with a non-RQG, how do you want to aggregate data the RQG data first
* We need to start somewhere and ideally small
* We start on visualisation level, but here it can happen that the user wants to do something, and needs to transform the RQG data first but cannot as we did not handle the transformations
* So we start on handling the transformations - how they should behave (each and every one of them) with RQGs - Jana and Kiarii to define
* To ensure users do not make visualisations that do not work, we can start by not allowing to visualise data outside of the RQG - you cannot select a column from a different data group if you selected a column from a RQG data group. And then once we start looking at visualisations, we start enabling more based on the need.

**Comment by janagombitova** [comment]
I realised we have not updated this issue with the decisions we made. From the user point of view we will support repeat question group data: 
* by breaking down the dataset into data groups, but keeping all groups in the dataset - so Salim works with one dataset that is organised into data groups 
* RQG data group will have more rows than other data groups 
* RQG data group will be indicated by an icon
* Lumen will maintain all group relations and in the UI we will not repeat columns as data point ID or instance ID 
* derived columns will for now go into the `transformations` data group, but derived columns from RQG data will remain in that group 
* Lumen will handle visualising data and maintaining the relations (if visualisation is using a column from a non-RQG and a RQG)
