### ISSUE TITLE
Allow to select more than one NUM column on Y-axis for bar charts

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2131]
# Context
## Why do we add this issue? 
Bar charts are the most used visualisations types in Lumen. And their use is growing further than the standard of analysing two variables, but to more variables in the visualisation. We add this issue to support cases where current stacking (splitting) bars do not work because of the structure of the dataset. 

# Problem or idea

## What is the current status quo
Currently, you can analyse three variables in one bar chart using stacking. This works really well if you select as the 3rd variable a text column. The buckets get split by the unique values. It is magical. 

![Screen Shot 2019-05-16 at 14 30 01 (2)](https://user-images.githubusercontent.com/12456965/57853864-21d0e600-77e7-11e9-9360-a6c2dfc406a2.png)

But for number columns, we treat the numbers in the same way as text and split or stack the bars by the unique values. This does not work. 

![Screen Shot 2019-05-16 at 14 44 47](https://user-images.githubusercontent.com/12456965/57854728-37dfa600-77e9-11e9-95dd-71a6954390cc.png)

## Example A
If we want to make a graph and split between the number of men and women by activity, three separate columns, you need to create two graphs. One graph showing the number of women per activity and the second one showing the number of men per activity. 

Ideally, you want the graph to show men and women as separate bars (or stacked) per activity in one bar chart. 

![Screen Shot 2019-05-16 at 14 28 27](https://user-images.githubusercontent.com/12456965/57854051-8ee47b80-77e7-11e9-9994-764285f74559.png)

Example: https://docs.google.com/spreadsheets/d/1kQyNeHw9WcI79-3ZJWoS_W3wuWWfRUKok8cHX5K_t9s/edit#gid=0

## Example B
With this dataset I track user adoption of the new data transformations we create as the assumption is that the use of derived column will decrease and the use of new transformations will increase. Each transformation is one column and the rows are per month. See here: https://akvointernal.akvolumen.org/dataset/5d14c8d1-89c9-443e-92c4-661d095c9369

Today I need to create a separate visualisation per transformation. Ideally, I want to be able to see a bar chart with the usage number of derived columns and category column next to each other per month. 

## If this change is successful what might we observe? 
- even more use of bar charts 
- but actually, less bar chart as what now requires two charts can be shown in one 

# Solution or next step
## How could we solve it?
Could we handle number columns differently in stacking to support this case to be able to end up with something like this? 

![Screen Shot 2019-05-16 at 14 42 10](https://user-images.githubusercontent.com/12456965/57854553-cf90c480-77e8-11e9-86b5-52b1a11486fa.png)

## How will this benefit the users? 
They will have less work as they do not need to create more charts (picture you have over 10 indicators where you compare men and women all the time). 

## How will it benefit Akvo? 
The first impression Lumen makes is positive, it is seen as a simple to use product. If we get this right we can further simplify a more complex case. What can result in more advanced users choosing to work with Lumen.

**Comment by Kiarii** [comment]
In response to **Case A**, it feels that the NUM data type can only be meaningfully used as a sub-bucketing option if it contains a few unique values.. else the user would expect options to define or limit the values.
Furthermore, case A would primarily require that the Gender data exist in the same col - since sub-bucketing only refers to the a single col. Secondarily, it would be possible to reference a group of columns when sub-bucketing - which is exactly the challenge we need to look at with MOQs and RQGs - it would however be best if we can storymap this inorder to also handle these (multiple option question and repeat question group data) and figure out the best way forward

**Comment by Kiarii** [comment]
**Case B** - I actually got an error on attempting to load the dataset with the link "Failed to fetch dataset" - but if I understand its context correctly, it feels very much like Case A; the need to split bars; figuring out A thus will solve B

**Comment by janagombitova** [comment]
@Kiarii Indeed, A and B are not two separate cases, just separate examples of one situation. I do not really follow your statement 

> In response to Case A, it feels that the NUM data type can only be meaningfully used as a sub-bucketing option if it contains a few unique values.. else the user would expect options to define or limit the values.

I created an example based on IUCN data here https://docs.google.com/spreadsheets/d/1kQyNeHw9WcI79-3ZJWoS_W3wuWWfRUKok8cHX5K_t9s/edit#gid=0 with how Google sheets handle this type of situation. This example is also the use request that started this issue.

**Comment by Kiarii** [comment]
@janagombitova 
> with MOQs there are more values in one cell
this is the case as long as the data hasn't been 'transformed'; we have been talking about splitting the data so it is viewable on the grid - thus my thinking..

> I created an example based on IUCN data
I think your example highlights what we need to figure out. 
I am of course getting a bit lost figuring out how the aggregation ought to work; shd it be applicable to both axis, does it belong in the X or Y? Atm in Lumen we have it in the Y, but bucketing & sub-bucketing on the X where it would appear we ought to have another aggregation (my thinking hurts :)

**Comment by Kiarii** [comment]
the proposal also implies an un-bundling of Sub-bucket options from the **Advanced** options of the X-axis, the aim being to dedicate the "Advanced" section to chart labeling and legend options for both X and Y axes. For Datasets "Advanced" should be relabeled "Filters" to remove what would break the intention.

**Comment by janagombitova** [comment]
After discussing the issue today with @Kiarii, @kardan and @tangrammer, looking at the case, the research and how Salim would go about creating such charts we realised the following: 

## Case 
Salim wants to create a bar chart where he wants to see the number of men and women per activity. If he wanted to see the number of men per activity he would define the x-axis to be based on activity (TEXT column) and then the y-axis-metric would be based on men (NUM). He would select how he wants to men data to be handled, aggregated (Does he want to see the SUM of men MEAN thus the average of men per activity). But because he also wants to see the number of women per activity, he would add another column to the y-axis. Then the men data and the women data are handled by the same aggregation method per activity, resulting in him seeing 2 bars (men and women) per activity. 

### Our misunderstanding
We initially thought that the case should be handled in what we call `Sub-buckets` in Lumen. But that is a different thing as you do not define the aggregation method on the x-axis but on the y-axis. 

## Changes to Lumen
Thus we want to: 
* Allow Salim to select more than one **NUM** column for the y-axis
* Limit current Lumen sub-bucketing to only **TEXT** columns (separate issue) 
* If Salim selects more than one y-axis column, do not allow him to define a sub-bucket on the x-axis to keep things simple for the start
* See how to reorganise items in the visualisation editor to ensure how Settings that apply on the chart view are shown in one space, and settings that apply on the x-axis and y-axis are shown in those parts of the editor. (separate issue)

**Comment by Kiarii** [comment]
https://invis.io/WQUHJW1CT38#/389619771_1-0_X_-_Sub-Bucketing
- here are the mockups illustrating how the selection of multple metric cols for the Y axis will work. Using multiple cols in the Y disables bucket splitting in the X and vice-versa as shown in the mockups.. 
- in the Y, aggregations are the first field; Count as default, and Mean as the next default once some column is selected
- implement this using the current design implementation, do not redesign the UI elements for now. However, with the Y the [X] is used differently than the ones we have; here it removes the entire field (not the selected col name as is the current case) and it should be implemented as illustrated in the mockups
- am available to discuss any questions/comments..

**Comment by tangrammer** [comment]
once #2421 was merged/deployed we'll need to use feature flag "?series-bar=1" to see the new changes

**Comment by janagombitova** [comment]
After testing the implementation on lumen.akvotest.org under the feature flag `?series-bar=1` I found a few small improvements that can be made to the implementation (also based on the mock-ups):

<img width="1248" alt="Screen Shot 2019-11-11 at 09 49 39" src="https://user-images.githubusercontent.com/12456965/68573793-bf406600-0468-11ea-87e2-131b44c32806.png">

<img width="1245" alt="Screen Shot 2019-11-11 at 09 52 23" src="https://user-images.githubusercontent.com/12456965/68573880-fd3d8a00-0468-11ea-9e2d-140c553a0e50.png">


* Remove `No series` --> Salim will not really understand what this means and it is just an extra in the UI not really adding a lot of information or benefit. 
*  Once I select the 2nd metric column I do not have the option to remove the 1st one. Can we allow that? So if there is only one column left, then we do not allow to remove it but once there are two and more I can remove any of the columns.

**Comment by janagombitova** [comment]
With Juan we agreed to take my 2nd point out from my previous comment and make it into a separate issue that can be handled in the future.

**Comment by janagombitova** [comment]
![Lumen - visualisations - bars with multiple metric columns](https://user-images.githubusercontent.com/12456965/68847527-20697300-06cf-11ea-821e-ca0ecf44e7bf.gif)
Works like a charm!

**Comment by janagombitova** [comment]
After testing the small change @tangrammer pushed to dark-test we agreed to **not** push the change as then users need to guess/know they can select more metric columns. Now it is nice and obvious with the button just being there in your face. Thus this task is done.
