### ISSUE TITLE
Create more derive columns in one go

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2141]
# Context

## Why do we add this issue?
To make analysing data in Lumen as easy as possible. 

# Problem or idea
## What is the current status quo? 
When deriving a column or when using any Lumen transformation, you go to the dataset, select the transformation, add the details and done. If you want to do the same thing again you again have the select the transformation option and go through all the steps. 

But what if you want to extract multiple values for more than one Caddisfly question in your dataset? Or what if you are working on your indicator formula and you need to categorise 5 different columns to simplify the data? 

## Example
These questions came up when we were researching scoring of data and what type of calculations are done on a dataset. It appeared that in many cases the original columns need to be scored first - instead of the text value assign a score number. And then the score columns are summed up into the final score. 

So 10 option questions with 4 possible options, so 10 columns with text values are weighted from 0 to 4. Then the score is summed up and based on the sum a farmer is compliant or not. For this case, Salim would have the create 10 score columns one after the other. 

# Solution or next step
Would it be possible to instead of having to go and select the transformation again, just create another one of the same kind and then derive them all in bulk?

**Comment by Kiarii** [comment]
idea:
![image](https://user-images.githubusercontent.com/12692444/58018146-b8b0e180-7b0a-11e9-98bb-a46ef0432040.png)
