### ISSUE TITLE
Support styling geoshapes based on text columns 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2168]
# Context
Geoshapes are most often used in projects focusing on agriculture to capture farms and their plots. *(Besides other cases out there, but will use this on the keep the explanation brief and to the point.)*

Often the farm datasets hold information about the farmer, which company she works for, details about her household or her yield and what she grows. When visualising the data Salim sometimes wants to see the distribution of yield per farm (number column) or type of vegetable per farm (text column). 

## Why do we add this issue?
- To make working with geoshapes as easy as possible and analysing data on maps as insightful possible.
- To support the main use cases. 

# Problem or idea

## What is the status quo? 
Currently, you can create a map and layer geoshapes on it. You can colour code the shaps based on number questions only. 

![Screen Shot 2019-05-24 at 13 35 24](https://user-images.githubusercontent.com/12456965/58325087-012d0f80-7e29-11e9-8bb8-c46ecb0d56c5.png)

You cannot use text columns to colour code the shapes. So if Salim wants to create a map with shapes and colour them by type of vegetable he cannot. He has to add the shape layer and then add the 2nd layer with points and colour these by vegetable type. 

## If this change is successful what might we observe
- more use of Flow geoshapes 
- more use of Lumen maps 

# Solution or next step
## How could we solve it?
Can we make it possible to select a text column to style the shapes? 

## Whose behaviour will change and how? 
It will simplify the life of Salim creating the maps as he will not have to work with many-layered maps and can easily create simple maps to use for further analysis or reporting. 

For Petra looking at the maps, it will be easier for her to understand the data and their context. 

## How will this change benefit users? 
- make it easier to work with maps 
- cover the majority of use cases when analysing and visualising shapes 

## How will this change benefit Akvo? 
- maps are a very popular way of showing data in the sector we work in, thus having a good mapping feature will only improve our market position
- for the consultancy work we do, it will simplify the workload of our colleagues as they just need to create one map layer rather than two

**Comment by tangrammer** [comment]
example full payload for https://demo.akvolumen.org/visualisation/5ce7ba20-b568-4bc5-bb01-9c85cae6340c

```json
{
    "id": "5ce7ba20-b568-4bc5-bb01-9c85cae6340c",
    "datasetId": null,
    "name": "Example map",
    "visualisationType": "map",
    "spec": {
        "layers": [
            {
                "popup": [],
                "gradientColor": "#3f51b5",
                "longitude": null,
                "pointSize": 3,
                "legend": {
                    "title": null,
                    "visible": true
                },
                "aggregationDataset": "5c0a25a6-ef21-463f-952e-ea10f01f7d65",
                "filters": [],
                "latitude": null,
                "visible": true,
                "aggregationMethod": "avg",
                "geom": "c1",
                "pointColorMapping": [],
                "pointColorColumn": null,
                "datasetId": "5a684e60-ef07-40ba-9570-4cf234990a77",
                "title": "Population data",
                "layerType": "geo-shape",
                "aggregationGeomColumn": "c118600767",
                "rasterId": null,
                "aggregationColumn": "c122620001"
            },
            {
                "popup": [
                    {
                        "column": "submitted_at"
                    },
                    {
                        "column": "c135820001"
                    },
                    {
                        "column": "c114750004"
                    },
                    {
                        "column": "c129950001"
                    }
                ],
                "longitude": null,
                "pointSize": "3",
                "legend": {
                    "title": "How long does it take to go there, get water, and come back from the drinking water source?",
                    "visible": true
                },
                "filters": [],
                "latitude": null,
                "visible": true,
                "aggregationMethod": "avg",
                "geom": "c118600767",
                "pointColorMapping": [
                    {
                        "op": "equals",
                        "color": "#388e3c",
                        "value": "Less than 30 minutes"
                    },
                    {
                        "op": "equals",
                        "color": "#f44336",
                        "value": "More than 1 hr but less than 2hrs"
                    },
                    {
                        "op": "equals",
                        "color": "#b71c1c",
                        "value": "More than 2 hrs"
                    },
                    {
                        "op": "equals",
                        "color": "#ff9800",
                        "value": "More than 30 minutes but less than 1 hr"
                    },
                    {
                        "op": "equals",
                        "color": "#81c784",
                        "value": "Water on premises"
                    }
                ],
                "pointColorColumn": "c135810003",
                "datasetId": "5c0a25a6-ef21-463f-952e-ea10f01f7d65",
                "title": "Water point data",
                "layerType": "geo-location",
                "rasterId": null
            }
        ],
        "version": 1,
        "baseLayer": "street"
    },
    "created": 1558690336519,
    "modified": 1558711340857,
    "type": "visualisation",
    "status": "OK"
}
```

only layer payload
```json
{
                "popup": [],
                "gradientColor": "#3f51b5",
                "longitude": null,
                "pointSize": 3,
                "legend": {
                    "title": null,
                    "visible": true
                },
                "aggregationDataset": "5c0a25a6-ef21-463f-952e-ea10f01f7d65",
                "filters": [],
                "latitude": null,
                "visible": true,
                "aggregationMethod": "avg",
                "geom": "c1",
                "pointColorMapping": [],
                "pointColorColumn": null,
                "datasetId": "5a684e60-ef07-40ba-9570-4cf234990a77",
                "title": "Population data",
                "layerType": "geo-shape",
                "aggregationGeomColumn": "c118600767",
                "rasterId": null,
                "aggregationColumn": "c122620001"
            }

```





aggregation dataset
https://demo.akvolumen.org/dataset/5c0a25a6-ef21-463f-952e-ea10f01f7d65
column referenciated
```json
{
    "columnName": "c122620001",
    "direction": null,
    "hidden": false,
    "sort": null,
    "title": "How many people live in your household? (Type number)",
    "type": "number"
}
```

**Comment by janagombitova** [comment]
DRAFT PLEASE INGNORE
After an initial discussion with @tangrammer this morning we agreed to research a bit more what the user expectations are, what the current practices are and what should Lumen handle and what we should consider an advanced functionality to park for later or not do at all. 

I found an older issue here, that might provide some background info: https://github.com/akvo/akvo-lumen/issues/1059

# Current status quo 

<img width="1278" alt="Screen Shot 2019-05-28 at 14 11 07" src="https://user-images.githubusercontent.com/12456965/58476922-86c6fd00-8152-11e9-85c2-fea34caea064.png">
*Example map: https://demo.akvolumen.org/s/0OkWiLQHuXg*

Currently, we can create this type of maps in Lumen. The geoshape layer is a heat map coloured based on a number column - showing the average household members, where the second layer holds points (from the same household dataset) coloured by answers to a text column, the time needed to fetch water. 

To work with **geoshapes** in Lumen today, they can only be styled based on a geo-point located in the geoshape (another column) and a number column. So we can create heat maps. So to work with geoshapes, you are dependent on another dataset (in the case of Flow data, it can be the same dataset) to style the shapes. The shapes act only as a container. But often shapefiles contain their own data column. These can be numeric or text 

## Current issues 
- to work with shapefiles you need to have an extra geo-point column to style the shape (shapes are today only empty containers) 
- can only style based on numeric columns and not on text 

# Expectation 
The request we received is if it is possible to also style geoshapes based on text columns. After talking with Joy, Ilyasse and Geert it seems (as usual) that there is more to it. There is the simple use case but to provide Lumen with the more advanced capabilities and more value more work is needed and changes to the current set up as well. 

## The simple use case
## The more advanced use cases 

# Next steps
- do we understand the use cases and their differences? 
- are there pieces of the use cases or use cases that we will not support and rather leave for specialised tools to handle (or for the future)? 
- for those cases that we want to support, what is needed and how can we break it down into small implementable chunks?
