### ISSUE TITLE
Category derived column for Number columns 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2181]
# Context
Why do we add this issue?

With #2071 we have implemented the initial functionality for the new transformation, **Derive Category column**. This one allows you to create a new column based on data in the TEXT column. To complete the implementation we need to add support to deriving a column based on a NUMBER column. 

For all the details about Why we should do this, what we expect to happen and change, and how will we measure, please check the epic #2071. 

# Solution or next step

This issue is focusing on implementing the 2nd part of category derived column, where Salim can also select a number column to derive a category text column. Because the number column behaves differently than the next one, we split the implementation.

The number column should not list the unique values but provide the options to define ranges and rules as below, higher than, equal to, etc. The new column will still be of TEXT data type.

![Screen Shot 2019-05-31 at 10 49 39](https://user-images.githubusercontent.com/12456965/58693792-d0e9f180-8391-11e9-8196-40e2daef2512.png)
 
For the full mockups go here: https://projects.invisionapp.com/share/8CRV05F9TZW#/screens

**Comment by janagombitova** [comment]
## Action buttons must stand out 
Right now the initial action is to Define a new category and in the UI it is not visible that that is an action. Can we use the styling we have for creating Groups? 
![Screen Shot 2019-06-12 at 12 26 04](https://user-images.githubusercontent.com/12456965/59349021-f1626600-8d18-11e9-80fe-930a8b2809f9.png)




## Remove new row 
The x icon to remove an extra added row can be made smaller, the same size as we have when removing an `and`

![Screen Shot 2019-06-12 at 13 47 29](https://user-images.githubusercontent.com/12456965/59349008-e90a2b00-8d18-11e9-839b-59b3dabbfc32.png)

## Create a new category 
Here I wonder if the name of the action is good as we use the word category in the new column. There a category is the new data value. In the data column (the numerical one on the left) we are creating the rule based on which the category will be applied to the data. Is there another term that might fit better to distinguish the two? Example: *Create data rule* ? I am open to ideas.

**Comment by tangrammer** [comment]
@janagombitova @Kiarii 
about `the Derive button should only be enabled is the new column name is added, all categories are added and unique. ` ... then,  should we add some notifications/validations about which "things" are required to enable the `derive` button ? thus, on the contrary it could be situations where the user will not know  why can't derive the category

**Comment by janagombitova** [comment]
After discussing our last comments with @tangrammer this morning we agreed: 
* to change the action buttons to follow the same style as the `group` one 
* make the remove row icon smaller 
* not change the text for `Define new category` as Juan persuaded me that it is the start of the entire process - you have nothing and now you are defining what the category will be based on and its name 
* validate missing category name by allowing to click on the `Derive column` button but show an error that the category column is missing. We chose for this option as if you have a case with many categories it might be hard to see what is missing in the UI as it is styled today. 

We also agreed that once @Kiarii and @loicsans are back from holidays to ask them to review the entire category column styling and suggest further improvements. But for now we aim to get it in front of users as soon as possible to learn more.

**Comment by janagombitova** [comment]
Released. All further improvements will be handled in separate issues
