### ISSUE TITLE
Update E2E docker-file due to security issue

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2188]
https://github.com/akvo/akvo-dockerfiles/network/alert/lumen-e2e-test/package-lock.json/lodash/open

**Comment by kardan** [comment]
Depends on https://github.com/akvo/akvo-dockerfiles/pull/11

**Comment by kardan** [comment]
Updating Cypress to use the latest image didn't fix this issue. So new PR https://github.com/akvo/akvo-dockerfiles/pull/12

**Comment by janagombitova** [comment]
@kardan I assume this has been released today, so closing the issue.
