### ISSUE TITLE
Feedback MVP

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#221]
This issue will hold the testing results and feedback for the Lumen MVP of 8 June 2016.

**Comment by mtwestra** [comment]
Comments Lumen testing - datasets

Bugs
====
- [ ]  I am trying to upload the file liberia.csv (~11.000 rows,https://drive.google.com/drive/folders/0BwEEfk7lVujkdFdZSGdQVnZEUVk) using drag and drop, but it fails with "DataFileDataSourceSettings.jsx:57 Failed because: Error: tus: unexpected response while creating upload" in the inspect data tab. When I try to upload a shorter version of the same file, the import succeeds.

- [ ]  When I try to upload the liberia.csv file using 'choose file' it fails with "upload.js:347 PATCH http://lumen.akvotest.org/api/files/abbabfbb6eec4ab8b842823db4f402a6 413 (Request Entity Too Large)"

- [ ]  If I go to http://lumen.akvotest.org/dataset/library directly using a fresh browser, the loading fails with 'Dataset.jsx:48 Uncaught TypeError: Cannot read property 'name' of undefined'


Feature changes
================
- [ ] The collections don't seem to work yet. Is this intentional? I think it might be good to implement it if it is doable, as showing how to order stuff is an important part giving people the feeling that they are in control.

- [ ] When data doesn't fit a cell, the content is cropped. This doesn't look very good. Perhaps just restrict the length, like in Excel?

- [ ] When I upload, all column types seem to be text. In future, it would be good to be a bit 'smarter' here, for example by investigating the first 10 rows, and guess a type based on that. 

- [ ] When an upload of a csv file fails, I don't get a feedback, just 'error'. A more meaningful error message would be very useful.

- [ ] When I delete a dataset, I would like to see a confirmation dialog

**Comment by iperdomo** [comment]
@mtwestra collections are not part of the MVP, check the list of features in the spreadsheet.

**Comment by kardan** [comment]
On 1.2, what size do we want to support?

**Comment by mtwestra** [comment]
I'll move the list of features to this document: https://docs.google.com/document/d/1XpBzVYzvvqEXFOe6N7h5K0v3LU5EBKW6jErTvD4ex6Q/edit#

**Comment by mtwestra** [comment]
@kardan, @iperdomo, I would say the same size as Lumen can handle: estimated size of a csv file with 1M rows?

**Comment by iperdomo** [comment]
@kardan let's change it to 10MB for now, 1M rows csv file depends on the number of columns, but it could get to 100+ MB easily

**Comment by kardan** [comment]
https://github.com/akvo/akvo-provisioning/issues/310

**Comment by iperdomo** [comment]
Closing as feedback is collected elsewhere and only identified _showstoppers_ will be logged in this issue tracker
