### ISSUE TITLE
Authgrade

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2215]
# Context
Akvo needs single sign on between Flow and Lumen. We also want to move away from Keycloak and use a hosted authentication provider. Auth0 have been chosen as provider.

# Problem or idea
Today Flow use Google and Lumen use Keycloak for authentication and authorization.

# Solution or next step
- [x] Isolate Keycloak within the Lumen code base.
- [x] Move authentication from using token claims to query the Keycloak API (decoupling authentication from authorization)
- [x] Switch to auth0 clients for openid-connect
- [ ] Migrate and move permissions to new authorization service

**Comment by janagombitova** [comment]
@kardan can we close this issue and create a new one that will only focus on the permissions once we start that work? Or does this issue hold more?

**Comment by kardan** [comment]
Let's close this
