### ISSUE TITLE
Cannot edit Derive Category column group

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2224]
# Context
*Why do we add this issue?*
To make the user experience as smooth as possible and allow users to make mistakes without having to redo everything. 

# Problem or idea
*What is the cause?*

When deriving a new Category column using TEXT data you can create groups. This is super handy. But what happens if you create a group and you realised you added one item too many? 

Today you can click on the group and see the selected items. But if I want to unselect an item it does not work. I can add another item to an already created group, but I cannot uncheck the checkbox once checked

![Editing groups.gif](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/c469099e-8974-4602-aadd-73ad2f7c47b4)

# Solution or next step
*How could we solve it?*
Would it be possible to be able to remove a value from a group by unchecking the checkbox?

**Comment by tangrammer** [comment]
This is working fine in current version
