### ISSUE TITLE
Map shows more than once

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2226]
# Context
*Why do we add this issue?*
To create a pleasant user experience with no weirdness going on

# Problem or idea
*What is the cause?*

By default when creating maps the zoom level is defined by the location of the data points. But we have one case where there are only data points used but the map by default zooms out so much that you see the world five times. 
 
![Screen Shot 2019-06-20 at 16 59 36](https://user-images.githubusercontent.com/12456965/59859437-f9f01780-937c-11e9-99f0-17cdebba285d.png)

I first thought that maybe something goes wrong with how we make geopoints out of the Flow data so I put the dataset in a google sheet and tried to generate geopoings. But my maps were the same. 

The map: https://lumen.akvotest.org/visualisation/5d0b8b6f-14f3-42a1-8378-ee3e334007a9
The dataset directly from Flow: https://lumen.akvotest.org/dataset/5d0b8b3c-617f-4e00-8dff-03cf57b5d018
The dataset from the google sheet link: https://lumen.akvotest.org/dataset/5d0b8ec1-a2f3-47f6-a838-416bdeebb4eb

# Solution or next step
*How could we solve it?*

**Comment by tangrammer** [comment]
the problem seems to be a data related problem:
the row `1491`  has this geopoint value `POINT(4170140500 41.409056)`  so the surrounding box takes that value as the bigger one

**Comment by janagombitova** [comment]
Indeed. After we cleaned the row the map works like a charm: https://lumen.akvotest.org/s/Zjv6-mPguoQ Thank you @tangrammer

**Comment by tangrammer** [comment]
yupie!
