### ISSUE TITLE
Handling user logout and language preferences 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2245]
# Context
I connected with Dan L on 17 July 2019 to discuss the current status quo of moving to Auth0 for Flow and Lumen and this question came up in the talk. You can find my notes here: https://docs.google.com/document/d/1uE4tc_Bz-nooJdDqP8L3Qe_ZuoOOAD9-WoNsvjKq7v0/edit#

## Why do we add this issue? 
We decided to move away from Keycloak to Auth0 for user authentication. This change brings a few user-facing consequences with it. 

We want to make sure that the Auth0 change is:  
* as smooth as possible in terms of as least possible obstruction to existing users as we can make with sufficient communication
* unifies Flow and Lumen a bit more in terms of user accounts, look and feel and workflows 
* we do not remove the important features out of the blue 

# Problem or idea 
The idea is to find a new place in Lumen's UI for users to change the language and log out. 

## Current status quo 
Today a user sees in the Lumen home page her email. She can click on it and she enters the Keycloak user admin page. Here she can change her details, log out and change the language. A user admin cannot change user details as Name and Email currently, either. 

![Auth0.gif](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/69d43ca0-cbab-4188-98c2-a6af5b39df3a)

With moving away from Keycloak this page will also disappear, right @tangrammer and @kardan? Thus we need to figure out how will she be able to: 
1. change her language from the current home page 
2. log out from the current home page 
3. edit an existing user (if you are a user admin): new issue https://github.com/akvo/akvo-lumen/issues/2246

# Solution or next step 
First of all, we need to: 
* confirm the user admin page will indeed disappear with moving away from Keycloak 
* check if there are any other changes needed to handle this properly 

## How could we solve it? 
If we can find a way to unify it with how these three tasks are handled in Flow, from the user's point of view, that would be ideal. But considering the UI layout is so different this might not be possible so we should aim for a simple and clear change. 

Handling log out and languages can be handled somewhere in the Lumen landing page. 
![Screen Shot 2019-07-19 at 11.52.13.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/c915a24c-38e2-4e7b-9ea7-c179d8496d0e)

- [ ] [Improve](https://github.com/akvo/akvo-lumen/pull/2244/files#diff-707813fe89bae260ba9383a76bb0082aR7) current keycloak home page settings in case of auth0 selection

**Comment by tangrammer** [comment]
Using user detail auth0 page to add user metadata
<img width="632" alt="Screen Shot 2019-07-22 at 11 38 34" src="https://user-images.githubusercontent.com/731829/61622559-4f1d9280-ac75-11e9-8e35-21531334e35e.png">


Then,  Auth0 Management API could return this meta data
Once that you have a [proper token](https://auth0.com/docs/api/management/v2/get-access-tokens-for-test) we can query using [API ](https://auth0.com/docs/api/management/v2#!/Users/get_users) ... 

[also we can query user_metadata and/or app_metadata](https://auth0.com/docs/users/search/v3/query-syntax)

user_metada could be modified also by user in auth0 user-management-detail-page
but app_metadata only could be modified by admin 

```shell
export BEARER=xxxxxxx......

---- user_metadata example

curl --request GET \
  --url 'https://akvotest.eu.auth0.com/api/v2/users?q=user_metadata.language%3A%22en%22&search_engine=v3' \
--header 'authorization: Bearer '$BEARER


--- app_metadata example

curl --request GET \
  --url 'https://akvotest.eu.auth0.com/api/v2/users?q=app_metadata.tenants%3A%22demo%22&search_engine=v3' \
  --header 'authorization: Bearer '$BEARER
```

will return 
```json
[
    {
        "email": "xxx",
        "email_verified": true,
        "name": "xxx",
        "given_name": "xx",
        "family_name": "xxx",
        "picture": "xxx",
        "locale": "en-GB",
        "updated_at": "2019-07-22T09:38:17.121Z",
        "user_id": "xxxx",
        "nickname": "xxx",
        "identities": [
            {
                "provider": "xxx",
                "user_id": "xxx",
                "connection": "xxx",
                "isSocial": true
            }
        ],
        "created_at": "2019-06-27T07:17:28.127Z",
        "user_metadata": {
            "language": "en"
        },
        "last_login": "2019-07-22T09:15:34.963Z",
        "last_ip": "xxx",
        "logins_count": 19,
        "app_metadata": {
            "tenants": [
                "demo"
            ]
        }
    }
]
```

**Comment by Kiarii** [comment]
since this is a step towards sth else and proper, could we show the language option as follows:
step 1: side menu
<img width="400" alt="Screenshot 2019-07-23 at 10 35 51" src="https://user-images.githubusercontent.com/12692444/61692258-f530d180-ad35-11e9-8bfa-e8810047288b.png">

step 2: side menu - user options
<img width="450" alt="Screenshot 2019-07-23 at 10 36 03" src="https://user-images.githubusercontent.com/12692444/61692156-c61a6000-ad35-11e9-8873-7d45bdadadf4.png">

**Comment by Kiarii** [comment]
In the case of displaying long user emails, we could consider a switch to showing the users' name instead

**Comment by janagombitova** [comment]
@Kiarii can you please share how that will work without indicated the Workspace as this is something we will not support at the moment? Thanks

**Comment by Kiarii** [comment]
yes, so we could it like this:
<img width="407" alt="Screenshot 2019-07-23 at 11 20 13" src="https://user-images.githubusercontent.com/12692444/61695266-de8d7900-ad3b-11e9-90c6-538d50a1c98f.png">

**Comment by kardan** [comment]
Started to work on the UI part and first did some kind of slider thingy. After talking to @Kiarii I realised the menu should pop out like an overlay (as when you click the arrow down next to the Workspace name in Slack). Started to work on that but so far not been able to get a menu working. The Keycloak service degradation issue made me not able to make more progress so far.

**Comment by janagombitova** [comment]
Works well on test.
