### ISSUE TITLE
Handle user editing 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2246]
# Context
We now have Auth0 running on test, meaning we can take the next steps towards removing Keycloak for user authentication in Lumen. This change brings a few user-facing consequences with it.

## Why do we add this issue? 
We want to make sure that the Auth0 change is:

* as smooth as possible in terms of as least possible obstruction to existing users as we can make with sufficient communication
* unifies Flow and Lumen a bit more in terms of user accounts, look and feel and workflows
* we do not remove the important features out of the blue 
* we keep the changes as simple and minimal as possible to be able to improve the UX in later iterations

After talking with Dan, Juan and Kiarii on what consequences this will have for Lumen users  (you can find my notes here: https://docs.google.com/document/d/1uE4tc_Bz-nooJdDqP8L3Qe_ZuoOOAD9-WoNsvjKq7v0/edit#). One group is handling log out and language selection (#2245) and the second is to make is possible to still edit existing user details. 

# Problem or idea 
The idea is to find a new place in Lumen's UI where a user with user admin rights can edit user details. 

## Current status quo 
Today a user sees in the Lumen home page her email. She can click on it and she enters the Keycloak user admin page. Here she can change her details, log out and change the language. A user admin cannot change user details as Name and Email currently, either. 

<img width="1263" alt="Screen Shot 2019-07-19 at 11 58 39" src="https://user-images.githubusercontent.com/12456965/61701206-11d10780-ad3e-11e9-9c82-ca6965ae1bb3.png">

With moving away from Keycloak this page will also disappear so we need to figure out how to allow to **edit an existing user on Lumen**. 

# Solution or next step
Editing user details could be enabled in the Admin view. We have an action there already. 

In Flow, it looks similar, and by clicking on edit you get to a new page to edit the user details. Or we can see if we can just make the fields Name and Email editable in the list directly.

We will not create a User page, where a user herself can set her preferences and edit details as this is currently out of the scope of this iteration.

**Comment by Kiarii** [comment]
we had some ideas to make some incremental changes to flow user management - [Flow Roles and Permission prototype](https://projects.invisionapp.com/share/PYQPG554Z5J#/screens/348168754) - I am unsure if this is still in the cards, when we talk about handling user editing similarly in flow and lumen. It is also worth noting that in flow, editing a user also enables editing their permissions.
My assumption, however, is that we might want to make as little changes as possible while we await to unify user mgmt in the two as per the FLMNFLY ideas that we have been working on in the first quarter; user mgmt on region/global, country and project level.. [mockups for country manager persona](https://projects.invisionapp.com/share/2YQHGYIHB87#/screens/343561534)
For now then I assume a band-aid solution of editing user info in situ as Jana suggested might work :)

**Comment by janagombitova** [comment]
That looks great! 

Indeed this issue is to only allow to edit a user's name and email. Roles and permissions will eventually be handled in Flow, as overall user management. So this is a temporary solution to make it possible for users: 
* to move away from their Google emails if they prefer to use another account 
* edit mistakes in names and emails
* add user names 

Secondly, yes the idea is to simplify how user roles are set up in Flow to create default roles: https://github.com/akvo/akvo-flow/issues/2989. When it comes to changing the hierarchy of elements to move away from folders, that will **not** be in scope.

**Comment by janagombitova** [comment]
In an chat @tangrammer we spoke about the reasons behind this change: 
* Sometimes user names are not well set, there are emails there or typos - so we need a way for user admins to be able to edit them 
* with moving to Auth0 most likely Flow users will change their emails from Google accounts to other accounts. This means they have to also be able to make the change in Lumen to be able to use the product. 

The first reason is ok and does not bring risks. The second one with changing emails is not as simple as it sounds as every new email needs to be validated and thus needs to follow the user invitation workflow. To keep this change simple and without risks, and because we will change user management again when we have the new service in place to handle authorisation, we agreed to **only allow editing of user names and not emails**.

**Comment by janagombitova** [comment]
Today we spoke with @kardan and @tangrammer about this issue. We agreed that having the admin to edit user names is a bit strange as the user should be able to set her name herself, but it was a good alternative to us losing the user page with moving away from Keycloak. But because Daniel implemented a simple UI where the user can click on her profile and edit her First and Last name we decided to change the implementation for a more simple and user friendly approach. 

**Decisions:**
* Each user can change her first and last name. This is then also updated in the User list. We will add an Edit profile option to the language and log out menu. 
* We will remove the option for the admins to edit existing users **fully** (only keeping the role change possible) thus allowing users to change their own first and last names 
* If it is not too much effort we will like to implement that when a user logs in and her first and last name are missing, she will see the screen to input that right away before entering the Library. This will ensure users have all the details for easy user recognition for User Admins

**Comment by kardan** [comment]
Closing this for now, see https://github.com/akvo/akvo-lumen/issues/2299 for user modal when no name
