### ISSUE TITLE
Creating new users with Auth0

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2247]
# Context
## Why do we add this issue?

We decided to move away from Keycloak to Auth0 for user authentication. This change brings a few user-facing consequences with it.

We want to make sure that the Auth0 change is:

* as smooth as possible in terms of as least possible obstruction to existing users as we can make with sufficient communication
* unifies Flow and Lumen a bit more in terms of user accounts, look and feel and workflows
* we do not remove the important features out of the blue
* keep the implementation as simple as possible as this is the MVP and later we will change more things (move authorisation to another service, ideally have user management handled only via Flow - from the users' point of view, etc) 

# Problem or idea
The idea is to see if how we currently create new users in Lumen (invite new users to join Lumen) will still work with Auth0 or if we need to change the implementation. 

## Current status quo
Currently, a new user is added to Lumen following these steps: 
1. User with Admin role goes to the `Admin view` 
2. Admin hits `Manage invitations`
3. Sees a list of users who are invited but did not sign up yet, clicks on `Invite user`
4. Fills in user email and hits `Invite user`
5. This new user receives an email with a link to join Lumen (if this user does not exist in Keycloak, then the email also holds a temporary password) 

![new user creation in Lumen](https://user-images.githubusercontent.com/12456965/61705361-ece09280-ad45-11e9-9c4f-9623fe17dde0.gif)

# Solution or next step

* [x] figure out is the user invitation emails we send out today are handled by Lumen or by Keycloak

* if by Keycloak then we need to simplify the new user creation to follow the most minimum workflow (as in Flow): Admin adds a new user in with user name and email and assigns the role --> the Admin then tells the new user the URL and email to use to sign up or log in
* if by Lumen then we need to test if all works well with Auth0 and if changes are needed 

## New workflow if needed

If the email sending is handled by Keycloak and adding new users to Lumen will not work because we moved to Auth0, then here is the proposed new workflow that we spoke about with Dan, Juan and Kiarii. The intention is to make adding a new user as simple and minimal as possible, following Flow's example. 

### New workflow
1. User with Admin role goes to the `Admin view` 
2. Admin hits `Add new user`
3. Adds user name and email and if the user had Admin or User role
4. Saves new user. 

### Things to discuss and change 
- will we have the user admin to add the user Name too? Then we need a UI for adding a new user. 
- does the Admin also decide on the role when creating the new user? or will that happen as today once the user is saved and in the user list? (in Flow the role is decided at creation) 
- we can remove the page with Invited users as this is no longer relevant if we change the workflow 
- anything else?

**Comment by tangrammer** [comment]
- [X]  figure out is the user invitation emails we send out today are handled by Lumen or by Keycloak

### current logic when inviting users:
+ lumen request keycloak to create a new user
+ lumen generates a random password 
+ lumen request keycloak to reset-password for the new-user with one-time-password=random-password 
+ lumen sends a verification link email to the user with one-time-password included


#### mail payload:
```
07:56:33.295 [XNIO-2 task-2] INFO  akvo.lumen.component.emailer - [support@akvolumen.org]
07:56:33.297 [XNIO-2 task-2] INFO  akvo.lumen.component.emailer - {Subject Akvo Lumen invite, Text-part Hi!

You have been invited to join Akvo Lumen by jerome@t1.lumen.localhost.
To complete the invitation process please visit:
https://t1.lumen.local/verify/0fe06c4a-02be-48f4-9fec-4a43eebb8b00
Using your email: support@akvolumen.org
and the temporary password: eCpGk2q6 to login.

Thank you

The Akvo Lumen Team
}
```


- [ ]  If by Keycloak then we need to simplify the new user creation to follow the most minimum workflow (as in Flow): Admin adds a new user in with user name and email and assigns the role --> the Admin then tells the new user the URL and email to use to sign up or log in

- [ ]  if by Lumen then we need to test if all works well with Auth0 and if changes are needed

**Comment by tangrammer** [comment]
(after merging #2257 )

####  an authenticated-auth0-user that has "admin" role (retrieved from authorization service) can: 
- [X] invite user

(after merging https://github.com/akvo/akvo-lumen/pull/2259 )
#### an invited user can:
- [X] use the email activation link
- [X] then,  can log in into lumen using google-connection

**Comment by tangrammer** [comment]
- [ ] log in with auth0 user password combination

**Comment by janagombitova** [comment]
After a quick chat with @tangrammer we agreed to keep the email invite functionality in Lumen: 
* as it is handled by Lumen technically so we do not need to implement or change that much
* we do not have to explain a new workflow now and then again later with iteration n2 to Lumen users 
* we could possibly use the same user experience for Flow too in the future.

The workflow is: 
1. User admin adds my email to Lumen. 
2. I receive an email saying something like this: this Lumen user invited me to this Lumen tenant with this email. Go here to login/signup. 
3. The url brings me to the Lumen tenant login page and I login or sign up based on my case. 

Having the email invites in place will remove the unclarity we now have where users do not know they were invited to a product and with which email.

**Comment by tangrammer** [comment]
after merging https://github.com/akvo/akvo-lumen/pull/2260
- new invited user could sign up with auth0

**Comment by janagombitova** [comment]
I did not test this one yet as I am not sure how to use all the feature flags, so will wait till we have everything done and we can turn on the flag on Lumen Test to streamline the testing steps (if possible)

**Comment by janagombitova** [comment]
Tested user invitation this morning. Steps I took: 

1. Signed up with a new user account `akvo.flow.test.user4@gmail.com`
2. As expected, could not access Lumen. 
3. Logged in with my admin account, jana@akvo.org and invited to user 
4. Received the email invite and clicked on the link that took me straight to the login/sign up page 
5. Logged in with Auth0
6. Got a blank page 

I am not sure this is because I did something wrong with the feature flags at the last step or we still have some unfinished work here or a bug. @tangrammer and @kardan can you two also check?

**Comment by janagombitova** [comment]
All works! I tested both workflows: 
* when the user signs up but is not invited and later invited
* when the user is first invited and then signs up

All work like a charm. We are still missing the branded Email verification pages, but that should be handled in another issue by @loicsans
