### ISSUE TITLE
Dataset update fails if column missing

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2254]
# Context

Geert reported an issue via support: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-240391-from-geert-at-akvo-dot-org

## Why do we add this issue? 
To make sure updating Flow data in Lumen is robust but also smart. 

# Problem or idea

Updating the dataset fails because some questions were removed from Flow after the dataset was created in Lumen. 

Here are the steps they took:
- Questions were added to the questionnaire, no data was actually collected for these questions. (https://1wash-salone.akvoflow.org/admin/ > 3. Other > 2. GVWC > 1. Project Affected People (PAP) )
- Dataset in Lumen was updated.
- Questions in Flow were deleted
- Update error in Lumen: (Failed to update dataset "Project Affected People (PAP)": Column mismatch. Following columns are missed in new data version:
[{:title "Affected Length & Width [m]", :id "c401720001"}
{:title "Affected Area [m2]", :id "c395350001"}
{:title "Nature of Structure (NS) with respective sub-weights", :id "c428610001"}
{:title "Type of Roof (TR) with respective sub-weights", :id "c403180001"}
{:title "Remarks", :id "c404770001"}]
- Those specific questions were deleted in Lumen as well. However, it still reports a column mismatch. 

The dataset set is this one: https://sierraleone.akvolumen.org/dataset/5d14e135-fa45-4c27-9dbe-9bf1898ab913

# Solution or next step
With @tangrammer we looked at the issue and Juan explained how the update logic works today: 
- Get the data from Flow
- Check the columns
- Run the transformation on the dataset
- The end

If the columns do not match, we stop the update process to make sure the 3rd step of running the transformations will succeed.

We thought we can change the update process to ignore the missing columns and fail the update if these are used in a transformation task. So if a column does not exist but is in a transformation we stop the process. But if it does not exist and is also **not** in a transformation we simply let it be and keep on updating.

**Comment by tangrammer** [comment]
2 important things here:
+  [Don't allow core/rename-column tx to be removable](https://github.com/akvo/akvo-lumen/commit/a6dc7fb26ca33bade23bb288f2943949752919f9) thus derive js transformation is based on column title
+ [Don't allow LINK updates to avoid columns](https://github.com/akvo/akvo-lumen/commit/790fc20226b7c36d7db1fb640fd00267de9b6112) thus LINK updates column names are always indexed so columns names are always c1, c2, c3, c4 .... and it makes impossible to distinguish if same column remains the same. Flow on the contrary maintain the column id so lumen can trust on this value

**Comment by janagombitova** [comment]
@tangrammer I have tested on dark-demo also following the steps you shared in Slack and based on the comments you added here and I did not find any issues anymore. I think it is ready for production.

**Comment by janagombitova** [comment]
Pushed to production on 15 August

**Comment by tangrammer** [comment]
flipped today to live prod and working there
