### ISSUE TITLE
Handling cell overflow in dataset editor

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#226]
Currently, overflowing cells wrap to the partially-obscured next line. 

![image](https://cloud.githubusercontent.com/assets/2589977/15896411/19df3c14-2d88-11e6-887e-f54450276142.png)

This doesn't look good. We should hide any overflow from the cell:

![image](https://cloud.githubusercontent.com/assets/2589977/15896440/44bcd932-2d88-11e6-837d-0744c6a6747d.png)

Optionally, we can also include an ellipsis to indicate the contents are truncated, like so:

![image](https://cloud.githubusercontent.com/assets/2589977/15896470/68131086-2d88-11e6-8b8f-eca5784e66ea.png)

There are pros and cons to including the ellipsis. Thoughts on this last point @mtwestra @Kiarii ?

**Comment by Kiarii** [comment]
@gabemart we could go for the first option to begin with, excel & trifacta handles overflows similarly while openrefine  adds new lines adjusting the rows height accordingly

**Comment by gabemart** [comment]
@Kiarii OK, first option has been implemented.

And yes, we have a minimum col width - in fact, I think cols are fixed at 200px at this early stage

**Comment by gabemart** [comment]
Closed via #237
