### ISSUE TITLE
Potential development problem: overwriting  hugsl function names

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2262]
# Context
Just realizing that we could change function behavior changing the order of hugsql imports, producing difficult bug to debug/locate

example
https://github.com/akvo/akvo-lumen/blob/20408f25e8c32d1a453497aa2f038a411b080aa1/backend/src/akvo/lumen/lib/dataset.clj#L15-L17

if we add here the line 
` (hugsql/def-db-fns "akvo/lumen/lib/transformation.sql") `

the function called here 
https://github.com/akvo/akvo-lumen/blob/20408f25e8c32d1a453497aa2f038a411b080aa1/backend/src/akvo/lumen/lib/dataset.clj#L55

will be the transformation.sql one instead of the dataset.sql version 

# Solution or next step
Prefixing hugsql functions

**Comment by kardan** [comment]
@tangrammer close this one?

**Comment by tangrammer** [comment]
not yet 😬 !

**Comment by tangrammer** [comment]
it could be closed after merging https://github.com/akvo/akvo-lumen/pull/2366
