### ISSUE TITLE
Cannot import data from idh.akvoflow.org

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2272]
If your user has access to both Flow and Lumen with the same email account you can import a Flow dataset to Lumen. You type in the Flow url, select the folder, survey, form and import the data. 

This works for any Flow instance I have access to besides one, idh.akvoflow.org. When I try importing data from this instance, the folder dropdown does not show. 

<img width="1278" alt="Screen Shot 2019-08-15 at 13 56 21" src="https://user-images.githubusercontent.com/12456965/63093260-c4bf0a80-bf64-11e9-8a96-e0c90756f1a9.png">

**Comment by tangrammer** [comment]
trying with my account i get "could not resolve alias" network message when lumen tries ajax call https://api.akvo.org/flow/orgs/idh/folders?parent_id=0, looking in akvo-flow-api repo https://github.com/akvo/akvo-flow-api/blob/f70610c0599ae2d7f967bf06ce048431247a4ffa/api/src/clojure/org/akvo/flow_api/middleware/resolve_alias.clj#L13 seems that the problem arises there, so maybe better to move this issue to that repo and fix/debug there the problem

**Comment by dlebrero** [comment]
There is a typo in the Flow configuration: the instances is aliased as "ihs". See https://github.com/akvo/akvo-flow-server-config/commit/1982add72ff52c903b1beee37c6a43de03d7b6c8

As there are several places in the configuration with the typo, leaving it to @muloem to fix it as it may need some manual changes or redeploy of that instance. 

flow-api (and Lumen) will start automatically working once the configuration is fixed.

**Comment by valllllll2000** [comment]
update: the flow config has been updated and app and dashboard were redeployed, if anyone can check it fixes your issue.

**Comment by janagombitova** [comment]
The issue is resolved also on Lumen's end. I can now import datasets. Thank you @valllllll2000
