### ISSUE TITLE
We need to be able to host images for use on our apps and external (ie. auth0)

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-lumen#2278]
# Context
Why do we add this issue?
At the moment, when using external service like we do for auth0, it doesn't allow us to host any file like company logo. The logo is loaded via https link. Problem is that we do not have internally a server that would allow us to store these.

# Problem or idea
What is the cause?
We need to set up a server which contains logos and other ressources we may want to pull in and use across external and internal services.

# Solution or next step
How could we solve it?
Setup a repository from which we can pull clear https link to images...

**Comment by kardan** [comment]
Added the logo to https://github.com/akvo/akvo-lumen/blob/develop/client/src/styles/img/AkvoLogo.svg

**Comment by kardan** [comment]
Chatted a bit with @orifito about this and then. Created a Google cloud storage bucket "akvo-public" and put the bucket in there. Now available at
https://akvo-public.storage.googleapis.com/AkvoLogo.svg

**Comment by kardan** [comment]
Since we created the new bucket, closing this for now
