### ISSUE TITLE
Languages of Login page

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2284]
# Context
Relates to https://github.com/akvo/akvo-platform/issues/152

# Problem or idea
We need to i18n the login pages

# Solution or next step
solution to adopt
https://community.auth0.com/t/how-to-pass-language-to-auth0-popup/10898/7

Template Version controlled on github.gist
https://gist.github.com/tangrammer/70d911cb5804bea471e71771c411999c

**Comment by tangrammer** [comment]
how to test it  😄 
if you open a new incognito window the language of login page (3 availables: es, en, fr) will be read from browser [settings](https://support.google.com/chromebook/answer/1059490?hl=en)
- go to https://dark-lumen.akvotest.org/?auth=auth0
- check that login page matchs  chrome language selection

if you are a normal lumen user the browser will have stored your language selection already starting on https://github.com/akvo/akvo-lumen/issues/2245
- so just try to login using https://dark-lumen.akvotest.org/?auth=auth0, then changes the language selection using the proper user-language menu, then try to login again https://dark-lumen.akvotest.org/?auth=auth0

**Comment by janagombitova** [comment]
Works really well 👏
