### ISSUE TITLE
Remove extra space under user in the Library side panel 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2285]
# Context
**Why do we add this issue?**
To make Lumen as visually appealing and simple as possible

# Problem or idea
With changes to how we handle languages and logout in Lumen, we now have an extra space under the user name in Lumen's Library side panel. 

![Screen Shot 2019-08-28 at 13.13.14.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/786ba76e-83df-4dc1-bdae-8289956de1d8)

# Solution or next step
Can we remove this extra space?

**Comment by Kiarii** [comment]
we are go on this issue
