### ISSUE TITLE
Extract data from new Caddisfly test type - e.Coli+TC

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2295]
# Problem or idea
**What is the cause?**

We are working on adding a new test type to Akvo Caddisfly to test e.Coli and TC in one test. This is a new test type that holds values for both parameters. 

When testing the workflow on Lumen, I was able to import that data and Lumen marked it well as Multiple data type. But when trying to extract the data the transformation fails. Try here: https://akvointernal.akvolumen.org/dataset/5d6d2793-0724-4521-8ee8-79a618baeeb5

# Solution or next step
How could we solve it?

Make it possible to work with this new data in Lumen.

**Comment by nhternup** [comment]
New parameters e.Coli + TC has been added to the Caddisfly json (caddisfly-tests-v2.json). Please update Lumen with this version. @tangrammer

**Comment by tangrammer** [comment]
@janagombitova could you point me the column name that you are referring to?
I've tried with `Test TC levels` and worked fine 🤔 https://akvointernal.akvolumen.org/dataset/5d6d2793-0724-4521-8ee8-79a618baeeb5

**Comment by janagombitova** [comment]
Thanks @tangrammer for testing. I tried too and all works fine!
