### ISSUE TITLE
Limit data sorting to one column only 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2306]
# Context
## Why do we add this issue?

To make it easy to view data and for Salim to understand what is happening to his table when data transformations are applied.  

## Current status quo
Currently, Salim can sort his dataset based on data in a column. He selects how he wants the sorting to be applied and then the entire rows are moved up and down in the data table. This is how sorting is expected to work. 

![Lumen sorting](https://user-images.githubusercontent.com/12456965/64406582-73e19400-d082-11e9-83c4-79acef56c932.gif)

Salime can now click on **another** column to sort that one and Lumen applies the sorting again. As shown in the example below, the first sorting stays put but the second one even though seemingly applied does not affect the dataset. 

![Lumen sorting2](https://user-images.githubusercontent.com/12456965/64406641-9a9fca80-d082-11e9-85cb-a2add2284af2.gif)

# Problem or idea

When discussing improvements for the sorting UI @Kiarii brought up a good point about keeping sorting to one column only: https://github.com/akvo/akvo-lumen/issues/867#issuecomment-528407804

> Taking back some of the current sorting model and thinking, I think sorting by more than column breaks the row data-relation mental model that a table gives - that each row reference a specific datapoint - in which case the grid/table loses its meaning. Technically this is doable and is what the current implmentation does.

> Sorting on a table I think should only apply on one column at a time, as long as the data-relations is to be maintained. This would mean that if a column sort has been applied to some column, applying a sort on another column (undoes the first sort and) takes over the sort..

**Current use of sorting:** 
* August - 15 events out of total 265 transformation events 
* July - 3 events out of total 257 transformation events 
* June - 8 events out of total 248 transformation events 
* May - 19 events out of total 625 transformation events
* April - 6 events out of total 161 transformation events 

I do not know if any user has tried to apply sort on more than one column for the same dataset. We never received any issues about it nor feedback. 

## Conclude: 
* the implementation allows applying sort on more than one column but actually only works for one column what can confuse Salim - see test dataset: https://lumen.akvotest.org/dataset/5d71ffb8-f523-474e-9e38-9e6c77048d05
* we overall aim to make it easy to work with data, thus avoid confusion 
* sorting is used but not as heavily so changes should not affect many users 

# Solution 
The idea is to limit sorting to only one column. If Salim selects a second column to sort, then sorting is automatically removed from the first column and applied on the second one

# Next steps 
* discuss feasibility with the team 
* decide on a solution

**Comment by Kiarii** [comment]
To add to the discussion, I had a call with @kardan on multi-col sorting, which is a bit awkward because every other sort has to respect the one before it i.e. subsequent sorts will present data as if it is not sorted. My thinking is that such an approach is not useful when looking at a large dataset; we practiced on a 6col, 5rows where all the data was in view, but even when you have a secondary sort, or a tertiary or even more, it is not clear what purpose these other ones serve. I am proposing that we do a single sort at a go, in which case, each subsequent sort undoes/overrides the previous one, and only consider anything beyond upon user request and research

**Comment by Kiarii** [comment]
Proposing to close this issue for now; 
I talked to Molo and found that a multi-col sorting is a useful feature when performing data cleaning - which atm lumen does not support - a direction that i think we are aiming at, so the functionality will be useful in the future.
Molo gave the example of working with a farmers' dataset where an analyst might be interested in i) a specific enumerator's submission, ii) on a specific data collection window, iii) for a specific village or similar, which in Lumen may only be achievable via mult-col sorting. Optimally he mentioned that a sort should work along a filter..
