### ISSUE TITLE
Cache Keycloak user ids

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2307]
# Context
While migrating to Auth0 we will for a migration time use the Keyclak API to get the authorization information.

# Problem or idea
The problem is that we will increase our usage of Keycloak by hitting its API more frequently. Earlier we used the information stored in the users JWT claims.

# Solution or next step
We should try and cache certain things like Keycloak user-id calls since these will not change over time. However, we do need to be delicate and not assume that any authorization related data will not change.

**Comment by tangrammer** [comment]
Maybe we could take same approach https://github.com/clojure/core.cache/wiki/LRU as we did here https://github.com/akvo/akvo-lumen/blob/af0a1fb077e3b554a057a0edff27f2baf13ef0f6/backend/src/akvo/lumen/component/keycloak.clj#L403

**Comment by tangrammer** [comment]
tested in dark-prod
