### ISSUE TITLE
Translate Lumen to the same languages as Flow is

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2314]
# Context 

## Why do we create this issue 
Our goal is to have Flow and Lumen as one product. Flow and Lumen provide a simple way to work with data at scale. To reach this goal we started with removing the data gaps and simplifying the overlaps across the two.

## Current status quo
Currently, Lumen is available in English, French and Spanish. Flow is available in English, French, Spanish, and Bahasa Indonesia, Portuguese and Vietnamese. 

# Opportunity 
Once all Flow users can use both products we should unify the languages we provide the functionalities in. This means: 
* Translating Lumen to the missing 3 languages (Bahasa Indonesia, Portuguese and Vietnamese)
* If one language is selected in Flow this should trickle down to Lumen functionalities. 

## How will this benefit our users 
If we solve the above-mentioned problems we assume these benefits to users:
* ability to use all features in their languages
* unified experience across all Flow and Lumen features 
* for those who will provide the translations we will also create more interest in Lumen 

## How will this benefit Akvo 
If we solve the above-mentioned problems we assume these benefits to Akvo:
* A more visible connection between Flow and Lumen enforcing our strategy and goals
* Easier to sell to large organisations/governments/programmes as they can use the tools in their languages 

## What risks we need to keep in mind
The biggest risk is keeping the translations up to date. This is a risk we already have today. For languages, the team speaks we keep the translations relatively well up to date. For the languages the partners requested and provided us with the translations, the missing strings are in English. This case requires to contact the partner again to request the update, so it is intense in terms of coordination. On the other hand, this collaboration also keeps the partnership alive and triggers interest in the new functionalities and product changes.

**Comment by tangrammer** [comment]
this relates to https://github.com/akvo/akvo-lumen/issues/2646

**Comment by janagombitova** [comment]
We should pick up the three missing translations: Bahasa, Portuguese and Vietnamese on a **on demand** basis. Thus once a partner requests it and agrees to help us with the translations, we will make them happen
