### ISSUE TITLE
Updating datasets 'reverses' change datatype transformation

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2347]
I am currently testing dark-demo, using this dataset: https://dark-demo.akvolumen.org/dataset/5d493e8a-2913-4b30-95d3-ee2c5a56fe47

<img width="1276" alt="Screen Shot 2019-09-24 at 12 36 25" src="https://user-images.githubusercontent.com/12456965/65504855-2cebff00-dec8-11e9-9cda-b96f70a0909e.png">

Steps I took today: 
1. Extracted a new column from a Caddisfly question - MPN (2nd last)
1. Changed the datatype for that MPN column (2nd last) from TEXT to NUM
1. Created a new category column based on the MPN column with 3 ranges
1. Updated the dataset

The update worked, as new submissions came in. But my change on the datatype is now gone and my category column is off as the datatype it was based on is not NUM anymore, but TEXT again

**Comment by janagombitova** [comment]
Hmm trying to reproduce it on other datasets and all works fine. Will comment again if I find more.

**Comment by janagombitova** [comment]
reopening the issue as @tangrammer managed to find something weird. The issue and description might change based on Juan's findings

**Comment by tangrammer** [comment]
changes successfully tested after #2351 
https://lumen.akvotest.org/dataset/5d8a3df2-4341-4c23-91f2-d7e8d62245ca

**Comment by tangrammer** [comment]
changes promoted to dark-prod and successfully tested with https://dark-demo.akvolumen.org/dataset/5d493e8a-2913-4b30-95d3-ee2c5a56fe47

**Comment by tangrammer** [comment]
@janagombitova IMO we can close the issue now
