### ISSUE TITLE
Clean up the viz editor

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#2359]
### Context
A number of elements on the viz editor are half baked or not optimally implemented - the user ends up having to read extra, often redundant text or looking at over emphasized/unnecessary elements - which means a slower viz-building workflow
This need not be done now, but I document them just so we don't forget about them 

#### Clearly indicate "Advanced" state; Open/Closed
- atm its not clear when this is open or closed since there is no visual indication whatsoever
<img width="725" alt="Screenshot 2019-09-26 at 16 37 06" src="https://user-images.githubusercontent.com/12692444/65692803-e9d28d00-e07b-11e9-9b4a-12132bdbfcde.png">

#### Clean up the sort picker to min visual distraction
- remove selected bg and style the font instead
- elongate the picker border to the field length and distribute options evenly 
<img width="680" alt="Screenshot 2019-09-26 at 16 27 21" src="https://user-images.githubusercontent.com/12692444/65692024-8b58df00-e07a-11e9-896a-75bef9e919e9.png">

#### Make it easy to view and pick short-list items 
for option list with 2 - 5 options consider making them visible without the need for scrolling or opening drop-down menus. This applies for instance to
- the legend placement picker
<img width="364" alt="Screenshot 2019-09-26 at 16 35 06" src="https://user-images.githubusercontent.com/12692444/65692686-a415c480-e07b-11e9-88f6-f07405254e39.png">

- Aggregation method picker
In addition to flattening the list, we could abbreviate text items (providing full text on mouse-overs) to make it that much easier to view and select applicable options 
<img width="368" alt="Screenshot 2019-09-26 at 16 48 17" src="https://user-images.githubusercontent.com/12692444/65693755-7762ac80-e07d-11e9-859b-1779e6f8b7b6.png">

#### Clean up the redundant and repetitive language on the UI
- remove [:] from field labels
- remove "type" from "Aggregation type"
- there are more items that go under this list but I do not list them for now..

#### FLIP X and Y axis 
The X has far more settings and it makes sense to keep the Y easily available atop. The proposed arrangement is sth notable with other viz editors

#### Remove [x] from mandatory fields
Remove the [X] icon from fields that cannot be left empty in respective fields e.g. for bar charts, the X-axis;
<img width="709" alt="Screenshot 2019-09-30 at 10 50 19" src="https://user-images.githubusercontent.com/12692444/65859109-21894f80-e370-11e9-895d-efd43868bd6c.png">

**Comment by Kiarii** [comment]
ideas on further decluttering the viz editor while presenting more content compactly, and glanceably;
<img width="1180" alt="Screenshot 2019-10-01 at 15 47 58" src="https://user-images.githubusercontent.com/12692444/65963227-fdf30180-e462-11e9-8ac9-364a8fa5782d.png">

**Comment by janagombitova** [comment]
@Kiarii all good ideas. One that is not clear to me was flipping the x and y axis. Which should be first? 

Another thing to reconsider is the order of items. For example: Shouldn't the axis label be before the legend settings, as you first select your column and thus can also simplify the label and then handle the legend?

**Comment by Kiarii** [comment]
> all good ideas
some are half baked so they might need refining before implementation..

> the x and y axis. Which should be first?
It seems to me the Y should be, it is the easiest to set up;

> Another thing to reconsider is the order of items. For example: Shouldn't the axis label be before the legend settings, as you first select your column and thus can also simplify the label and then handle the legend?
Yes, that is a good point, I hadn't really poked the 'advanced settings there'

**Comment by janagombitova** [comment]
@Kiarii should we use this issue to also look at the **Bar chart** editor to move the items that are more for chart settings away from the axes?

**Comment by Kiarii** [comment]
@janagombitova that is indeed a good suggestion

**Comment by Kiarii** [comment]
more ideas

![image](https://user-images.githubusercontent.com/12692444/66998584-2d4d7380-f0dd-11e9-9551-be46e11b8e10.png)

**Comment by Kiarii** [comment]
The following mockups illustrate improvements that have been agreed upon with @janagombitova, touching upon the separation of [data] and [options] in viz editor: https://invis.io/8QUMVLBMRSE#/391333037_0-0_New_Viz_-_ES

Footnotes:
#### share + export: 
- this we can combine; export can be a 3rd option under share; Download [as PNG] [as PDF] 
#### New viz
- given that the user might need to create a bunch of visualizations, we should consider the ability to do so from within a visualization; to save them the detour of having to a) go back to the lib b) click +Viz, in order to c) end back in the viz editor. 
#### Form fields
- lets round off form fields to make them easy on the eye, we have lots of this in the viz editor..
#### Font
- on section headers, field labels, field texts, etc font size and weight need some adjustments to drive user focus appropriately.. Loic should give more input here.
#### Padding
- Padding also needs to be adjusted for the various components
#### iconography
- where icons are used, e.g. toggles, sort etc, use proper iconography - supported by browsers, consult Loic on how to approach this, atm it appears that we have used code-generated/built shapes :(
- all icons should have mouseover texts so the user can always confirm underlying actions if they are unsure
#### dropdown without caret (& design hypothesis)
- removing the caret reduces visual overcrowding..
- this will not affect usability from dropdown fields which actually double as text input fields > to support suggestive typing when picking options..
- there are no iconography to communicate both dropdown and typing for form fields. In our case when a field is activated, both the cursor and dropdown options come into view so the user is aware of the options available for them
- field labels are kept - so the user is always aware that they need to take an action that by default implies typing.. which is okay
- this also makes col name truncations - [...] - clear

#### [x] in dropdown/text input form fields

- Remove from mandatory fields! Eg. for a bar chart, the Bucket field is mandatory, the user cannot build a bar chart without it; therefore the field do not need [x] the user upon choosing a col can change it but cannot leave the field empty.. 
- the [x] will however be used to remove cols that are indeed removable from the visualization engine; e.g. as in the selection of multiple cols in a barchart. The [x] will however be placed outside the form field as its purpose is not to clear the selection but the field itself

#### learning as we go
We start with these hypotheses and refine as we learn. NB for Maps, we have decided to postpone refinements there.. but of course if there is time to look at them during this exercise, we can do so..
