### ISSUE TITLE
Refactor client error pages

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2360]
At the moment we're using different markup for different error states like, not authorized, or email not verified. We should refactor to reuse and align fully with Flow.

## Not authorized
http://t2.lumen.local:3030/ (make sure to not have access to t2)

## Email not verified
http://t1.lumen.local:3030/auth0_callback#error=unauthorized&error_description=EMAIL_VERIFIED_ERROR

**Comment by tangrammer** [comment]
email verified error page seems good

<img width="843" alt="Screen Shot 2019-10-07 at 10 22 32" src="https://user-images.githubusercontent.com/731829/66295789-63744180-e8ec-11e9-9744-6347370546f6.png">

**Comment by tangrammer** [comment]
Not authorized also seems good 

<img width="848" alt="Screen Shot 2019-10-07 at 10 32 12" src="https://user-images.githubusercontent.com/731829/66296396-c0bcc280-e8ed-11e9-85ee-625322ba2086.png">
