### ISSUE TITLE
Limit the number of visualisations we show in the dashboard editor side panel 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2369]
# Context 
## Why do we have this issue? 
We aim to have at least all Flow users using Lumen, which means scale. Thus Lumen needs to be able to handle many users, creating many visualisations and many dashboards with many visualisations and work smoothly and fast. 

## Problem
Yesterday we found an issue in Lumen that caused the loading to decrease rapidly in Lumen (overall). After some investigation, we saw that we have a dashboard with about 80 visualisations on the Lumen tenant that caused the overall performance decrease. Secondly, there are over 700 visualisations on this tenant. 

The way we load the visualisations in the editor in the dashboard and how we load visualisations in the Lumen dashboard editor seem to cause slower performance eventually all across Lumen. 

## Current status quo

Today we show a side panel with **all** visualisations on that tenant. They are not organised (in a user-visible way). We show them all and Salim scrolls through the list and clicks on the visualisations he wants to add to the dashboard. 

![Screen Shot 2019-10-02 at 15.00.35.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/c1d2b712-619f-438f-97a0-2a645da78d2b)

# Opportunity 
When looking at this loading issue we also asked ourselves why would Salim need to see all the visualisations in the editor in the first place? He most likely will add the visualisations he worked on recently. 

The suggestion is to: 
* organise the visualisations in the side panel by modification date (most recently modified -  changed, created - on the top) 
* show 10 visualisations and then add the option to `Show more` 
* once Salim clicks on `Show more` load the next 10

## What are we trying to solve? 
* performance issue 
* user experience by showing Salim the most recent visualisations that he most likely will work with when creating a dashboard. 

## What risks we need to keep in mind?
* the number 10 is a guess, we can consider more if Lumen can handle the load and it does not involve too much scrolling --> should confirm and decide with testing 
* does this solve the issue with loading the visualisations in the opened dashboard? 

# Related issue 
With this improvement, we also propose to change the search bar called 'Filter list by title' to a dropdown with the list of datasets and title 'Filter by dataset'. See issue

**Comment by kardan** [comment]
👍

**Comment by kardan** [comment]
The number of visualizations are not an issue any longer.
