### ISSUE TITLE
Dashboard editor should do one request to get the dashboard

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2374]
In the Dashboard editor, we do one request per thing in the dashboard. We should rework this and use the same approach we do in shared dashboards. Make one request that returns the necessary data.

Making one request per thing in Dashboard becomes an issue when a dashboard contains a lot of things. We have seen examples of Dashboards with 70 things and it makes no sense to have 70 concurrent requests coming into the backend when we could solve it with one.

**Comment by tangrammer** [comment]
tested in live prod
