### ISSUE TITLE
Review Lumen performance on Dashboards with large number of items

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2376]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
## Unfiltered 
```sql
EXPLAIN ANALYZE SELECT id, dataset_id as "datasetId", "name", "type" as "visualisationType", spec, created, modified, author FROM visualisation
```

QUERY PLAN
--
Seq Scan on visualisation (cost=0.00..139.18 rows=918 width=896) (actual time=0.010..0.965 rows=879 loops=1)
Planning time: 0.647 ms
Execution time: 1.079 ms


## Filtered 
```sql
EXPLAIN ANALYZE SELECT id,
       dataset_id as "datasetId",
       "name", "type" as "visualisationType",
       spec,
       created,
       modified,
       (SELECT jsonb_object_agg(key, value) FROM jsonb_each(author) WHERE key IN ('name', 'given_name', 'family_name', 'email')) AS "author"
FROM visualisation;
```

QUERY PLAN
--
Seq Scan on visualisation (cost=0.00..1539.13 rows=918 width=765) (actual time=0.137..22.420 rows=879 loops=1)
SubPlan 1
-> Aggregate (cost=1.51..1.52 rows=1 width=32) (actual time=0.024..0.024 rows=1 loops=879)
-> Function Scan on jsonb_each (cost=0.00..1.50 rows=4 width=64) (actual time=0.020..0.021 rows=1 loops=879)
Filter: (key = ANY ('{name,given_name,family_name,email}'::text[]))
Rows Removed by Filter: 17
Planning time: 0.964 ms
Execution time: 22.699 ms

**Comment by dlebrero** [comment]
For the authz, we don't really need the author, so maybe we can also have two different queries to the DB.

**Comment by kardan** [comment]
@dlebrero yes, we're already doing that. Have a "slim" query for the auth https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/lib/visualisation.sql#L17
