### ISSUE TITLE
Auth Issue for Tech Consultancy Team

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-lumen#2419]
# Context
Hi @tangrammer @kardan 

We have some projects that required to download Akvo Lumen API endpoints for our partner. (e.g. [Chart Generator](https://github.com/akvo/akvo-tech-consultancy/blob/master/lumen-api/lumen-echarts-generator/figures/Get%20Visualisation%20Json.ipynb) and [Lumen Trigger Update](https://github.com/akvo/akvo-tech-consultancy/tree/master/lumen-api/lumen-trigger-update)). 

# Problem or idea
All of our Application doesn't work since we moved to the new auth method so we cannot access these all the endpoints. 

# Next step

Please give us an example of how to get all these API endpoints with the new auth method?

Gracias,

**Comment by tangrammer** [comment]
Created a new client app 'akvo-tech-consultancy' in akvofoundation.eu.auth0.com with password grant and same setttings  as `akvo` client app.

**Comment by kardan** [comment]
@tangrammer @dedenbangkit Is this solved?
