### ISSUE TITLE
Extracting Caddisfly photos does not give right url

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2426]
I was looking at a support request that came in and I replicated the issue. The problem is: Photo urls coming from Flow look like this: https://akvoflow-156.s3.amazonaws.com/images/f91af1cc-92c2-4a6e-b94e-9f0f69bb5e1b.jpg but if extracted from a multiple data type the url does not render correctly. 

Each Flow photo url holds the Flow instance ID `akvoflow-156` the photos belongs to. 

When capturing Caddislfy data, some tests also hold photos. These have similar urls, like: https://akvoflow-156.s3.amazonaws.com/images/47023137-7245-4d19-a09c-4894b8b219bf.jpg

In Lumen to work with Caddisfly data, Salim has to use the `extract multiple values` option. Here he can choose to extract a photo too. However, here is where the bug is. Instead of the url pointing to the instance (in our case akvoflow-156 it points to uat1). 

The example data set is here: https://akvointernal.akvolumen.org/dataset/5dc5854f-c4a0-4e6e-b2bc-952b8147f294. I extracted the Caddisfly photos and indeed in Lumen they point to UAT1 and not to akvoflow-156. But when I check the data on Flow, they point to akvoflow-156.

**Comment by tangrammer** [comment]
IMO it could be closed now
