### ISSUE TITLE
Horizontal bars axis in wrong order when stacking applied 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2433]
When we create a bar chart we can change its orientation to 'horizontal

![Screen Shot 2019-11-12 at 16.39.19.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/a1c44609-8da1-4d4f-a387-16f7c1c7acc6)' 

However, once stacking/splitting is applied (either via sub-buckets or the to-be-released feature of multiple y-axis columns) the now horizontal y-axis flips order with 0 no longer at the cross point with x-axis.

![Screen Shot 2019-11-12 at 16.38.40.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/945d9ac3-bf2f-42eb-aa2d-d31833b793e0)
![Screen Shot 2019-11-12 at 16.39.01.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/7ab526bf-b4ac-40e7-8d77-57d255677d96)
Steps to reproduce: 
1. Create a bar chart
2. Change to horizontal
3. Add a stacking subbucket --> see the now horizontal y-axis flip

**Comment by tangrammer** [comment]
released and tested on live prod
