### ISSUE TITLE
Derive column - javascript not working with specific case

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2444]
When Salim wants to derive a new column using javascript we indicate when the expression is not correct and disable the `Derive` button. This way Salim knows something is off. 

![Screen Shot 2019-11-18 at 16.00.14.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/36c132ce-bfe2-4594-ae52-607160b59784)

Irene reported a case, where she wanted to create a new column using the Derive column - javascript transformation: 
1. she put in her code and there was no warning from Lumen
2. she hit `Derive`
3. she saw the confirmation in green that the Transformation was applied but there was no column. 

In console she got this error indicating that the transformation was not valid. 
![Screen Shot 2019-11-18 at 13.48.02.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/7abe06dc-56bb-455d-b863-5321647d8831)

The issue: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-274355-from-irene-at-akvo-dot-org
She tried to apply the transformation on this dataset: https://footballforwater.akvolumen.org/dataset/5dc143c0-e885-4bea-a05d-c359cd4788fb
The transformation: `row["functionality_water"] == "Partially functioning" ? "2. Partially functioning" :
row["functionality_water"] == "Functioning" ? "1. Functioning" :
row["functionality_water"] == "There is no water facility installed by program yet" ? "4. There is no water facility installed by program yet" :
row["functionality_water"] == "Not functioning" ? "3. Not functioning" :
""`

Can we check why the transformation failed and why Lumen did not give an error (why did Lumen allow to proceed with the derivation)?

**Comment by tangrammer** [comment]
Javascript code can't contain the word `function` inside ... in this code we have: "`function`ality_water"

Investigating now why we don't have a proper error response here

**Comment by janagombitova** [comment]
Perfect! We should indeed indicate in the UI that you cannot use the word function and not allow to click on the Derive button in such cases.
