### ISSUE TITLE
Make use of question groups in question dropdowns

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2451]
In issue #2437 we added Flow question groups to the Lumen data view. This means, that Salim sees how the columns are grouped. The implementation is basic to solve the mentioned issue of handling duplicated column header in derive column transformation. 

This issue wants to see how we can take the information on question groups further. 

Across Lumen we have places where Salim works with questions. He selects them in transformations, in visualisations, in dashboard filters. We know Flow datasets can have hundreds of columns so working with the question/column dropdowns can be painful. The question/column groups help to break down the dataset structure and keep things organised. 

Now that Lumen has the data, can we make more use of them? Can they be implemented in the dropdowns somehow?

**Comment by tangrammer** [comment]
https://github.com/akvo/akvo-lumen/pull/2454
