### ISSUE TITLE
Don't hit keycloak-authorization-service if user exists in the cache

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2489]
# Context
We get 500 status response trying to edit dashboards with many vizs, thus lumen tries to auth each one through keycloak/allowed-paths
https://github.com/akvo/akvo-lumen/blob/69b171ee712cec7ff795a8972fff95b9b9ad3432/backend/src/akvo/lumen/component/keycloak.clj#L445-L456

Cache is working fine but ... we always call request-header function  
https://github.com/akvo/akvo-lumen/blob/69b171ee712cec7ff795a8972fff95b9b9ad3432/backend/src/akvo/lumen/component/keycloak.clj#L453

so at the end we reach the http.client connection manager limits getting a `Timeout waiting for connection from pool`

# Problem or idea
https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=akvo-lumen&authuser=1&minLogLevel=0&expandAll=false&timestamp=2019-12-19T14%3A36%3A43.021000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22akvo-lumen%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.pod_name%3D%22lumen-blue-749d954957-g8xhd%22%0Aresource.labels.container_name%3D%22lumen-backend%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Atimestamp%3D%222019-12-19T14%3A35%3A08.272994021Z%22%0AinsertId%3D%22rylxs3a5j4iqddzhk%22&scrollTimestamp=2019-12-19T14%3A35%3A08.272994021Z

# Solution or next step
Avoid keycloak call until necessary

**Comment by dlebrero** [comment]
Even if this change is ok, note that the issue is really on how we actually load the visualisations, which is causing a "stampede" to the backend, which is not scalable here, neither it was on the authorisation side. 

@kardan has been working on fixing how we load the dashboards.

**Comment by tangrammer** [comment]
tested here 
https://lumen.akvotest.org/dashboard/5dfbb67f-6c2f-4f6c-bdaf-120110821132

**Comment by tangrammer** [comment]
and here
https://demo.akvolumen.org/dashboard/5dfbb7ff-e627-4cfc-afcf-c87021d9ed41
and here
https://footballforwater.akvolumen.org/dashboard/5df0cb78-8436-4985-b9e2-7de48fb9a8c8

**Comment by tangrammer** [comment]
@muloem fixed :)
