### ISSUE TITLE
CI don't capture E2E tests logs

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2500]
# Context
In out CI build pipeline we run the end to end tests (e2e). In this step among other things, we enforce Clojure specs checks.

# Problem or idea
In SemaphoreCI the logs of the e2e tests are lost. Making any spec problem really difficult to figure out.
https://akvo.semaphoreci.com/jobs/32ef441b-cae8-4019-bc49-02c2fc9e8e80#L443

# Solution or next step
Fix the issue..

## Ref
https://github.com/SeleniumHQ/docker-selenium/issues/87
https://forums.balena.io/t/dbus-failed-to-connect-to-socket-host-run-dbus-system/3107/14

**Comment by tangrammer** [comment]
@kardan IMO this could be closed by https://github.com/akvo/akvo-lumen/pull/2507
