### ISSUE TITLE
Scatter visualization returns unstable/random results 

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2537]
# Context
https://flowhelp.reamaze.com/admin/conversations/lumen-bug

# Problem or idea
Reproducible example:
just reload this vis to get random results
https://akvointernal.akvolumen.org/visualisation/5e342bb6-1a91-4b9d-b5f2-c2ad6e267ec5

<img width="775" alt="Screenshot 2020-02-03 at 11 57 13" src="https://user-images.githubusercontent.com/731829/73647778-89cca280-467c-11ea-87a9-4d4d2a1025b7.png">
<img width="776" alt="Screenshot 2020-02-03 at 11 57 04" src="https://user-images.githubusercontent.com/731829/73647779-89cca280-467c-11ea-9c75-f40dd860e12a.png">
<img width="801" alt="Screenshot 2020-02-03 at 11 56 57" src="https://user-images.githubusercontent.com/731829/73647780-89cca280-467c-11ea-8fbf-b365520c9d91.png">

After analyzing different request payloads the visualization specification keeps stable so it's not related to that part

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
looking into the scatter aggregation query details I realised that we are using a `max-points:2500` default value with an `ORDER BY random()` Postgres function.
These 2 options working together make indeterministic the query/graph result on datasets with rows above 2500 rows as the example provided in the previous issue description

Also found that this approach is the same as we have with `line` and `bubble` graphs

@muloem what do think we should proceed?

**Comment by janagombitova** [comment]
Considering our partner datasets will have more than 2500 rows, this needs to be handled to ensure partners can rely on the visualisations.

**Comment by iperdomo** [comment]
>  Does there need to be the limit?

Yes. We need to define a limit. Also make sure that we notify the user if a dataset backing the visualization is larger than the defined limit.

**Comment by iperdomo** [comment]
Just to clarify my previous comment, even if we define that we support 1M rows, we need to define and enforce that limit. It can't be _boundless_.

**Comment by janagombitova** [comment]
500k rows, would that we a good boundary? We do not have a dataset this big, yet so it gives us a buffer.

**Comment by iperdomo** [comment]
Checking in local development the count **match** but the result of 2 runs is different:

```
lumen_tenant_1=> select count(*) from ds_35433b39_23ed_48f6_8180_f74b29035b3e;
 count 
-------
  5000
(1 row)

lumen_tenant_1=> SELECT n_live_tup as estimate FROM pg_stat_all_tables WHERE relname = 'ds_35433b39_23ed_48f6_8180_f74b29035b3e';
 estimate 
----------
     5000
(1 row)

SELECT
  (reltuples/relpages) * (
    pg_relation_size('ds_35433b39_23ed_48f6_8180_f74b29035b3e') /
    (current_setting('block_size')::integer)
  )
  FROM pg_class where relname = 'ds_35433b39_23ed_48f6_8180_f74b29035b3e';
 ?column? 
----------
     5000
(1 row)

```

![sales-viz](https://user-images.githubusercontent.com/178474/80560684-34d1cb80-89e2-11ea-8fb7-031c461104a3.png)

The sample data is the 5K rows from here - http://eforexcel.com/wp/downloads-18-sample-csv-files-data-sets-for-testing-sales/

**Comment by iperdomo** [comment]
We know now that we need to _sample_ a large dataset. And we found that PG supports a `TABLESAMPLE` [1] with a stable random seed produces the same result [2].

My proposal is to fix the reproducibility part by moving from `ORDER random()` to `TABLESAMPLE` with a stable seed. Because we want some type of _randomness_ in that seed, we could use the `created` date/time from the dataset converted to a long value (timestamp). It's _stable_ per dataset.

[1] https://www.postgresql.org/docs/11/sql-select.html
[2] https://gist.github.com/iperdomo/8f1dfae5f353f8430364d4cc5f2a65c0

**Comment by tangrammer** [comment]
After asking to Irene and Carmen if a scatter/bubble/line with more than 2,5K points is useful and  get NO as the answer, we agreed on don't sample the dataset and don't' return chart results if points are higher than this 2,5K limit **but** we need to show a UI message with a warning notice that says something like "Results are bigger than 2,5K so you need to use grouping facilities to reduce them"

**Comment by janagombitova** [comment]
After talking with Juan, I now understand the approach. With most of the charts, we do not draw the chart until "good" data and proper grouping (aggregations) is selected. 

For example, with **bar charts** we draw the bars right after Salim selects the bucket column (x-axis). If Salim selects a column that has too many different variables, Lumen does not draw the chart and shows an error: `Bad request`. It is not the best error message, but it shows the user that the column she selected does not work and she needs to select a different one. 

<img width="1238" alt="Screen Shot 2020-05-04 at 10 46 40" src="https://user-images.githubusercontent.com/12456965/80949579-8f10c900-8df4-11ea-8818-41745a5f7dcd.png">

If I make the same selection with **bubble charts** we do draw the chart (showing the 2,5k random data). Despite, this is being a good approach to making the visualisations work, it does not represent the actual dataset and that is why we will NOT render the chart and show a warning message to the users (as we do with bars in the example above). 

<img width="1240" alt="Screen Shot 2020-05-04 at 10 48 17" src="https://user-images.githubusercontent.com/12456965/80949806-00e91280-8df5-11ea-8d66-832155b79463.png">

For the error message, I would suggest the text to be: `Results are more than 2,500. Please select another column.`

**Comment by tangrammer** [comment]
Notification sent

**Comment by janagombitova** [comment]
As far as I can tell the fix solved the problem we were addressing. 👍 

I, however, am not sure the scatter plots work well in general and the visualisation editor elements are correct, but I need to test it out more and consult with Carmen and Irene. I will create a separate issue if we need to make changes.
