### ISSUE TITLE
Fully upgrade react to 16.8.0 (hooks version)

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2569]
# Context
We need to fully upgrade client code to use current react 16.8.0 version. That means to follow new lifecycle approach and remove the UNSAFE_  prefixes already added for compatibility 

Also remove warnings
<img width="1077" alt="Screenshot 2020-02-19 at 09 25 36" src="https://user-images.githubusercontent.com/731829/74815691-ff31a780-52f9-11ea-88eb-2b6674d4dcfe.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
@tangrammer considering we flipped a lot of changes to this to production today, is there more to be done here or can we close the issue?

**Comment by tangrammer** [comment]
still we need to take care of migrating 
`react-dom.development.js?9f84:89 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`
