### ISSUE TITLE
akvo.lumen.postgres.filter/sql-str fails with empty filters

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2575]
# Context

https://github.com/akvo/akvo-lumen/blob/74c792f829abadaec82ea48bda1b8dd8031acb7e/backend/src/akvo/lumen/postgres/filter.clj#L102

# Problem or idea
relates #1656 work consequences 

# Solution or next step
https://github.com/akvo/akvo-lumen/commit/3fb00beb12707ffd55e8ffce4d8cfee289e5a9a7
https://github.com/akvo/akvo-lumen/commit/f9cc8fc17a2a9ff9985491ac65d8db8a95c6e261

**Comment by kardan** [comment]
Fixed quickly!
