### ISSUE TITLE
Label cut of in donut chart viz

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2593]
# Context
https://akvoo.reamaze.com/admin/conversations/lumen-labels-cut-of-in-visuals?action=show&controller=admin%2Fconversations&id=lumen-labels-cut-of-in-visuals

![Screenshot_25_02_2020__10_07](https://user-images.githubusercontent.com/731829/75696180-73c9f600-5cab-11ea-94a8-06f12db7c3c4.jpg)

- bar chart approach
<img width="749" alt="Screenshot 2020-03-02 at 17 26 23" src="https://user-images.githubusercontent.com/731829/75696189-77f61380-5cab-11ea-93e6-e2f725448be7.png">

- following same bar chart approach
<img width="380" alt="Screenshot 2020-03-02 at 17 27 52" src="https://user-images.githubusercontent.com/731829/75696218-86442f80-5cab-11ea-9045-889d84b4c47d.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
@muloem what do you think if we follow the same approach as we have with bar chart? ^^ see images attached in issue description

**Comment by muloem** [comment]
@tangrammer are we able to wrap the text into a box so that it all fits? and only cutoff after say 80 xters (or whatever you feel makes too cluttered)?

**Comment by tangrammer** [comment]
<img width="1131" alt="Screenshot 2020-03-05 at 13 23 26" src="https://user-images.githubusercontent.com/731829/75981377-aad71c00-5ee4-11ea-92b3-0e9c1ef913c2.png">
<img width="1280" alt="Screenshot 2020-03-05 at 13 23 51" src="https://user-images.githubusercontent.com/731829/75981383-ae6aa300-5ee4-11ea-875e-d1f83f4e0bba.png">

**Comment by tangrammer** [comment]
previous comment/changes affect only to viz not to dashbaord

**Comment by tangrammer** [comment]
BUT: Christien Bosman in Reamaze issue shares a dashboard image

**Comment by muloem** [comment]
We will put this issue on hold for now pending further study.  But the workaround is to rearrange the layout of the visualisations on the dashboard to create more room for the ones where the text is cut off and that way its possible to see the complete label.
