### ISSUE TITLE
Provide a way for gather user feedback

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2596]
# Context
We're already capturing _exceptions_ in the client and server, but we want to collect _feedback_ and bugs/errors from the users.

# Solution or next step
Select and integrate a user feedback service in Lumen

**Comment by tangrammer** [comment]
we should keep plugin on shared dashboard and remove it from exporter version

**Comment by tangrammer** [comment]
same with vizs shared and exported

**Comment by tangrammer** [comment]
@iperdomo should we close this issue?
