### ISSUE TITLE
Show used datasets in dashboard filter dropdown

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2627]
# Context
With #1656 we added the option to add filters to Lumen dashboards. After creating a dashboard with visualisations, Salim can also add filters to it. Once added, when viewing the dashboard the user can filter out the data and the visualisations will update based on the value. 

Thus the dashboard filters and visualisations are based on the same dataset. If a visualisation does not come from the filter-dataset a '!' is indicated in the visualisation. 

# Problem
When Salim adds the dashboard filters he needs to select a dataset first. He can select from **all** datasets in the Library. But for the filters to actually work, he needs to choose the same dataset the visualisations are made from. This means, he needs to know which dataset to choose, what is hard as that is nowhere indicated in the visualisations. And if there are many datasets in the Library he will have to go through a full list.

# Idea 
Instead of expecting Salim to know which dataset to work with, can Lumen only provide him with the datasets that he can choose from when selecting the filter? These datasets would be the ones that are used for the visualisations in his dashboard. 

<img width="1258" alt="Screen Shot 2020-03-31 at 13 33 01" src="https://user-images.githubusercontent.com/12456965/78021846-3745f480-7354-11ea-8990-a829b2a289b6.png">

The benefit of this would be: 
* Salim not having to remember which dataset to choose --> less effort for him 
* Salim cannot choose a dataset that no visualisation is based on, thus Lumen ensuring the filters will always work 

# Next step
Is this possible? What do you think? @tangrammer and @Kiarii

**Comment by tangrammer** [comment]
changes deployed to live prod
