### ISSUE TITLE
Multiple dashboard filters do not work well 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2629]
# Context
Recently we added the option to add filters to Lumen dashboards (#2523). Salim can add filters that then the dashboard viewer will use to filter out the data in the visualisations to see only what he/she is interested in. Salim can add one filter to the dashboard or many. The viewer, let's call her Petra, can then filter out the visualisations based on one value or more. If she chooses more filters they filter out the data by the first AND second filter, etc. 
 
# Problem or idea

When testing the multiple filter behaviour I noticed it does not work well. After applying the 2nd filter it is as if the first filter is ignored and the second filter applied instead of using the AND rule. If I remove the second one, then none is taken into account. 

So it seems that the filter is applied (or un-applied) on which the user clicks, regardless if one is already selected.

Below is the example I used (a simple dataset to make it easy to see what should happen) 
Dataset original: https://docs.google.com/spreadsheets/d/1KT9D8DBUbPGXD3eGNjwi7fcQIcy6d9591ruFgcK-AkM/edit#gid=0
Dataset on Lumen: https://akvointernal.akvolumen.org/dataset/5e84673b-3937-4fa6-ac64-f76e92a78b69
Dashboard: https://akvointernal.akvolumen.org/s/5hLtOVjWPFI

![multi filters](https://user-images.githubusercontent.com/12456965/78144578-1521a480-7430-11ea-9add-8d0398d294f8.gif)

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
This bug only happens in shared dashboard, editor mode seems fine

**Comment by janagombitova** [comment]
Fixed and released. Well done 👍
