### ISSUE TITLE
Don't allow delete column transformation if there is a visualization using the column

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2634]
# Context
This came via a support request. A user deleted a column that was used in several visualizations and now a shared Dashboard is broken.

# Problem or idea
We don't restrict the "Delete column" transformation leading to surprising results.

* Create a new visualization and use a column of an existing dataset
* Verify that the visualization works properly
* Go to the dataset (source of the visualization) and *delete* the column used in the visualization - We don't restrict this operation
* Go back to the visualization and notice an error of non-existing column

Example:

![broken-viz](https://user-images.githubusercontent.com/178474/78523690-e14cd300-77d1-11ea-99cc-29cae8501f56.gif)

# Solution or next step
* Restrict the "Delete column" transformation when the column is used in visualization(s)

**Comment by janagombitova** [comment]
`Solution or next step
Restrict the "Delete column" transformation when the column is used in visualization(s)`

When not allowing to delete a column we should also inform Salim on why he is not allowed to remove this column. Thus saying you cannot delete this column, it is used in these visualisations.

**Comment by janagombitova** [comment]
Works for me 👍 Any specific reason @tangrammer why you did not close the issue after flipping production?

**Comment by tangrammer** [comment]
nope 😄
