### ISSUE TITLE
Redact the token info in the  source of the Dataset

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2635]
# Context
We're transferring sensitive information to the client. The `token` used for refreshing datasets should not be transferred to the client.

# Problem or idea
* Some sensitive data is sent to the client, we need to protect it

# Solution or next step
* Don't send `token` information in the `source` map of a Dataset

**Comment by tangrammer** [comment]
@iperdomo changes deployed to live prod and checked library and dataset endpoints responses ... no token(s) around now
