### ISSUE TITLE
Stop sending email in Sentry errors

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2636]
# Context
When a client error happens we log the problem in Sentry. Part of the _crash report_ includes the email of the user. We should protect it.

# Problem or idea
Instead of sending the plain text email address, we should protect it and send the ODIC `sub` claim. We still have a way of getting the email via the OIDC IdP.

# Solution or next step
Use JWT the claim `sub` instead of `email`

**Comment by valllllll2000** [comment]
After checking sentry logs for client, it appears we are sending: email, full name, keyclockId, link to profile picture... All these fields are private data according to GDPR and should not be sent if not needed. In my opinion, logs don't need them. I would remove the following fields: 
Email, name, admin, attributes, email_verified, family_name, firstName, given_name,
https://akvo.org/user_metadata, keycloakId, lastName, nickname, picture.
sub -> is filtered by Sentry so no point in sending it

Unless anyone confirms there is a valid reason to keep this data and why? Does it help the error tracking in some way?

**Comment by iperdomo** [comment]
> Unless anyone confirms there is a valid reason to keep this data and why? Does it help the error tracking in some way?

IMO we send all this data because is the default and we didn't bother into filtering. I don't think we have ever contacted a user directly based on a crash report, so I see very little value on sending all that data to Sentry.

**Comment by janagombitova** [comment]
Agree with @iperdomo. We do not use the emails for further error investigation, so we should not  send the personal data
