### ISSUE TITLE
Internationalise backend user messages

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2646]
# Context
https://github.com/akvo/akvo-lumen/pull/2642#discussion_r405938385
All the backend messages need to be translated in client side, we need to support Spanish and French

# Problem or idea
No current approach

# Solution or next step
TODO

**Comment by iperdomo** [comment]
An _easy_ solution is to respond a "Message Key" instead of a full error message. The client uses a translation map key -> Localized error message to show messages to the user. We use that approach in Flow.
