### ISSUE TITLE
Dashboard shared maps don't refresh values after dashboard filter changes

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2659]
# Context
https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-324588-from-andrew-at-akvo-dot-org
Only happens in shared dashboard maps. Doesn't happen with other vizs or dashboard versions

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
Relates to https://github.com/akvo/akvo-lumen/issues/2606

**Comment by tangrammer** [comment]
@janagombitova could we close this issue?

**Comment by janagombitova** [comment]
![map isse ](https://user-images.githubusercontent.com/12456965/80950827-e748ca80-8df6-11ea-98fb-4e3ad95eb2fc.gif)
Yes we can! All works very well now. Good job.
