### ISSUE TITLE
Import js modules relative to root src folder

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#266]
Should be able to configure webpack to support this.

**Comment by jonase** [comment]
I looked into this and it's quite easy to enable in webpack using

```
resolve: {
  root: path.resolve('./src'),
  extensions: ['', '.js', '.jsx']
}
```

But we also need to teach eslint to resolve correctly, this can be done with the packages `eslint-plugin-import` and `eslint-import-resolver-webpack` and adding `"import/resolver": "webpack"` to `.eslintrc.json`. 

The remaining problem is to get atom's eslint plugin to understand how to resolve modules as well, see https://github.com/AtomLinter/linter-eslint/issues/610

**Comment by kardan** [comment]
@gabemart what's the status on this one. Have work been done or something we should push for the future?

**Comment by finnfiddle** [comment]
@gabemart is the prupose of this one to let you do something like
```javascript
import MyClass from '/path/to/my/class';
```
instead of 
```javascript
import MyClass from '../../../my/class';
```
?
