### ISSUE TITLE
Don't send back data in PUT visualization payload

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2679]
# Context
Client-side send visualization `data` to the backend each time visualization spec changes. The problem is that `backend` doesn't use/need this `data` at this place but the network bandwidth is wasted

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
@tangrammer and @marvinkome is this issue done? Can we close it?

**Comment by tangrammer** [comment]
yep!
