### ISSUE TITLE
Allow to add dashboard filters based on NUM and DATE data

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2704]
# Context
*Why do we add this issue?*

In #1656 we introduced filters to Lumen dashboards. There you can see the full story. The main reason to add this issue is to further build upon the work done and provide a more substantial way of using Lumen dashboards and exploring data. 

# Problem or idea
*What is the cause?*

Today we support filtering on TEXT data type. Lumen also knows the datatypes DATE and NUM. These columns you cannot select when adding filters. 

But it can be interesting to see visualisations and compare insights also based on date of submission, age of kids in school, income of farmer, etc. 

# Solution or next step
*How could we solve it?*

* Support filtering for DATE and NUM values. 
* Possibly reuse how we handle defining the filters in visualisations (or category transformation)

**Comment by janagombitova** [comment]
Start with DATE

**Comment by tangrammer** [comment]
@janagombitova ,  do we assume that date filter means date range filter? so the user specifies 2 dates to filter results on that time frame?

**Comment by janagombitova** [comment]
@tangrammer Yes
