### ISSUE TITLE
Add question group navigation to dataset

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2705]
# Context
As part of the work to support RQGs in Lumen we decided to improve the dataset UI change how we display question groups. To make the change doable, small and iterative, this issue handles only one small piece of the puzzle and can be addressed and released independently from the other changes.

## Why do we have this issue? What are we trying to solve? 
* Make the UI accommodate large datasets better by providing a way to navigate large datasets (clicking on groups and seeing those columns only rather than an endless horizontal scroll) 
* Give users a better overview of the dataset structure 
* Follow the Flow form structure to create more coherence/consistency across the products 
* Support the assumption that users work with only subsets of the data at a time and even focus on one column only at the time 
* As RQGs need to be treated as a separate grid due to the different number of rows, but are still part of the one dataset, breaking the dataset view by question group allows us to accommodate the uniqueness of the RQGs 

## How will this benefit the users & Akvo?
* No one can really digest large dataset tables easily and yet we still prefer to look at data in a grid, the change breaks the grid into digestible pieces
* Can easily get a quick overview of their data
* Do not lose track of the column of interest due to the nature of scrolling 
* The easier we make it to get a grasp of a dataset to more interested users will be to further explore data and use Lumen 
* We assume that this change will increase the use of Flow datasets in Lumen (direct import) 

# Opportunity 

## Current status quo
We have the concept of question groups in Lumen datasets already. The questions groups are shown as the top row of the dataset. 

<img width="1266" alt="Screen Shot 2020-05-27 at 14 43 09" src="https://user-images.githubusercontent.com/12456965/83027432-6913c880-a030-11ea-8c8a-b44797d3bae1.png">

## The idea 

Move the question groups to a side panel (that the user can expand and hide). Each group is clickable and shows only the columns that belong to that group. 

![Screen Shot 2020-05-27 at 13.07.45.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/2fb1ba8d-cf38-4ed3-bfc8-70a5ab7428dd)
*Please ignore the blued out areas, these happened when taking a screengrab via invision* 

## Details to keep in mind/figure out 
* How will this change affect datasets that do not come from Flow and do not have the concept of question groups? Will they then only have the `Transformations` question group once created and what will show if they do not do any transformations on the dataset? 
* This change should not affect how Transformations work --> Some transformations, like split column, are done today in a side panel and the dataset view "moves" to the side to create space. This behaviour should not be affected by this change 

# Next steps 
* We will NOT implement the `search` option that is shown in the mockups just yet 
* This issue will NOT make the question groups expandable to show the list of columns and allow the user to click on those, just yet. 
* This issue is to ONLY: 
   * List the groups in the side panel, 
   * Break the grid to show the columns that belong to the group
   * By default land on the `Metadata`group selected 
   * Create the `Transformations` group once a new column is created via one of the transformations (as today)
   * `Transformations` group will remain the last one as it is today

**Comment by Kiarii** [comment]
> How will this change affect datasets that do not come from Flow and do not have the concept of question groups? Will they then only have the Transformations question group once created and what will show if they do not do any transformations on the dataset?

For consistency, we could say a dataset with no data or question group does not show the data / question group navigator (sidebar) but once a derived col is created, the dataset hence consist of two data groups (Ungrouped columns and derived columns, ..) which we can then show. 

On a side note, I am going by Derived columns to denote user created columns, instead of transformations, since Transformations are also doable in columns without the end result being a new col..

**Comment by janagombitova** [comment]
> On a side note, I am going by Derived columns to denote user created columns, instead of transformations, since Transformations are also doable in columns without the end result being a new col.. 

We call them Transformations because the new columns are a result of all the possible transformations under that action button. The "other" transformations that do not create a new column, happen on the column itself. I worry that calling the group `Derived columns` will create the expectation that only the columns created by the Derive column transformation show here, what is not the case.

**Comment by marvinkome** [comment]
Can I get the link to the Invision design? @Kiarii

**Comment by Kiarii** [comment]
@marvinkome here you go: https://invis.io/JHXDE589BYT#/417456348_0-0_DG_-_Metadata

**Comment by janagombitova** [comment]
![testing new UI](https://user-images.githubusercontent.com/12456965/85274016-a9733480-b47e-11ea-9612-2f46efe1ec29.gif)

I did an initial round of testing and noted a few "issues". Overall it works well and looks well, just a few things to tweak: 
* [ ] there is a "side bar" between the group navigation and the dataset that looks off 
* [ ] each group now has the `arrow` that usually indicates that you can open up the group and see the content in there. As we do not show the questions in the side bar, should we remove the arrow? (please check with @Kiarii) 
* [ ] you cannot close the side panel yourself. The arrow is the but clicking on it does not work

**Comment by janagombitova** [comment]
Extra question, but this might be for another issue --> after I do a transformation, should Lumen not bring me automagically to the Transformations groups? @Kiarii and @marvinkome , what do you think?

**Comment by Kiarii** [comment]
> each group now has the arrow that usually indicates that you can open up the group and see the content in there. As we do not show the questions in the side bar, should we remove the arrow? (please check with @Kiarii)

- yes for now lets drop that arrow

> should a RQG have the icon (arrows) in the side panel to indicate that this one is repeated? @Kiarii and @marvinkome what do you think?

- yes

**Comment by Kiarii** [comment]
col edit menu appears to crash the data view
![col edit issue](https://user-images.githubusercontent.com/12692444/85280419-c87ac200-b490-11ea-9554-6b436535d88e.gif)

**Comment by janagombitova** [comment]
@marvinkome I tested this morning and found a funny funny bug: When you click to see another data group, the side panel automatically closes. It should remain open

![testing new UI](https://user-images.githubusercontent.com/12456965/85669899-9bacf180-b6c0-11ea-9053-ce8336c4535c.gif)

**Comment by janagombitova** [comment]
One bug we found with @marvinkome 

Steps to reproduce: 
1. select a dataset
2. open the transformation log
3. close it
4. go to another data group
5. open the transformation log again

**Comment by janagombitova** [comment]
All seems to work well now! Well done @marvinkome 👍
