### ISSUE TITLE
Simplify dataset header 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2706]
# Context
As part of the work to support RQGs in Lumen we decided to improve the dataset UI. To make the change doable, small and iterative, this issue handles only one small piece of the puzzle and can be addressed and released independently from the other changes. 

## Why do we have this issue? What are we trying to solve? 

We want to simplify the UI of the dataset view to maximise the use of page real estate and make it more visually appealing.  

## How will this benefit the users and & Akvo? 
* gives users more space on the screen for the data

Plus as this change is part of a larger UI improvement of the dataset editor to support RQGs so we can assume that the entire change will: 
* make Lumen more attractive for Flow users that have RQG data and thus strengthen our value (as they can make use of the existing Lumen features as transformation log, easy transformations, custom visuals, direct Flow update, etc)
* by making it easy to work with RQG data we strengthen our market position as competitors do not have an easy way to handle the data 

# Opportunity 
## Current status quo
Currently, there is a lot of white space and unused real estate in the Lumen dataset view. The page starts with a row holding the dataset name, autosave status. The second row has the actions: Transformations, Visualisations, Row and Column count, Transformation log. 

<img width="1266" alt="Screen Shot 2020-05-27 at 14 43 09" src="https://user-images.githubusercontent.com/12456965/83020229-7a58d700-a028-11ea-890e-a5d8db72072e.png">

## The idea 
We are changing and improving the UI of datasets in Lumen and this issue aims to simplify the top page real estate. 

The idea is to combine the two rows into one as shown in this screen shot. The changes are: 
* Reverse the colour of the back arrow to black arrow and a white background
* Move the saved status under the dataset name 
* Move `Transform` action to the right
* Remove the `+` icon from the `Transform` action 
* Move `Visualise` to the right 
* Simplify the current `Create visualisation` action to `Visualise`
 * Hide the Row and Column count. @Kiarii will this be moved somewhere else (on a group level) 

<img width="1215" alt="Screen Shot 2020-05-27 at 13 07 45" src="https://user-images.githubusercontent.com/12456965/83020225-7927aa00-a028-11ea-83b4-4b8dc634f545.png">

# Next steps

**Comment by Kiarii** [comment]
> Hide the Row and Column count. @Kiarii will this be moved somewhere else (on a group level)

@janagombitova since question and data groups will differ (metadata, derived cols, rqgs, ..), i think it might be more relevant to consider that count by number of submissions in the form for instance, a date range for the submissions or some other stats related to the form itself..

**Comment by janagombitova** [comment]
Well once we implement the summaries per column all this info will be presented there, right? So we can remove the element from the UI?

**Comment by Kiarii** [comment]
yes..

**Comment by marvinkome** [comment]
How would this affect other pages that uses the same UI (Visualization pages for example)

**Comment by janagombitova** [comment]
@MK if this change has implications on other pages, let's pause it for now and focus on the changes related to how data is presented (the question group navigation and handling RQGs). 

@Kiarii can you connect with Marvin and discuss the implications and then define the needed changes? 

Once we are clear on the magnitude of the implications we can take up the issue.

**Comment by marvinkome** [comment]
In the dataset header (and other headers), there's a save button for when autosave fails. I talked with @Kiarii about it and he added this new design to accommodate the save button.

![image](https://user-images.githubusercontent.com/30107382/83636657-391f7480-a59e-11ea-8840-1cc585da1bae.png)

@janagombitova @tangrammer what do you think about it?

**Comment by janagombitova** [comment]
Looks good to me

**Comment by janagombitova** [comment]
Very nice change and works well! 👍 

We intentionally removed the number of rows and columns from the dataset. I am noting this decision down here. After the release, we will see if we get users asking for those counts. If so, we will need to think of how to add it back (and what to add back), but in the new UI.

**Comment by janagombitova** [comment]
Released
