### ISSUE TITLE
Change data type indication from text to icons

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2707]
# Context

As part of the work to support RQGs in Lumen we decided to improve the dataset UI. To make the change doable, small and iterative, this issue handles only one small piece of the puzzle and can be addressed and released independently from the other changes.

## Why do we have this issue? What are we trying to solve? 
To simplify to UI and clean it up a bit, easily distinguish between a standard element and a data value. 
 
## How will this benefit the users & Akvo? 
* cleans up the dataset UI making it more appealing and easy to orientate in 

Plus as this change is part of a larger UI improvement of the dataset editor to support RQGs so we can assume that the entire change will:

* make Lumen more attractive for Flow users that have RQG data and thus strengthen our value (as they can make use of the existing Lumen features as transformation log, easy transformations, custom visuals, direct Flow update, etc)
* by making it easy to work with RQG data we strengthen our market position as competitors do not have an easy way to handle the data

# Opportunity 

## Current status quo
* We have these datatypes now:
   * Number
   * Text
   * Date
   * Multiple
   * Geopoint
   * Geoshape

These are indicated as text next to the column header. 

<img width="1203" alt="Screen Shot 2020-05-27 at 14 43 09" src="https://user-images.githubusercontent.com/12456965/83030811-1b995a80-a034-11ea-8df2-aa47e11af061.png">

## The idea 

The idea is to change all datatypes to icons. On mouseover, the data type should be shown. On clicking on the type icon, the user should have the option to change the data type, as it works today.  
<img width="878" alt="Screen Shot 2020-05-27 at 13 07 45 2" src="https://user-images.githubusercontent.com/12456965/83030825-1f2ce180-a034-11ea-8d8a-0f521fae433c.png">

# Next steps  
* Use the icons as shown in the mockups 
* Kiarii can provide icons where not available

**Comment by janagombitova** [comment]
Just to update the current status: We have these datatypes now:
* Number
* Text
* Date
* Multiple
* Geopoint
* Geoshape
* Option

**Comment by Kiarii** [comment]
@janagombitova aren't Option and Multiple are Text data types?

**Comment by janagombitova** [comment]
@Kiarii In theory they are, but in practice they are automatically given to Flow option questions, geoshapes and Caddisfly and specific transformations only work for them. So they need to be shown as Option and Multiple so Salim see why Lumen behaves differently with these columns.

**Comment by Kiarii** [comment]
I see, but arent they handled as Text when it comes to the types of transformations and aggregations they comply to?

**Comment by janagombitova** [comment]
@Kiarii they are not actually. 

MULTIPLE is applied to Flow Caddisfly and geoshape questions. With this data type, these columns are selectable for the `extract multiple values` transformation. No other data types are selectable here. This is because the MULTIPLE data types hold more than one value and Lumen knows how to process them with the transformation. 

OPTION - here the difference is how visualisations behave. They look like TEXT but in the case of OPTION Lumen does not look at unique values per cell when drawing the visualisation, but looks are variables and groups them automatically making it easy to analyse multiple answer option questions. 

Also, MULTIPLE and OPTION can be changed to other data types but not other way around

**Comment by janagombitova** [comment]
When testing with Chrome in a private browser the icons did not show

<img width="1278" alt="Screen Shot 2020-10-15 at 19 49 19" src="https://user-images.githubusercontent.com/12456965/96167420-a9aca980-0f1f-11eb-9204-e2d1d457a57a.png">

**Comment by Kiarii** [comment]
and the mousetooltip for the 'code' data type is "Multiple values"..

**Comment by janagombitova** [comment]
Resolved. Tested. Released.
