### ISSUE TITLE
Existing maps do not load data

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2708]
Issue reported via support: https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-347284-from-ima-at-akvo-dot-org

It seems that maps that were created before and worked now do not show any data and do not load in the dashboards. 

Example: https://demo.akvolumen.org/visualisation/5c0a3746-fb86-4b4b-b684-635ed01a1b83

I created this map and all the layers worked fine and were properly selected. The set up is still there, all components are selected in the editor but no points show. There is no error showing in the console.

**Comment by janagombitova** [comment]
When creating a new map I get a 500 error
<img width="1133" alt="Screen Shot 2020-06-03 at 12 15 16" src="https://user-images.githubusercontent.com/12456965/83625236-e8a31980-a593-11ea-962f-af2401112656.png">

**Comment by tangrammer** [comment]
SSL error on prod lumen-maps container
`"2020-06-03T10:30:04.746Z - info: [LAYERGROUP ERROR] -- 400: Error: Postgis Plugin: SSL error: certificate verify failed"`

**Comment by tangrammer** [comment]
Confirmed that `prod` and `test` k8s envs have same problem

**Comment by iperdomo** [comment]
The problem was outdated `ca-certificates` package in the `windshaft` container (based on https://github.com/akvo/akvo-maps) ... We made a small change in the base container to get an updated certificates file and redeploy lumen
