### ISSUE TITLE
Fix translation string

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-lumen#2726]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
And a few more to update: 

* [ ] remove double space is partially translated 
<img width="466" alt="Screen Shot 2020-06-23 at 14 10 44" src="https://user-images.githubusercontent.com/12456965/85402133-70f55880-b55b-11ea-9262-e2e6440e4c31.png">
* [ ] translation to title case is missing 
<img width="1105" alt="Screen Shot 2020-06-23 at 14 14 10" src="https://user-images.githubusercontent.com/12456965/85402475-0bee3280-b55c-11ea-8a05-ecb3f26f5342.png">

**Comment by janagombitova** [comment]
I checked on dark-demo assuming the changes are there following the conversation from yesterday in Slack and saw that `To titlecase` is still not translated. 

<img width="1261" alt="Screen Shot 2020-07-01 at 09 12 42" src="https://user-images.githubusercontent.com/12456965/86214212-27b89080-bb7b-11ea-8285-5399dd357d8f.png">

**Comment by janagombitova** [comment]
Released
