### ISSUE TITLE
Support custom col-width to accommodate long values

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#2728]
**Context**
Cols appear to have a fixed width. This is problematic when viewing or copying cell values that spill over the specified width; it simply is not possible to view the entire content of such values. Here is an example shot of such data
<img width="644" alt="Screenshot 2020-06-23 at 15 17 59" src="https://user-images.githubusercontent.com/12692444/85402930-309ad800-b565-11ea-947e-3164bd6400eb.png">

**Solution or next step**
Especially now that we are already splitting datasets into groups, it makes sense to support custom col widths when present cell values. Custom col width here may refers to two things
1. Lumen renders col widths by the cell values; therefore each col width is determined by the row with the most values in that col
2. In addition to point 1, it might also mean that the user is able to drag col-dividers to set a custom col-width in whatever way it suits their data viewing

The first might suffice, since the latter may be more of a nice to have..

**Comment by janagombitova** [comment]
I would actually suggest giving the user the option to expand the column width for the columns she wants to see fully. It may happen that many columns in the group will be too long resulting in the columns expanding too much, resulting in more scrolling and not being able to get a good overview of the data. By allowing the user to expand the column she really needs to see we can keep a condensed view and also allow her to better work with the data. 

If we implement a drag option or an action icon (like the example below) should be determined by what is feasible to implement.
