### ISSUE TITLE
Simplify dataset grid UI

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2735]
# Context
https://github.com/akvo/akvo-lumen/issues/2705

## Current status quo 
<img width="1259" alt="Screen Shot 2020-06-25 at 11 00 27" src="https://user-images.githubusercontent.com/12456965/85689706-272f7e00-b6d3-11ea-9a6e-83a481fdb7bf.png">

# Opportunity 
Simplify data groups grids to "fit" more rows and clean up the UI. 

## Idea 

The idea is to move away from the grey-white-grey colour divisions of rows to have them all white and divided by a line as in the mockups provided. 

Secondly, we should decrease the row height as currently there is a lot of unnecessary white space with the intention to fit more rows in the view. 

@Kiarii do you agree (I believe there was an old issue for this, but cannot find it anymore) and if yes, can you provide the specs.

**Comment by Kiarii** [comment]
Yes, there is some clean up due for the grid, atm my view in dark-demo is actually the old view of 'too' narrow rows. We should aim for:
- a visual balance between the amt of content in view and resting (white) spaces for eye @marvinkome lets pick this up 
- ditching the header and row backgrounds and use row dividers instead
- representing data types by icons
- middle aligning row text to row container

**Comment by janagombitova** [comment]
Let's keep this change again to the minimum, so looking at the design of the grid, no changes to icons. Lets handle that is a separate issue.

**Comment by janagombitova** [comment]
I checked dark-demo just now and there are 2 things we need to change (one improvement and one bug) 

# Decrease the row hight

See the before and after screenshot. The new UI design has very high rows, that one does not need to scan the data. I understand the concept of "resting space for the eyes" but working with tables one is used to narrow rows. Plus not there is simply too much unused white space and by decreasing the rows we can show more data in the screen. Please decrease them.  

<img width="1236" alt="Screen Shot 2020-07-01 at 08 45 57" src="https://user-images.githubusercontent.com/12456965/86211969-8419b100-bb77-11ea-9d3b-682cf9c4066a.png">
<img width="1238" alt="Screen Shot 2020-07-01 at 08 46 32" src="https://user-images.githubusercontent.com/12456965/86211974-85e37480-bb77-11ea-8eac-e6ff55db0219.png">

# Divider line missing 
Between every two rows the division line is missing 

<img width="943" alt="Screen Shot 2020-07-01 at 08 50 00" src="https://user-images.githubusercontent.com/12456965/86212195-e07cd080-bb77-11ea-8845-e578472bd279.png">

**Comment by janagombitova** [comment]
Finalised, well done
