### ISSUE TITLE
Importing new datasets does not recognise repeated groups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2748]
When testing today on dark-demo, I noticed that a new dataset that I import from Flow does not recognise that there is a repeated group in it. Existing datasets, that I used the days before are fine. I am not sure if this is a new issue introduced today or it was here longer. 

**Example 1**  
* Flow: Dataset: uat1 > _ _ Lumen test > Example dataset (for testing and demos) > form ID: 554339123
* repeated group is `Family`
* Lumen: https://dark-demo.akvolumen.org/dataset/5efdb44b-c50a-4431-8ffc-53f6b1f42fdb

**Example 2**
* Flow: uat1 > _ _ Lumen test >Imported data - larger - with RQGs > Form ID: 214279115 
* repeated group is the second group
* Lumen: https://dark-demo.akvolumen.org/dataset/5efdb2d9-17e3-472d-91fa-f999d6fe57a0

I also noticed that when looking at the datasets in the Library, they do not indicate the origin `from Flow`. Could this be the problem? But then they do show the group navigation, so Lumen knows it is from Flow as with non-Flow datasets we do not show the data group navigation.

**Comment by iperdomo** [comment]
> I noticed that a new dataset that I import from Flow does not recognise that there is a repeated group in it.

@janagombitova what do you mean by **does not recognise** ?

We removed the current implementation of RQG, the one that places everything in one cell, as per PR: https://github.com/akvo/akvo-lumen/pull/2733

In the comments I asked about the existing imported datasets:
https://github.com/akvo/akvo-lumen/pull/2733#issuecomment-648938109 https://github.com/akvo/akvo-lumen/pull/2733#issuecomment-649254485

@tangrammer said that he was going to delete those:
https://github.com/akvo/akvo-lumen/pull/2733#issuecomment-648946798

**Comment by janagombitova** [comment]
I see. So then the following question is, why does the UI not mark the groups as repeated with the icon? @marvinkome

**Comment by iperdomo** [comment]
> I see. So then the following question is, why does the UI not mark the groups as repeated with the icon?

I think because the client _doesn't know_ that is repeated. I'm checking if the metadata about the group is there.

**Comment by janagombitova** [comment]
Thank you!
