### ISSUE TITLE
Simplify error message for dataset update fail & resolve reason for failure (if applicable)

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2755]
A user just got this error message when updating a dataset. It is too long, he does not know what went wrong and thus cannot react to it. We should show enough information for a non-technical person to know what is going on, but not too much. 

The message:

Failed to update "COVID ENQUETE INDIVIDUELLE". Batch entry 0 UPDATE dataset_version SET columns= '[{"type":"text","title":"Identifier","columnName":"identifier","groupName":null,"groupId":null,"sort":null,"direction":null,"hidden":false},{"groupId":null,"key":true,"groupName":null,"sort":null,"direction":null,"title":"Instance id","type":"text","hidden":false,"columnName":"instance_id"},{"type":"text","title":"Display name","columnName":"display_name","groupName":null,"groupId":null,"sort":null,"direction":null,"hidden":false},{"type":"text","title":"Submitter","columnName":"submitter","groupName":null,"groupId":null,"sort":null,"direction":null,"hidden":false},{"type":"date","title":"Submitted at","columnName":"submitted_at","groupName":null,"groupId":null,"sort":null,"direction":null,"hidden":false},{"type":"number","title":"Surveyal time","columnName":"surveyal_time","groupName":null,"groupId":null,"sort":null,"direction":null,"hidden":false},{"type":"text","title":"Device Id","columnName":"device_id","groupName":null,"groupId":null,"sort":null,"direction":null,"hidden":false},{"type":"text","title":"LOCALITÉ","columnName":"c108590003","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"geopoint","title":"Prendre les coordonnées GPS du lieu de l''enquête","columnName":"c118741397","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Sexe de la personne interrogée","columnName":"c132630004","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"number","title":"Age de la personne interrogée","columnName":"c136602191","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Situation matrimoniale","columnName":"c102620005","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Profession de la personne interrogée","columnName":"c132630005","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Fonction sociale","columnName":"c136602192","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Niveau d''études","columnName":"c116580002","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"number","title":"Combien de personnes dépendent de vous pour satisfaire leurs besoins essentiels ?","columnName":"c110550003","groupName":"GENERALITES","groupId":"136611884","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Avez-vous déjà entendu parler de la nouvelle maladie à coronavirus (COVID-19) ?","columnName":"c120540006","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Quel type d''informations avez-vous reçu sur la maladie ?","columnName":"c122620153","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Par quels canaux ou sources avez-vous entendu parler du nouveau coronavirus ?","columnName":"c108552588","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Faites-vous confiance à ces canaux ?","columnName":"c136602196","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Si oui, pourquoi faites-vous confiance à ces canaux ?","columnName":"c116531628","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Le mois dernier avez-vous entendu ou vu un message sur le COVID-19? spots audio et audio-visuels ","columnName":"c136670010","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Si oui sur de quoi parle-ton dans ces messages concernant le COVID-19 ?","columnName":"c100570137","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Comment jugez-vous la qualité des messages vus ou entendus ?","columnName":"c136602198","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"À quel niveau évaluez-vous le risque que vous contractiez le nouveau coronavirus ? ","columnName":"c138600008","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"En quoi est-ce que vous vous sentez concernés par les messages reçus ?","columnName":"c136602199","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Quels sentiments avez-vous en écoutant ces messages ?","columnName":"c132620020","groupName":"INFORMATIONS SUR LA MALADIE","groupId":"102620007","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Selon vous, qui est le plus à risque de contracter le coronavirus ? ","columnName":"c138600012","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Comment se propage le corona virus?","columnName":"c132620025","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Quels sont les principaux symptômes ?","columnName":"c136602205","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Savez-vous comment prévenir la maladie a coronavirus ? ","columnName":"c132620030","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Que faites-vous, vous et votre famille actuellement, pour éviter de contracter le coronavirus ces derniers jours ?","columnName":"c122620170","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Que faire si vous ou un de votre famille présentez des symptômes de cette maladie ? ","columnName":"c138600018","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"number","title":"Si je resterais en quarantaine dites nous durant combien de jours ?","columnName":"c132620034","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Connaissez vous le numero vert du Covid-19 ?","columnName":"c102610219","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Dites nous le numéro","columnName":"c136680016","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Que voudriez-vous savoir de plus sur la maladie ? ","columnName":"c108590021","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Pensez-vous que la maladie à coronavirus crée une stigmatisation contre des personnes spécifiques ? ","columnName":"c136602211","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Dans votre communauté citer les groupes à risque de discrimination à cause du coronavirus ?","columnName":"c126760014","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Pensez-vous que la maladie à coronavirus peut augmenter les violences faites aux femmes et aux filles ?","columnName":"c116531638","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Si oui pourquoi ?","columnName":"c130610004","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Pensez-vous que la maladie à coronavirus peut augmenter la charge de travail des membres de la famille ? femmes et les filles au sein du ménage ?","columnName":"c134610139","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Si oui, quel membre de la famille verra sa charge de travail s’augmenter le plus ? ","columnName":"c118800021","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Si oui pourquoi ?","columnName":"c118790014","groupName":"CONNAISSANCES","groupId":"132620022","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Est-ce que le gouvernement a pris ces mesures ?","columnName":"c134640021","groupName":"MESURES PRISES PAR LE GOUVERNEMENT","groupId":"124550155","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Quelles sont les mesures prises par le gouvernement que vous comprenez ?","columnName":"c134640022","groupName":"MESURES PRISES PAR LE GOUVERNEMENT","groupId":"124550155","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Que faites-vous d’habitude en cas de grippe régulière ? ","columnName":"c116531642","groupName":"MESURES PRISES PAR LE GOUVERNEMENT","groupId":"124550155","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Quel sont les moments clé de lavage des mains que vous connaissez ?","columnName":"c106641830","groupName":"WASH","groupId":"110550016","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Decrivez nous comment on doit laver les mains ?","columnName":"c126760019","groupName":"WASH","groupId":"110550016","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Êtes convaincu que le Covid-19 existe au Mali ?","columnName":"c122620181","groupName":"AUTRES","groupId":"124560006","sort":null,"direction":null,"hidden":false},{"type":"text","title":"Commentaires ","columnName":"c106681384","groupName":"AUTRES","groupId":"124560006","sort":null,"direction":null,"hidden":false}]', transformations= '[]' where dataset_id= '5ede3ffd-28a4-4d28-9136-5c55d651f896' and version= 70 was aborted: ERROR: duplicate key value violates unique constraint "dataset_version_dataset_id_version_columns_key" Detail: Key (dataset_id, version, md5(columns::text))=(5ede3ffd-28a4-4d28-9136-5c55d651f896, 70, ba30393e9da66178a9df45abbe06b84a) already exists. Call getNextException to see other errors in the batch.

**Comment by janagombitova** [comment]
Plus we should handle the failure is the cause is on Lumen's side

**Comment by janagombitova** [comment]
https://akvoo.reamaze.com/admin/conversations/akvolumen-support-request-number-361722-from-boroma-at-akvo-dot-org The support tread

**Comment by tangrammer** [comment]
Relates https://github.com/akvo/akvo-lumen/pull/2732

**Comment by tangrammer** [comment]
<img width="963" alt="Screenshot 2020-07-20 at 10 57 00" src="https://user-images.githubusercontent.com/731829/87919274-d9125e00-ca77-11ea-920d-810cb3c0352f.png">

**Comment by tangrammer** [comment]
https://console.cloud.google.com/logs/viewer?interval=PT1H&authuser=1&project=akvo-lumen&minLogLevel=0&expandAll=false&timestamp=2020-07-20T08%3A49%3A33.040000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.project_id%3D%22akvo-lumen%22%0Aresource.labels.container_name%3D%22lumen-backend%22%0Aresource.labels.cluster_name%3D%22production%22%0Aresource.labels.pod_name%3D%22lumen-blue-bdf79ddc7-m9jpg%22%0Atimestamp%3D%222020-07-20T08%3A48%3A56.625755857Z%22%0AinsertId%3D%22ec45aw014yidv0ume%22&scrollTimestamp=2020-07-20T08%3A48%3A56.626003016Z&dateRangeStart=2020-07-20T07%3A49%3A33.040Z&dateRangeEnd=2020-07-20T08%3A49%3A33.040Z

**Comment by tangrammer** [comment]
more on https://docs.google.com/document/d/1HL1r4EBlKeG9yjtlxNm-pIsITEdeIM_SmNzEJO1HEBs/edit?usp=sharing

PS: publishing in gdocs to protect _sensible_ data

**Comment by tangrammer** [comment]
Perhaps root cause: https://github.com/akvo/akvo-lumen/blob/master/backend/src/akvo/lumen/lib/transformation/engine.clj#L253 should be `(inc version)` ?

**Comment by janagombitova** [comment]
All works now. Closing issue
