### ISSUE TITLE
Order of data groups does not match order of question groups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2756]
When testing the changes on demo.akvolumen.org I noticed that the order of data groups does not match the order of question groups. The expectation is that the order in the dataset is the same as in the form. 

For example: 
Dataset: https://demo.akvolumen.org/dataset/5f058d43-8bfe-4426-90c8-6f78425891e3
Flow: uat1 > _ _Jana > Example webform > New form
<img width="804" alt="Screen Shot 2020-07-08 at 11 13 36" src="https://user-images.githubusercontent.com/12456965/86900771-0d972900-c10c-11ea-8d18-5572df418110.png">

**Comment by janagombitova** [comment]
This issue is still present. I imported the same dataset to Lumen test: https://lumen.akvotest.org/dataset/5f60c0bd-1028-45f4-90fc-0eea25e69bac

**Comment by janagombitova** [comment]
Guys, what is the status of this change? Solved? Can we close?

**Comment by tangrammer** [comment]
yep

**Comment by janagombitova** [comment]
![Screen Shot 2020-10-29 at 15 30 04](https://user-images.githubusercontent.com/12456965/97587409-a6bfb780-19fb-11eb-8b38-ac0c1ca106e5.png)

The issue seems to still be present. See example above from importing the dataset from https://gietrenk.akvoflow.org/admin/ > 2. Household baseline > Baseline study for SLCDD2

**Comment by tangrammer** [comment]
i can reproduce the problem if feature-flag data-groups=`true` 
with `false` groups are properly ordered

**Comment by marvinkome** [comment]
@tangrammer sure it's not related to the recent data groups changes?

**Comment by tangrammer** [comment]
after double checking this production dataset https://demo.akvolumen.org/dataset/5f9fbd84-4bf8-4904-a7b8-5954f822c7d1 we can close this issue
