### ISSUE TITLE
Visually differentiate data groups (non selectable items) from the columns (selectable items)

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#2757]
# Context
In lumen-test when doing a transform - a split e.g. - the data groups are disordered; the metadata which should be the first in the dropdown list is presented after the first question group

Also there is a need to visually differentiate data groups (non selectable items) from the columns (selectable items), when the two appear the same visually, it makes the differentiation that more hard and even more so since it is not clear where one group ends and another beings..

**Comment by janagombitova** [comment]
@Kiarii we are handling the bug about the data group order here: https://github.com/akvo/akvo-lumen/issues/2741#issuecomment-652236594 

But we can use this issue to handle the 2nd part: **visually differentiate data groups (non selectable items) from the columns (selectable items)**
