### ISSUE TITLE
Pivot table - Show total for when only row is selected 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2761]
Pivot tables are a great way to get an overview of your dataset. Often users use the default simple aggregation `count` to get a quick understanding of the structure of the dataset, or to track the data collection (so how many submissions are made per each location). 

When one starts making a pivot table, we show the `total`. Then Salim wants to see the count of submissions per Device ID, so he selects Device ID column in `rows`. And now we show the count but no longer the total. He wants to see that `total` there so he knows how big the dataset is. He would have to select a column to get the `total` back, but often he does not want that data there. 

![pivot table](https://user-images.githubusercontent.com/12456965/87317063-cc957f00-c526-11ea-9b0b-3cd35efdb2d2.gif)

*Issue requested by West Africa team who uses pivot tables predominantly*

**Comment by marvinkome** [comment]
From a few research, this is a backend issue. @janagombitova the rows and columns are coming from the backend, so all we need to do Is add the `total` to column or row depending on what's selected first
