### ISSUE TITLE
Don't support dashboards with more than 100 visualisations 

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2765]
# Context
Relates to #2763 and #2374 
https://docs.google.com/document/d/19TW6KwhqkMi48DCR2u-FMYvrjjq3As7IQYAM8CgHrIE/edit#

# Problem or idea
Currently, there are some dashboards with too many data included (eg dashboard described in #2763  has 143 visualizations attached) DB performance is degraded even totally exhausted 

# Solution or next step
We need a boundary in backend-side and client-side to don't support these bigger vizs numbers 

Implementation order: locate existing ones, communicate about the problem (with when the change is in place and which dashboards will be affected), add the cap, add a UI element informing about it (once cap reached maybe), release, communicate again

**Comment by janagombitova** [comment]
https://github.com/akvo/akvo-lumen/issues/2763#issuecomment-664546046 based on this we do not need to make any further changes to limit the number of visuals in a dashboard but we do need to look at how we load them. This will be handled in the linked issue.
