### ISSUE TITLE
Dataset grid not fully expanded

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2767]
![Screenshot 2020-07-20 at 10.06.35.png](https://images.zenhubusercontent.com/5c8f6c3ea7f08c1a3af97cc1/362779fe-5d61-4941-a770-0f3c62b188f4)

Sometimes the dataset grid does not expand to the full width of the screen. It does not happen all the time and sometimes it shows and then in a split second readjust and shows full width.

**Comment by tangrammer** [comment]
<img width="1280" alt="Screenshot 2020-08-31 at 13 26 56" src="https://user-images.githubusercontent.com/731829/91715348-bbafd400-eb8d-11ea-9b7a-fda2b5a5be75.png">

today still happening to me on https://dark-demo.akvolumen.org/dataset/5f4bfb6b-76c2-41dd-858d-e59a9ada97cb

**Comment by tangrammer** [comment]
image showing dataset view without RQG feature-flag ... I've just enabled it on (dark-live)-production  to let internal users try RQG UI ... 
Anyway the RQG UI feature should be opt-in and opt-off

**Comment by marvinkome** [comment]
It works for me. Did it happen repeatedly?

![image](https://user-images.githubusercontent.com/30107382/92366643-5314aa00-f0ed-11ea-9a17-8663aebfcefe.png)

**Comment by janagombitova** [comment]
Works for me fine too. I am going to close this issue again and the rule again applies: if the issue appears again, reopen to fix

**Comment by janagombitova** [comment]
When testing on lumen.akvotest.org I again experience the issue when switching the view 

<img width="1239" alt="Screen Shot 2020-09-21 at 09 37 11" src="https://user-images.githubusercontent.com/12456965/93742319-2c2a9d80-fbee-11ea-9a06-36efccd9d646.png">

**Comment by janagombitova** [comment]
Released. Closing this issue.
