### ISSUE TITLE
In library view, update-dataset link is lost after clicking in dataset [client]

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2770]
# Context
https://akvo.slack.com/archives/CCH3D1YUT/p1595318090000800

<img width="372" alt="Screenshot 2020-07-21 at 10 10 25" src="https://user-images.githubusercontent.com/731829/88029570-7766f800-cb3a-11ea-9075-0cbc294489a5.png">

<img width="314" alt="Screenshot 2020-07-21 at 10 10 16" src="https://user-images.githubusercontent.com/731829/88029580-79c95200-cb3a-11ea-8caf-c72b7374b38f.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by marvinkome** [comment]
The `source` is not sent when you request for groups that's what's causing the bug. Two solutions would be
1: Add the `source` when fetching groups
2: Refetch datasets without groups when you go back to the dashboard.

Which option would be better @tangrammer?

**Comment by tangrammer** [comment]
thanks to @marvinkome for figuring out the problem
