### ISSUE TITLE
Allow to clear an item in the dropdowns in visuals 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2780]
In the dropdowns in the visualisation editor once you select an item, you cannot deselect it (clear the dropdown). So if you, for example, decide that you do not want to show a value on the y-axis in your bar chart, you have the recreate it as you cannot unselect the column. 

This makes the user have the do a lot of re-work as a result of exploring/playing with the data. 

In some dropdowns you can 'select' the `Choose item` placeholder, or there is an `x` to clear the selection.

**Comment by Kiarii** [comment]
Here is a [mockup of - removable input states](https://www.figma.com/proto/XQtjy781ugZ8dmmaA9hWnO/Lumen-style-guide?node-id=487%3A26&viewport=515%2C411%2C0.5466272234916687&scaling=scale-down) - using 8 point grid for all components and spacing i.e. calling for visual unification of input field component incl icons sizes and spacing

**Comment by janagombitova** [comment]
Perfect! Thank you @Kiarii 

@marvinkome once we get to this, lets see how to unify it across all dropdowns if possible.

**Comment by janagombitova** [comment]
I looked at the different dropdowns we have in Lumen and where we can give the option to clear the selection. There are dropdowns where Salim **must** select an item, so these should not be changed (like the dataset one in visuals). 

Below is a list of dropdowns I think we can allow Salim to clear: 
* bar chart y-axis metric column (if unselected the aggregation should automagically turn to `count`)

**Comment by janagombitova** [comment]
<img width="598" alt="Screen Shot 2020-07-29 at 12 38 30" src="https://user-images.githubusercontent.com/12456965/88790413-710af880-d198-11ea-8189-a94973f330aa.png">

I found an issue with the implementation when looking at lumen.akvotest.org. In bar charts, when you select more metric columns, in the 2nd, 3rd, etc dropdowns if the column name is too long, you cannot remove the selection

**Comment by janagombitova** [comment]
and one more: in bars, the bucket column (x-axis) should NOT be clearable (you need this column to actually make the bar chart so we should enforce users to fill it in)

<img width="647" alt="Screen Shot 2020-07-29 at 12 42 24" src="https://user-images.githubusercontent.com/12456965/88790836-102ff000-d199-11ea-983e-60b9c9d57661.png">

**Comment by janagombitova** [comment]
Works like a charm! Well done. Ready for production
