### ISSUE TITLE
Lazy load maps on public dashboards

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2795]
While trying to resolve #2763 we concluded we can improve how we load public dashboards and decided to lazily load maps as the user scrolls down the dashboards. 

## Original comment

The issue is not the number of visualisations, but the number map visualisations, due to the "stampede" on the number of request to load those maps.

For example, https://demo.akvolumen.org/dashboard/5dfbb7ff-e627-4cfc-afcf-c87021d9ed41 has 35 visualisations, of which 8 are maps. 

Loading the public dashboard, which contains all the data for all visualisation but the maps, takes 500 ms. This is reasonable.

But after loading the dashboard, the 8 maps make ~240 concurrent request to the backend to draw the maps. This is what is causing the DB to choke. Note that this is just for one single user.

I will look at what is the bottleneck on those requests, but it would be good to change the FE code to lazily load the maps as they the user scrolls down the dashboard.

_Originally posted by @dlebrero in https://github.com/akvo/akvo-lumen/issues/2763#issuecomment-664546046_

**Comment by Kiarii** [comment]
some thoughts for consideration [on loading huge content or loading content under low speeds](https://medium.com/google-design/connect-no-matter-the-speed-3b81cfd3355a)

**Comment by janagombitova** [comment]
An interesting read with some good options. To be able to make this change more concrete, @Kiarii could you propose which solution would be the best for us? 

I think we should be progressively loading the visuals in the dashboard based on order. There is no need to load visuals at the bottom if there are 50 more on top the user first needs to see. So I would go for loading what is in the beginning and as the user moves down, show loading as he goas. But I would like to hear your thoughts.

**Comment by Kiarii** [comment]
totally; priority should be given to the top most elements on the dashboard and the rest should load in order. For complex components like maps, we should consider progressive loading..

**Comment by janagombitova** [comment]
Can we close this issue?

**Comment by janagombitova** [comment]
Checked a few dashboards in production. All seems to work in my view. @tangrammer and @marvinkome please reopen the issue if more work is needed to be done
