### ISSUE TITLE
Cannot update dataset (or import) for Ecosia 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2809]
Ecosia reported an issue with updating a dataset in Lumen. The update fails due to `null`. Normally this error means that there is a row missing the data point ID value. I checked in the Flow data export but all rows seem fine. Then I tried importing the dataset from scratch but the import failed. 

Can you check what might be going on? 

On Flow: ecosia.akvoflow.org > TREE PLANTING IMPACT > Planting site registration and monitoring > Planting site registration
On Lumen: https://ecosia.akvolumen.org/dataset/5f05f582-72ed-421e-8b24-f7f170e96f3b

**Comment by tangrammer** [comment]
So the problem is: form submission that has a RQG without any answer related

**Comment by janagombitova** [comment]
I tested it out and updated the dataset successfully! Well done @tangrammer 👍
