### ISSUE TITLE
FILTER with OPTION column OPTIONS

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#2824]
# Context
So far depending on the column type that we use in filters we have different options related, eg: when we filter using a TEXT column we have `exactly matches` and `is empty` options, 

Now we have another OPTION column type in lumen client and backend

At first glance, the change will affect to filter-transformation, visualizations and filter-dashboard

# Problem or idea
We need to define which options do we need for OPTION column type
eg: `contains`, `only contains`, `not contains`...

# Solution or next step
provisional fix commited
https://github.com/akvo/akvo-lumen/pull/2823/commits/34630abc3dc98c78f34f02d03ebaad28497afa9f#diff-ec32bd22053c6993811545a78d62403e

**Comment by tangrammer** [comment]
@janagombitova are you ok if we start with `contains, only contains, not contains` filter values for OPTION columns?

**Comment by janagombitova** [comment]
@tangrammer I took a look at how we handle TEXT to have something to lean on and make sure we do not introduce a different approach with OPTION. 

When filtering in the **dataset** we have for TEXT: `value is` and `value contains`. 
When filtering in the **visualisation** we have for TEXT: `exactly matches` (what can be understood as 'value is' just written in a more explicit way) and `is empty`

Before I say yes or no to your suggestions, I want to make sure I understand how they will behave: 
* `contains` --> I assume, that here I can type a part of the value in the cell and the filter will be applied. Right? 
* `only contains` --> Is `only contain` what we have as `exactly matches`? If yes, I would suggest we stick to `exactly matches` to keep things consistent. How will this work for OPTION columns with multiple answers? Will the user have the define the entire string?
* `not contains` --> I feel this one is redundant. I can define the filter using `contains` and get the same result. What is the extra value for having this one in your view? 
* we should also add the option 'is empty' for OPTION filters to make sure we cover all cases

**Comment by tangrammer** [comment]
Lets say we have this data
```
row1 => one|two
row2 => two|three
row3 =>  three
```

* `contains` value `one` should return `row1`
* `only contains` value `two` should return `row1, row2`
* `only contains` value `three` should return `row3`
* `not contains` value `one` should return `row2, row3`
* we should also add the option `is empty` for OPTION filters to make sure we cover all cases  **OK**

yep I agree that using `exactly matches` instead of only contains is more consistent from the user point of view :)

**Comment by janagombitova** [comment]
@tangrammer 

> `only contains` value `two` should return `row1, row2`

Should it not return anything as it does not exactly match any of the rows?
