### ISSUE TITLE
Pivot table on MDI error 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2835]
I am looking at existing visualisations and how they work now with the new OPTION column. So I took a dataset that has been updated post-release and going through all linked visualisations to see if they work. I found one that does not work. I do not know, however, if this is related to the OPTION column or not. But we should take a look. 

It is a pivot table that has an OPTION column selected as the `column` one and a text column for `rows`.
The visualisation: https://mdi.akvolumen.org/visualisation/5f2197bd-74a7-44b3-a54b-fe6ab2f23544
<img width="1225" alt="Screen Shot 2020-08-24 at 10 34 09" src="https://user-images.githubusercontent.com/12456965/91022370-660b8280-e5f5-11ea-98cd-6ecb29ae1914.png">

**Comment by tangrammer** [comment]
Good catch!, indeed we didn't take a look to the relation of column and pivot, line&area charts

**Comment by janagombitova** [comment]
After making some pivot tables it seems: 
* if OPTION is selected for `row` and a TEXT for `column` it works fine
* if OPTION is selected for `column` and a TEXT for `row` it does not work
* if OPTION is selected for `row` and a OPTION for `column` it does not work 
* if OPTION is selected for `row` and a NUMBER for `column` it works fine
* if OPTION is selected for `column` and a NUMBER for `row` it does not work

**Comment by janagombitova** [comment]
As for line and area charts, they work well. I still think we should not allow to select TEXT and OPTION on y-axis as that makes no sense from the chart perspective: https://github.com/akvo/akvo-lumen/issues/2688

**Comment by tangrammer** [comment]
Organising results :) 
* `row` OPTION  and `column` TEXT => OK
* `row` OPTION  and `column` NUMBER => OK
* `row` TEXT  and `column` OPTION => FAIL
* `row` OPTION  and `column` OPTION => FAIL
* `row` NUMBER  and `column` OPTION => FAIL

**Comment by tangrammer** [comment]
@janagombitova IMO we can close this issue now

**Comment by janagombitova** [comment]
Tested on demo and yes we can! Works like a charm. Well done 👍 

Single select option data - https://demo.akvolumen.org/visualisation/5f43a98f-8adc-4a50-8276-334e5e85ab2b
Multiple select option data - https://demo.akvolumen.org/visualisation/5f43a9ec-005c-4046-970f-a365d98a05aa
