### ISSUE TITLE
Enable OPTION flag and Legend order flag on all Lumen tenants 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2840]
We implemented two new features: OPTION data type (#2620) and Leged order (#625) and both features are behind their respective feature flags. Since last week Thursday, we have the features enabled on a few instances for testing. We are more comfortable with the implementation and would like to push it to **all** users. However, we also want to keep the option to turn off the feature in case a user finds an issue (have a safety net). 

So the idea is to enable both flags to all tenants, have it running for a week and next week remove the feature flag and have the changes by default available. 

Does this make sense as a release strategy? @tangrammer and @kardan

**Comment by tangrammer** [comment]
So we should have been endorsed the approach described in this issue and in this [doc](https://docs.google.com/document/d/1PbTbnleUuole3rY-7Sr35k08PBShh6c7bghox2QEp8I/edit) from the beginning of this impl but we didn't so in this occasion we'll release in the old fashioned style

**Comment by janagombitova** [comment]
All right. Let's talk more on how to go about releasing repeated groups so we cover it early enough. Closing this issue
