### ISSUE TITLE
`Main` and `Transformations` group names are not translated

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2916]
# Context
The _data groups_ `Main` and `Transformations` are fixed strings. They're not translated.

![2020-09-21_1205x390](https://user-images.githubusercontent.com/178474/93757144-8c2d3e00-fc06-11ea-8be6-a79b00cde685.png)

# Problem or idea
We're using fixed strings for `Main` and `Transformations` data groups.

# Solution or next step
Use translatable UI string for those groups. - https://github.com/akvo/akvo-lumen/blob/df77290a749d6b2f24723d8d105dd6d76f4bfa78/client/src/components/dataset/sidebars/GroupsList.jsx#L27

**Comment by marvinkome** [comment]
Merged
