### ISSUE TITLE
New column definition structure breaks GenerateGeopoints components

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2933]
# Context
A user reports that she/he can't generate Geopoints because the list of available columns is **empty**

# Problem or idea
* With the introduction of the new data grid we have changes the structure of the response from the server to: `["group", [{col_1}, {col_2}, {col_n}]`
* This new data structure is not understood by the GenerateGeopoints inner `SelectColumn` that expects the list of column definition in the first position, not in the 2nd one

# Solution or next step
* Fix the reference to the 2nd position in the array

**Comment by iperdomo** [comment]
The fix didn't include proper handling of *classic* data grid

**Comment by kardan** [comment]
Reopen since the issue is wider and not only related to Geopoints but we still want the full description and context.

**Comment by kardan** [comment]
Fixed in https://github.com/akvo/akvo-lumen/pull/2936
