### ISSUE TITLE
Missing translations strings for new data view 

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#2938]
In the new data view we miss translations key in english for "main" and "transformation" which makes warnings appear in the browser console while developing even if the actual translations defaults to the key.

**Comment by janagombitova** [comment]
Hasn't this already been handled: https://github.com/akvo/akvo-lumen/issues/2916?

**Comment by kardan** [comment]
Ah, that why there were translations already. Then we should just add the English keys to not have errors in the browser console.
