### ISSUE TITLE
Lumen dashboard not loading due to pie charts

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2952]
An issue reported via support. This dashboard: https://pipep-rca.akvolumen.org/s/Ojje88GFLBA loads and then disappears. From the console it seems that some pie charts are causing the problem. 

![Screen Shot 2020-10-08 at 12 03 50](https://user-images.githubusercontent.com/12456965/95445309-2d362b80-095f-11eb-9652-0f211395d4fe.png)

**Comment by iperdomo** [comment]
the accessor function is getting the `key` property of `a` or `b` ... and it seems that some data have `key` and `label` to `null`
![accesor](https://user-images.githubusercontent.com/178474/95469819-5915d900-0980-11eb-8c3c-4562cbbf64ba.gif)
