### ISSUE TITLE
Removing a dashboard filter makes an invalid GET request

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2954]
# Context
When removing a filter from a Dashboard definition, the client makes an invalid GET request with a `null` path leading to an HTTP 500 response.

# Problem or idea
![Peek 2020-10-08 17-01](https://user-images.githubusercontent.com/178474/95477124-4b645180-0988-11eb-9cb1-4e214790fd4c.gif)

# Solution or next step
* Verify from where that `null` value is coming, make sure that we don't send invalid requests

**Comment by janagombitova** [comment]
@iperdomo can we close this issue?

**Comment by marvinkome** [comment]
Yes
