### ISSUE TITLE
Show data groups in all dropdowns 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2960]
Each dataset in Lumen now is organised by data groups. These split the columns into smaller units and make it easier to keep an overview of especially lengthy datasets. 
<img width="1160" alt="Screen Shot 2020-10-12 at 20 26 07" src="https://user-images.githubusercontent.com/12456965/95778837-34e03200-0cc9-11eb-9e61-31158e44c7b8.png">

The groups show also when the user selects a column she wants to work with, in dropdowns when transforming and visualising data. 
<img width="1160" alt="Screen Shot 2020-10-12 at 20 26 36" src="https://user-images.githubusercontent.com/12456965/95778871-445f7b00-0cc9-11eb-8338-2168271b45f7.png">

With this issue we aim to ensure we show the data groups in all dropdowns in a consistent manner. The dropdowns where the groups are missing are: 
* all visualisations > setting filters for the selected dataset > column to filter by 
* area chart, x-axis dropdown 
* area chart, y-axis dropdown
* bubble chart, bucket column
* bubble chart, size column 
* line chart, x-axis
* line chart, y-axis 
* map, geopoint/geoshape column 
* map, colour coding column 
* map, styling indicator geopoint column
* pie chart, bucket column 
* polar chart, bucket column 
* donut chart, bucket column 
* pivot table, column 
* pivot table, row 
* scatter plot - all dropdowns 
* dashboard - filter - dropdown where once selects the column to use as filter

**Comment by Kiarii** [comment]
In this change, it would be nice to bundle up the following:
- #2757 i.e. visually differentiate between selectable and non-selectable items in the dropdown
- use a distinct highlight - blue - for selected option and mouseover to reduce the feeling that a selected option is disabled.. The datagroup label is a non-selectable option and therefore shouldnt have hover effect
- visually indicate repeated datagroups so they are easily identifiable
- [Specs](https://www.figma.com/file/XQtjy781ugZ8dmmaA9hWnO/Lumen-style-guide?node-id=1121%3A0)

<img width="333" alt="Screenshot 2020-10-14 at 11 28 14" src="https://user-images.githubusercontent.com/12692444/95964029-0ec5a980-0e11-11eb-97fb-d3fd8c2e9967.png">

In the future we might consider:
- collapsing and expanding datagroups to improve col-picking esp for large datasets
- denoting datatypes by icons as we have done in the grid
