### ISSUE TITLE
New data grid walkthrough steps show in visualisation editor 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2963]
![Screen Shot 2020-10-14 at 08 40 07 (2)](https://user-images.githubusercontent.com/12456965/95952743-f6499500-0df8-11eb-880f-917d39563814.png)

A few releases back we introduced the new data grid that is presented to users with a walkthrough. This is shown once a user for the 1st time opens a dataset. She sees all the steps, can click through or dismiss them. 

However, Lumen showed me the steps also when in the visualisation editor. 

Steps to take to reproduce issue: 
1. From the Library go directly to Visualisation 
2. Select visualisation type, I used bar 
3. Select dataset
4. Now you should see the steps in to top left corner of your screen. 

The idea is that the walkthrough **only** shows on the dataset view and only once.

**Comment by janagombitova** [comment]
I just noticed that the walkthough shows also in other parts of Lumen and it shows when I hit 'enter' on my keyboard. Hope this helps to reproduce the issue

**Comment by marvinkome** [comment]
@janagombitova can you test this one lumen-test?

**Comment by janagombitova** [comment]
@marvinkome I did and I could not get it to show anymore. Good job.
