### ISSUE TITLE
Misleading label in Dataset row count

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#2999]
# Context
A CSV dataset with data unrelated to Akvo Flow, displays a *form submissions* suffix.

![2020-10-27_305x56](https://user-images.githubusercontent.com/178474/97285406-7680e900-1842-11eb-81ba-f8dd8c4b107f.png)

# Problem or idea
The *form submissions* suffix should be appended to Akvo Flow datasets, the CSV files should use *rows* or similar.

# Solution or next step
* Detect the type of Dataset and use the proper label for rows: *form submissions* for Akvo Flow, *rows* for the rest

**Comment by janagombitova** [comment]
Closing this issue as it is already being handled here: #2996
