### ISSUE TITLE
Importing new Flow dataset on demo.akvolumen.org gives error - Failed to fetch groups

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#3006]
![Screen Shot 2020-10-29 at 15 25 18](https://user-images.githubusercontent.com/12456965/97586930-213c0780-19fb-11eb-94df-fc58ad9cb875.png)

Steps to take to reproduce: 
1. Click to create new dataset from Flow 
2. Import one 
3. Open

The error shows right away. But after a few minutes the dataset opens just fine. 

See: https://demo.akvolumen.org/dataset/5f9acf92-eb3d-4585-b222-f6a9b6f91b49

**Comment by tangrammer** [comment]
this is related with the backend thread we use for importing the data to data-groups table

is not a bug, just an implementation detail of this feature(-flag)

**Comment by marvinkome** [comment]
Do I need to make any changes in the client to match this?

**Comment by tangrammer** [comment]
so far not, we need firstly decide if we want to go ahead with the 2 threads in the backend

**Comment by janagombitova** [comment]
Just to put it in simple terms - Does this mean, that once we remove the feature flag, the issue will not longer be there?

**Comment by tangrammer** [comment]
exactly

**Comment by janagombitova** [comment]
ok. then I am closing this issue
