### ISSUE TITLE
Submissions count shows group row count 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#3007]
![submisisons count](https://user-images.githubusercontent.com/12456965/97590574-0cfa0980-19ff-11eb-9731-bf9fb36f6dc2.gif)

Recently we added the option to see the total number of submissions per dataset. As the row count can differ per data group, we decided that for Flow dataset we just show the count of the `metadata` group and name it `submissions`. 

But on demo.akvolumen.org the actual number today changes based on the group you are in. 

Geert, who noticed it: 
* likes that you see the scale of each group
* if we show the size of each group - calling it `submissions` is confusing to him and `rows` would be cleared 
* if we show the size of the dataset then the number should not change. 

Secondly, he noticed that the count of the repeated group shows the total of 16905 but a visualisation made from a column in this group sums up to only 15499. Why are the numbers different?

**Comment by janagombitova** [comment]
For now I suggest we do not go for the **perfect** option but one that ensures: 
* **a** count is correct (either one submissions count for the entire dataset or we show per each group as now)
* asks for **minimum** work. 

We can always pivot on this later.

**Comment by janagombitova** [comment]
We went for the implementation to show the count on the level of the **dataset** not the data group. On dark-demo all works fine. The count is correct from Flow and other datasets and it remains the same regardless of which group you are looking at. 

If we see the need to also show the count for each data group, it will be addressed in the future and in a separate issue.

**Comment by tangrammer** [comment]
flipped to live prod
