### ISSUE TITLE
Too many bucket columns values will throw "bad request" error

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#3015]
# Context
When crafting a chart (bar) with "too many"bucket column values an error "Bad request" is shown to the user.
https://recordit.co/fUTrxnFZWC

# Problem or idea
It's very unfriendly to get an error after only selected a dataset and a column.  Also since the data could be updated this error could appear once data have been collected.

# Solution or next step

- We should probably default to a value (if nothing else maximum 200). But not sure it's really nice to see graph with 200 bars in most cases. Is it a good idea to limit by default?
- We should show a better error message. "Bad request" is just bad

**Comment by janagombitova** [comment]
I found this issue that seems to try to handle the same problem: https://github.com/akvo/akvo-lumen/issues/1659 and here is how we set the limit of 2,5k for some other charts: https://github.com/akvo/akvo-lumen/issues/2537#issuecomment-623341039 (to provide some context) 

Reading the linked issue, @Kiarii agrees that we should draw a bar with a limited amount of columns. I would suggest a number through which it is clear to the user that this bar chart has too many buckets, but a value that Lumen can easily handle. If 200 works, then great. 100 might also be ok. 

We secondly, need to inform the user that there is more data that we are not showing. I would like to hear @Kiarii thoughts on this. I find rendering a message in `advanced` a bit hidden as it assumes the user will open that part. He might not. What other alternatives can we think of?

**Comment by Kiarii** [comment]
Thought for food; can we be smart with bucketing which would imply at least 2 things:
1. Whenever the possible values exceed 200, then we default the bucketing to 200
2. Auto-bucketing values based on the possible values e.g. If there is only 12 possible buckets for the selected col, then the auto-bucket would default to '25' buckets and disable '50', '100' and '200'. This would means that the "top x" caption is closer to the 'truth.' The user would still be able to change the auto-bucket to other possible bucket options.. NB we already caption charts by the number of buckets to show;
<img width="336" alt="Screenshot 2020-11-04 at 12 47 15" src="https://user-images.githubusercontent.com/12692444/98095675-ec68fe00-1e9b-11eb-8fa0-1025d9bd7164.png">

Do we carry that caption forward to dashboards? I tried looking at some dashboard but I didnt find any chart with the "top-x" caption? Or is it deemed unnecessary to do that?


3. One more thing; according to the current implementation, it is not an error when values for a selected col exceed the max possible buckets, thus should it should be communicated as an info. For now it suffices to caption the chart as we do currently, for later can wait and see if there will be a need to provide extra context..
