### ISSUE TITLE
Support for 'to uppercase' transformation using data groups

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#3036]
# Context
To support repeated question groups, on the backend we have a new version of datasets called "dataset_version_2" which includes the concepts of "data groups". We need to add the transformation facilities to the new dataset_version_2.

# Problem or idea
It's a deep subject and we need to get a proper understanding of the problems. 

Some random issues might be:
1. Old Flow data without namespaces
2. How do we handle derive transformations?
3. How do we handle combine columns

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
From @iperdomo on Zulip https://docs.google.com/spreadsheets/d/1HiwOe8Io7vnuN62yNi_g7NYyzvJuBufWBv6OAP8KLls/edit#gid=1409395453

**Comment by iperdomo** [comment]
> It's a deep subject and we need to get a proper understanding of the problems.
> 
> Some random issues might be:
>
>    Old Flow data without namespaces
>    How do we handle derive transformations?
>    How do we handle combine columns

We have changed the scope of this issue and we're only going to deal with one transformation **without** thinking in backward compatibility.

**Comment by tangrammer** [comment]
we need to take care of vacuum if data-groups https://github.com/akvo/akvo-lumen/blob/issue%2F3036-to-uppercase/backend/src/akvo/lumen/lib/transformation.clj#L54

**Comment by iperdomo** [comment]
* As part of this changes we removed the `repeatable` attribute from columns definition. There is still client code that relies on this property
* We want to filter out `hidden` columns from the client - See #3045

**Comment by janagombitova** [comment]
What is the status of this issue?

**Comment by iperdomo** [comment]
As described in one of the comments, we support `core/to-uppercase` without backward compatibility.
I'm going to close this issue and open a new one when we tackle the backward compatibility.
