### ISSUE TITLE
Map visualisation for "dataset_version_2"

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#3037]
# Context
To support repeated question groups, on the backend we have a new version of datasets called "dataset_version_2" which includes the concepts of "data groups". Map creation includes the job to craft SQL for Windshaft to use against the dataset tables. 

# Problem or idea
The current code is very untested.

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
Work started https://github.com/akvo/akvo-lumen/pull/3078

**Comment by janagombitova** [comment]
I believe the implementation happened here: https://app.zenhub.com/workspaces/akvo-k2-55d493e09e846e9104ab9478/issues/akvo/akvo-lumen/3091
