### ISSUE TITLE
Columns included in a transformation with data groups can only belong to one data-group

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#3061]
# Context
Relates #3036

We should restrict columns included in the transformation payload also in `client` side 

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
merged backend side

**Comment by janagombitova** [comment]
Great! I live the error I get when I try to combine two columns from different groups. 

But indeed we should also limit on the client side. So when Salim selects one column, in the 2nd dropdown only columns from that group should show. For derive javascript transformation I guess there is nothing to do on the client side at the moment, right?

**Comment by tangrammer** [comment]
> But indeed we should also limit on the client side. So when Salim selects one column, in the 2nd dropdown only columns from that group should show. 
ok!

> For derive javascript transformation I guess there is nothing to do on the client side at the moment, right?
yep, although we could do some tricky thing (reuse backend logic in client side) it would be fairly more complicated
