### ISSUE TITLE
Support for 'to merge-datasets' transformation using data groups

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#3073]
# Context
Merge-datasets transformation is slightly different from the others. UI needs to specify a source dataset to be merged in current/target one besides selecting the merge-column in both datasets.
Also UI/transformation let the user select any column that user needs from source dataset.

# Problem or idea
How/Where to place new merged columns?

# Solution or next step
We decided to create same data-groups in target dataset as user has selected in source dataset UI

**Comment by tangrammer** [comment]
Perhaps we can add data-group info to the UI columns to be merged....
<img width="1070" alt="Screenshot 2020-12-02 at 11 33 31" src="https://user-images.githubusercontent.com/731829/100861542-46a4b100-3492-11eb-8851-1629d3ce32fd.png">

**Comment by Kiarii** [comment]
@tangrammer yes, having that datagroup info would help the user understand/see the dataset structure

**Comment by muloem** [comment]
#### Issues to sort out

- [ ] Handle the case where a user tries to merge a column from a group from which they previously merged a different column

**Comment by Kiarii** [comment]
From our discussion and as we deemed fit;
- merged data group could be differentiated from originals (when their names match) by an icon indicator e.g.
![image](https://user-images.githubusercontent.com/12692444/101627492-7c680d80-3a2f-11eb-859c-2ab83d47ad7e.png)

- We prevent the remerging of already merged cols by disabling their selection, and adding a tag line "Already merged"
![image](https://user-images.githubusercontent.com/12692444/101627674-c05b1280-3a2f-11eb-9524-d033b3a0364f.png)

**Comment by janagombitova** [comment]
Copying the update from @iperdomo from Zulip to here as we track decisions on the issue:

> Yesterday with @Juan we manage to get some *feature parity* when merging datasets with the previous version
> Today we're going to do some more testing
> Let me explain what do we mean by feature parity.

> We realized that the most recent discussions are not just about migrating to data groups, but also refine the merging functionality, e.g. In the current version if you merge the same datasets more than once, you always get new columns. There is no cleverness in the way we do it, you merge, you get new columns, even if you pick the same column again. Somehow, we want now to do something more clever. If you merge the same datasets again, the new columns magically get added to the "proper" group (potentially an existing one). This is a refinement on the functionality that in our opinion should be out of scope.

> So what is feature parity, you merge, you get new data group(s) (with the selected columns). If you merge again, you get new groups (again, and potentially duplicated). If the user "forgot" to add a column in the first merge, she/he can undo the previous merge and do it again with the proper columns.

Jana: Great decision! The purpose of the weekly goals is to be able to deliver value to ensure the user can get the workflow done from A to Z. If it means we need to slice away some *extra* features, then we have properly embraced the weekly iteration concept. But we need to not forget to note these decisions down and make issues for the future, so we do not forget. 

@iperdomo and @tangrammer can you please create a separate issue for the additional functionality on the merge column so we can pick it up once we go for a 2nd iteration round.

**Comment by Kiarii** [comment]
(feature request) for later improvements: we could use some additional dataset metadata (e.g. creator, or created/modified date) to identify/differentiate datasets when doing a merge, as can be seen in the screenshot its impossible to tell the Registration datasets; My assumption would be that partners would have self descriptive names for datasets but ... 

Ideally, lumen would only show mergeable datasets - i.e. datasets which share the same key / primary id

<img width="1401" alt="Screen Shot 2020-12-14 at 15 09 49" src="https://user-images.githubusercontent.com/12692444/102081974-2d045180-3e22-11eb-9afc-0acf65a4af34.png">
