### ISSUE TITLE
Add data-groups aggregation maps support 

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#3091]
# Context
external map service recibes a plain SQL with table and columns related in the visualisation, then this map service uses same lumen db to read the data to be visualised

# Problem or idea
with data-groups we don't have one table but several ones for each dataset-version(-2)

# Solution or next step
We aggreed on using postgres views to be used from the external map service. these views need to not be temporary (as current ones used in lumen aggregations)

**Comment by tangrammer** [comment]
@kardan @iperdomo should we persist the view name together in dataset_version_2 table? (so we need to create a new column there)

**Comment by janagombitova** [comment]
@tangrammer and @kardan I am closing this issue as I believe it is handled already. It there is still work to do, please reopen and comment
