### ISSUE TITLE
Capitalized group names affects to derive-js transformation 

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-lumen#3092]
# Context
right now we capitalize group names by default in dataset view data-group
![Screenshot 2021-01-12 at 10 52 44](https://user-images.githubusercontent.com/731829/104298490-53221d80-54c4-11eb-8b92-ee419ea090ee.png)

# Problem or idea

trying js transformation `row["Non repeatable"]["Family name"]+" welcome"`  **FAILS**
but `row["Non Repeatable"]["Family name"]+" welcome"`  **SUCCEED**

![Screenshot 2021-01-12 at 10 53 51](https://user-images.githubusercontent.com/731829/104298778-ad22e300-54c4-11eb-97be-8d075b8aa981.png)
![Screenshot 2021-01-12 at 10 53 57](https://user-images.githubusercontent.com/731829/104298789-af853d00-54c4-11eb-881a-24968c24ebe5.png)

# Solution or next step
How could we solve it?

**Comment by tangrammer** [comment]
@janagombitova @kardan should we adapt the backend to be case insensitive or just don't change letter case in frontend

PS: changing behaviour in client is just removing css class, backend changes should have more changes and tests and perhaps more unknown consequences (thinking in undo with existent datasets with 2 groups having different letter case)

**Comment by tangrammer** [comment]
Relates https://github.com/akvo/akvo-lumen/blob/de85cd70ad8dcd2c60e9de97d00f479ace9a4806/client/src/components/dataset/sidebars/GroupsList.scss#L21

**Comment by janagombitova** [comment]
@tangrammer I would say we show things are they are. So do not change letter case in the frontend. It is less work and the users see the data, titles, etc as it is put in.

**Comment by kardan** [comment]
Agree

**Comment by tangrammer** [comment]
finally we need to adapt "Metadata", "Main" and "Transformations" in backend side thus I don't think we want to show these values in lower case 🤔

**Comment by janagombitova** [comment]
Agree.
