### ISSUE TITLE
Large dataset support

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#314]

**Comment by jonase** [comment]
This work involves both front-end and backend support. 

There are many issues to consider for the front-end

* We will attempt an "infinite/lazy load" [supported by react-virtualized](https://github.com/bvaughn/react-virtualized/blob/master/docs/InfiniteLoader.md).
* The datasets we get from the backend might not have all transformations applied yet. This means we need to apply non-persisted transformations before displaying the new data (which can fail)
* In the case of non-applied filter transforms, we might end up with a situation where all the lazy loaded data is filtered out. Turn back and fetch more?
* Sorting probably needs to be refactored to only be done on the backend (as all rows are needed to sort).
  * We might still have non-applied transforms when the user sorts which will complicate things as the transform might change the sort order but the backend is unaware. The safe thing would be to wait for the backend.

**Comment by kardan** [comment]
Interesting links for backend pagination
http://use-the-index-luke.com/sql/partial-results/fetch-next-page
https://blog.jooq.org/2016/08/10/why-most-programmers-get-pagination-wrong/
https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/
