### ISSUE TITLE
Keep track of `inFlight` status of API requests

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#315]
Related to #313 

We should add an `inFlight` key to library entities where an API call has been made to fetch the entity. 

This is to prevent the situation where an entity is currently being fetched, but before the fetch returns, a component checks to see if that entity is loaded, and, finding it has not, makes a new, redundant API call to fetch the component again.

This is a general problem and should be solved at the store level rather than the component level.

Previous comment from @jonase:

> This seems like a very general problem. Instead of adding logic to the different components (in the lifecycle methods, making them less declarative) I wonder if we could take a more general approach? Perhaps an inFlight key on the entities to keep track of in-progress api requests?
> 
> So for example fetchDataset(id) would check if this request is already in progress, something like
> 
> ```
> export function fetchDataset(id) {
>   return (dispatch, getState) => {
>     if (inFlight(getState().library.datasets[id])) {
>       return;
>     }
>     ...
> }
> ```
> 
> and add reducers for fetchDataset{Request|Failure|Success}:
> 
> ```
> function datasetFetchRequested(id) {
>   // switch the inFlight key to true
> }
> function datasetFetchSuccess(dataset) {
>   // update the dataset, and set inFlight key to false
> }
> ```

(of course, we should also set the inFlight key to false on failure)

**Comment by finnfiddle** [comment]
@gabemart is this still an issue? I cant see anywhere that we are sending multiple requests for the same thing

**Comment by gabemart** [comment]
@finnfiddle yes this is still an issue. One way to reproduce is:

* emulate a slow network connection
* load the library view
* click on a (large) dataset to enter the dataset view (which will trigger a call to `/api/datasets/$datasetId`)
* immediately hit the lumen back arrow to return to library
* click on the same dataset to return to dataset view

In the example above, the original api call to load the dataset is `inFlight`, but until that call is *complete* the client just sees that the dataset is not loaded, and will make a new call for the dataset every time the user enters the dataset view for that dataset, until the original call completes.

You end up with a waterfall like this:
