### ISSUE TITLE
Transforms that don't have an effect are not logged

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#333]
How to reproduce:
1) import some data
2) do a transform that has no effect on a column, for example 'to lowercase' in an all-lowercase column, or 'remove double spaces' in a column without double spaces.
3) The transform will not be logged in the transformation log

Expected behaviour:
A transform that does not have an effect should still be logged in the transform log, because the dataset might be 'refesh-enabled', so new data could come in later. In that case, the transform might have an effect.

**Comment by kardan** [comment]
The described issue is no longer the case
