### ISSUE TITLE
Datasets with dependent visualisations won't delete

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#334]
How to reproduce:
1) Create a dataset with some dependent visualisations
2) Try to delete the dataset. In the dialog, click 'delete'
3) The dataset does not delete.

Expected behaviour:
The dataset should be deleted, together with the dependent visualisations

**Comment by kardan** [comment]
This was fixed in https://github.com/akvo/akvo-lumen/issues/335
