### ISSUE TITLE
Import issue with CSV file (estimate: 4)

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#359]
During world water week we found that a particular CSV (crafted in Win and edited on Mac OS?) caused issues.

**Comment by kardan** [comment]
@LarsSjogreen  @bjelkeman did one of you have the CSV file?

**Comment by LarsSjogreen** [comment]
I've forwarded the original and the corrected one(s?) via mail.

**Comment by jonase** [comment]
We are "guessing" the csv file encoding using `com.ibm.icu.text.CharsetDetector` (via `org.akvo.lumen.import.csv/get-encoding`). Some detected charsets are apparently not recognised as a valid encoding by postgres `COPY ... FROM STDIN WITH (FORMAT CSV, ENCODING ...` which leads to failed imports.

Example: 
```
(get-encoding (java.io.ByteArrayInputStream. (.getBytes  "year,mmddyy\n2007,120107\n")))
```

which means that the following csv file will fail to import

```
year,mmddyy
2007,120107
```

**Comment by jonase** [comment]
@peeb Is this one ready to review?

**Comment by peeb** [comment]
Yup, although I'd like to discuss with you.
