### ISSUE TITLE
prototype feedback

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#36]
@gabe, @jonas, @kiarii, some comments:
- [ ] when I am editing a visualisation, I can 'save changes', but there is no 'Cancel' button. I would expect to be able to cancel an edit operation, for example if I find out I am editing the wrong visualisation.
- [ ] it took me a while to figure out that I need to click the 'DASH' link in the top left hand corner in order to return to the 'Home' screen. But perhaps this is a matter of visual design.
- [ ] when I go to a visualisation and open it for editing, the left sidebar doesn't collapse, which means that the visualisation screen is partly hidden. I would expect that when I open a visualisation for editing, the left side bar minimizes.

**Comment by jonase** [comment]
> when I go to a visualisation and open it for editing, the left sidebar doesn't collapse, which means that the visualisation screen is partly hidden

This is probably just a temporary bug

**Comment by mtwestra** [comment]
- [ ] The four elements at the top on the home screen: "All, Datasets, Visualisations, Dashboards", are actual filters, but they feel like tabs. So when I have selected the 'Dashboards' tab, for example, I would expect to have a button 'new Dashboard', instead of having to choose from a dropdown what new thing I want to make.

**Comment by Kiarii** [comment]
The current structure places the 'New' on the same level with the Library/Collection; which implies that whatever entity is being created is not limited by the 'second' level (tabs/filters). If that was to be the case, the mental model would become a bit complex; if active subtab/filter = Datasets, it will be difficult to understand why one cannot add a new Visualization/Dashboard in their Library/Collection; and that they have to select the All filter/subtab to remove the New 'entity' limitation. If the current model is as confusing, we can explore alternatives..
