### ISSUE TITLE
Integrate Vega aggregations

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#360]
Vega has built-in support for a range of aggregations.

We should implement a subset of these in order to meet our need to perform per-visualisation aggregations, where the aggregation becomes part of the visualisation specification.

As a first step, we should include the following metric aggregation types:

````
count
sum
mean
median
min
max
````

As these are all implemented very similarly in vega, the cost of implementing all is only marginally greater than the cost of implementing one.

## Grouping

We should first implement aggregation grouping in the simplest possible way, which is specifying a grouping column index, and grouping rows where the grouping column value is identical.

More complex grouping types will require more substantial UI changes to the visualisation changes,. The cost of these more complex grouping types should be assessed once simple grouping is working, at which point we will be in a better position to form a realistic estimate of the effort involved.

**Comment by mtwestra** [comment]
as an example use case, we can use the situation described here: https://docs.google.com/document/d/12MLKZYCogFDpJaD-LfNahu5Y_DziLxlNbqdyb0r0uAs/edit#heading=h.i96q2ri8fycx

**Comment by mtwestra** [comment]
We need to look at how we implement Grouping aggregations and Metric aggregations, as explained in the document above:

**Group aggregation**
Given a data set consisting of rows and columns, a group aggregation basically puts the rows into different groups, based on some rule. The end result of this is simply groups of items - it cannot be displayed yet. 

**Metrics aggregation**
Once we have groups of items, we need to derive numbers from them that can be mapped to the graphical marks in the chart. This is a metrics aggregation. It takes a number of items, and computes a single number (or a set of numbers, such as in percentiles).
