### ISSUE TITLE
Refactor transformation handling

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#361]
We will attempt to apply each transformation on the backend immediately instead of batching them up until the user closes the dataset tab.

* [ ] Move generated data tables to a dedicated schema
* [x] Don't copy-on-write the entire dataset for each transformation.
  * But always keep the original (imported) dataset around
  * Destructive update on a single cloned table?
  * Or, always copy-on-write, but have a plan for some kind of "garbage collection" later
* [x] Refactor frontend to make async calls to the backend for each transformation

We need to watch out for "race conditions" where the user applies multiple transformations in succession while previous transformations are in progress. This was not an immediate problem before because it was not possible to open a dataset with in-progress transformations. Two possible solutions:

* Transformation queue on the backend (per dataset/user/tenant/lumen)?
* Don't allow this on the front end.

**Comment by kardan** [comment]
Creating separate issue for the schema change https://github.com/akvo/akvo-lumen/issues/376
