### ISSUE TITLE
Create new AWS Akvo account for Lumen

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#362]
Create Lumen AWS account and specify AIM management.

The reasons for having a separate AWS account for Lumen are:
- FLOW uses one bucket per instance, which means that AWS accounts run out of space
- Need for developers to have full access to data and billing info

Things to consider:
- What IAM accounts to create. This will be decided based on need during the development process
- How to enable consolidating billing so Akvo only gets a single bill.

**Comment by kardan** [comment]
Closing this since we decided on Google cloud.
