### ISSUE TITLE
Implement secrets management solution

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#365]
Implement a secrets management solution for Lumen.

Both AWS and Kubernetes have their own solutions for this, so a first option is to use what is offered as part of the cloud service. In the case of AWS, it could also be an option to use S3 in combination with encryption.

**Comment by kardan** [comment]
Secrets are handled via Kubernetes as http://kubernetes.io/docs/user-guide/secrets/ Secret files are in the private config repo https://github.com/akvo/akvo-config/issues/17
