### ISSUE TITLE
Create short list of new transforms

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#371]
The overall document describing transforms is described here:
https://docs.google.com/document/d/1gJ7ebKR9wUod03491thJqvlcjk-v-c-z8duIh_5YNek/edit

Two transforms that we will tackle next are:

* Expand functionality of 'interpret as date' column. At the moment, the format that can be specified is very limited. We should support a wider range of formats. For example, we could use the http://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html parsing string?

* Combine columns. This involves choosing two columns, a new column name and a separator, after which the system creates a new column containing of the combination of the other two columns.

**Comment by kardan** [comment]
- [ ] Combine columns 
- [ ] Expand interpret as date

**Comment by jonase** [comment]
@mtwestra on the date parsing,  we're using pg functions for data type conversions so I would suggest using https://www.postgresql.org/docs/9.5/static/functions-formatting.html#FUNCTIONS-FORMATTING-DATETIME-TABLE instead of javas SimpleDateFormat
