### ISSUE TITLE
X axis labels don't fit on the graph

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#391]
Currently, x axis labels are cut off on the graphs.

<img width="781" alt="screen shot 2016-10-10 at 11 39 34" src="https://cloud.githubusercontent.com/assets/478954/19232117/43be5774-8ede-11e6-9b9c-efc67ed46954.png">

**Comment by gabemart** [comment]
I'm going to merge this with #394 - the cause of both issues is using fixed padding for the visualisations, and the solution to both issues is to create a responsive system that works out the length of the longest label and adjusts the padding accordingly
