### ISSUE TITLE
Placement of labels for donut and pie charts

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#395]
Currently, labels are placed on top of each other when slices are small. We should have a separate legend at the side of the chart.

<img width="339" alt="screen shot 2016-10-10 at 12 12 38" src="https://cloud.githubusercontent.com/assets/478954/19232934/dd2b1f2e-8ee2-11e6-8e9c-ac03729bd1fb.png">

**Comment by gabemart** [comment]
After some thought - it would be possible to attempt to work out programmatically when a legend will be more legible than labels on the pie chart itself, but this seems a bit unnecessary at this stage. I propose we add "show legend" and "show segment labels" as checkboxes in the visualisation editor, and leave it to the user to choose the best combination. 

In the future, we can still attempt to detect label overlap programmatically, and use this check to guess at the best default settings per-chart while still letting the user change these settings

**Comment by mtwestra** [comment]
@gabemart, having this as a checkbox for the user seems fine to me. As during the building of the visualisation it is clear that labels overlap, the user can just select that checkbox at that moment. As you say, a more advanced implementation could be considered later, but is not needed now.
