### ISSUE TITLE
Keycloak production server setup (estimate 32)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#407]
Setup Keycloak production server and test server running on AWS or Kubernetes. 

Needs to be in same network segment as other services

**Comment by kardan** [comment]
@iperdomo what's the status on this?

**Comment by iperdomo** [comment]
@kardan i'm working on it, but is not something that will be ready in the next 2-3 weeks. Based on our technology decisions, there are several issues we need to solve/workaround:

* A _production_ setup implies a high availability (imho)
* We can use CloudSQL (hosted MySQL) for storing data in GCP
* By default the nodes use multicast over UDP for discovery. Something that is not available in GCP, so we need to workaround it: https://cloudplatform.googleblog.com/2016/02/JGroups-based-clustering-and-node-discovery-with-Google-Cloud-Storage.html
* There is **limited** capacity on the Platform group

**Comment by orifito** [comment]
@iperdomo Could you please share the reason to not run keycloak on kubernetes?

**Comment by jonase** [comment]
@orifito we plan to run keycloak on kubernetes, with external storage (as a service, probably cloudsql)

**Comment by orifito** [comment]
@jonase oh great! I misunderstood the use of "single node" and "GCP" on the description 👍

**Comment by iperdomo** [comment]
@orifito yeap, as @jonase pointed out, _single node_ means a single node using Kubernetes on GCP

**Comment by iperdomo** [comment]
Just to log more details:
Based on the available documentation for stage 3, we're interested in _Standalone Cluster Mode_ and not _Domain Cluster Mode_

> Standalone clustered operation mode is for when you want to run Keycloak within a cluster. This mode 
> requires that you have a copy of the Keycloak distribution on each machine you want to run a server 
> instance

> Domain mode is a way to centrally manage and publish the configuration for your servers.
> Running a cluster in standard mode can quickly become aggravating as the cluster grows in size. 
> Every time you need to make a configuration change, you have perform it on each node in the cluster. 
> Domain mode solves this problem by providing a central place to store and publish configuration. It 
> can be quite complex to set up, but it is worth it in the end. This capability is built into the Wildfly 
> Application Server which Keycloak derives from

https://keycloak.gitbooks.io/server-installation-and-configuration/content/v/2.3/topics/operating-mode.html

https://docs.jboss.org/author/display/WFLY10/Admin+Guide#AdminGuide-Operatingmodes

Notice that configuration here means touching files, not necessary getting configuration from environment variables or a configuration repository. IMHO, if we need to change configuration files, it means that we need to  rebuild the image and roll out a new version of the service.

Thoughts?

**Comment by kardan** [comment]
I don't know enough about this but I remember looking at the Keycloak Dockerfiles at some point. They seems to show that one can use env vars for some things. But I guess there is more than what's shown here https://github.com/jboss-dockerfiles/keycloak/blob/master/server-mysql/changeDatabase.xsl

**Comment by iperdomo** [comment]
@kardan the file you're linking is a XLST transformation applied using saxon [1] . So reading env variable values in this case is a saxon capability. This of a search/replace using `sed` but with some tool that understand XML.

[1] https://github.com/jboss-dockerfiles/keycloak/blob/master/server-mysql/Dockerfile#L4

**Comment by jonase** [comment]
this is successfully deployed and in use
