### ISSUE TITLE
Set up Lumen production database (estimate: 7)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#408]
Set up the Lumen production database. Depending on the choice of cloud service, this will be either RDS or done on Kubernetes.

Things to consider:
- Should support Postgres 9.3 and Postgis.
- The actual database used should be able to be deployed on a different cloud system. This in case of countries with strict requirements regarding the storage of data on their own territory.
- Encryption of data. Is it possible to do encryption using user-provided keys?
- Scaling - how do we create a cluster of database servers? How do we do sharding? Each tenant in  Lumen has a single database.
- Possibility to inlcude custom Postgres extensions. RDS is limited to a number of provided extensions.
- Handling backups

**Comment by kardan** [comment]
We decided to give http://elephantsql.com/ a try. But while migrating we will work against the existing RDS instance

**Comment by kardan** [comment]
We need someone to help us getting dedicated plans on ElephantSQL. We will need a dedicated instance because of how we split user data per database. It's only on the "dedicated" plans we are able to create more databases. For the production database 100GB seems too small hence we suggest one Enormous Elephant for production but one Happy hippo for the test db https://www.elephantsql.com/plans.html.

**Comment by mtwestra** [comment]
For now, we will purchase one HH instance.

**Comment by kardan** [comment]
Apparently the uuid-ossp extension is not available on ElephantSQL.  Postgres docs suggest that one should use gen_random_uuid() from "pgcrypto" instead.
https://www.postgresql.org/docs/9.6/static/uuid-ossp.html

**Comment by kardan** [comment]
At the moment the test cluster is running against with a "dev" tenant, everything setup with the add-tenant.sh script. It is however a bit of a mess that one needs to 
- 1 bootstrap the master "lumen" database
- 2 deploy lumen to migrate the lumen database to get the tenants table
- 3 run the add-tenant script to create tenant db + populate tenants table
- 4 restart container to force the app to migrate available tenants.

We should move tenant migrations to be done when the tenant manger requests a connection to the tenant. However we need to keep the "migrate all tenants on start" task to not have tenants get too far behind if they are not used. 

This whole issue with migrations is something that should be reviewed, maybe there is a better strategy. Like keeping the migrations as an external thing and do it as part of CI. But that needs to be reviewed.

**Comment by jonase** [comment]
done.
