### ISSUE TITLE
Implement Continuous Integration (estimate: 16)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#410]
The aim is to implement Continuous integration for Lumen.

Workflow:
- github has feature branches, develop branch, master branch
- feature branches are deployed only on developer's machines
- develop branch should be automatically deployed to test server
- master branch should be automatically deployed to production.

This is the same setup as Akvo.org and Akvo RSR have at the moment.

Decision is to use Travis to implement this.

**Comment by kardan** [comment]
Travis does not have built in support for Google Container Engine. CricleCI do have an article on the subject https://circleci.com/docs/continuous-deployment-with-google-container-engine/. They do look very similar so we need to consider switching CI provider if Travis proves to become difficult to use.

**Comment by kardan** [comment]
- [ ] Setup tests to run on CI
- [ ] Enable production deployments
- [ ] Setup test database
- [ ] Setup test cluster
- [ ] Setup Google networking for testing environment
- [ ] Enable test deployments

**Comment by kardan** [comment]
We didn't mange to setup the test env because of databases. Either we need to get a DB somewhere or enable a local Postgres db.

**Comment by kardan** [comment]
We got an Elephantsql account credentials and will continue work.
