### ISSUE TITLE
Derived column user interface (estimate: 16)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#412]
To implement the derived column functionality, we will start with making the functionality available with minimum UI. The reason is that this will already unlock the functionality for demos and first implementations by Akvo staff, while we can work on a better UI experience for other users.

Implements https://github.com/akvo/akvo-product-design/issues/192

The first phase of the derived column support user interface will therefore contain:
- a transform where the following items can be specified:
  - name of new column
  - javascript of transform function
- check validity of javascript

The UI needs to solve these questions:
* how to give semantic correctness feedback
* how to assist the user in formula building

Backend work is described in issue https://github.com/akvo/akvo-lumen/issues/429

**Comment by mtwestra** [comment]
Some useful examples:
* http://kb.tableau.com/articles/knowledgebase/understanding-logical-calculations
* http://tableaubook.com/v9/workbooks/Formula%20Language%20Reference.PDF
*  https://support.office.com/en-us/article/Use-the-Expression-Builder-56214db9-8b54-44f3-bc19-2a55427b5d4c

Interestingly, both of these use the notation [NAME] to refer to columns

**Comment by nadiagorchakova** [comment]
At the iteration planning today we agreed that the 'temporary solution' for the UI should include the following elements: 

- a sidebar with options
- possibility to pick new column's title
- some text area for input (someone suggested CodeMirror, if it makes sense at this stage)

**Comment by jonase** [comment]
This work has been merged into https://github.com/akvo/akvo-lumen/tree/feature/429-derived-column-backend so we can test the entire feature in a single branch. Closing this one.
