### ISSUE TITLE
Decision on AWS versus Kubernetes

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#413]
We need to decide the main cloud service to use to run Lumen. We have narrowed down the choice between Amazon AWS and Google's Kubernetes.

The requirements are:
- Should support JVM, Postgresql with Postgis, and have docker support
- If possible, should support custom extensions in Postgres
- If possible, should support data encryption with user-provided keys
- Should make it easy to log, and monitor
- Should have regional awareness, so data can be close to users
- If possible, should be able to run as open source (Kubernetes is open source, for example)
#### On Postgres database
- RDS offers easy management
- Kubernetes needs more management by us, how much?
- Cost - is there a substantial difference in cost of large-scale data useage?
- On encryption: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html and https://cloud.google.com/compute/docs/disks/customer-supplied-encryption

**Comment by mtwestra** [comment]
Some articles comparing the two solutions:
* https://railsadventures.wordpress.com/2015/12/06/why-we-chose-kubernetes-over-ecs/

**Comment by mtwestra** [comment]
Where we would like to be:
* To not be locked in into a certain cloud provider. This means that, Akvo services should be able to be migrated to a different linux-based cloud service with limited effort.
* To be able to select data centers in Europe where data is stored and processed
* We should only use third-party tools if they are at least be replicated or replaced by open source tools with limited effort.

**Comment by kardan** [comment]
Decision on Docker, Kubernetes and Google Cloud (GKE).
