### ISSUE TITLE
Setup SSL for Lumen (estimate: 16)

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#420]
Enable SSL on akvolumen.org.

**Comment by kardan** [comment]
A wildcard SSL is ordered.

**Comment by Lynngre** [comment]
The decision was made by @peeb @orifito to attempt to use Letsencrypt for Lumen instead of using standard SSL certs. So this has been handed over to DevOps for now.

**Comment by peeb** [comment]
Trying out kube-lego for this iteration.

**Comment by kardan** [comment]
https://github.com/kubernetes/kubernetes/tree/release-1.0/examples/https-nginx
https://medium.com/@patrickeasters/using-traefik-with-tls-on-kubernetes-cb67fb43a948#.5y527h4zh

**Comment by Lynngre** [comment]
As requested, we've added akvolumen.org & *.akvolumen.org to our wildcard SAN certificate. The new cert has been forwarded to @orifito for implementation.

**Comment by orifito** [comment]
Thanks @Lynngre ! Forwarded to @kardan & @peeb too

**Comment by kardan** [comment]
- [ ] Order new certs with akvolumen.org & *.akvolumen.org
- [ ] Get certs from provider
- [ ] Create cert bundle
- [ ] Create tls secret in akvo-config
- [ ] Add tls secret to k8s cluster
- [ ] Create ingress object that works with demo.akvolumen.org and add to akvo-config
- [ ] Move from demo.akvolumen.org to *.akvolumen.org (akvolumen.org?)
- [ ] Redirect http traffic to https
- [ ] Make sure Lumen is only accessible via port 443 and not 3000

**Comment by kardan** [comment]
Leaving as is for now. Will pick up this and discuss on a wider front (ops, platform) in Jan.

**Comment by kardan** [comment]
Leaving as is for now. Will pick up this and discuss on a wider front (ops, platform) in Jan. A TLS https://github.com/akvo/akvo-platform/issues/2

**Comment by peeb** [comment]
FYI SSL cert has been generated and verified. Remainder of work is to figure out how to integrate and deploy it with Kubernetes/Google Cloud. @oriol @lynngre

**Comment by kardan** [comment]
@peeb Added a PR on the production TLS secret https://github.com/akvo/akvo-config/pull/23

There is a WIP ingress at https://github.com/akvo/akvo-platform/blob/ingress/k8s/ingress/prod.yaml. This ingress does not use the correct ip, to make it work we have to tweak /etc/hosts:
```
35.186.204.113 demo.akvolumen.org
```
It looks like we need to create a Nginx ingress controller which we can tweak and assign the correct ip. But this is more me thinking loud.

**Comment by kardan** [comment]
Deployed and new IP added.

**Comment by peeb** [comment]
New cert received from @Lynngre today

**Comment by oriol** [comment]
Hi, 

Can you please remove me from this thread?

Regards
Oriol

**Comment by kardan** [comment]
@oriol sorry, not sure how you got involved. The issue is closed now. If you keep getting spammed by us, please contact me and I'll try to look into why this happened. Sorry for the noise.

**Comment by oriol** [comment]
Thank you Daniel, no problem!

**Comment by peeb** [comment]
I think it's because I mentioned "at oriol" instead of "at orifito" in one of the comments - since rectified.

Sorry for the inconvenience, all.
