### ISSUE TITLE
Define javascript expressions to support in derived columns (estimate: 8)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#428]
Investigate the implications of using javascript for transformations. We should start to define expressions to support. Further work would be proper sandboxing, but it's not within the scope of this issue.

**Comment by jonase** [comment]
[Userdefinedtransformations.pdf](https://github.com/akvo/akvo-lumen/files/597347/Userdefinedtransformations.pdf)

**Comment by mtwestra** [comment]
@jonase, it might be useful to also be able to refer to aggregated quantities of columns, such as their count, mean, max, min, count unique, etc. This will enable a lot of formulas such as computing percentages etc. On the other hand, it might need some kind of caching to remain efficient: you wouldn't want to compute [column name] / count('column name') for 1000 rows because the count of all rows would be done 1000 times. What do you think?

**Comment by kardan** [comment]
The initial work described in the issue description is done.
