### ISSUE TITLE
Perform aggregation before sending data to the client (pie charts)

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#431]
As some of the data in Lumen could be sensitive, we can't expose the raw data that is used in public visualisations to the client. Aggregations of the data are usually not problematic, as those can't be retraced to individuals when reasonable precautions are taken. We need to look at how this could be best achieved.

**Comment by gabemart** [comment]
We have taken the first step towards making this possible with https://github.com/akvo/akvo-lumen/pull/469 which performs aggregations in a separate step to rendering charts from aggregated data (for non-map-type visualisations). Currently these aggregations still happen in the client, but it would be possible in principle to perform these aggregations on the backend. This would be desirable anyway for large datasets.

I don't think it will ever be possible to programmatically determine whether or not an aggregation - even an aggregation performed on the backend - is transformative enough to protect sensitive information, but certainly this could be a helpful tool to aid users in achieving this outcome.

**Comment by jonase** [comment]
see also https://github.com/akvo/akvo-lumen/issues/472 which is kind of a prerequisite to this issue. In general we need to do aggregations on the backend if we don't want to expose "raw data" to clients. Doing aggregations on the backend is also a path to supporting larger datasets.

**Comment by jonase** [comment]
@mtwestra I think this issue is too large/general. We should probably split it up per visualisation type.
