### ISSUE TITLE
Investigate Keycloak re user management MVP (estimate: 32)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#438]
It needs to be investigated which parts of user management workflow can be handled by Keycloak.

Here's part of the workflow we were unsure about:

<img width="554" alt="screen shot 2016-12-01 at 15 09 59" src="https://cloud.githubusercontent.com/assets/21127166/20796816/48e17362-b7d8-11e6-82a0-0af5f3e68617.png">

For the reference, here's the user management story map: http://mur.al/mBXBa8J1

**Comment by kardan** [comment]
## Emails
- @jonase setup (limited non SSL) email support in Keycloak. 
- Workflow around accounts are well supported in Keycloak. 
- Workflow around inviting to a org/tenants/group is not something that is built into Keycloak. 

## Profile management 
[Account Console](https://login.test.akvo-ops.org/auth/realms/akvo/account) (https://login.test.akvo-ops.org/auth/realms/akvo/account)

Keycloak does not have a profile image feature built in (https://issues.jboss.org/browse/KEYCLOAK-598?_sscc=t).

**Comment by kardan** [comment]
- [ ] Create user
- [ ] List users for tenant
- [ ] Add user to tenant
- [ ] Remove user to tenant

**Comment by kardan** [comment]
We did do investigations
