### ISSUE TITLE
Mockup for user management MVP

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#439]
Agreed at the last user story mapping session that we need a mockup of our MVP solution.
@Kiarii let us know when you have something to share!

For the reference, here's a link to user management story map: http://mur.al/mBXBa8J1

**Comment by Kiarii** [comment]
lets have a demo of the current state: https://invis.io/UZ9KUXR9R#/209476027_0-_Product_Page in tomorrows standup

**Comment by nadiagorchakova** [comment]
We've had a demo today, so I'm closing this issue...
