### ISSUE TITLE
Improve visualisation spec format (estimate: 16)

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#449]
# Context

Most of a visualisation's properties are defined by the `spec` object. Aside from the `type`,  `name`, `datasetId` and `visualisationType` (which are defined directly on the visualisation object, because we use these data in other parts of Lumen), everything needed to render or edit a visualisation is defined by the `spec`.

The current empty `spec`, from [Visualisation.jsx](https://github.com/akvo/akvo-lumen/blob/develop/client/src/containers/Visualisation.jsx), is as follows:

````
spec: {
     filters: [],
     datasetColumnX: null,
     datasetColumnXType: null,
     datasetNameColumnX: null,
     datasetNameColumnXType: null,
     datasetGroupColumnX: null,
     datasetGroupColumnXType: null,
     datasetSortColumnX: null,
     datasetSortColumnXType: null,
     reverseSortX: false,
     aggregationTypeY: 'mean', // default to mean
     labelX: null,
     minX: null,
     maxX: null,
     datasetColumnY: null,
     datasetColumnYType: null,
     labelY: null,
     minY: null,
     maxY: null,
     showLegend: null,
}
````

# Problem or idea

The current spec definition has been iterated on in an as-needed way, and is not formally defined anywhere outside of the frontend code.

The format of the spec is confusing and redundant.

Not having a formal definition makes it unclear what changes will break existing visualisations.

# How could we solve it?

We should formally define the spec, and improve upon the existing format, prioritising clarity and conciseness.

This will also create a clear version history for the spec, so we know when we are making breaking changes.

This will help with both #430 and #434

**Comment by gabemart** [comment]
My thinking on this issue is preliminary, but I propose a format closer to:

````
spec: {
  filters: [],
  axes: [
    {
      name: 'primary',
      dataColumn: null,
      dataColumnType: null,
      labelColumn: null,
      labelColumnType: null,
      aggregationColumn: null,
      aggregationType: 'mean', // default to mean
      axisTitle: null,
      sort: false,
      sortType: null,
    },
    {
      name: 'secondary',
      column: null,
      columnType: null,
      labelColumn: null,
      labelColumnType: null,
      aggregationColumn: null,
      aggregationType: 'mean', // default to mean
      axisTitle: null,
      sort: false,
      sortType: null,
    },
  ],
  legends: [],
}
````

## Thoughts

Labelling an axis as "X" or "Y" probably isn't necessary or even a good idea. E.g. if we want to change a vertical bar chart to a horizontal bar chart, it seems far easier to make a change like this:
````
spec: {
  ...
  axes: [
    {
      name: 'primary',
      ...
      orientation: 'vertical', // becomes "horizontal"
    },
    {
      name: 'secondary',
      ...
      orientation: 'horizontal', // becomes "vertical"
    }
  ],
}
````

than to transpose a bunch of properties from an "x" axis object to a "y" axis object. Furthermore, not all chart types have an "x" or a "y" axis.

It also seems extensible (and particularly, extensible without breaking existing visualisations) to model things this way

**Comment by gabemart** [comment]
It's also possible that labelling the axes as "primary" and "secondary" is unnecessary also - but my intuition is that it will make things easier for charts where only one axis is needed to render a visualisation

**Comment by jonase** [comment]
@gabemart I'm closing this one as I think every visualisation spec has been looked at/refactored. Feel free to reopen if necessary.
