### ISSUE TITLE
Filter option in visualisations

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#453]
# Context
Lumen Visualisation has a 'Filter' feature, which allows to remove/keep rows based on set criteria.

# Problem or idea
Setting filter **after** graph type, x axis and y axis were selected does not result in any changes to the graph.
Tested on http://demo.akvolumen.org

# Solution or next step
The expectation is that filtering would result in fewer data points on the graph.

**Comment by nadiagorchakova** [comment]
@gabemart I cannot replicate the issue again. I presume it had to do with timeout and not visualisations at all. so please close the issue, if you cannot reproduce it either.

**Comment by gabemart** [comment]
I haven't been able to reproduce - possibly it was caused by some side effects of https://github.com/akvo/akvo-lumen/issues/461 which we are addressing separately
