### ISSUE TITLE
Lumen admin console (estimate: 64)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#455]
# Context
As part of user management discussion and mockup review, we agreed that the next step would be setting up admin console.

For user management mockup, see this issue: https://github.com/akvo/akvo-lumen/issues/439

# Solution or next step
Admin console MVP should show a list of Lumen users, featuring their Name, Email and Role.
Here's the mockup view:

![9 ac members](https://cloud.githubusercontent.com/assets/21127166/21150303/d6112fa4-c15e-11e6-97f2-3bcdd328d33f.png)

It should be possible to Invite new members and delete the ones which should not have access to Lumen anymore. 
As already discovered, Keycloak has some limitations, e.g. it's not possible to add a profile photo.

## Backend implementation roadmap
- [x] GET /api/users - List users on tenant (protected, admin only?)
- [x] POST /api/user-invite - (protected, admin only) What about non existing users? Should send email to invited user. Invite needs secret, expire (timedate), used (boolean)
- [x] GET /verify/:id - (public), should be "consumed" if used. 
- [x] Move admin endpoints to /api/admin/[invites users] 
- [x] Update auth middleware to require tenant admin role for /api/admin access
- [x] Add a rule to nginx for verification links
- [x] Implement SMTP emailer & use correct host for emails
- [x] Add env vars to k8s deployment
- [x] Fix KC client naming
- [x] Rework smtp/dev-mailer creation
- [x] Move to an additional confidential KC client
- [x] Add PR for email/kc client secrets
- [x] Add email secret / config to clusters
- [x] Enable user registration in KC
- [x] Namespace keycloak groups
- [x] Remove (dev-env?)
- [x] Fix client form submit issue
- [x] Add tests
- [x] Clean up

**Comment by kardan** [comment]
Ref:
- https://github.com/keycloak/server_admin_guide/blob/1248c8013487e76f22d557c305af8946b904124d/topics/clients/oidc/service-accounts.adoc
- https://github.com/keycloak/server_admin_guide/blob/029494e5470edc01f460295ceeded742cef8aa18/topics/sessions/offline.adoc

**Comment by kardan** [comment]
- [ ] GET /api/users - List users on tenant (protected, admin only?)
- [ ] POST /api/user-invite - (protected, admin only) What about non existing users? Should send email to invited user.
- [ ] GET /verify/:id - (public), should be "consumed" if used.
- [ ] DELETE /api/users/:id (protected, admin only) Remove user from tenant. (sign out user?)

**Comment by kardan** [comment]
## Deployment notes

Pre:
- [ ] Create gorups with roles
- [ ] Set group members
- [ ] Update Deployment to use new env var bindings kubectl apply -f ./deployemnt with new build sha
- [ ] Make sure the new client have realm-admin role
- [ ] Make sure cluster have the new mailjet credentials (after key rotation)

Post:
- [] Remove lumen client
