### ISSUE TITLE
Authentication errors in the client due to expired access token

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#461]
# Context
When using Lumen at times (kinda often) you get error messages about authentication. It is then required to reload the page to be able to continue to work.

# Problem or idea
The problem is that the access token generated by Keycloak is too old. To get a new token we need to reload the browser to get a new token.

# Solution or next step
We should try and update tokens when needed before we issue request to the backend. There is a keycloak.updateToken method available in the Keycloak JS adapter. We should try and integrate that at call sites to the backend.
Ref: https://keycloak.gitbooks.io/securing-client-applications-guide/content/topics/oidc/javascript-adapter.html

**Comment by jonase** [comment]
I think there's also a timeout for these update tokens (`SSO Session Idle`) but the defaults are longer.
