### ISSUE TITLE
Gray out not-yet implemented features

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#462]
## Context
At the moment we have placeholder items in the UI. Examples are the bulk row editor. It's confusing that these just generates error messages in the JS console at the moment.

## Problem or idea
Before we enable users in the system it would be a good thing to hide / make it clear these are not available in the UI. Alternative we could keep things as in but just say we're fine with this as the product is still not "done"

## Solution or next step
Either remove, disable or keep them. @nadiagorchakova @Kiarii @loicsans @gabemart @jonase @peeb any strong ideas on these?

**Comment by Kiarii** [comment]
hide/remove would be my choice..

**Comment by nadiagorchakova** [comment]
I believe we should leave those in place, as they give some indication about the scope of Lumen functionality. 
I agree that it might be confusing from the UI point of view, so I'd propose to grey them out, or indicate in some other way that the said features are in development.

**Comment by jonase** [comment]
* Dataset view
  * Settings
  * Dataset Editor
    * Bulk row editor
    * Bulk column editor
    * Merge datasets

**Comment by nadiagorchakova** [comment]
Had a look just now.

When you click on the triple dot here, most of the options in the menu are not yet available. Only delete option has been implemented so far:

<img width="1028" alt="screen shot 2017-05-05 at 15 25 20" src="https://cloud.githubusercontent.com/assets/21127166/25747358/8bfc894a-31a7-11e7-810a-1eb020beaa0b.png">

And then, in the menu ribbon at the top, only Share option is available so far. 

<img width="270" alt="screen shot 2017-05-05 at 15 30 11" src="https://cloud.githubusercontent.com/assets/21127166/25747434/c3ca7b3e-31a7-11e7-9068-c091fb1779de.png">

**Comment by Kiarii** [comment]
- removing unimplemented/unfunctional buttons would be my preference..
