### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#464]
# Context
Where does Akvo lumen live? At the moment you need to know the url to your tenant. For example:
https://www.akvolumen.org ;; tries to host non existing www tenant
https://akvolumen.org ;; complains about cert and will show the default K8s backend.

# Problem or idea
There is no landing page where users can login see their tenants and navigate to them.

# Solution or next step
Build a new things that let people sign in and jump to their tenants. Maybe jumping between tenants should also be possible.

https://projects.invisionapp.com/share/UZ9KUXR9R#/screens/209476027_0-_Product_Page

**Comment by nadiagorchakova** [comment]
I'm not sure if it's feasible anymore to have a Lumen specific landing page as we're now talking about 'solutions' and packaging products and services in bundles.

**Comment by finnfiddle** [comment]
@nadiagorchakova can this be closed?

**Comment by nadiagorchakova** [comment]
let's close it indeed. Don't think Lumen-specific landing page will be needed any time soon.
