### ISSUE TITLE
Move to latest version of the resumed library

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#492]
# Context
When fixing the broke file uploads, we managed to introduce a new bug that was caused by lumen - resumed interaction. 

# Problem or idea
The problem is that we're using a SNAPSHOT version of resumed. We should reference a proper release.

# Solution or next step
Upgrade to a release.

**Comment by finnfiddle** [comment]
@kardan is this still an issue?

**Comment by kardan** [comment]
There is a new version of the resumed library but upgrading to latest deps are not the same as this issue. Hence closing.
