### ISSUE TITLE
Enhance client Nginx config

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#493]
# Context
When file upload broke we investigated headers that was passing though the different proxies. This raised some thoughts.

# Problem or idea
It seems like the Google load balancer already sets X-Forwarded-For, see https://cloud.google.com/compute/docs/load-balancing/http/#components. But we the header in our client Nginx config:
https://github.com/akvo/akvo-lumen/blob/develop/client/default.conf#L17
https://github.com/akvo/akvo-lumen/blob/develop/client/default.conf#L25

We also don't have gzip enabled in Nginx, this cause us to send more data than necessary. 

# Solution or next step
- [ ] Delete line 17 & 25 in the Nginx conf 
- [ ] Verify that we still receive X-Forwarded-For in the backend.
- [ ] Enable gzip in Nginx

**Comment by jonase** [comment]
done & merged
