### ISSUE TITLE
Don't use 'latest' on based Docker images

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#505]
# Context
To have more deterministic builds we need to rely on proper versions of based images. Using `latest` version in base images makes our builds a _moving target_.

# Problem or idea
Using `nginx:latest` or just `clojure` as our base Docker images makes the system builds less deterministic.

# Solution or next step
Use `nginx:1.11` and `clojure:lein-2.7.1` as base images.

**Comment by kardan** [comment]
Fully agree - merged!
