### ISSUE TITLE
Scatter plot - workshop 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#512]
# Context
In December, we discussed bar graph UI and workflow together with Gabe, Kiarii, Karolina, Loïc and Daniel. As a result, we improved the graph. It would be good to do the same exercise with scatter plot.

# Problem or idea
There were a few features in Gabe's earlier prototype that could be implemented for scatter plot, e.g. the varying size and colour hue of data points on the graph. Would be good to explore how to use these and other features best in the context of a scatter plot. Workflow in general can be address as well.

# Solution or next step
Let's schedule a workshop during this iteration period.

**Comment by janagombitova** [comment]
Closing this issue as Finn is working on improving scatter plots
