### ISSUE TITLE
Akvo theme for Keycloak

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-lumen#516]
# Context
We need a branded login page for all Akvo services. Lumen is the first application using the Keycloak service.

# Problem or idea
We're using the default Keycloak theme that doesn't follow Akvo's identity/branding. We have a _draft_ of a theme at https://kc.akvotest.org/auth/ but there are several user interactions that are broken, e.g. Register, Forgot password, etc.

# Solution or next step
Create a proper [Theme](https://keycloak.gitbooks.io/server-developer-guide/content/topics/themes.html) for Keycloak with Akvo's branding

**Comment by iperdomo** [comment]
https://github.com/akvo/akvo-platform/issues/5

**Comment by nadiagorchakova** [comment]
Closing the issue as we've deployed Akvo theme for Keycloak
