### ISSUE TITLE
Upgrade client dependencies

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#523]

**Comment by jonase** [comment]
This issue will possibly be more involved this time as we're going to attempt to update to webpack2

**Comment by jonase** [comment]
We handled https://github.com/akvo/akvo-lumen/issues/515 this iteration. I'll push this issue to the next milestone.

**Comment by jonase** [comment]
For this milestone we've update react to 15.5.4 + any third party library that needed to be updated as part of this
