### ISSUE TITLE
Vertical scrolling and scrollbar problems

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#524]
# Context
In a complex, multi-pane multi-view app like lumen, scrolling should feel natural, and it should always be obvious which part of an interface will scroll when the user inputs a scroll action

# Problem or idea
In a few different places, there is some odd vertical scrolling behaviour. For example in the maps editor, in some browsers there are two vertical scrollbars visible in the same area. Other side effects include elements which are intended to always display at the bottom of the viewport being displayed in other positions at certain viewport sizes

There are a couple of issues relating to this problem, but the basic issue is elements set to `height: 100%` in cases where the contents are taller than the viewport height

# Solution or next step
Most likely solution is replacing `height: 100%` on some elements high up the tree with `min-height: 100%` but naturally we will need careful regression testing with this change in cause other styling relies on the current system

**Comment by gabemart** [comment]
Another cause is browsers running under Windows showing scrollbars for content with an `overflow: scroll` property even when the content fits in its container without any overflow

**Comment by gabemart** [comment]
Replacing `overflow: scroll` with `overflow: auto` resolves 95% of these issues

**Comment by mtwestra** [comment]
@gabe, Can't really test this as I don't have access to different kinds of browsers. I trust you have looked at this in different browsers, so ok for me.
