### ISSUE TITLE
Investigate need / posibilities to expand javascript for derived columns (e.g. IF function)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#527]
# Context
Partners expect Lumen to support them with monitoring and assigning scores based on set criteria. 
For instance, using scoring for fair trade certification of farmers. For that, derived column can be used.

# Problem or idea

Javascript supports ternary operator which can already do the job. 
Our assumption is, however, that for a more user-friendly experience users need a more conventional IF function (the way it is used in Excel). 

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Duplicate https://github.com/akvo/akvo-lumen/issues/671
