### ISSUE TITLE
Flow monitoring support (design part)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#530]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
@nadiagorchakova is this still an issue?

**Comment by nadiagorchakova** [comment]
We still don't treat Flow monitoring data in any special way in Lumen. However, let's close it for now and create a more detailed issue when it's time to deal with it.
