### ISSUE TITLE
Getting data from Flow (authentication + technical import)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#531]
# Context

We need to integrate Flow with Lumen in a way that enables users to easily move Flow data to the Lumen environment. It is an important component for Lumen, as it greatly simplifies the way users interact with Lumen and Flow

# Solution or next step

Lumen uses a Flow Rest API for consuming data, passing JWT tokens for auth/authz.
Doc by Ivan outlining the reasoning behind the decision and some details on the implementation: 
[Lumen - Flow integration.pdf](https://github.com/akvo/akvo-lumen/files/790160/Lumen.-.Flow.integration.pdf)

**Comment by jonase** [comment]
https://github.com/akvo/akvo-flow-api

**Comment by jonase** [comment]
* Figure out how to get and store an offline token in the backend
* Client work: User needs to pick instance/survey-id/form-id
* Backend work: Build a lumen dataset using survey definition/data points/form instances.

**Comment by kardan** [comment]
Client:
- [ ] Error handling for wrong instance
- [ ] UI for when we have to wait for Flow API

Backend:
- [ ] Don't hardcode keycloak endpoints
- [ ]
