### ISSUE TITLE
Additional user admin console features

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#533]
# Context

Issue #455 was intended as a minimal implementation of user management functionality. This issue fleshes out the minimum implementation.

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

# Backend
- [x] Delete invite
- [x] Promote user to admin
- [x] Demote admin user
- [x] Remove user from tenant
- [x] Don't allow a tenant member to be invited again
- [x] Refactor test
- [x] Extend add tenant scripts to setup KC user & group

## Client 
- [x] Basic email address validation for user invites
- [x] Disable submit button until valid email address is entered
~~User list should also show pending invites~~
~~Don't allow a tenant member to be invited again~~
- [x] Enable/Remove admin privileges
~~Show feedback that invite email has been sent~~
- [x] Ensure admin user cannot delete herself
- [x] Ensure logged-in admin user cannot delete herself

Note: crossed-out items will move to a subsequent iteration

**Comment by peeb** [comment]
User invite form should validate that the entered text is a valid email address.

**Comment by kardan** [comment]
```
# Create invite
/api/admin/invites POST
202 Invite created

# Delete invite
/api/admin/invites/:id DELETE
204 Successful delete ;; Idempotent
410 Gone              ;; Consumed or expired

# Promote user to admin
/api/admin/users/:id PATCH {"admin": true}
200 OK {user representation}
404 Not found         ;; No user with id

# Demote user
/api/admin/users/:id PATCH {"admin": false}
200 OK {user representation}
404 Not found         ;; No user with id

# Remove user from tenant
/api/users/:id DELETE
204 No content        ;; Idempotent
```

**Comment by peeb** [comment]
See #355 for mistaken commit to this branch by @peeb - should have been #533

**Comment by kardan** [comment]
While figuring out how to extend the add-tenant script with user in keycloak (with 2FA enabled). I talked to @iperdomo who pointed me at https://lists.jboss.org/pipermail/keycloak-user/2016-January/004484.html

**Comment by iperdomo** [comment]
@kardan perhaps we can just _test_ the functionality. It seems that there is _some_ possibility that his works. https://issues.jboss.org/browse/KEYCLOAK-2513
