### ISSUE TITLE
Buttons look different across Lumen

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#536]
# Context
Perhaps we should have a more limited selection of buttons types (styling-wise)?

# Problem or idea
Here's a selection of different varieties of buttons:

<img width="150" alt="screen shot 2017-02-02 at 17 42 12" src="https://cloud.githubusercontent.com/assets/21127166/22558732/1003f344-e96f-11e6-846b-6545fb3804b8.png">
<img width="293" alt="screen shot 2017-02-02 at 17 42 02" src="https://cloud.githubusercontent.com/assets/21127166/22558731/1003a308-e96f-11e6-8343-6e7aeb206fed.png">
<img width="384" alt="screen shot 2017-02-02 at 17 41 54" src="https://cloud.githubusercontent.com/assets/21127166/22558733/101b0e26-e96f-11e6-93c5-30824e481a1c.png">
<img width="172" alt="screen shot 2017-02-02 at 17 41 43" src="https://cloud.githubusercontent.com/assets/21127166/22558734/1021fe5c-e96f-11e6-933c-8a82fe4d68ad.png">

# Solution or next step
Would be nice to have an opinion of the design team

**Comment by Kiarii** [comment]
i have already had a chat on this and other small issues with @Gabe but the priority has been on new features..
