### ISSUE TITLE
Some views obscured by sidebar

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#540]
# Context

Ideally, frontend views should behave as consistently as possible when minimising and maximising the sidebar. Right now, if you view a collection or the user admin (for example), the sidebar minimises but when you maximise it again it obscures the content of the view partially. The view should reflow in accordance with the visibility of the sidebar.

# Problem or idea

Views can be configured to display "maximised", but from then on do not respond to the state of the sidebar.

# Solution or next step

Audit areas in the application where this happens and ensure that the sidebar is never obscuring content.

**Comment by finnfiddle** [comment]
@gabemart is this still a thing? I cant see where you can hide the sidebar anywhere

**Comment by gabemart** [comment]
@finn yep this sidebar feature has removed so this issue can be closed
