### ISSUE TITLE
Update `bar` and `scatter` spec formats

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#541]
# Context
To keep visualisation specs as simple and easy to work with as possible, we are moving from a generic spec template to per-visualisation-type spec templates

# Problem or idea
`bar` and `scatter` templates have not yet been updated. We should update them ASAP, as all existing visualisations of these types may stop working when they are updated

# Solution or next step
Create type-specific specs for `bar` and `scatter` with no unnecessary properties

**Comment by finnfiddle** [comment]
@gabemart this looks like its been done already. can it be closed?

**Comment by gabemart** [comment]
@finnfiddle yep
