### ISSUE TITLE
Add 'capitalise first letter' transform

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#546]
Currently, we support three 'change case' options:

1) to lower case
2) to upper case
3) to Title Case

In some cases however, you only want to have the first letter capitalized, and the rest lower case. This would be 'lower case with first letter capital'. We should add this as a transform there.

**Comment by nadiagorchakova** [comment]
Isn't it the same as Title case transform? @mtwestra 
At least it worked for me:

<img width="223" alt="screen shot 2017-02-07 at 15 07 03" src="https://cloud.githubusercontent.com/assets/21127166/22694337/235f3166-ed47-11e6-99e1-4f64e73d6255.png">

**Comment by mtwestra** [comment]
@nadiagorchakova, almost: title case gives all words in a sentence a capital first letter. It is called like that because book titles are often printed that way: "Gone With The Wind". Sometimes that is not what you want - sometimes you just want a single capital letter: "Gone with the wind"

**Comment by nadiagorchakova** [comment]
yes, let's close it.
