### ISSUE TITLE
Reverse order input fields derived column

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#548]
Currently, the input field order on the derived column sidebar is:
1) code
2) new column title
3) column type
4) if transformation fails.

However, after working with it for a while, I notice that when you create a derived column, the first thing you want to provide is the name of the new column, then the code, and then the expected type. I also notice that I often forget to supply the expected type of the column, leading the empty columns.

I think we should change the order to reflect that flow, so:
1) new column title
2) column type
3) code
4) if transformation fails.

If we know the column type, perhaps we could even check if the expression result has the expected type during the user feedback.

**Comment by kardan** [comment]
This is no longer valid
