### ISSUE TITLE
Automatically recognize number columns

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#549]
# Context
At the moment, when we import data into Lumen, all columns are left as text strings. One of the first things a user then needs to do is convert all the columns to the right format. This is annoying, and leads to long transform chains in the transform log.

# Solution
We could start with automatically recognizing numbers. For that, we need to check if all cells in a given column, apart from empty ones, satisfy the following conditions:
* only contain alphanumeric symbols(0..9) and optionally a single decimal point '.'
* not contain leading zeros (as in that case it could be a telephone number)

The difficulty will be to deal with other numeric formats:
* 100.000 (decimal point as thousand separator)
* 1,53 (comma as separator)
* 10,000 (comma as thousand separator)
* 10,000.2993 (you get the idea)

It could be that this type of alternative number formats need to be supported by having some kind of options when the data is read in.

**Comment by kardan** [comment]
At the moment we auto detect numbers like:
1
100.000

Leading zeros will be ignored and parsed as number
