### ISSUE TITLE
Always trim strings at import

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#550]
Sometimes, data that is imported has leading or trailing strings. This can happen when data has been entered as free text, or when a single space is filled in to get past an obligatory question. It can be hard to spot them, so this can cause difficult situations during data cleaning.

As there is no clear use case for needing leading or trailing spaces, we will always trim strings at import time.

**Comment by kardan** [comment]
Currently we do trim the columns names

**Comment by finnfiddle** [comment]
@kardan is this still an issue?

**Comment by kardan** [comment]
This should be fixed.
