### ISSUE TITLE
Styling not displayed correctly in some cases

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#553]
In some cases, the styling of the header of the data column is not displayed correctly. I have not been able to reproduce this yet.

Browser: Chrome 56.
<img width="1005" alt="screen shot 2017-02-07 at 15 11 13" src="https://cloud.githubusercontent.com/assets/478954/22694566/0894c62e-ed48-11e6-98c1-87c0470b6bc2.png">

**Comment by gabemart** [comment]
This is probably related to the CSS caching issue, which we should address separately if needed

**Comment by mtwestra** [comment]
@gabe, ok, closing for now.
