### ISSUE TITLE
Order of UI  choices orientation legend not logical

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#554]
When a map is created and the user goes to the legend tab in a data layer, the position of the legend has four choices, displayed from left to right: 
1) Top
2) Right
3) Bottom
4) Left

This order is confusing, as the 'right' and 'left' buttons are actually on the left and right side. In addition, the naming is off as the top and bottom ones are actually also centered.

### Proposed solution
Proposed solution is to 
1) either fix the order while still having the four choices in a row: (left, right, top, bottom)
2) have two options: bottom and top, and left, middle, right.

**Comment by finnfiddle** [comment]
@gabemart I cant see where to change the position of the legend. Is this still a thing?

**Comment by nadiagorchakova** [comment]
We disabled this option when we introduced legends for multiple layers @finnfiddle As it was too much to display at the top or bottom of the map. So I think I'll close this issue then..
