### ISSUE TITLE
Color selector does not work

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#555]
### How to reproduce
1) create a map
2) go to the theme tab
=> the color selector cannot be used (nothing happens when it is clicked)

There does not seem to be an obvious error in the inspect tab.

**Comment by mtwestra** [comment]
Cleaning browser cache solved this issue. Keeping issue open to see if it reappears.

**Comment by gabemart** [comment]
I think we should close this now - if the CSS caching issue persists, we should address that separately

**Comment by mtwestra** [comment]
Ok, closing.
