### ISSUE TITLE
Add ability to change data layer name in maps

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#557]
### Context
Currently, the data layer name of a data layer in a map cannot be changed. It is always 'Undefined Layer 1'.

### Proposed solution
Give the user the ability to edit the name of the data layer. An alternative, for now, could be to simply give the layer the name 'Layer 1'.

**Comment by gabemart** [comment]
Unless something has gone wrong, the name of a data layer can be changed via the overflow menu, as per the mockups

![image](https://cloud.githubusercontent.com/assets/2589977/22728529/53445426-edd6-11e6-8362-3dfd5a9aec91.png)

**Comment by mtwestra** [comment]
@gabe, you're right, this was probably related to the issue with css styling
