### ISSUE TITLE
Display colour picker unique values in alphabetical order

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#559]
### Context
When a map is made with a data layer, the unique values in the colour picker on the theme tab are shown in an order that seems to be random. Perhaps it is ordered by the first occurrence. Sometimes, this gives unintuitive results, for example when I am making a lot of 'yes'/'no' maps, and the order of those changes between maps.

### Expected behaviour
Expected behaviour would be to show the unique values alphabetically.

**Comment by gabemart** [comment]
This seems like a clear improvement to me 👍

**Comment by gabemart** [comment]
closed via #565
