### ISSUE TITLE
Column name needs to be visible when colour selector is used

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#560]
# Context
Context is a user who is making a map, and has already created the data layer. Next step is to style the points. At this moment, the selection of the column to use for colour the points, and the selection of the colour, happen at two different tabs. This means that at the moment the user wants to select the colours, the context of the column name is not available. As the meaning of the values are often given meaning in the column name, this leads to the user having to go back and forth between the tabs to decide on the colours.

An example is a column 'water_point_functional', for which it makes sense to make 'Yes' green, and 'No' red. Another example would be 'high_risk_ecoli', for which 'Yes' would be red, and 'No' would be green. 

# Proposed solution
The column name needs to be visible when the colours are selected. Proposed solution is to move the move the selection of the colour coding column to the Theme tab. Additionally, we should reconsider the name 'Theme', and see if 'Styling' would be more clear.

**Comment by finnfiddle** [comment]
@gabemart this looks like its not an issue anymore right?

**Comment by gabemart** [comment]
@finnfiddle yep
