### ISSUE TITLE
Display text of empty cells in visualisations

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#561]
### Context
In many visualisations, the unique values of a column play a role and are displayed as part of a visualisation, for example a pie chart, or a bar chart. In these cases, empty cells can be an issue, because there is no text shown.

### Proposed solution
Provide the user with a custom text field for empty cells: "Display name of empty cells".

**Comment by finnfiddle** [comment]
Closing as it looks like its been fixed
