### ISSUE TITLE
Rethink design for data filters

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#562]
### Context
Currently, visualisations support adding multiple data filters. This supports well the generic use case in which a user might want to restrict the dataset on which a visualisation is based. 

However, there is a common use case that can be performed this way, but which seem to take too many steps. This is excluding empty items from aggregation based on the same row on which the aggregation is performed. For example, excluding null values, or rare items which basically mean 'unknown', such as '999'. 

### Proposed solution
In these cases, it might make sense to use a similar filter UI as used in the pivot table: a display of unique values, with a checkbox for easy removal or inclusion.

**Comment by gabemart** [comment]
I wonder if we should merge this issue with #474

**Comment by mtwestra** [comment]
@gabe, yes, this is the same issue. I'll put the text there and close this issue.
