### ISSUE TITLE
Bar charts - no visualisation produced

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#568]
# Context
<img width="1208" alt="screen shot 2017-02-08 at 12 16 11" src="https://cloud.githubusercontent.com/assets/21127166/22735361/a866eaae-edf9-11e6-8b3e-94402f2f9f29.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
merged & fixed
