### ISSUE TITLE
Multiple copies of visualisation on save

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#569]
# Context
New visualisations can be saved to the library

# Problem or idea
When saving a new visualisation, hitting the save button rapidly in succession can sometimes create multiple copies in the library

New visualisations aren't given an ID until the user hits "save" the first time, so window for this race condition is between the user hitting "save" the first time, and the application state updating with the visualisation id

# Solution or next step
We should keep track of when "save" is pending for new visualisations, and not dispatch further save requests to the backend until the first request is resolved

**Comment by jonase** [comment]
merged & fixed
