### ISSUE TITLE
Add a 'display title' property to visualisations

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#573]
### Context
At the moment, a visualisation has a title that is used for two things:
1) To display the visualisation in lists within Lumen
2) To display as visualisation title on dashboards or individual visualisations

However, these are two very different things, that should be separated. It often happens that the title that is displayed for a graph is quite long, and provides some context. The name of the visualisation in lists in Lumen is just for identification purposes.

### Proposed solution
Add an explicit 'Display title' property to the visualisation that can be supplied by the user. If not filled in, this could copy the name of the visualisation.

**Comment by finnfiddle** [comment]
@nadiagorchakova is this still a planned feature?

**Comment by nadiagorchakova** [comment]
@finnfiddle no, not in our short-term planning
