### ISSUE TITLE
Expand dataset filters if present

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#576]
### How to reproduce
1) create a visualisation
2) add a dataset filter
3) save and close the visualisation
4) reopen the visualisation
=> the dataset is only shown when the '+' button is clicked. 

This makes it hard to see if dataset filters are present on a visualisation, as there is no difference in initial display.

### Expected behaviour
Expected behaviour would be for the dataset filters to be shown (if present) when a visualisation is opened.

**Comment by janagombitova** [comment]
Handled with the redesign of visualisations editor
