### ISSUE TITLE
Ability to choose colours in pie charts

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#578]
# Context
At the moment, colours in pie charts are determined in a way that leads to unwanted results. As shown below, "Yes" and 'No' answers are shown as two different colours in two consecutive pie charts, which is very confusing.

<img width="509" alt="screen shot 2017-02-08 at 15 33 48" src="https://cloud.githubusercontent.com/assets/478954/22741634/26b69322-ee14-11e6-879c-d229f1c30384.png">

In addition, it is necessary for the colours to be coordinated across visualisations, so that the colours used in a map can be made the same as the colours used in a related piechart

# Solution or next step
There are two ways this could be approached:
1) a fixed (default) colour scheme could be applied to the unique values in answers, but only after they have been alphabetised. 
2) similar to a map, a user could specify a styling, in which she chooses the colour for each value present.

**Comment by gabemart** [comment]
I think for now, simply sorting the aggregated data by the label field before rendering it will be a big improvement. This ensures that segments with identical labels will be mapped to the same colors, even across different pie charts, *so long as those pie charts have the same number of total labels, and the labels are identical*.

Longer term, the solution might well be to let user pick colors per-segment, but I don't think that's realistic to target for this iteration.

**Comment by gabemart** [comment]
As an example - sorting the aggregated data is enough to ensure that the colors are consistent between the first two charts below. But adding a third label, as in the final chart, will upset the color scheme, even with sorting.

Another option would be to use some kind of hash on the label text to determine the segment color, which would ensure consistent mapping of label text to color - but in that case, there would be no guarantee against two or labels in the same chart mapping to very similar colors. 

![image](https://cloud.githubusercontent.com/assets/2589977/23410087/ed29d65c-fdc5-11e6-88f7-1053bfb6a76a.png)

![image](https://cloud.githubusercontent.com/assets/2589977/23410150/2a82db84-fdc6-11e6-907f-743845bb7463.png)

![image](https://cloud.githubusercontent.com/assets/2589977/23410179/3a135934-fdc6-11e6-8c6f-3c0030c0920b.png)

**Comment by mtwestra** [comment]
@gabe, I agree that sorting and then assigning is probably the only realistic way at this moment.

However, I think we will need to move towards colour pickers for pretty much all visualisations, as colours are so full of meaning usually, that they can't really be assigned automatically. In addition, if you include empty data this would always come first (at least I guess so), which would give rise to differences between pie charts that include or exclude 'no data'. 

Overall, I guess the general principle to go for is: users can assign colours to unique values that are used in visualisations, in the same way as in maps.

**Comment by gabemart** [comment]
>  In addition, if you include empty data this would always come first (at least I guess so)

Currently we check for empty data and "force" it be last, so the presence or otherwise of empty data  shouldn't effect the colors of other segments (empty data is unique in this regard)

Going forward, user-defined colors sounds like something we will have to devote some time to

**Comment by mtwestra** [comment]
@gabe, a great, that will help already.
