### ISSUE TITLE
Can't select X-axis column before selecting Y-axis column

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#588]
### How to reproduce
1) create an empty visualisation
2) select a datasource
3) try to select a bucket (X-axis) column
=> the X-axis column can not be selected. Only after selecting a Y-axis column can the X-axis column be selected.

To be clear: the dropdown of columns is shown correctly, but if one item is selected, the selection is not saved, and the dropdown reverts to its unselected state.

### Expected behaviour
I would expect that I can select the X or Y column in any order.

**Comment by gabemart** [comment]
Closed via #632
