### ISSUE TITLE
Replace "legend" text with custom text

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#589]
### Context
Currently, when we show a legend in a chart, we display the word 'Legend', and then the unique values plus their colours. However, this does does not help the user in understanding what the values mean. For example, if the values are "yes", and "no", the user needs to see the question that was asked in order to interpret the meaning, for example "Is the water point functioning?", or "Is the water point broken?".

### Proposed solution
The proposed solution is to replace the word 'Legend', which is superfluous, by a custom text. This custom text could be prefilled with the name of the column.

**Comment by nadiagorchakova** [comment]
Can be defaulted to column name but should be user-editable as well.

**Comment by nadiagorchakova** [comment]
Looks like it's implemented and deployed
