### ISSUE TITLE
Visualisation and Dashboard resizing workflow

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#591]
### Context
Currently, the title of a visualisation is shown at the top of the visualisation. The string is not wrapped, which means that if the graph is scaled, a long title is cut off, as shown in the image below.

<img width="357" alt="screen shot 2017-02-15 at 11 40 57" src="https://cloud.githubusercontent.com/assets/478954/22970767/a95fbede-f373-11e6-8733-2bc5ff8c29f5.png">

### Proposed solution
Proposed solution is to let the title wrap over two or more lines.

**Comment by nadiagorchakova** [comment]
Added it to the next iteration. Considering we give test access to partners soon, it might complicate user experience, especially when you don't know you can resize the graphs by hand.

**Comment by nadiagorchakova** [comment]
an example of a cut-off axis title from a demo dashboard:

<img width="536" alt="screen shot 2017-03-29 at 10 27 19" src="https://cloud.githubusercontent.com/assets/21127166/24445521/75b54af0-146a-11e7-97c8-508e0a3b6d00.png">

**Comment by nadiagorchakova** [comment]
Probably, for the start, we could limit the length of axis titles.

Design problem:
What should we be adjusting to display the graph correctly?

**Comment by gabemart** [comment]
After discussion, we have agreed to tackle the issue of text wrapping in visualisations as part of the larger issue of creating visualisations that can render correctly at a wide range of sizes.

This poses both design and technical challenges.

Design challenges include:

* How to handle when a visualisation must render in a space too small to include all of its text and other detail in a legible way. In the ideal case, what should we show to the user? How can we make sure important information is still available, in a generic system?

* How to preview how a visualisation will look at different sizes when the user is creating a visualisation in the editor. How can we prevent surprises?

Technical challenges include:

* Handling the display of text when using SVG or canvas, where we cannot rely on the browser to resize and wrap text for us.

* Handling the resizing of complex visualisations in a performant way

# Next steps

Let's arrange a meeting for next week to go over the problem space. I will prepare some material on the scope of the challenge, and the potential technologies we can use, as I see them

**Comment by gabemart** [comment]
Merging #704 into here

quoted below:

---

# Context
For several columns, Y axis title is not displayed on the line graph.

# Problem or idea
Looks like when values are 5,000 and above on Y axis, axis title disappears..

<img width="1275" alt="screen shot 2017-05-01 at 15 41 01" src="https://cloud.githubusercontent.com/assets/21127166/25581095/deca43d0-2e85-11e7-99f4-8eae9a494127.png">


# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment]
Another example to add to this issue:

<img width="682" alt="screen shot 2017-06-28 at 17 00 06" src="https://user-images.githubusercontent.com/21127166/27644237-42ad9d0a-5c23-11e7-81a5-1f679a96d0e8.png">

https://demo.akvolumen.org/visualisation/59520993-5f55-47f2-a2e9-35c13a4e7a23

**Comment by nadiagorchakova** [comment]
we'll review dashboard survey results and decide what can be done next

**Comment by janagombitova** [comment]
As many of the proposed changes are already implemented or handles in some other way and because the example visualisations with issues no longer exist I am closing this issue. If we find a case we we log it in again.
