### ISSUE TITLE
Add ability to create histograms

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#594]
### Context
Currently, when the x-axis (bucket) column is numerical, every numerical value gets its own bucket. However, for many numerical variables, it makes sense to define bins with a certain width, so a histogram can be created.

### Proposed solution
When the bucket axis is numeric, allow creating bins. One of the easiest ways to do this is to let the user specify the number of bins to use, and let the system compute the bin sizes. Other options could also be possible, and need to be investigated.

**Comment by nadiagorchakova** [comment]
Joy has commented that a histogram in Lumen would in particular help with data cleaning, e.g. identifying outliers.
