### ISSUE TITLE
Horizontal bar chart

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#595]
### Context
Currently, we only support vertical bar charts. However, in some cases a horizontal bar chart is a better way of displaying data.

### Proposed solution
Proposed solution is to add a visualisation type 'Horizontal bar chart'.

**Comment by nadiagorchakova** [comment]
What's especially nice about horizontal bar charts is that you can display long text labels for bars in a more readable way. This could be very handy with Flow data where columns represent often long survey questions. 

Example of a horizontal bar graph:
<img width="477" alt="screen shot 2017-05-24 at 17 40 05" src="https://cloud.githubusercontent.com/assets/21127166/26412302/9760d114-40a8-11e7-855c-ea8f465c6cd9.png">

**Comment by janagombitova** [comment]
Released and in the wild
