### ISSUE TITLE
Pivot table - show totals for sums and rows

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#601]
### Context
The current version of the pivot tables shows the aggregated values for all the cells defined by the choice of row and column aggregation. 

In the case of count and sum, we can also show show the totals for each row and each column. It is often useful to see the totals, for example to check if a sum is ok, or to judge the relative magnitude of items. In the case of percentages, it is convenient to see if the percentages add up to 100%.

### Proposed solution
For each row and column when count or sum are chosen as aggregates, display the totals. Totals for each row can be shown on the right hand side of the table, totals for each column at the bottom.

**Comment by gabemart** [comment]
closed via #647
