### ISSUE TITLE
Pivot table - naming UI elements

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#603]
In the pivot table definition screen, there are a number of items for which we should look at the name:

* Aggregation: Although what technically happens is 'aggregation', I wonder if users are familiar with this term, and would understand what is meant in this context. In Excel, what is used here is the word 'values' (together with a summation symbol), which might be an alternative. Or perhaps something more descriptive as 'values shown in cells'.

* Categories: I don't quite understand the use of the word categories here. The vertical dimension could also be said to have categories. Perhaps 'Columns' is more clear here as it refers to the columns of the table?

* Category values and Row values: Perhaps we could be more explicit here that this UI element is about excluding / selecting certain values. Perhaps: "filter row values" and 'filter column values'?

**Comment by janagombitova** [comment]
We now have Aggregation, Rows and Columns as categories grouped in the visualisation editor. Aggregation can indeed be confusing, but it is now used across all visualisation types and we have not received any feedback on this so far. I am closing the issue for now and we can reopen it later if needed
