### ISSUE TITLE
Pivot table - column width / hyphenation

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#604]
### Context
Currently, a pivot table is optimised to show as many columns as possible on the screen, so as to avoid the user having to scroll. However, this leads to a number of unwanted issues at extreme cases, as shown in the image below:
<img width="947" alt="screen shot 2017-02-20 at 12 36 37" src="https://cloud.githubusercontent.com/assets/478954/23123616/61e6352a-f769-11e6-8c55-aa5c48812504.png">

### Proposed solution
After discussing this, we propose the following set of changes:
* use a minimum column width of about 10 characters wide
* on columns: cut off long names after 64 chars and show full name on hover
* on columns: wrap names (exact hyphenation will be described in a different issue).
* on rows: cut off long names after 64 chars, and show full name on hover
* on rows: don't wrap - show name on single line.

**Comment by gabemart** [comment]
@mtwestra I'm not sure I agree that we shouldn't wrap row titles - 64 chars is still very long, especially seeings as, without wrapping, a single long row title will dictate the width of the entire column

I agree we should minimise wrapping in that column if possible, but I think it might still be desirable to allow that column to wrap to some degree in some cases

**Comment by gabemart** [comment]
Perhaps it would be acceptable to limit wrapping to a max of 2 lines for row titles?

**Comment by mtwestra** [comment]
@gabemart yes, I think wrapping to 2 lines would be exceptable

**Comment by gabemart** [comment]
Closed via #628
