### ISSUE TITLE
Pivot table - inprove hyphenation

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#605]
### Context
Currently, we use the the CSS statement "word-break:break-word" to specify whether text labels in pivot tables are being wrapped. Although this does wrap the lines, the quality of the wrap is not very high, as can be seen in the image below:

<img width="983" alt="screen shot 2017-02-20 at 12 14 47" src="https://cloud.githubusercontent.com/assets/478954/23123884/8b70f708-f76a-11e6-9d04-d630143ddac7.png">

In CSS3, there is a new way of specifying wrapping, and this is through the "hypens" property (https://developer.mozilla.org/en/docs/Web/CSS/hyphens). From the specification: "Hyphenation rules are language-specific. In HTML, the language is determined by the lang attribute, and browsers will hyphenate only if this attribute is present and if an appropriate hyphenation dictionary is available. "

Specifying "hyphens:auto" instead of the "word-break:break-word" leads to this result:

<img width="984" alt="screen shot 2017-02-20 at 12 14 39" src="https://cloud.githubusercontent.com/assets/478954/23123991/03856dc8-f76b-11e6-8e41-af1bc15f1a64.png">

Which is much better.

### Proposed solution
The proposed solution is to investigate using the hyphens property to specify wrapping.

**Comment by gabemart** [comment]
@mtwestra I wrote a detailed reply here yesterday, but it seems like it didn't save properly and has disappeared.

To summarize:

* `hyphens: auto` doesn't have very wide browser support yet (in particular it's not supported on Chrome on Windows

* `hyphens: auto` doesn't guarantee against cell contents overflowing out of the bounds of the cell, which is quite serious when used in a table

I think we should implement #604 first and then see where we are

**Comment by mtwestra** [comment]
@gabemart 
On the first one, I indeed misinterpreted the browser support (http://caniuse.com/#feat=css-hyphens), I missed the fact that green here means 'Mac only'. So yes, let's do #604 first.

If we still run into trouble, perhaps something like https://github.com/bramstein/hypher could be useful.
