### ISSUE TITLE
Pivot table - add different ways to display a value

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#606]
### Context
Currently, we support different types of aggregations for values shown in cells: mean, max, min, count, sum, where count is the default.

When count or sum is used, there are a number of logical ways that the values can be displayed. The actual value is one option. Fractions, as expressed in %, is another. 

Other options for sum are:
* Sum as fraction of total
* Sum as fraction of row
* Sum as fraction of column

Other options for column are:
* Count as fraction of total
* Count as fraction of rows
* Count as fraction of Columns

### Proposed solution
In the current selection of value selection, add the 6 options described above.

**Comment by mtwestra** [comment]
In addition, in many cases it might be valuable to have two different ways of showing a value in a single cell. For example, you might want to show count as a number, and count as a percentage of the total.

**Comment by gabemart** [comment]
closed via #647
