### ISSUE TITLE
Pivot table - hoover information message is always shown

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#607]
### Context
In the pivot table specification page, when a user hovers over the aggregation method, a message is shown "Choose a category column and a row column to use aggregations other than count". However, this message is always shown, also when a row column and category column are already selected

<img width="405" alt="screen shot 2017-02-20 at 13 43 57" src="https://cloud.githubusercontent.com/assets/478954/23125581/bb723932-f772-11e6-91e3-b64a64294731.png">

### Proposed solution
Only show message if row/category column are not selected yet.

**Comment by gabemart** [comment]
This was fixed in the last iteration (I didn't actually realise there was an issue for this!)
