### ISSUE TITLE
Limit number of categories (columns) in pivot tables

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#609]
# Problem or idea
In some cases a pivot table can be orders of magnitude larger than the source dataset. An example where this happens is if the user selects two columns (for rows and categories) that are both "id" columns (i.e. all unique values). Then the resulting pivot table will contain `n^2` cells (there are often many more rows than columns for typical datasets). 

The point of a pivot table is to reduce and aggregate the source dataset. A pivot table *is* the visualisation so if the pivot table is too large it is also less useful.

# Solution or next step

There might be many options on how to best solve this:

* Set a maximum number of categories. If the number of categories exceeds a certain threshold we can notify the user that we don't support a pivot table using this column as a category column.

* Set a maximum size of the resulting pivot table. The threshold could also be a limit on the number of cells, which we can calculate (`columns x rows`) and if exceeded report that pivot table is too large.

**Comment by nadiagorchakova** [comment]
The suggestion from milestone planning is to put a limit of 50 to the number of columns.

**Comment by gabemart** [comment]
As a first step, we can limit the number of categories to 50 on the client side, even when the API returns data for more than 50 columns. 

It would be better (faster, more efficient) if the api returned an error of some sort, but at the least having a client-side check will avoid attempting to render a table so big that it locks / crashes the browser

**Comment by gabemart** [comment]
closed via #648 - but we should revisit this at the backend-level at a later date
