### ISSUE TITLE
Dashboard - improve visual quality (borders, autoscale) of visualisations and text boxes

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#611]
# Context

Currently, the visualisations need to be manually re-sized once they are added to a dashboard.
Otherwise, part of legend and also axis labels could appear cut off.

<img width="922" alt="screen shot 2017-02-21 at 14 26 04" src="https://cloud.githubusercontent.com/assets/21127166/23166654/b8a2e9d4-f841-11e6-838c-22fccff3372b.png">

# Problem or idea

Our presentation to Hilton (also their internal one to the board) requires a professionally looking dashboard

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Multiple improvements have been made on the dashboard improving is visual appeal. I am closing this issue as it is not specific enough anymore. For concrete cases we will open new issues
