### ISSUE TITLE
Increase selection of colours

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#616]
### Context
Currently, we have only a limited number of colours that can be selected, as shown below.

<img width="223" alt="screen shot 2017-02-28 at 12 42 07" src="https://cloud.githubusercontent.com/assets/478954/23404056/5a2a8afc-fdb3-11e6-8488-7baf76311810.png">

This is a bit limited, and misses neutral colours such as greys. For example, it misses a clear 'orange', which is often needed in traffic-light type colour schemes for points.

### Proposed solution
Increase choice of colours, and include set of grey scales.

**Comment by gabemart** [comment]
related to #592

**Comment by gabemart** [comment]
closed via #629
