### ISSUE TITLE
Dashboard - add filter / order options to find visualisations

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#620]
### Context
Currently, when a user edits a dashboard, on the left hand side a list of all visualisations is shown. When many visualisations are present, it becomes very hard to find back a visualisations. 

### Proposed solution
Add options to make it easier to find back a visualisation. For example:
* Ordering. Often, a user goes back and forth in adapting a visualisation and then putting it on a dashboard. Therefore, in many cases the most recently added visualisation will be the one the user needs. When the user can sort the list of visualisations with 'most recently changed', this would already help
* Filtering. If the left hand column has its own filter (perhaps immediate, without needing to click 'search', a user could enter some characters she knows are in the name of the visualisation, and find it back in that way.

**Comment by nadiagorchakova** [comment]
Looks like this one was implemented and deployed.
