### ISSUE TITLE
Custom order of items in legend

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#625]
### Context
Currently, items in a legend are shown in alphabetical order. However, this does not always make sense, especially with ordinal data types, as shown below.

<img width="200" alt="screen shot 2017-03-01 at 10 02 58" src="https://cloud.githubusercontent.com/assets/478954/23452987/c8c98810-fe66-11e6-9f15-f5fefe9d3aa4.png">

### Proposed solution
Proposed solution is to allow users to change the order of the items in the legend, for example as part of the UI where they specify the colours for each item.

**Comment by janagombitova** [comment]
I have changed the title to not limit the improvement to only Maps. It might be valuable to change the order of items in the legend for any visualisation option. 

In the image Mark shares above ideally the order of things would be from the highest risk to the lowest (or another way around). 

![screenshot 2019-03-04 at 11 40 20](https://user-images.githubusercontent.com/12456965/53728517-3b62c280-3e73-11e9-9d11-a9786a3230e6.png)

In this case, the lowest range should go first and the highest last to make it easier to read the legend and associated colours.

**Comment by Kiarii** [comment]
Based on the assumption that there are a ltd number of categories on which to apply a custom order, we could 
- introduce a legend-category-order-editor where the user opts for a custom order ad can use a drag and drop to arrive at the desired order as illustrated.. 
- determine whether we refer to this as categories or values and word the UI accordingly
![image](https://user-images.githubusercontent.com/12692444/64532644-8e359f00-d31a-11e9-81e4-28b29cc100a4.png)

**Comment by janagombitova** [comment]
@tangrammer I checked all our visualisations where we have a legend and it is useful for all cases: Bar, Bubble, Map, Pie, Polar, Donut, Scatter. 

I propose we start with Pie  (as there is where you started) > push to production under the flag > test internally > once confirmed that all is ok add to the other visualisation types, in the same way, > push to all users without feature flag

**Comment by janagombitova** [comment]
Found one little bug with the current implementation: 

<img width="1250" alt="Screen Shot 2020-08-11 at 13 36 46" src="https://user-images.githubusercontent.com/12456965/89892945-c5ba6480-dbd7-11ea-9fc5-226ff09a514b.png">

It shows also for `polar chart` what is fine, but the order is not applied - so it does not actually work. 

For `pie` and `donut` where it also shows, it works like a charm

**Comment by tangrammer** [comment]
@janagombitova @Kiarii 
which will be the UX option(s) /design in case stack bar chart?
<img width="963" alt="Screenshot 2020-08-14 at 09 13 53" src="https://user-images.githubusercontent.com/731829/90223545-8e81c880-de0e-11ea-8440-c3e802f0ff15.png">

**Comment by janagombitova** [comment]
> @janagombitova @Kiarii
> which will be the UX option(s) /design in case stack bar chart?

@tangrammer my suggestion would be: 
1. I create a bar chart
2. I can specify the legend order
3. But I decided to split the bars meaning my legend is now based on the data from the sub-bucket column. I should now be able to change the order of the legend based on the values for the sub-bucket column (currently the bucket column data still shows in the legend-order editor
4. If I remove the sub-bucketing, the legend order is based on the bucket column as before. 

The above should apply also if more than one metric column is selected. In that case, you cannot split the bucket (what is good and should remain like that) but the legend then shows the different metric columns. 

Considering how things are organised in the side panel I would propose to reorder things as now it is chaotic and decisions about the legend are not in the same spot but broken into two places. How about we move `show legend` under advanced, the same way as we have it for Pie charts? 
<img width="360" alt="Screen Shot 2020-08-17 at 11 13 02" src="https://user-images.githubusercontent.com/12456965/90379195-afe6ec80-e07a-11ea-9f5f-044d4677e407.png">

So this means 3 changes: 
* if sub-bucket selected to ensure that the legend order is based on the sub-bucket data 
* if more than one metric column is selected, make the legend order is based on the metric columns
* move the show legend option and leged order under `Advanced` in the same way as we have for Pie charts

**Comment by tangrammer** [comment]
@janagombitova scatter isn't ready yet :) https://github.com/akvo/akvo-lumen/pull/2815#issue-467272906

**Comment by janagombitova** [comment]
> @janagombitova scatter isn't ready yet :) [#2815 (comment)](https://github.com/akvo/akvo-lumen/pull/2815#issue-467272906)

Ah! You got me too excited about all these changes :)

**Comment by janagombitova** [comment]
Besides the public link bug, I found also this one: Scatter plots colour does not match the legend. Before when I created a scatter plot and only defined then y and the x, the scatter dots were all the same colour. Now they get coloured and once I select the category column that should define the colour, it is not applied. 

<img width="1218" alt="Screen Shot 2020-08-18 at 13 34 50" src="https://user-images.githubusercontent.com/12456965/90508240-a089a100-e157-11ea-825c-b78dea560f46.png">

**Comment by janagombitova** [comment]
and one more: On maps, organising the legend works very well. But the colours on the legend that shows on the map are different from the colours shown in the legend editor. Changing the colour scheme does not make a difference in the legend editor.

<img width="1216" alt="Screen Shot 2020-08-18 at 13 48 29" src="https://user-images.githubusercontent.com/12456965/90509476-aa140880-e159-11ea-8ba7-57bff5c5d8b6.png">

**Comment by janagombitova** [comment]
Support documentation all set: https://lumensupport.akvo.org/article/show/85897-visualisation-colours-and-legend

**Comment by janagombitova** [comment]
Just for sake of keeping the updates also on the issue. The map problem with the colours not matching and the scatter plot one too are now resolved. However, when the order of values is changed in other visualisations (like bar) it is not applied. WiP and needs to be handled before we can push to users.

**Comment by janagombitova** [comment]
After another test round on dark-demo we are good to go
