### ISSUE TITLE
Pivot tables - can't vertically resize pivot table in dashboard editor

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#644]
### How to reproduce
* Create a pivot table with small vertical size (for example by not selecting buckets for the rows)
* save the pivot table
* create a dashboard and put the pivot table on it
* try to reduce the vertical size of the pivot table
=> the pivot table can't be reduced in size, only made larger

Example below - this is the smallest vertical size.
<img width="561" alt="screen shot 2017-03-07 at 15 30 11" src="https://cloud.githubusercontent.com/assets/478954/23660833/01168e8c-034b-11e7-97d2-b95a7d6f4a79.png">

### Expected behaviour
The pivot table should be able to be resized to any size.

**Comment by gabemart** [comment]
Dashboard entities are "sized" based on a responsive 12-column grid. Currently, the default minimum height for visualisations is 4 units, on the basis that most visualisation types will be indecipherable (or even throw rendering errors) if we attempt to render them at too small a size.

I'll chance the min height for pivot tables from 4 to 1 - I suspect 2 might be a better long-term min-height than 1, but let's try 1 and see how it goes.

**Comment by mtwestra** [comment]
@gabe, this sounds fine
