### ISSUE TITLE
User admin - implement invite manager

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#646]
# Context
Currently an admin user can invite a user to create a Lumen account but there is no way to manage these 
user invitations.

# Solution or next step
Refactor the `Users` component to be polymorphic + conditionally display **pending** users (invites). Create a delete invitation action to allow for rescinding invitations - the backend API endpoint for this is already implemented by @kardan.

![manageinvites](https://cloud.githubusercontent.com/assets/155294/23852550/46db6c6e-07e0-11e7-86d8-45834c9ea4a9.png)

This issue follows on from #533

**Comment by kardan** [comment]
Duplicate https://github.com/akvo/akvo-lumen/issues/679 ?

**Comment by peeb** [comment]
@kardan yes. I'm closing this.
