### ISSUE TITLE
Derived column creation fails unexpectedly

### ISSUE THREAD

**Issue by mtwestra** [akvo/akvo-lumen#655]
### How to reproduce
Phenomenon was observed in a dataset with:
* first column of type text, called 'date'
* second column of type text, called 'country'
* derived column with code 'row["date"]' and type text fails
* derived column with code 'row["country"]' succeeds.
<img width="1050" alt="screen shot 2017-03-14 at 15 36 21" src="https://cloud.githubusercontent.com/assets/478954/23905823/88cba9f8-08cc-11e7-8738-85d22d683d6d.png">

### Expected behaviour
Derived column should work in both cases.

**Comment by jonase** [comment]
this happens when a csv file contains a byte order mark (BOM)

**Comment by jonase** [comment]
This issue will be resolved by https://github.com/akvo/akvo-lumen/issues/672. Specifically because the `AutoDetectReader` we're now using [drops the BOM](https://github.com/apache/tika/blob/master/tika-core/src/main/java/org/apache/tika/detect/AutoDetectReader.java#L88-L92) for us.
