### ISSUE TITLE
Refactor frontend api module

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#667]
# Context
The frontend api module makes sure that the auth token is always up-to-date when making backend requests

# Problem or idea
In addition to updating the auth token the api module also parses the result json payload and throws away the rest of the `response` object. This means that the call sites can't inspect e.g. the http response code making it harder to do proper error handling or receiving no-body responses (e.g. 204).

# Solution or next step
Delegate the body parsing to the call sites. So instead of `api.get(endpoint).then(result => ...)` we should for example do `api.get(endpoint).then(response => response.json()).then(result => ...)`

**Comment by peeb** [comment]
@jonase I'm thinking that this is an ideal opportunity to standardise API call imports and to uniformly use `api.get()` rather than `get()`. Thoughts?

**Comment by jonase** [comment]
Merged :+1:
