### ISSUE TITLE
Extend add tenant script to add clients valid urls

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#670]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
On the topic of why we need this. It's currently not possible to have subdomain wildcards in redirect urls (`https://*.akvolumen.org`) and there's a good chance that this will never be supported. See for example https://github.com/keycloak/keycloak/pull/3241 and http://lists.jboss.org/pipermail/keycloak-dev/2016-September/008133.html
