### ISSUE TITLE
Smart data type recognition on import (CSV files)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#672]
# Context
Currently a user has to do a number of transforms to convert text to date or number in imported CSV datasets.
Flow-imported datasets (demo version) have ' data type smart recognition' in place.

# Solution or next step
Implement smart data type recognition on import of CSV files

**Comment by nadiagorchakova** [comment]
no mock-ups needed, a pure technical issue

**Comment by jonase** [comment]
merged :+1:
