### ISSUE TITLE
Setting up analytics (Piwik)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#675]
# Context

There are two use cases for setting up Piwik analytics
- Akvo internally would like to track user behavior to provide better service and improve Lumen. For this case, it would be interesting to track the library page inside each partner's instance, e.g. https://demo.akvolumen.org/library and Lumen landing page.
- partners will eventually be interested in statistics on their publicly shared visualisations and dashboards. I imagine they would be interested to know stats on page views, geo location of viewers, etc. 
- partners might also be interested in stats on visualisations and dashboards embedded on their own websites

# Problem or idea

# Solution or next step
To configure Piwik, we need to install Piwik JavaScript tracking tag. More on that [here](https://piwik.org/docs/installation/#configuring-piwik).

Ideally, visualisations and dashboards should have their title reflected in the URL. Otherwise, it might be difficult to use Piwik analytics. For the first implementation, however, we could probably do without it.

**Comment by kardan** [comment]
We should hook up Piwik. There are two different was to go about it. 

- Global: track usage in one "bucket" and then we only need to setup one thing one time in Piwik and add a js lib to our client app (+ an id). This is easiest to setup and makes global queries simple.
- Tenant: track in one bucket per tenant. This will require us to add the tenant to Piwik every time we create a new tenant. It will make stats per tenant easiest but more difficult to get the "full lumen" stats.

**Comment by nadiagorchakova** [comment]
When I think about use cases, we'll need to track number of clicks on all publicly shared dashboards as part of PPP4 grant reporting. For this case, the 'global' option seems to be more suitable.

On the other hand, I foresee some partners would want to see their individual tenant stats. Will we be able to extract these stats from our 'global bucket'?

**Comment by nadiagorchakova** [comment]
shall we at some point return to this issue @kardan?
It would be nice to track (global) usage of Lumen features to see which features are most popular (most used), and which are not. Could inform our decisions going forward.

I must say that my earlier assumption that partners would also be interested in their own instance stats seems to be wrong.

so we would need to define events that would be interesting for us to track https://matomo.org/docs/event-tracking/#tracking-events (as shared by @iperdomo )

**Comment by iperdomo** [comment]
Just as a side-note: when _track the usage of Lumen features_ we need to make sure all data sent fo Piwik (now Matomo) is anonymous. Let's have GDPR always in mind :)

**Comment by Lynngre** [comment]
@iperdomo & @nadiagorchakova: 

1. we by default, respect anyone's wishes who have selected to not be tracked
2. it is legal that we collect IP Addresses as long as we respect the user's wishes re switching the tracking off & we detail the info in our policies & it's easily available 3. & that we stop and remove all info when/if requested.  
3. Tracking is not illegal by GDPR as long as we have good reason & helps us to know which country visits come from for example.
4. Data must be protected correctly.
5. Akvo would like to track more than clicks/virtual visits. So for our own stats we would like to add visits/view tracking for all the instances - the tracking of clicks would be additional to those in-app metrics.

**Comment by nadiagorchakova** [comment]
Some initial thoughts on the events that we could try tracking with Matomo (Piwik)

- choosing Data File as a data source when loading dataset to Lumen
- choosing Link as a data source when loading dataset to Lumen
- choosing Akvo Flow as a data source when loading dataset to Lumen
- choosing GeoTIFF as a data source when loading dataset to Lumen
- merging datasets (clicking on a 'merge' button?)
- deriving a new column (clicking on 'derive column'?)
- rendering of a map with raster data layer (can this be tracked?)
- rendering of a map with geoshape data layer (can this be tracked?)
- click on 'share' a vis
- click on 'share' a dashboard
- click on 'get embed code' for a vis
- click on 'get embed code' for a dashboard
- click on 'Help' button

About event-tracking with Matomo: https://matomo.org/docs/event-tracking/#tracking-events

**Comment by nadiagorchakova** [comment]
@finnfiddle so I tried to draft events we could track, not sure it makes sense from event set-up point of view. It's open to suggestions.

**Comment by nadiagorchakova** [comment]
@finnfiddle if we just mention type of page in the title, will it mean that we won't be able to aggregate all visualisation-related events? Trying to understand implications from analytics point of view.

**Comment by finnfiddle** [comment]
@nadiagorchakova I suggest I implement it and then you go in to the analytics and see if anything needs to be improved in terms of the way we are tracking the events

**Comment by nadiagorchakova** [comment]
sounds good @finnfiddle

**Comment by Lynngre** [comment]
@janagombitova we need normal web analytics tracking on Lumen. Right now we cannot track which visualisations etc are being shared.  This issue was added quite some time ago & I have mentioned it a few times.

All it takes a piece of code to be added into every visualisation/page or dashboard that loads so that we can at least do standard tracking.

Let me know when you guys are ready to have me setup the SITEIDs for each Lumen instance.

**Comment by kardan** [comment]
@Lynngre is there a way to create new SITEID via an API? Asking since we have a script that creates tenants. If we're adding analytics I think we should make sure new tenants is setup as part of that script.

**Comment by Lynngre** [comment]
@kardan is this what you need?  https://developer.matomo.org/api-reference/reporting-api#SitesManager

**Comment by kardan** [comment]
For now we only have internal usage tracking. We don't provide any tools for tenants to see stats on their usage. If we want that we should treat it as another feature, hence closing this issue for now.
