### ISSUE TITLE
Assessment of technical and devops debt

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#678]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment]
There is a github project on pending UI improvements:
https://github.com/akvo/akvo-lumen/projects/5

Might come in handy when assessing technical/design debt

**Comment by kardan** [comment]
Backend:
- Fix test database issue (https://github.com/akvo/akvo-lumen/issues/680)
- Review and refactor tests to use something like (https://github.com/akvo/akvo-lumen/blob/develop/backend/test/akvo/lumen/component/user_manager_test.clj#L48)
Devops:
- Speed up deployments (https://github.com/akvo/akvo-lumen/issues/681)
- Make changes to K8s deployments part of the deployment process (https://github.com/akvo/akvo-lumen/issues/615)
