### ISSUE TITLE
Add interface for managing pending user invites

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#679]
# Context
Currently there is no way to view or manage pending invites.

![screenshot from 2017-03-30 10-50-27](https://cloud.githubusercontent.com/assets/155294/24498549/bc758208-1536-11e7-8529-5d4989ad26a7.png)

# Solution or next step
Implement invitation management in the admin console.

**Comment by kardan** [comment]
Duplicate of https://github.com/akvo/akvo-lumen/issues/679 ?
