### ISSUE TITLE
"" in CSV files should not be parsed as a date

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#690]
# Context
Empty values in manually uploaded csv datasets are parsed as dates in text-to-date transformations.

# Problem or idea
Because of the above, text-to-date transformation can produce incorrect output. It complicates data cleaning and analysis.

<img width="332" alt="screen shot 2017-04-12 at 12 28 57" src="https://cloud.githubusercontent.com/assets/21127166/24958266/0ab9dc2c-1f8f-11e7-82c0-8c5aa4242f36.png">

<img width="284" alt="screen shot 2017-04-12 at 12 32 53" src="https://cloud.githubusercontent.com/assets/21127166/24958272/0f6eb8d2-1f8f-11e7-96ae-16551aa436e8.png">

<img width="228" alt="screen shot 2017-04-12 at 12 29 14" src="https://cloud.githubusercontent.com/assets/21127166/24958277/1282cf54-1f8f-11e7-9d19-5026da9b85a0.png">

**Comment by peeb** [comment]
Solved by #672

**Comment by jonase** [comment]
merged
