### ISSUE TITLE
Rethink the grid component

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#691]
# Context
One of the limitations of the current grid component is that you cannot resize columns and long text in columns is not wrapped. As a result, it's difficult to work with some columns.

<img width="236" alt="screen shot 2017-04-12 at 16 07 30" src="https://cloud.githubusercontent.com/assets/21127166/24962342/febc4a24-1f9b-11e7-92f5-23d18c4fd885.png">

# Solution or next step
Probably rethink which grid component we want to use. 
Might be needed for supporting Flow repeated question groups as well.

**Comment by janagombitova** [comment]
Handling repeated question groups has its own issue as well as handling the problem where the columns are not wide enough for their content. Supporting Salim in handling data in a different way that in the grid is also in its own issue, thus this issue is irrelevant and a duplicate. Closing
