### ISSUE TITLE
There is no way to clear Search field 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#698]
# Context
In the top right corner we have search field:

<img width="1059" alt="screen shot 2017-04-24 at 14 46 41" src="https://cloud.githubusercontent.com/assets/21127166/25337641/eadf76a6-28fc-11e7-82bb-05eacfc8463d.png">

It works Ok but there is no way to clear search field once you're done searching.
Refreshing the page doesn't help. 

# Problem or idea
The problem is that once you found an item you were looking for, you want to clear search results to continue your work. Right now the Search functionality filters all datasets, visualisations and dashboards and conceals not relevant items from the list.

Refreshing the page doesn't help and there is no way to re-log in either.

# Solution or next step

**Comment by gabemart** [comment]
Agreed solution is to add ability to clear search

before:
![image](https://cloud.githubusercontent.com/assets/2589977/25630447/1cec065a-2f65-11e7-8a8f-8fc5f506ca81.png)

after:
![image](https://cloud.githubusercontent.com/assets/2589977/25630483/3753c3de-2f65-11e7-9058-ca94647b9997.png)
