### ISSUE TITLE
Perform aggregation before sending data to the client (bar charts)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#699]
# Context
As some of the data in Lumen could be sensitive, we can't expose the raw data that is used in public visualisations to the client.

# Solution or next step
We tackled pie charts in the previous milestone. Bar chart is an often used visualisation type (at least judging by Lumen demo instance). Seems logical to address it next.

**Comment by nadiagorchakova** [comment]
The aggregation seems to be necessary to comply with GDPR legislation. 
Not only for bar charts but for other visualisation types as well where we might expose raw data to the client.

**Comment by janagombitova** [comment]
Handled together with https://github.com/akvo/akvo-lumen/issues/1381 when moving all aggregations away from the client.
