### ISSUE TITLE
Y axis title is not displayed on the graph

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#704]
# Context
For several columns, Y axis title is not displayed on the line graph.

# Problem or idea
Looks like when values are 5,000 and above on Y axis, axis title disappears..

<img width="1275" alt="screen shot 2017-05-01 at 15 41 01" src="https://cloud.githubusercontent.com/assets/21127166/25581095/deca43d0-2e85-11e7-99f4-8eae9a494127.png">

# Solution or next step
How could we solve it?

**Comment by gabemart** [comment]
Merging into #591
