### ISSUE TITLE
Numbers on X axis do not match the source column

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#705]
# Context
I was playing around with scatter plots and noticed that it's problematic to display years on an axis.
By years I mean e.g. 2007 as a number, so not set in date format.

# Problem or idea
I used this dataset to create a scatterplot: https://demo.akvolumen.org/dataset/58b7e0b9-8d89-41a1-acba-f72ed46cb668

The year appeared like this in the dataset:

<img width="180" alt="screen shot 2017-05-01 at 16 43 24" src="https://cloud.githubusercontent.com/assets/21127166/25582574/4fc4db88-2e8e-11e7-9548-298f35a70da9.png">

(I double-checked - all values look like real years, not values like 200,000 and so on.)

In the visualisation though the year column is displayed as:

<img width="676" alt="screen shot 2017-05-01 at 16 41 05" src="https://cloud.githubusercontent.com/assets/21127166/25582627/87f61b2a-2e8e-11e7-97d4-f78005e92bb7.png">

# Solution or next step

**Comment by gabemart** [comment]
I think this is working as intended - one of the values in the "year" column is `200102014`. The x-axis numbers adjust relative to the largest value.

Filtering out that value should fix the problem.
