### ISSUE TITLE
Round up decimals in the derived column

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#712]
# Context
Some derived column functions might result in decimal numbers like that:

<img width="165" alt="screen shot 2017-05-03 at 12 17 32" src="https://cloud.githubusercontent.com/assets/21127166/25656818/15c20fdc-2ffb-11e7-98d5-356e933f9d02.png">

# Problem or idea
We should probably round up those decimals to just two or three digits after decimal point. 
Otherwise, it might be problematic to work with these numbers and also visualise them in a meaningful way.

**Comment by janagombitova** [comment]
Completed
