### ISSUE TITLE
Replace grey keycloak login page with Akvo theme

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#720]
# Context
When logging in to Lumen, users see this screen:

<img width="1253" alt="screen shot 2017-05-09 at 09 42 12" src="https://cloud.githubusercontent.com/assets/21127166/25840358/d59ecaf8-349b-11e7-928a-356694b15640.png">

# Problem or idea
As we agreed with Loïc, the keycloak theme should be ideally replaced with Akvo design.
Since it will be used as a point of single sign-on to all Akvo products, it has to be product-neutral. 

# Solution or next step
How could we solve it?

**Comment by iperdomo** [comment]
Duplicated? https://github.com/akvo/akvo-lumen/issues/516

**Comment by loicsans** [comment]
yes duplicated, closing this
