### ISSUE TITLE
Currency data type

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#721]
# Context
Currently we support number, text and date data types.

# Problem or idea
When working with financial data, for instance farmer crop yields, some values might contain currency symbols. Once it gets into Lumen, it will be identified as text type, e.g. UDS80,00.

One would need to use the derived column functionality to subtract currency symbols and then turn it into numbers. Only then it will be possible to analyse and visualise this data.

# Solution or next step
Would it make sense to introduce currency data type?
I think @peeb and @kardan had some ideas

**Comment by janagombitova** [comment]
I am closing this issue: 
- we have not received any requests of this type from our early adopters
- this use case has not shown to exist - currency columns usually have the currency code in the column header and the data is numerical, thus falls under NUMBER data type and this problem does not exist 
- we have an alternative solution for the few edge cases - split column transformation can be used to get the number data in a separate column
