### ISSUE TITLE
Date display should be configurable

### ISSUE THREAD

**Issue by bjelkeman** [akvo/akvo-lumen#723]
# Context
Date on the X axis in a area chart (probably others too) are displayed with precision to the second.

# Problem or idea
It is very rare that you want dates displayed with that precision. 
Example: https://demo.akvolumen.org/visualisation/59145131-82e9-4c86-b024-bf47a09b7e84
https://demo.akvolumen.org/s/VrZLYMlHPiY

# Solution or next step
You want a date display to be configurable, to at least: YYYY, YYYY-MM, YYYY-MMM, YYYY-MMM-DD

**Comment by gabemart** [comment]
Merging with #979
