### ISSUE TITLE
Webpack dev server configuration change

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#725]
# Context
We use webpack dev server for local development.

# Problem or idea
Recently, a security related update was released which breaks our current config.

https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a

It's worth reading the link, but as a summary, the security issue this update fixes is to do with remote websites being able to bypass CORS restrictions and get information about a machine that is running devpack web server. In other words, the security issue affects dev machines while running the dev server, not lumen at the deployment stage.

# Solution or next step
We could "fix" the problem using the `disableHostCheck: true` config option, but that seems like a bad idea because it leaves the security hole open.

We can also fix the problem by changing the listen host from `localhost` to `t1.lumen.localhost`, but this breaks `t2.lumen.localhost`. I haven't found a way to bind to two specific hosts on the same port with webpack dev server.

I don't know how often other developers use `t2`. I don't use it very often. I would suggest that for now we change the listen host to `t1`, accept that `t2` will break, and then explore if it's possible to listen at multiple hosts.

@jonase What are your thoughts?

Note: both the problem and the proposed solution will have no impact on production instances, only local development instances.

**Comment by gabemart** [comment]
I'm on holiday on Monday, so I've created a prospective PR that can be merged if people agree with my suggestion, or deleted if people don't

**Comment by jonase** [comment]
@gabemart Great research on this! I don't use `t2.lumen.localhost` either, and I suspect the same goes for @kardan and @peeb. I will merge the PR.

**Comment by kardan** [comment]
Agree to drop t2. Good work.
