### ISSUE TITLE
Restriction the no of visualisations for pricing tiers - investigation 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#736]
# Context
Why do we add this issue?

# Problem or idea

Frontend:
- what happens in the UI when a user reachers the max number of visualisations?

# Solution or next step
How could we solve it?

**Comment by kardan** [comment]
I was thinking that it would be simple to enforce creation of new visualisations on the backend. If the client tries to create a new viz we could respond with something else than 200. But @gabemart enlightened me on the fact that we probably not want users spending time configuring their viz to then in the end get a "failure message" and not be able to save their work.

**Comment by nadiagorchakova** [comment]
Closing this one with more detailed issues as a follow up
