### ISSUE TITLE
Review support for matrix for datasets

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#738]
From QA session

A dataset like:

City;Population;Water coverage
Stockholm;100000;2
Gothenburg;50000;1

Can also be represented in matrix form like:

;Stockholm;Gothenburg
Population;100000;50000
Water coverage;2;1

A missing piece is of coure the "city" part which one would need to get manually from the user.

**Comment by janagombitova** [comment]
In the current cases the new Split column transformation is used. I am closing this issue for now and we can reopen it if needed once the opportunity arises again.
