### ISSUE TITLE
Trimming whitespace on import

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#739]
# Context

At the Lumen training, someone suggested (automatically) trimming leading and trailing whitespace at dataset import.
This way a user won't have to inspect all text columns after import and trim whitespace on the column-by-column basis. I think it might be an interesting idea.

**Comment by jonase** [comment]
👍 I agree with this @nadiagorchakova. It's very difficult to find a use case where you don't want to automatically do this. I also think we should trim column titles. Especially in derived column code it's very confusing with trailing whitespace, where you would need to write `row["My Column    "]` for it to work.

**Comment by Kiarii** [comment]
Options:
- provide an option in the import dialog for the user to allow this
- Perform trim after import; and notify user about the operation - e.g. in the transform log so they are aware that the operation has been performed on the data. If there is clearly no need for data with trailing & leading whitespaces, the notification can be grouped ("Removed t&l whitespaces from 10 cols: Names, Address, ...) and undoable..
- Provide a bulk action on suggest cleaning operations "Remove t&l whitespaces on the dataset"

**Comment by iperdomo** [comment]
> provide an option in the import dialog for the user to allow this

This is what other software do. Excel, Libreoffice, a _preview_ of the dataset before actually importing

**Comment by jonase** [comment]
@Kiarii I don't know of a scenario where a user would want to deal with leading/trailing whitespace? Did you discuss any specific examples/scenarios?

**Comment by Kiarii** [comment]
@jonase, I cant think of any key scenarios either; the thing about having a notification in the log is just so the user would know that something happened to their data.. in that case it may just read "removed t&l whitespaces from the dataset"
