### ISSUE TITLE
Pivot backend returns 500 error when all values filtered out via value toggle menu

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#741]
# Context
Pivot table editor allows to pick column and row values that should be shown in the pivot table.
For example:

<img width="937" alt="screen shot 2017-05-18 at 16 55 20" src="https://cloud.githubusercontent.com/assets/21127166/26208694/0a8c127e-3beb-11e7-95e1-c5d35b05d9cc.png">

It works similarly with row values.

# Problem or idea

Lars noticed that if you deselect all values from the list, the last one on the list gets duplicated.
I tried it as well with this pivot table: https://demo.akvolumen.org/visualisation/591db22c-4206-494e-8166-21789702950a and managed to reproduce it.

It goes from just two 2 values to 3 when all are deselected:

<img width="377" alt="screen shot 2017-05-18 at 16 59 50" src="https://cloud.githubusercontent.com/assets/21127166/26208942/aef14cb2-3beb-11e7-984f-563b82f3c6f9.png">

And the same with row values:

<img width="371" alt="screen shot 2017-05-18 at 17 02 30" src="https://cloud.githubusercontent.com/assets/21127166/26209019/e9e3836c-3beb-11e7-9c1d-83c1e309e500.png">

# Solution or next step

**Comment by gabemart** [comment]
The underlying issue here is that the API returns a 500 error when there are no results to return (i.e. because the combination of filters filters everything out).

I can think of a couple of ways to address this - one is the have the backend return a valid response even when there are no results to return. The other is for the client to detect that all values are toggled off, in which case the client could show something like "No data" without making a call to the backend at all.

@jonase What do you think?

**Comment by gabemart** [comment]
Also, #740 is the same issue as this, so I will merge #740 into this issue

copied below:

---
@jonase says:

# Problem or idea
If you apply a filter in your pivot visualisation that (presumably accidentally) filters out all categories we generate invalid sql and return `500 Server Error`.

# Solution or next step
In this case we should probably only return the "rows" and no categories

**Comment by gabemart** [comment]
@jonase I agree, I think the most correct thing for the backend to return is the most data that it can.

if the dataset looks like

![image](https://cloud.githubusercontent.com/assets/2589977/26211776/405fa6b8-3beb-11e7-8272-de867c20b513.png)

then a pivot table might look like this:

![image](https://cloud.githubusercontent.com/assets/2589977/26211844/6a76e2f4-3beb-11e7-8664-20d0f55d210b.png)

Then if we filter only to cats:

![image](https://cloud.githubusercontent.com/assets/2589977/26211873/836802fc-3beb-11e7-860c-71f7d21c78aa.png)

At this point, the api response looks like:

````
{
  "rows":[
    [
      " black",
      2.0
    ],
    [
      " brown",
      3.0
    ],
    [
      " grey",
      1.0
    ]
  ],
  "columns":[
    {
      "title":" color",
      "type":"text"
    },
    {
      "title":" cat",
      "type":"number"
    }
  ],
  "metadata":{
    "categoryColumnTitle":" pet type"
  }
}
````

If we then filter out "cat", we get a backend error. The response which I think would be most correct would be simply:

````
{
  "rows":[
    [
      " black",
    ],
    [
      " brown",
    ],
    [
      " grey",
    ]
  ],
  "columns":[
    {
      "title":" color",
      "type":"text"
    },
  ],
  "metadata":{
    "categoryColumnTitle":" pet type"
  }
}
````

**Comment by jonase** [comment]
I'm not sure what the correct response would be, but we need to at least fix the `500 Server Error`. Anytime the backend consistently returns this there is a bug there.

@gabemart As for the response, I think this is almost certainly a user "mistake" so we could show it as such. As you said, if everything is filtered away there are no more "colors" left and then the "correct" response could be

```
{
  "rows":[],
  "columns":[
    {
      "title":" color",
      "type":"text"
    },
  ],
  "metadata":{
    "categoryColumnTitle":" pet type"
  }
}
```

**Comment by jonase** [comment]
> We could do something different, like show all the colors in the dataset

@gabemart After thinking about it, this feels wrong. The user has specified a set of filters, and if those filters happen to filter out all the data we would ignore all of them.

**Comment by gabemart** [comment]
@jonase I agree. So I guess the backend should return the "correct" response and the client should then show some helpful information? I guess the information should also vary according to the context. In the editor, it might be something like "All (rows/columns) are toggled off" but in a published visualisation it might just be "No data".

The "published visualisation" case isn't really relevant just now (why would a user publish a pivot table with no values) but once datasets can update, a pivot table might fall into the "no rows" or "no columns" case at any time

**Comment by kardan** [comment]
We need to review if this is already fixed.
