### ISSUE TITLE
Clean up Lumen Demo

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#748]
# Context

As more Akvonauts start using Lumen demo environment, it becomes very clattered.
A demo environment should ideally be clean with items relevant for partner demos.

# Problem or idea

The idea is to refresh demo environment every three moths to get rid of old (and broken) visualisations and dashboards).
I've asked in akvo core which visualisations and dashboards are still important and need to be kept for now.

**People flagged the following:**
- dataset "Fiji Nurse Station_UNICEF.16.Mar" https://demo.akvolumen.org/dataset/58ca31f7-21ce-4144-861e-b7e2aa066a92 and the following visualisations connected to it:

<img width="351" alt="screen shot 2017-05-31 at 12 22 08" src="https://cloud.githubusercontent.com/assets/21127166/26627749/c410207c-45fb-11e7-8d87-a1f9406f7fa7.png">

- dataset "Fiji Nurse YEAR_22.March.17" https://demo.akvolumen.org/dataset/58d24393-f512-45e6-b115-762babfbd54d and the visualisations connected to it:

- Population access to safe water supply services
- Fiji: Main water source
- Number of sanitation facilities benefitting girls and women
- Number of sanitation facilities benefitting the disabled
- Main Toilet type
- Population of Nurse Centre access to sustainable water supply service
- Access to affordable water supply service
- Population access to sustainable sanitation services
- Access to affordable sanitation services
- Number of main water sources with Water Safety Plan
- Population access to safe sanitation facilities
- Institutions with hand washing facilities containing water 

- dataset "UNICEF FJ - Improved WASH.29/3" https://demo.akvolumen.org/dataset/58db1877-0035-4c04-a7cd-284166dee802 and the following visualisations connected to it:

<img width="367" alt="screen shot 2017-05-31 at 12 34 03" src="https://cloud.githubusercontent.com/assets/21127166/26628198/7019eb18-45fd-11e7-84d1-8beb16360ea9.png">

- dataset "M4C_Pacific_11.04.17" https://demo.akvolumen.org/dataset/58ecb23d-be76-4519-a15e-53ce067afcf5 and the following visualisations connected to it:

- Markets in the M4C program
- Gender of market vendor (Solomon Islands & Fiji)
- Total income from Market last week (Fiji)
- Total income from Market last week (Solomon Islands)
- Infrastructural Impacts: Health
- Market Vendor Association membership by Vendors
- Membership of the MVA Executive
- Consultation on infrastructural changes (UN Women or Council)
- Infrastructural Impacts: Economic
- Infrastructural Impacts: Safety

- dataset "M4C_infrastructure_12.4.17" https://demo.akvolumen.org/dataset/58ed9536-36b7-499d-9946-3119ce7633f9 and the following visualisations connected to it:

<img width="351" alt="screen shot 2017-05-31 at 12 37 48" src="https://cloud.githubusercontent.com/assets/21127166/26628338/ec6549c4-45fd-11e7-98fa-20dd70ef3a41.png">

- dataset "UNICEF RMI General 16.5.17" https://demo.akvolumen.org/dataset/591ac67a-521c-482a-9171-ecc8eea479c1 and the following visualisations connected to it:

<img width="361" alt="screen shot 2017-05-31 at 12 19 00" src="https://cloud.githubusercontent.com/assets/21127166/26627677/8b64c5ac-45fb-11e7-82de-9dd40c822507.png">

- dataset "UNICEF RMI Mother 16.5.17" https://demo.akvolumen.org/dataset/591ac6a4-3bd0-492b-90d0-9d79ab355692 and the following visualisations connected to it:

<img width="338" alt="screen shot 2017-05-31 at 12 24 24" src="https://cloud.githubusercontent.com/assets/21127166/26627836/100b733c-45fc-11e7-85dc-56c91ad7f600.png">

- dashboard "Fiji National Water and Sanitation Indicators" https://demo.akvolumen.org/s/m2mIkD2XZcA
- dashboard "Mars Pakistan pilot" https://demo.akvolumen.org/dashboard/58ae7788-2409-448f-ab41-8675aadc4403
- all resources containing '**G4AW**', incl:
https://demo.akvolumen.org/visualisation/5912c5a1-6708-402b-9fd6-83684ed6f485
https://demo.akvolumen.org/visualisation/58c8a671-3381-4475-b686-0bbc6d864db6
https://demo.akvolumen.org/visualisation/58c8a563-a036-4c2f-a16c-b8ffb7b42382
- all resources containing '**Berbak**'

# Solution or next step

We must be careful with not removing datasets and visualisations, which were used in the dashboards listed above.
As it's not possible to do a 'selective' refresh, we'll do it manually this time. **So all resources created before the 1st of March should be deleted.** Next time it would be nice to automate the refresh process, if possible.

**Comment by gabemart** [comment]
Pasting text versions of the images above for search and replace purposes:

````
water functionality of nurse stations throughout fiji
toilet functionality of nurse stations throughout fiji
24 hr nurse station fiji
Institutions with access to safe improved sanitation services
Institutions with access to safe improved water supply services
Improvements made to the markets (fiji & Solomon islands)
Improvements needed for the market
households visited by Atoll
mean number of children under age 5 per household visited
number of households visited per atoll / island
map of households visited
proportion of mothers who are currently pregnant
school attendance amonst mothers
mean age of women when they married
percentage of children under 23 months who were breastfed
mean number of (live) children per mother
mothers education level
````
