### ISSUE TITLE
User notification when a large dataset is being uploaded

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#752]
# Context
It's possible to upload a large dataset into Lumen, for example 2.5Mb in size, however it crashes Lumen when you open it.
https://lumen.akvotest.org/dataset/5923eed7-9a62-40c4-b731-ef06c377b7b6

# Problem or idea
We're planning to support large datasets later in the year. In the meantime, perhaps it would makes sense to add a user notification so that they don't attempt to upload datasets larger than certain size.

# Solution or next step
How could we solve it?

**Comment by nadiagorchakova** [comment]
and if a dataset is too large to be uploaded to Lumen at the moment, there should be some user notification about it. 
Perhaps @Kiarii will have some ideas about that

**Comment by Kiarii** [comment]
@nadiagorchakova I think in the import workflow, we had some error handling; in this case, you cannot hit the import/create dataset button if size > allowed importable size; you would get an error msg within the import process, from which you can determine whether to import a diff dataset or cancel the process altogether.. @jonase correct me if I am wrong

**Comment by nadiagorchakova** [comment]
yep. At the moment you get a generic error, which doesn't tell you much but is of course good for a start. What I'm missing here as a user, is some hint as to how I could resolve this error, what do I do next.

<img width="721" alt="screen shot 2017-07-19 at 16 09 11" src="https://user-images.githubusercontent.com/21127166/28371278-ce706956-6c9c-11e7-9ba1-7e69f338a513.png">

And if you use a link as a data source, you don't get an error at the moment, just perpetual loading icon.

<img width="1273" alt="screen shot 2017-07-19 at 13 49 18" src="https://user-images.githubusercontent.com/21127166/28371360-0f93817a-6c9d-11e7-89ef-2ed24c5fb133.png">

**Comment by Kiarii** [comment]
got you :) I think I and @jonase need to align on how best to handle that; below is what i had referenced
![image](https://user-images.githubusercontent.com/12692444/28371910-f4190a00-6ca6-11e7-81c7-ea30cb90f801.png)
