### ISSUE TITLE
Config max request body in immutant.web

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#76]
https://dpaste.de/e6Ag/raw
Like:
(update m-conf :configuration #(.setServerOption % UndertowOptions/MAX_ENTITY_SIZE 8388608))

@jonase @iperdomo @gabemart What would be a good value?

**Comment by iperdomo** [comment]
What's the default? And the proxy value?

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by kardan** [comment]
No max by default http://undertow.io/undertow-docs/undertow-docs-1.2.0/listeners.html#common-listener-options

**Comment by kardan** [comment]
No max value by default, but we do limit to 10mb in the Lumen lb Nginx container https://github.com/akvo/akvo-provisioning/blob/develop/docker/lumen/lb/default.conf#L1
