### ISSUE TITLE
Bulk action & event notification

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#762]
# Context
Bulk action menu (BAM) on the Library doesn't show if the user scrolls so that the top menu also goes out of view. Since it assumes no background or color it is difficult to notice. 

<img width="1071" alt="screen shot 2017-05-29 at 12 38 30" src="https://cloud.githubusercontent.com/assets/12692444/26544779/c94cffa6-446b-11e7-9ada-ef047c38bc98.png">

# Problem or idea
It noticeability is also hampered by the fact that the user may not be paying attention to the top section of the page when they are selecting resources in the library; i.e. if they are looking at what resources to select, it will be difficult for them to notice the BAM when it is presented at the top.. 

# Solution or next step
The BAM shd pop out in a way that is noticeable. It would make sense to have it as a floating item so that it remains in view when the scrolls

It might also make sense to have the BAM event notification (atm displayed at the top) displayed at relatively the same area as the BAM. At the moment the 2 require that the user scroll back to the top to access them. Alternatively, these could be displayed at the bottom to (i) to support viewability even when the user has scrolled the top menu out of view, (ii) to reduce confusion between what elements of the top menu are hidden to accommodate the BAM, and (iii) to distinguish the top menu and the BAM, (iv) avoid making the top menu large if the BAM was to be added to it or atop 

<img width="1348" alt="screen shot 2017-05-29 at 12 40 55" src="https://cloud.githubusercontent.com/assets/12692444/26544857/282b9460-446c-11e7-9272-973faf0984ff.png">

We could borrow from Material's design pattern for the BAM event notification; https://material.io/guidelines/components/snackbars-toasts.html (desktop) ; such bottom placement would also mean that both the BAM and its action events can be shown relatively one the same location

BAM Example:
![image](https://cloud.githubusercontent.com/assets/12692444/26545475/65b90a7c-446e-11e7-8640-b0842b25d856.png)

Notification Example:
![image](https://cloud.githubusercontent.com/assets/12692444/26545503/810f29a0-446e-11e7-86fd-c5fb9d912af5.png)

If need be, we can further add Actions to the Notification e.g. UNDO as suggested by snackbar

**Comment by loicsans** [comment]
Priority: 7
Effort: 4

**Comment by gabemart** [comment]
![image](https://user-images.githubusercontent.com/2589977/27340805-57f16990-55d3-11e7-92eb-2a3fa4664585.png)

![image](https://user-images.githubusercontent.com/2589977/27340843-7092403c-55d3-11e7-80c6-5ed1a0582c56.png)

@loicsans I move the components to the bottom of the viewport and integrated the buttons with the new mixin you created, but I haven't attempted to do any styling beyond that. Are you happy to do the styling on this branch?

**Comment by Kiarii** [comment]
one important thing which we need to ensure is that the bulk menu doesn't hide the last item in the list. it has to work like an inset element to ensure that all list items are viewable in full and selectable
