### ISSUE TITLE
Split up "New entity" button

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#764]
#context
Library menu redo - decouple NEW actions, enhance filter & menu separation

# Problem or idea

The top menu appears confusing; it is thought that to create an Asset, it is necessary to select its corresponding filter option. e.g. To create a visualization, some users click on the Visualization filter and then click the [New] > Visualization

The workflow [New] > Visualization/Asset can also be minimized by having dedicated buttons e.g. + Visualization,  given that there are a ltd number of Assets creatable. If need be, the search field can be collapsed, and expanded on request, to comfortably accommodate + Asset links

# Solution or next step
How could we solve it?

![image](https://cloud.githubusercontent.com/assets/12692444/26545828/d375135c-446f-11e7-9335-12e39d36b569.png)

**Comment by loicsans** [comment]
Priority: 10
Effort: 2

**Comment by gabemart** [comment]
As discusses, in this branch we will also remove the "list" view and default to the "grid" view, and remove the "sort by" menu, on the basis that there isn't a great amount of using for sorting by name currently
