### ISSUE TITLE
Unify icon usage

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#766]
# Context
There are some inconsistencies in the usage of icons in terms of size but also 'meaning' e.g. on the Library the [Menu] and [List view] are the same - this may confuse some users. 

# Solution or next step
We need to consider at least 3 things:

- Color: standardize and ensure it doesnt create visual noise/distraction
- Size: atm all icons are oversized in contrast to other interface elements.
- Meaning: Ensure all icons are not ambiguous in their meaning --> this means that we might abandon the usage of icons to denote Assets..

- As in the ss below, we may not have a mixed (bar + line) chart as an icon for a pie chart

<img width="427" alt="screen shot 2017-05-29 at 17 35 39" src="https://cloud.githubusercontent.com/assets/12692444/26553637/469818d2-4495-11e7-867e-18e249aa400b.png">

- the same applies to datasets: if the icons do not represent the different types, it is not useful to merely use a generic icon

**Comment by Kiarii** [comment]
- icon styling ought to be the same throughout the app
![image](https://cloud.githubusercontent.com/assets/12692444/26580818/764e974c-4542-11e7-8716-dd6c77805297.png)

**Comment by loicsans** [comment]
Fontawesome was integrated, as well as a new set of icons for bigger assets.
