### ISSUE TITLE
Swatch - glare-free colors - for visualizations

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#767]
# Context
Color usage in visualization atm includes colors with glare.

# Problem or idea
We could create a swatch of about 20 glare-free colors from which visualizations use e.g. https://www.highcharts.com/demo/column-basic

**Comment by loicsans** [comment]
Loic and kiarii to decide on a colour palette of 20 colours.

**Comment by loicsans** [comment]
A palette to start with: 
![screen shot 2017-06-22 at 12 53 52](https://user-images.githubusercontent.com/1717219/27428453-bdf7f7cc-574a-11e7-97df-97f4e6ca34bb.png)
