### ISSUE TITLE
Unify dialogue boxes

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#768]
# Context
Review dialog boxes, error messages, exceptions, ..

# Problem or idea
We need to unify the 'language', descriptions, buttons or Actions e.g. the dialog below shd have direct title, text and actions

<img width="611" alt="screen shot 2017-04-27 at 10 39 07" src="https://cloud.githubusercontent.com/assets/12692444/25472868/d574ee0a-2b35-11e7-8767-7851bef431e2.png">

# Solution or next step
Example
- Title: Remove user "Nadia" - we shd user Name in place of Email here.. 
- Description: no need for a desc if the action is straight forward
- Actions: Default | Primary: "Cancel | Remove"

**Comment by loicsans** [comment]
Priority: 10
Effort: 1 but depends on technical stuff
