### ISSUE TITLE
Unify asset naming convention

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#769]
The Title element works differently in datasets, visualisations and dashboards. Maybe we could look into unifying it?

Datasets: The title is given at import stage, it's not possible to edit when inside the dataset (or anywhere else)

<img width="902" alt="screen shot 2017-05-11 at 15 50 53" src="https://cloud.githubusercontent.com/assets/21127166/25952724/ba63cf96-3661-11e7-85f0-96f7c96c8514.png">

Visualisation: It's possible to edit the title when in the visualisations editor

<img width="1090" alt="screen shot 2017-05-11 at 15 53 04" src="https://cloud.githubusercontent.com/assets/21127166/25953458/be12e620-3663-11e7-922d-8b350ecfada1.png">

Dashboard: It's possible to edit the title when in the dashboard editor but in a different place, compared to the visualisations editor

<img width="1269" alt="screen shot 2017-05-11 at 16 08 41" src="https://cloud.githubusercontent.com/assets/21127166/25953594/2bd03924-3664-11e7-8cdf-b9654bfcbbf1.png">

**Comment by loicsans** [comment]
Priority: 7
Effort: 1 for dashboard, needs investigation for datasets

**Comment by gabemart** [comment]
@Kiarii @loicsans in the dashboard editor, now that the name is displayed in the header and can be edited from the header, should we just remove the title above the dashboard entirely?

If we keep it:
![image](https://user-images.githubusercontent.com/2589977/27682606-2b7ef2a8-5cbb-11e7-92dc-d2a0b82f806a.png)

If we remove it:
![image](https://user-images.githubusercontent.com/2589977/27682625-39f81dd2-5cbb-11e7-9095-440676387fdc.png)

I think we should remove it
