### ISSUE TITLE
Unify highlight color-code for all interactive elements

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#770]
# Problem or idea
We have inconsistent usage of highlight (mouse-over) color coding.

In the ss below: it is difficult to differentiate between Active, Mouseover/Highlight states of the various elements: filter option ALL, sort options Created (which is the highlight in this case) and Asset highlight

<img width="1044" alt="screen shot 2017-05-29 at 13 48 58" src="https://cloud.githubusercontent.com/assets/12692444/26547031/ad7ea4fa-4475-11e7-9e64-555cc390ebc9.png">

# Solution or next step
How could we solve it?

**Comment by loicsans** [comment]
Priority: 10
Effort: 1
