### ISSUE TITLE
Refine New dataset Dialog

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#772]
# Problem or idea
There is a number of improvements to make here so i will just get to what we might need to do

<img width="478" alt="screen shot 2017-05-29 at 16 47 16" src="https://cloud.githubusercontent.com/assets/12692444/26552129/83840d02-448e-11e7-8ae4-8f4ba838a81a.png">

# Solution or next step
- Full-screen-size the process; it is not necessary to have this as a pop-up
- Place the Checkbox on the lefthand side of the selection "File has column headers". On this option, we seem to have deviated from the workflow we had (if i remember correctly, it was in the last screen, where a preview would be available so the user didnt have to think or remember or go open the file to know for sure if there is a header and so on..) - please confirm. 
- The text No file selected is not necessary - I think the action to be taken shd be easy to determine given the two options: (i) Drop file [...] OR (ii) Select file
- As in the naming convention that we have with Visualizations, shd we provide the 'naming' for the new dataset at the top? > Change it to "Import Dataset"
- Indicate process/progress - atm this look like tabs and remotely communicate progress. we could do it as follows:

![image](https://cloud.githubusercontent.com/assets/12692444/26553212/57b562a2-4493-11e7-9941-b8035d12a55e.png)

**Comment by loicsans** [comment]
Priority: 7
Effort: 5
