### ISSUE TITLE
New item dismiss Action

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#773]
# Context
Why do we add this issue?

What convention should we use for dismissing a 'full-screen-sized 'New Item action e.g. New
- Visualization, Dataset, Dashboard
- Transform
- etc

# Problem or idea
- Shd we provide a [Back] icon to dismiss New Asset creation or continue with the [X]?
- Do we need to tell the user that the action has been dismissed? If so how?

# Solution or next step
How could we solve it?

**Comment by loicsans** [comment]
We do not notify
