### ISSUE TITLE
Re-label "Dataset editor" to "+ Transform"

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#775]
# Context
Why do we add this issue?

# Problem
The button [Dataset editor] could be taken both to mean New Transform or a View

<img width="335" alt="screen shot 2017-05-29 at 17 39 57" src="https://cloud.githubusercontent.com/assets/12692444/26553814/f76c192e-4495-11e7-9ad8-5402e15a29ee.png">

# Proposal
- To be precise we should re-label it as "+ Transform" to mean add/new transform. This would conform with the convention of "+ Dataset, + Visualization, + Dashboard proposed for the redesign of the Lib's top menu
- "+ Transform" also makes a clear connection with "Transform" log in contrast to _Dataset editor log_

**Comment by loicsans** [comment]
Priority: 8
Effort: 1
