### ISSUE TITLE
Review the testing story

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#78]
At the moment we have a few tests, we need to review how to deal with tests. We need to make sure we are not afraid to move fast!

This requires to both write unit tests, and also functional tests. To enable functional tests we need to:
- [ ] Enable test using db locally
- [ ] Enable db at CI server

Review if we can add lint / version tools to CI.

**Comment by zzgvh** [comment]
I'm reopening since there's more travis-db stuff to be done. Created a new branch though.

**Comment by iperdomo** [comment]
@zzgvh the idea is to have smaller issues with concrete descriptions, instead of a "container" of stuff.
