### ISSUE TITLE
Modal dialog dimensions

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#780]
# Context
[Borrowing descriptions](https://material.io/guidelines/components/dialogs.html#) Dialog types include:

- Alerts are urgent interruptions that inform about a situation and require acknowledgement.
- Simple menus display options for list items, whereas simple dialogs can provide details or actions about a list item.
- Confirmation dialogs require users to explicitly confirm a choice.
-- [Dialog usage guidelines](https://www.nngroup.com/articles/modal-nonmodal-dialog/)
# Problem
In this example, the dialog is extra long that is required by its content; which leave the user in confusion as unto whether some content is missing in the middle

<img width="514" alt="screen shot 2017-05-30 at 11 13 53" src="https://cloud.githubusercontent.com/assets/12692444/26574196/1a43474a-4529-11e7-99ef-09b2ecbc49fd.png">

# Proposal
The height and width dimensions need to defined; 
- the height by content 
- the width could be fixed for all modal dialogs

- About the placement: I am thinking centred dialogs appear 'well' anchored to the page in contrast to those hanging at the top, opinions?

**Comment by Kiarii** [comment]
Dimensions to cater for:

![image](https://cloud.githubusercontent.com/assets/12692444/26576277/f524049c-4530-11e7-841c-3f1714cac70e.png)

**Comment by Kiarii** [comment]
The end result should be simple e.g. as shown below, to ensure that it takes as minimal time as possible for the user to accomplish their task or dismiss it

![image](https://cloud.githubusercontent.com/assets/12692444/26578565/085bd7e4-4539-11e7-86f4-abf0095aa145.png)

**Comment by Kiarii** [comment]
# For Modals with lots of content: we need to show at least 2 items all the time:
(i) Modal title, (ii) Description, (iii) Actions: to ensure the user is able to determine the course of action, access content/buttons without having to scroll these 3 out of view e.g.

![image](https://cloud.githubusercontent.com/assets/12692444/26586978/a623fba8-4559-11e7-8285-0158f5ee4760.png)

**Comment by loicsans** [comment]
Priority: 10
Effort: 1
