### ISSUE TITLE
New collection modal improvements

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#782]
# Idea
<img width="508" alt="screen shot 2017-05-30 at 13 34 18" src="https://cloud.githubusercontent.com/assets/12692444/26579493/c578a7fa-453c-11e7-9f82-9cda28a155cc.png">

# Proposal
- minimize header; New collection suffices
- provide similar naming convention as other items; Untitled collection, as the default
- place Cancel and Create in proximity

![image](https://cloud.githubusercontent.com/assets/12692444/26579814/2a3ff35e-453e-11e7-80e1-2ebb7d51fcdf.png)

**Comment by loicsans** [comment]
Priority: 10
Effort: 1
