### ISSUE TITLE
Color coding irreversible actions

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#783]
# Context
Distinguishing Confirmed and Unconfirmed irreversible actions by color code

# Problem or idea
Currently we are Cautioning the user twice when they initiate an irreversible action e.g. Delete by (i) Showing a confirmation dialog and (ii) Color coding the action Red. 
The second 'cautioning' is unnecessary; and may only serve to delay confirmation or dismissal of the action

![image](https://cloud.githubusercontent.com/assets/12692444/26585876/244b139e-4556-11e7-8f4d-29e2fcdc4320.png)

# Solution or next step
- For Actions that require confirmation e.g. the Delete or Remove buttons we do not need to color coded the Red; no need to caution the user a second time.
- Irreversible actions that we do not confirm can be color coded Red

Many scenarios in Lumen assume the first option; in which case the above modal may appear as follows:
![image](https://cloud.githubusercontent.com/assets/12692444/26586090/c5a98716-4556-11e7-8eb4-5105a75c8fab.png)

**Comment by janagombitova** [comment]
Modal dialogue is no longer colour coded in red. Currently in red are errors. I assume we can close this issue for now
