### ISSUE TITLE
Item referencing on modals

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#784]
# Context
In order to consistently handle item (dataset, visualization, collection, user, ..) referencing in modals and other places

# Problem
Currently we have used a number of conventions as in the following examples:
- Delete dataset "Youth tobbacco use"
- Delete collection Some collection name

# Proposal
Use semicolon to reference items e.g.
- Share visualization: Visualization name
- Delete dataset: Dataset name
- Delete user: Firstname Lastname

![image](https://cloud.githubusercontent.com/assets/12692444/26586244/51421842-4557-11e7-8103-d2dd8fbe4ad9.png)

**Comment by Kiarii** [comment]
If the semicolon is not meaningful, we can resort to the quotation mark; just saying/thinking out aloud/not thinking at all/..

**Comment by loicsans** [comment]
Priority: 10
Effort: 1 but depends on technical stuff
