### ISSUE TITLE
Map legend header shows data type

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#787]
Created via Reamaze by Joy:

Link: https://akvoo.reamaze.com/admin/conversations/map-legend-header-shows-data-type
Assignee: Nadia Gorchakova

Message:
Steps
1. Create a map
2. Add a Legend

Issue:
Legend header text  is not customisable and also shows data type.

**Comment by nadiagorchakova** [comment]
I think I agree with Joy on that: other visualisation types allow legend customisation so it's logical (and useful) to have it in maps too. Also, data type in legend text is not necessary.

**Comment by gabemart** [comment]
closed via #936
