### ISSUE TITLE
Scatter plot does not display labels

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#788]
Created via Reamaze by Joy:

Link: https://akvoo.reamaze.com/admin/conversations/scatter-plot-does-not-display-labels
Assignee: Nadia Gorchakova

Message:
Steps:
1. Create a scatter plot
2. Add an aggregator field

Issue:
In the visualisation generated you cannot see what the fields are aggregated on.

Example
Say you have the data for 500 schools
1.  Y- axis : Number of students
2. X-axis : Number of toilets

So you get 500 points

Not you aggregate on Provinces ( say 6).
Now you only get 6 points but looking at the visualisation the user has no context about the aggregation field.

It will be good to display these values on top of the points

**Comment by nadiagorchakova** [comment]
Example: 

<img width="1267" alt="screen shot 2017-05-31 at 10 34 13" src="https://cloud.githubusercontent.com/assets/21127166/26623042/abffc55a-45ec-11e7-9b1c-ec9d466045a4.png">

**Comment by gabemart** [comment]
closed via #937
