### ISSUE TITLE
Hide item checkbox by default

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#789]
# Context
Hiding and revealing actions as need be

# Problem
In the library, we currently show item selection checkbox by default, even though multi-select is not the primary or secondary Action that users are going to do in that view

<img width="373" alt="screen shot 2017-05-31 at 14 56 21" src="https://cloud.githubusercontent.com/assets/12692444/26630913/70c56182-4611-11e7-86cc-5a56038f0d7d.png">

# Proposal
Show the checkbox as a mouse-over (same as with the [...] icon) and reveal checkboxes for other items upon the checking of any one of them.

This will also declutter the interface

**Comment by loicsans** [comment]
Priority: 5
Effort: 3
