### ISSUE TITLE
Data source adapters

### ISSUE THREAD

**Issue by LarsSjogreen** [akvo/akvo-lumen#791]
# Context
We have a number of external parties that want to connect their data sources to Lumen and CSV integration might not cut it in the long run. We also want our data sources to be automatically updating, first with scheduled updates but later on also with push updates where available. This is some of the integrations that probably needs to happen in the coming quarters:

| Name                              | Project            | Structure/tecnology         | Importance |
|-----------------------------------|--------------------|-----------------------------|------------|
| Earthwatch                        | Ground Truth 2.0   | REST API/JSON               | Promised   |
| Gavagai                           | Ground Truth 2.0   | REST API/XML (or JSON?)     | Probably   |
| Access databases                  | 9 country program  | MS Access (ODBC/JDBC?)      | Promised   |
| WinDev                            | 9 country program  | HFSQL                       | Promised?  |
| DHIS2                             | 9 country program  | REST API (JSON?)            | Promised?  |
| InfluxDB (from Akvo IoT back end) | SNV, Harvest Moon  | REST/JSON + Influx Queries  | Promised?  |
| World bank dev. indicators        | Lumen curated data | Zipped CSV or API           | Suggested  |
| IEA                               | Lumen curated data | Semi structured Excel files | Suggested  |
| UNDB HDI | Lumen curated | CSV file | Suggested |
| Gapminder | Lumen curated | Excel file | Suggested |

## Reasons for having adapters (external from Lumen core)
* Make it possible for us to, more easily, connect a large number of different external data sources to Lumen
* Makes the external data sources depend on Lumen and not the other way around (**dependency inversion**)
* Makes it possible to **work interdependently** with Lumen and with data source adapters.
* Make data source adapters and the Lumen product independently deployable, minimizing the shared dependencies.
* Makes the data adapters and the Lumen adapter consumer **testable**
* Make it possible for **third parties to adapt data sources** to Lumen without our involvement at all (better Open Source, more freedom)
* Making **monitoring** of external data sources possible
* Having **common functionality** for data sources (caching, metadata, refresh support, push updpate functionality) in one place

[More background reading on my thoughts on Data source adapters can be found here](https://docs.google.com/document/d/1qT3VDmPO8qm01ojldUUIOJbgACSHnVnUDadORLeZlks/edit#)

# Problem or idea
## What is Lumen data source adapters?
* A way of interfacing to external data sources making Lumen depend on the adapter interface instead of depending on a large number of upstream interfaces (that can change). **Conceptually it is...**
  * An **Anti corruption layer**, preventing models from the bounded contexts of upstream systems leak into the bounded context of Lumen
  * A **Facade**, narrowing down the different available APIs so that there will be no feature creep (by neglect or by accident)

* **Concretely it could be...**
  * A service running in a separate environment. For example a node.js service made with the [Loopback.io scaffolding tool/framework](http://loopback.io/) running on a serverless backend in Kubernetes, such as [Fission](http://blog.kubernetes.io/2017/01/fission-serverless-functions-as-service-for-kubernetes.html).

## The ideal solution would be a piece of technology that
* Transforms the data model from the original data to the (import) data model of Lumen.
* Supports a limited number of actions/verbs that we want all data sources to support
* Handles (either by islolation or by configuration and pass through) the authentication/authorization of the source system
* Transforms the source data format to JSON?
* Allows us (or a third party) to quickly deploy a new adapter whenever it's needed

# Suggested solution or next step
- [ ] Explore if [Fission](http://blog.kubernetes.io/2017/01/fission-serverless-functions-as-service-for-kubernetes.html)/[Loopback.io](http://loopback.io/) could be a suitable solution.
- [ ] Deciding what kind of actions/verbs that data sources should support
- [ ] Deciding what data format should come out of the adapters (that Lumen likes to eat)
- [ ] Researching how permissions should be handled
- [ ] Researching the workflow for Lumen users when adding an external data source (that has been "adapted")
- [ ] Breaking this epic down into smaller actionable issues

**Comment by iperdomo** [comment]
Without being involved in the _complete_ conversation,  IMHO digging exploring technologies is _too soon_, or better said, technologies are an _implementation detail_. Lumen needs to make a decision on a higher level (and abstract) architecture decision, e.g. external datasets will be consumed in a JSON format over an HTTP(S) protocol.

**Comment by LarsSjogreen** [comment]
Yes. Fully understood.

We've had a discussion on this and decided on using CSV over HTTP(S) as the first integration point (reasons for this choice being that CSV enforces data structure ("tidy data") and that many systems already have CSV report functionality built in).

The responsibility of implementing "adapters" is put outside of Lumen product. Choice of implementation technology is not part of this issue.

Still to be decided (I think) is if OAuth or basic auth (or both) should be supported from start.
