### ISSUE TITLE
Thumbnail /preview for library item holder

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#792]
# Problem
In thinking of how to give a gist of the kind of content an item holds besides its metadata (Title, Creator, type, ..) we could use thumbnail screenshots (full or part) of the item to give a 'preview' so to call it of the content in an item. 

We currently are using generic icons and text descriptors but these do not individually or in combination provide as enough gist as a thumbnail/preview might. Given the provision of a filter menu, we might not need to repeat an item [type] by icon or text; the user can select a specific type and deduce the gist of each from the thumbnails; 

![image](https://cloud.githubusercontent.com/assets/12692444/26666641/ae15bf44-46a9-11e7-97ed-11c94e973968.png)

# Proposal
The idea is not to make the content readable but to give an idea of what it is by using a thumbnail preview e.g. 

![image](https://cloud.githubusercontent.com/assets/12692444/26667194/a5ae1768-46ac-11e7-9b50-0e96ba42debf.png)

- The GRID view would also become the primary library view as it provides more gist to the items in contrast to the LIST
- The preview/thumbnail provides more value than asset type generic or even specific icon
- the thumbnail preview will be usable in other parts of the app e.g. in the dashboard editing visualizations' preview

# Context and examples
- Uplabs.com showcased projects
<img width="749" alt="screen shot 2017-06-01 at 09 02 35" src="https://cloud.githubusercontent.com/assets/12692444/26666533/1b41d96e-46a9-11e7-9939-0428882e428b.png">

- Invision projects
<img width="1180" alt="screen shot 2017-06-01 at 09 12 53" src="https://cloud.githubusercontent.com/assets/12692444/26666881/fc595b38-46aa-11e7-9c69-e98966ad839e.png">

**Comment by loicsans** [comment]
Priority: 5
Effort: 8
