### ISSUE TITLE
A mechanism for auto-refreshing Trial Lumen env 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#793]
# Context
Interested partners will be given access to trial Lumen env - https://trial.akvolumen.org

# Problem or idea
The idea is to refresh (delete) the resources that partner creates every three months since they sign up. This way, the partner can check out different functionalities in Lumen but not actually using it for real work.

# Solution or next step

**Comment by janagombitova** [comment]
We no longer use the trial instance as hubs use their own instances for demoing and trialling purposes
