### ISSUE TITLE
Remove Alphabet when library items are sorted by name

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#794]
# Context
Why do we add this issue?

# Problem 
Alphabet list when sorting items by name introduces some UX issues: 
- it breaks the scanning line - the user has to switch from the alphabet line and the item title line; it would suffice to not have the alphabet - the user can scan the item labels - and save the effort of scanning two separate lines
- it adds content/elements to the library in contrast to doing sorting only as other Sort options; which introduces an unexpected behaviour
- Alphabet list can work as a VIEW to minimize distraction it creates when it is added into the library as we have used it atm

<img width="1033" alt="screen shot 2017-06-01 at 09 46 40" src="https://cloud.githubusercontent.com/assets/12692444/26667778/7cc8c188-46af-11e7-9f45-af247f317ae8.png">

# Thoughts & proposal
- It feels that if the user knows by what letter an item begins, it might be simpler to use the search field to find it in contrast. It might be more usable to have a versatile search e.g. supporting  suggestive searches, and show results during typing
- we also need to review whether these sort options are really needed; if items are by default presented by modified data, then we could get rid of the sort option entirely - given that all created items are modified and it is easier for users to recall them by their modification time than by their creation time. The sort by name we can remove and provide a versatile search to cater for it

**Comment by loicsans** [comment]
Agreed to only show "last modified" view.
alphabet will go
Priority: 8
Effort: 2

**Comment by gabemart** [comment]
@loicsans we also agreed to only support the "grid" view going forward, correct? This branch seems a sensible place to do that too
