### ISSUE TITLE
Empty search result page

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#795]
# Problem or idea
We need to provide feedback when a search result returns no data

# Solution or next step
- Hide filter options when there are no results found
- Atm use a [x] icon in the search to undo a search; return to lib/collection. This enables access to the + Asset (Dataset, Visualizations, Dashboard) without having to undo a search. e.g.

![image](https://cloud.githubusercontent.com/assets/12692444/26674498/681bcafe-46c9-11e7-9fdc-02ff791508d5.png)

If this may be deemed confusing, we could restructure the top menu so that during a search it is focused to searching only; + Asset are hidden e.g.

![image](https://cloud.githubusercontent.com/assets/12692444/26674654/cea4534a-46c9-11e7-9fb1-345f0a14a5e0.png)

- in both cases the user can also use the browser back button to go back to their page and thereby undo the search

**Comment by loicsans** [comment]
Second solution.
Priority: 7
Effort: 2

**Comment by gabemart** [comment]
Hiding the filter options is a little more complex than showing the message due to implementation details, so let's show the message as a first pass. I'll come back and work on hiding the filters if there's time in this milestone
