### ISSUE TITLE
Dataset filters for date fields don't seem to be working correctly

### ISSUE THREAD

**Issue by punchagan** [akvo/akvo-lumen#800]
# Problem 
I'm trying to filter a dataset using a column which is a date field and visualize only the rows which have a date after `01/01/2017`, but this doesn't seem to work.  On saving the filter, the date seems to use a default value of `1970-01-18 09:30`.

**Comment by jonase** [comment]
After talking to @punchagan this seems to be for visualisations where we do the aggregation on the backend, so I'll assign it to myself.

**Comment by jonase** [comment]
After some debugging, I think there are two issues going on here:

* #741 
* The client sends a numeric timestamp value (in second precision) but the backend expects a string in millisecond precision.

@gabemart I think we send strings as the filter `value` in all other cases? Should we do that here as well? Also, I think maybe the client should send timestamps in millisecond precision?
