### ISSUE TITLE
Make login options clear

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#807]
# Problem
Currently, the login options are not clearly communicated; besides the Google options does not communicate the action it offers:

<img width="1013" alt="screen shot 2017-06-06 at 12 20 05" src="https://cloud.githubusercontent.com/assets/12692444/26822472/d3d7fc1c-4ab2-11e7-8dc9-02ba1001c92e.png">

# proposal

![image](https://cloud.githubusercontent.com/assets/12692444/26822356/6aede202-4ab2-11e7-8239-f075972bc1de.png)

@iperdomo are there limitations to restructuring the keycloak login page?

**Comment by iperdomo** [comment]
@Kiarii there are non limitations, just need to be made. We already have issues related to this #516 #720 

cc/ @nadiagorchakova

**Comment by iperdomo** [comment]
BTW, using Google Sign-in was enabled just for testing purposes. We need to agree as organization if we want to do that. cc/ @LarsSjogreen

**Comment by LarsSjogreen** [comment]
I have no opinion at all on that. In Flow we do allow (or require?) Google sign in, right?

Why do we offer OpenId sign in from one company (Google) and not from others (Facebook, Dropbox, GitHub, LinkedIn etc)? Is there a specific reason that we decided to go with this company and not others?

**Comment by Kiarii** [comment]
+ also consider providing the logout option

**Comment by nadiagorchakova** [comment]
Loic says it will be taken care of as part of the landing page work
