### ISSUE TITLE
Implement keyboard support

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#809]
# Context
Support easy workflow for power users

# idea
In cases where the keyboard can be used to streamline workflows e.g.

- [ ] - Return for search
- [ ] - Escape for dismissing a dialog
- [ ] - Arrow buttons for scrolling a dropdown menu
- [ ] - Using letter key for selection
- [ ] - Browse tables with arrow keys

# Next step

**Comment by loicsans** [comment]
Priority: 10
Effort: 6

**Comment by nadiagorchakova** [comment]
Agreed to close it for now and implement it on the case by case basis, where needed.
