### ISSUE TITLE
Verify dropped / selected file format

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#810]
# Context
For new dataset importing modal

# Problem
Currently the user can proceed to the Settings step even when the file attached is of an unacceptable format

# Idea
Checking the format should be made at the file dropping/selection step; which would save the user the workflow of having to be brought back to the step after encountering a failure on clicking Import in the third step

**Comment by loicsans** [comment]
Priority: 5
Effort: TBC
