### ISSUE TITLE
Clean up border wobble

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#812]
# Context
We often use borders to show e.g. that an element is highlighted or selected

# Problem or idea
Adding a border can reflow a container or cause a list of items to slightly shift, creating a disconcerting "wobble" effect

# Solution or next step
In my experience an easy way to prevent this is to add a transparent border of the desired width to all elements in a group, and then change only the border color when we want to show a border

**Comment by janagombitova** [comment]
@finnfiddle is this issue still relevant?
