### ISSUE TITLE
Object initialisation and type switching in visualisation editor

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#814]
# Context
We use complex javascript objects to represent visualisations

# Problem or idea
In the visualisation editor, in some circumstances we see javascript errors where we attempt to access properties on `null` where the editor expects a nested object.

There are a few different approaches to solve this. One is to have stricter null checks whenever we access nested properties. We could use a library to help with this. Another object is to do a fuller initialisation on new visualisation objects, using empty objects on nested properties instead of null.

A related problem is "initialising" objects when switching visualisation type. Currently we create a new, empty object when the type is switched, but in some circumstances it would be nice to retain some properties, especially for closely related visualisation types (e.g. pie and donut charts)

# Solution or next step
Decide on one of the above options to prevent null property access errors while preserving as much detail as possible when switching between visualisation types

**Comment by janagombitova** [comment]
I assume the goal of this issue is to make it easier for the user to be able to switch between different visualisation types. This issue has already been resolved. I am closing it but if there is more to in than what I understand please reopen
