### ISSUE TITLE
Make fuller use of flexbox

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#815]
# Context
initially, we were hesitant to use flexbox due to uncertainty about browser support targets

# Problem or idea
Now that we have committed to using flexbox in some areas, there is no advantage to minimising its usage, so we should use it for layout wherever it makes sense.

There is some layout styling that was done before we decided to use flexbox that would much cleaner and more succinct it it were rewritten in flexbox. In particular, the various header components and the library listing.

**Comment by loicsans** [comment]
closing this for now
