### ISSUE TITLE
Remove client side transformations code

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#817]
# Context
We haven't done this kind of hunt in a long time, and the codebase has been changing rapidly.

We should hunt for any code or components that are literally not invoked anywhere or which are still stubs with no content, and eliminate them.

**Comment by jonase** [comment]
One big part of this I suspect is the old client side transformations code which I think never got deleted.

**Comment by gabemart** [comment]
A lot of the old modal code got deleted in the last release

**Comment by janagombitova** [comment]
@kardan is this issue still relevant?
