### ISSUE TITLE
Pivot table editor 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#819]
# Context
With a bar graph, when I switch to a different dataset while editing the visualisation, the previously input values are automatically cleared up. I think it's the same for other graphs too.

# Problem or idea
Pivot table shows a different behaviour. When I switch to a different dataset while editing, some fields are cleared up while others still have values and dropdown from the previous dataset:

<img width="1268" alt="screen shot 2017-06-08 at 17 28 25" src="https://user-images.githubusercontent.com/21127166/26937281-39cc838e-4c71-11e7-883f-a6c86b0ccd9c.png">

In case above, I changed dataset from 'New York City - Leading causes of death' to 'Chikhwawa Core Asset Analysis -- Handpumps' but I still get a dropdown from the New York dataset in the field 'Row column'

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
This issue is no longer present. Case closed
