### ISSUE TITLE
Activate visualization type switching

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#822]
# Problem 
It appears that other than the Map type, the selection of other chart types simply deactivates the re-selection of other types; the dropdown is disabled 

<img width="436" alt="screen shot 2017-06-09 at 12 18 49" src="https://user-images.githubusercontent.com/12692444/26969485-913435b6-4d0e-11e7-9bf2-b1ceae00d762.png">

# Solution
Users should be able to switch visualization types after making a selection

**Comment by Kiarii** [comment]
I also have the feeling we can cut back on the usage of text with the assumption sth actions are quite straightforward; e.g.

- Type [in place of] Visualization type
- Dataset [in place of] Source dataset
- Filters [in place of] Dataset Filters
- Save [in place of] Save changes

**Comment by janagombitova** [comment]
Easily swtiching between different visualisation types has been implemented as well as some of these text improvements with the redesign. Closing this issue
