### ISSUE TITLE
Present chart type picker on type change action

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#823]
# idea:
- present chart type picker on type change action for consistency
- arrange picker in a grid to make good use of type icons
- centre align type icon and label: reduce lateral movement when making a connection between the two for a respective type
- use a less callout color for the icons by default and increase the saturation accordingly upon selection/mouseover

# proposal
![image](https://user-images.githubusercontent.com/12692444/26971973-43f62ca0-4d18-11e7-992e-bda6df28223c.png)

**Comment by Kiarii** [comment]
have had a change of hearts; I am now leaning towards a scrollable container for single select options (drop downs) incl. viz types, aggregation types for lists with 2 - 7 options.. such as illustrated below:

<img width="383" alt="screen shot 2018-07-24 at 15 23 39" src="https://user-images.githubusercontent.com/12692444/43137818-92efa72a-8f55-11e8-9d4e-8c7a0bf4d7db.png">

such a style guide enables a number of things:
- Seeing the selected option and others
- Options in view can be selected without the need to click, scroll & click as with dropdowns
- Switching and viewing options in a list is compact (no need to occlude other UI elements) in contrast to dropdowns: this makes explorative visualization simpler

**Comment by janagombitova** [comment]
This change has been implemented with the entire redesign of the visualisations editor.
