### ISSUE TITLE
Prioritize the placement of [Save] in the visualization editor

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#825]
# Context
In the meanwhile that we deliberate autosave, it makes sense to make the placement of the Save button more prominent in the interface; 

# Problem or idea
the last thing we want is for the user
- to lose their progress if they navigate away without saving, or
- to wonder/worry where the save button went - it keeps pushing down the sidebar 

# proposal
two options:
- stick it to the bottom of the sidebar so it is no longer pushed below
- move it to menu Area, marry it with the "unsaved changes" or in effect get rid of it by making the [Save] disabled if all changes are saved and Active (callout) if there are unsaved changes

It is also worth considering supporting Ctrl S for power users.

**Comment by Kiarii** [comment]
e.g.

![image](https://user-images.githubusercontent.com/12692444/26973536-b78b58dc-4d1f-11e7-965d-3de7729fa1ec.png)

only download (actions in the far right) is functional, but when we build others, depending on how we place them; we can result to icons or text; if autosave manage becomes a reality, we will also have improved things a bit

**Comment by finnfiddle** [comment]
does this look alright @Kiarii ?
<img width="1440" alt="screen shot 2018-03-12 at 4 18 59 pm" src="https://user-images.githubusercontent.com/4628721/37288970-3ec8e51a-2611-11e8-8413-5cf925279902.png">
