### ISSUE TITLE
Download map in GIS file format

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#827]
# Context

In Lumen training with Asia hub, we were also looking at different maps built in Lumen. Someone suggested it would be helpful to download a map built in Lumen in GIS file format.
Then it would be possible to reuse and further enhance the map in GIS software packages.

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
We will provide the option to download maps as a pdf or a png as these requests came from user research on how the maps and other visualisations are used. We have not received requests recently on downloading maps in GIS file format. But for now lets keep this open to see what to do about it in the future

**Comment by kardan** [comment]
This sounds like a whole research project to me. Unless we really need this, I would vote to close the issue.

**Comment by janagombitova** [comment]
I was thinking of the same, actually. Ok let's close and reopen if the request comes up and we start researching
