### ISSUE TITLE
Line chart - single value on X axis not displayed

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#836]
# Context

I added year values to the x axis of a line chart. No values get displayed on the line chart, in case there is only one value available. In the source dataset I used all the values for 'year' column contain '2016'. 

Example: 

<img width="1267" alt="screen shot 2017-06-09 at 16 06 09" src="https://user-images.githubusercontent.com/21127166/26978977-9c7edc9a-4d2d-11e7-8cd2-11bdcd7b94c7.png">

Dataset: https://demo.akvolumen.org/dataset/5919bbbb-d255-4a84-8efa-ae8d823b3eb0

What is the cause?

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
![screen shot 2019-01-07 at 10 16 12](https://user-images.githubusercontent.com/12456965/50759441-4fb88380-1265-11e9-8427-bf39ecb5c024.png)

Issue resolved
