### ISSUE TITLE
Research monitoring

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#843]
At the moment we have limited insight into our running applications. Concerns are for example RAM usage and JVM details.

**Comment by jonase** [comment]
This could be a good start when exploring JVM monitoring on google cloud: https://cloud.google.com/monitoring/agent/plugins/jvm

**Comment by janagombitova** [comment]
@kardan and @dlebrero What is the status of this issue?

**Comment by kardan** [comment]
Agree, hence closing this issue.
