### ISSUE TITLE
Ensure a visualization has a title

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#844]
# Problem
Upon clicking on the title to edit, lumen removes the holder text from the visualization; even though on clicking away the holder "Untitled visualization" remains, it is no longer presented on the visualization preview..

<img width="1175" alt="screen shot 2017-06-12 at 11 54 26" src="https://user-images.githubusercontent.com/12692444/27026329-09895de4-4f66-11e7-9174-50d2272116cf.png">

# ideas?
If the user doesnt edit the title, lumen shd revert to the previous one, to ensure that each contains a title 

Not sure how we want to handle this, we might need to align on this one

**Comment by janagombitova** [comment]
This issue is resolved. When you create a chart 'Untitled visualisation' remains in view until Salim makes and edit to the title. If he gives it a title and the deletes that title, it jumps back to 'Untitled visualisation' what is sufficient
