### ISSUE TITLE
Panel-lize the visualization editor

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#845]
# Context & background
The visualization editor is liable to get long, overly long depending on the configurations that a user makes

<img width="381" alt="screen shot 2017-06-12 at 16 19 33" src="https://user-images.githubusercontent.com/12692444/27035896-a37f8110-4f8b-11e7-88e8-f50fac0ca149.png">

For visualizations with simple configurations, this is fine; but otherwise, the editor becomes a bit cluttered and it is easy to tell where one section of configurations ends and another begins. 
Furthermore, collapsible config sections may enable the user to focus on the section in which they are currently working by hiding others. e.g.
![image](https://user-images.githubusercontent.com/12692444/27035937-d58a6c56-4f8b-11e7-830f-97620f06c959.png)
 
# proposal
if we deem it worthwhile to do this, we would have to consider the different sections that apply to each chart type

**Comment by janagombitova** [comment]
The redesign has already been implemented. This is a duplicated issue
