### ISSUE TITLE
Tabs for visualization editor

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#846]
# Context
In order to enable for quick editing of a chart's Data, legend, pop up and theme, we need to consider the introduction of respective tabs in the data editor
Furthermore, the map chart type already has this so this might just be a point for introducing it to other chart types and thereby giving some consistency on how these sections are handled. 

<img width="386" alt="screen shot 2017-06-12 at 16 29 16" src="https://user-images.githubusercontent.com/12692444/27036076-5d791766-4f8c-11e7-9be2-4d49ad86f7e0.png">

# Solution or next step
How could we solve it?

**Comment by finnfiddle** [comment]
@Kiarii maybe we can incorporate these things into the actual chart canvas - ie making elements of the charts interactive so that the users can edit in the same place that the changes will be reflected. @nadiagorchakova @gabemart @kardan ?

**Comment by nadiagorchakova** [comment]
if that will make user experience better, I'm in for it

**Comment by janagombitova** [comment]
@Kiarii and @finnfiddle do you think this issue is still relevant in the light of the recent refactor?

**Comment by Kiarii** [comment]
i think it might be..

**Comment by Kiarii** [comment]
closing this issue and moving further work to #2359
