### ISSUE TITLE
Switch to latest Node.js and NPM

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#857]
# Context
Make sure dev team are using latest release of Node.js and the NPM package manager.

# Problem or idea
Node v8 and NPM v5 are now the stable releases. NPM v5 is considerably faster than previous versions which will benefit us in local development and production build times.

# Solution or next step
Update node version in `./circle.yml` & `./client/Dockerfile` and commit new NPM lockfile into git.

**Comment by kardan** [comment]
Switching to newer versions caused issues on CircleCI

**Comment by janagombitova** [comment]
@kardan what should we do about this issue?
