### ISSUE TITLE
Move changing data type to column edit menu

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#859]
# Context
At the moment Data type and Column header are links, although differently color coded; this brings about some confusion

<img width="413" alt="screen shot 2017-06-16 at 15 18 53" src="https://user-images.githubusercontent.com/12692444/27226341-3baea326-52a7-11e7-8dc6-4101187945d6.png">

# Idea
- Move the Data type switching menu into the Column Edit menu: 
- which would mean there is only one menu for a col header
- Make the col header as the clickable item (which is a larger target) to reveal the menu
- Reduce the font size of the data type; only take 4 chars: TEXT, DATE, NUM, GEO, ..

![image](https://user-images.githubusercontent.com/12692444/27277333-94ecc63e-54e6-11e7-815d-9464726b58fb.png)

![4F25D664-C209-4086-8102-783BD189C71E](https://user-images.githubusercontent.com/12456965/81767870-c4df3d00-94d9-11ea-91e9-1d5825d1fa25.jpeg)

**Comment by Kiarii** [comment]
Please note that the actions have been re-ordered; to introduce some hierarchy: frequently used or most likely used appearing atop..

**Comment by Kiarii** [comment]
#871: Group col-edit-menu options: proposes a grouping for the options

**Comment by janagombitova** [comment]
Relevant issues: https://github.com/akvo/akvo-lumen/issues/863 and https://github.com/akvo/akvo-lumen/issues/872

**Comment by janagombitova** [comment]
Keep open for Anthony O
