### ISSUE TITLE
Unify date expression

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#860]
# Context
Months are easily identified with their text abbreviation Jan, Feb, etc. When dates are presented as 2017 03 01 it becomes tricky to id the month from the day. Additionally the date abbreviations 1st, 2nd, 3rd, are unnecessary; 2017 Mar 01, or 2017 03 Jan is explicit by itself. 

- Lib: Jan 3rd 2017
- Dashboard: 2017-06-01

# Proposal 
Id and unify all date instance where used in lumen to: 
- Jan 03 2017

This also implies the same in datasets: Jan 03 2017 is less confusing than 01 03 2017; which would have different interpretations depending on Jerome's locale or computer set region

**Comment by gabemart** [comment]
Merging with #979
