### ISSUE TITLE
Right align numerical data

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#861]
# Context
Aligned data is easier to scan than non-aligned data. e.g. A number col aligned right makes it easy to see values in terms digit count

Some thumb rules for tabular data presentation:
1. Numerical data is right-aligned (this doesn't incl. Geo data, phone numbers, IPs etc; each of these has to be handled case by case as the respective data types are supported). 
2. Textual data is left-aligned

# proposal
![image](https://user-images.githubusercontent.com/12692444/27276655-88a11db4-54e4-11e7-9b1b-bf55164ced2f.png)

This issue might need more thinking in order to determine how to handle the special numerical data types, but I put it up for documentation purposes

**Comment by janagombitova** [comment]
Works well also with switching data types from text to number and back
