### ISSUE TITLE
Show more characters to support long COL titles

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#862]
# Context
We are at the moment supporting about 15 chars for col titles which makes it difficult to understand the data since a mouseover to reveal truncated text is necessary for most cols. In this example all col titles are truncated :( 
<img width="1265" alt="screen shot 2017-06-19 at 11 46 35" src="https://user-images.githubusercontent.com/12692444/27276814-0e630a84-54e5-11e7-83a6-f834602856aa.png">

# idea
- Reduce col title font size
- Remove bold styling
- Support 2 lines ~ 30 chars before truncating

![image](https://user-images.githubusercontent.com/12692444/27277079-c198d2dc-54e5-11e7-841e-c272e9f1d96c.png)

This would also make it easy for the user to determine whether to rename a col (if need be) when they are able to see much if not all of the title.. other functionalities also require understanding the title so the more its visible, the easier it is for the user to determine their course of action..

**Comment by Kiarii** [comment]
![image](https://user-images.githubusercontent.com/12692444/27277171-1618ebf8-54e6-11e7-8778-b71a96750dde.png)

**Comment by Kiarii** [comment]
In the wake of thw new data type - Geopoint - it may be best to adjust the placement of the type label in the col header to accommodate the longer type, for now:

![image](https://user-images.githubusercontent.com/12692444/28824838-98cd2d5e-76cc-11e7-869e-ca0cab8a330c.png)

**Comment by janagombitova** [comment]
This issue to seems seems to address the problem described here: https://github.com/akvo/akvo-lumen/issues/868. To ensure we handle the problem in one issue I am referencing this one and closing it.

**Comment by janagombitova** [comment]
Closed the wrong issue, so reopening this one. To clarify the task is to:
* [ ] Adjust column header styling 
* [ ] Support 2 lines ~ 30 chars before truncating
* [ ] Change how data type is displayed

**Comment by Kiarii** [comment]
Following the discussion and considering the UX side of things, the last proposal made might improve the scannability and readability of both col **data types** and **names** as illustrated below. This would also mean that the col titles can use a lesser font weght and font and thereby reduce visual distraction and enable long titles to be easily readable..

<img width="1092" alt="Screenshot 2019-09-06 at 12 20 25" src="https://user-images.githubusercontent.com/12692444/64416959-d6e22380-d0a0-11e9-9cd8-83d922af3520.png">

**Comment by muloem** [comment]
@tangrammer is this fully completed?

**Comment by tangrammer** [comment]
nope :/
