### ISSUE TITLE
Minimize the prominence of col data type

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#863]
# Problem 
Atm this is taking more screen space than necessary; and with bold styling and a font similar in size with the col title. In addition the placement of 2 links side by side (COL Type & Title) hampers the UX; it is not clear if both are links, why they are placed next to each other with different color coding and what action they represent.

<img width="425" alt="screen shot 2017-06-19 at 11 56 29" src="https://user-images.githubusercontent.com/12692444/27277253-5d9739f8-54e6-11e7-9fab-cf17fbcc4d9e.png">

# Idea
One way to address this is to minimize the prominence of the data type by
- Reducing the font size
- Reducing the font color
- Removing the link; combining data type changing with the col edit menu: #859
- i.e. Type text to rep TYPE only
- Flipping the type to leave space for longer col titles 

![image](https://user-images.githubusercontent.com/12692444/27277628-824fd092-54e7-11e7-99b6-5293b6617c58.png)

**Comment by janagombitova** [comment]
When working on this issue we need to decide on the final designs as we have two options now: https://github.com/akvo/akvo-lumen/issues/862#issuecomment-319353887

**Comment by janagombitova** [comment]
This issue once handled will be done as part of the issue referred above as they both handle the same change
