### ISSUE TITLE
Present question descriptions for Flow data

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#865]
# Context
Just as with the indication of whether a col was a compulsory or optional question, a question's description also plays part in determining what transforms are to be performed or how a cols data is to be analyzed 

# Idea
Show col descriptions, by default (2 options, other ideas?)
- by enlarging the title field to accommodate this or
![image](https://user-images.githubusercontent.com/12692444/27279408-3346a7b8-54ed-11e7-83e3-b9357876b1c7.png)

- by showing them as an extra row under the title row
![image](https://user-images.githubusercontent.com/12692444/27279427-440da77c-54ed-11e7-97ed-90d406c2876c.png)

**Comment by janagombitova** [comment]
I do not see the value of this change. The question descriptions created in Flow's survey editor hold explanations for Alphonso on how to ask the question or what answers to expect. They are not notes for data analysis. Thus I do not see the value of cluttering the data analysis step with more details. Furthermore we have not received this request from our users or heard it in any feedback sessions so far. 

For now I am closing it and we can always reopen if the value arises again
