### ISSUE TITLE
Col edit menu options hidden if col is sorted

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#866]
# problem
It appears that when a column is sorted, some of the col edit menu options - Filter, Whitespace, Change case - are hidden:

<img width="211" alt="screen shot 2017-06-19 at 14 01 49" src="https://user-images.githubusercontent.com/12692444/27282281-efd51004-54f7-11e7-9a45-494e476357de.png">

# next step
Is this on purpose? If not, we need to show all options..

![image](https://user-images.githubusercontent.com/12692444/27282399-62bbcaea-54f8-11e7-9713-120c7531d35e.png)

**Comment by nadiagorchakova** [comment]
Hi @Kiarii! Filter, change case, whitespace removal options are only available on text data types at the moment. I think the one in the example is a numeric one.

**Comment by Kiarii** [comment]
Thanks @nadiagorchakova, I didnt realize this; I guess given the case (that filters are not part of NUM data types) I can close this issue?

**Comment by nadiagorchakova** [comment]
I think it would make sense to add Filters to NUM data types. The other options  - change case, whitespace removal are not relevant for NUM type.

**Comment by janagombitova** [comment]
Closing this issue. If we see the need to add filtering for number columns then we need to open a new issue dedicated to handling that opporunity
