### ISSUE TITLE
Support expanding col width

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#868]
# Context
In  some cols, the titles and values are truncated and hidden respectively

# Problem
It appears it is not possible to expand col width to reveal title and values in full, which will be desirable in most cases

# Proposals
Lets review these together..
- support resizing col width
- keep minimum (current?) & max (when all values are revealed?) width to make resizing usable
- drag col right edge to resize
- double click col edge at col title to toggle from min to max

**Comment by janagombitova** [comment]
We aim to resolve the problem first with this change: https://github.com/akvo/akvo-lumen/issues/862 and then consider more changes if still necessry. Closing this issue
