### ISSUE TITLE
Perform Transforms in a separate screen

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#869]
# Context / idea
Perform transform actions in a separate screen from the dataset to accommodate
- previews
- complex transforms e.g. scoring, clustering, ..
- long texts (col titles, cell values, etc
- dedicating a transform to a screen reduces distraction

# next step
kiarii to provide mockup..

**Comment by Kiarii** [comment]
e.g.

![image](https://user-images.githubusercontent.com/12692444/28776415-42ee7e9c-75ff-11e7-8260-cadd0144b357.png)

**Comment by janagombitova** [comment]
I am closing this issue as we should decide on in when discussing supporting more complex transformations as scoring and handle it then at once
