### ISSUE TITLE
Re-label change data type options

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#872]
# Context
#859 Merge data type & col edit options menu 
After merging the data type & col edit option menus, it might make sense to re-label the change data type:
- To text
- To number
- To date

![image](https://user-images.githubusercontent.com/12692444/27324909-58f2076a-55af-11e7-809f-12d0680feef0.png)

**Comment by janagombitova** [comment]
This issue once handled will be done as part of the issue referred above as they both handle the same change
