### ISSUE TITLE
Keep col edit menu in view

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#873]
## Context
the user may open the menu at the rhs edge of the screen;

<img width="1390" alt="screen shot 2017-06-20 at 12 02 31" src="https://user-images.githubusercontent.com/12692444/27325221-6435192c-55b0-11e7-9e28-e3b2883add01.png">

## Problem
If the menu options are not visible, 
- it forces the user to forfeit an action, instead to scroll to bring the menu in view
- it might give the illusion that the col is not editable of there is a bug
 
## proposal
Build in a mechanism to always bring the menu in view (e.g. to the left if the user opens it at the edge as in the example above)

**Comment by janagombitova** [comment]
I could not reproduce this issue. For the last column the menu is always in view. @Kiarii can you clarify this a bit more or close the issue? thanks

**Comment by Kiarii** [comment]
its still there; if you open a submenu item on Sort, Whitespace, Change case
