### ISSUE TITLE
filtering for date in dataset filter 

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#877]
Created via Reamaze by Nikki
![filter_by_date](https://user-images.githubusercontent.com/21127166/27392533-3418dbd2-56a7-11e7-99d7-9d11740db614.gif)
:

Link: https://akvoo.reamaze.com/admin/conversations/bug-in-the-date-filter

Message:
Hi guys, 

Just been trying to filter based on date. I’ve recorded a gif of what happened. I’ve entered the filter as after 01/01/2014 (selecting the DD/MM/YYYY format) - however in the fitler text it states 1970. Could be  bug in the display or something else. 

Can you have a look please?

**Comment by jonase** [comment]
I believe this is a duplicate of https://github.com/akvo/akvo-lumen/issues/800

**Comment by nadiagorchakova** [comment]
True! Thanks @jonase, closing this one
