### ISSUE TITLE
New user invite missing the name of a person who invited

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#881]
# Context

The invitation email to the trial instance trial.akvolumen.org is missing the name of a person who sent the invitation.

<img width="436" alt="screen shot 2017-06-22 at 11 28 06" src="https://user-images.githubusercontent.com/21127166/27427152-3e1ff7ae-573e-11e7-8ece-ce534433ae77.png">

Maybe @peeb and @kardan could have a look?
# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by peeb** [comment]
@nadiagorchakova , after @kardan has refactored user management, we can pass the user's name into the API response, which can then be included in the email text.

**Comment by nadiagorchakova** [comment]
thanks for the update @peeb

**Comment by kardan** [comment]
Turns out users in Keycloak don't have their first name and family named filled in. Hence the email renders empty. Suggestion is to the email address instead
