### ISSUE TITLE
Improve the user invite text

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#882]
# Context

The current version looks like that:

<img width="436" alt="screen shot 2017-06-22 at 11 28 06" src="https://user-images.githubusercontent.com/21127166/27428117-5f0a80d0-5741-11e7-91a9-c82d39fcd536.png">

# Solution or next step
@peeb agreed to have a look

**Comment by kardan** [comment]
Let's wait to do this until after the user management refactor is done.

**Comment by peeb** [comment]
👍  @kardan ^^
