### ISSUE TITLE
Clickable Akvo Lumen logo on shared visualisations and dashboards

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#887]
# Context

For the Ground Truth 2.0 project, our partners might share visualisations made with Lumen via different social media channels (it's just an assumption at this point as it's not yet clear what user behaviour will be).

Thomas and Lynn who are in touch with Ground Truth partners suggested that Akvo Lumen logo, which is already visible in the bottom right corner of shared visualisations, should click through to either akvo.org or the future Lumen landing page. This will help raise more awareness about what Lumen and Akvo as a whole do.

**Comment by janagombitova** [comment]
Completed and in place. Clicking on Akvo Lumen logo brings you to the Product's page on akvo.org
