### ISSUE TITLE
The client doesn't differentiate between "no entities" and "api hasn't responded yet"

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#899]
# Context
The client calls the API for a list of entities (visualisations, datasets etc) and then shows the results to the user. 

But currently, when "dumb" components are fed an empty list of entities, they can't know if it's because the api has returned 0 entities (empty library), or if it's because the api hasn't responded yet or has failed to respond.

This makes it difficult to show appropriate help text. If we add help text for "empty library", the user might see if for a short time before the API returns and the library view is populated. This is confusing and bad UX

# Problem or idea
We fixed this with collections by using an initial state of `null` rather than using an empty array or object. Therefore whenever the list is non-null we know it's been returned by the API.

We could do the same with all entity types, but it will very probably involve fixing some parts of the code that expect those entity lists to never be `null`.

We could also use some other representation, like a special `haveReponse` key or something, but this introduces considerably more complexity and corner cases.

# Solution or next step
I think using `null` might be the best option, but would be interested to hear other opinions.

@jonase @peeb what do you think?

**Comment by janagombitova** [comment]
@kardan what is the status of this one?
