### ISSUE TITLE
Integrating akvo-maps with Lumen

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#901]
# Context

Currently maps are rendered entirely client side in Lumen with the entire dataset in browser memory. This works well for small datasets (say, less than 10 000 points) but does not scale to medium/large datasets.

[Akvo-maps](https://github.com/akvo/akvo-maps) is a project that serves map tiles (server generated) using [windshaft](https://github.com/CartoDB/Windshaft). Windshaft is potentially a good candidate for use in lumen because it is specifically designed for postgres/postgis (which we're using to store datasets in lumen).

Windshaft is a node *library* which interacts with postgres, redis and mapnik so we can not directly use it as a library in our jvm based backend.

# Problem or Idea

After an initial meeting (@iperdomo, @kardan, @nadiagorchakova, @LarsSjogreen) we discussed the following possible high level approach on how to integrate the akvo-maps tiler with Lumen:

The idea is to add a new tiler service to our deployment. This tiler service would be built by the platform team but run (and maintained?) by the lumen dev team. The tiler will have direct access to our tenant databases in order to run the queries necessary to build the tiles.

The tiler will not talk directly to the browser (client) but instead requests will go via the current backend where they can be validated, authenticated and authorized. The backend will then build a windshaft map config object which is used to get a map token from the tiler (windshaft). Once the client gets the map token we believe it can talk directly to the tiler from then on.

![lumen-maps](https://user-images.githubusercontent.com/101023/27636184-f04d85f8-5c12-11e7-9e7b-5e0ed7a48732.png)

# Solution or Next Step

**Comment by LarsSjogreen** [comment]
Question/clarification:

How do we allow the client to talk to the tiler while we still protect the tiler endpoint that accepts SQL queries? (I.e. how do we ensure that someone doesn't issue their own SQL queries to the tiler when they have client access? Security by obscurity is not sufficient. Should we have separate endpoints?)

**Comment by kardan** [comment]
Other research topics: 

- how to integrate Lumens current setup with one "master" database with a table containing tenants (jdbc string with different passwords) and akvo-maps current _approach_ with host/<db>/ to dispatch based on db. 

- the underlaying table name for a dataset changes on things like transformations, undo and in the future probably updates. How does this work when the map editor generates sql and send to the tiler. Can the map config be updated based on an existing map token?

- the map token returned from the tiler; is that used as a hash for caching of tiles, if so what happens when data updates (maybe this is not how it works)?

**Comment by jonase** [comment]
@LarsSjogreen 

> How do we allow the client to talk to the tiler while we still protect the tiler endpoint that accepts SQL queries?

I don't know. A lot of these things are yet to be researched I think (same with @kardan's thoughts above). The issue description is perhaps more a summary of what we discussed, and the feasibility of it need to be researched. That's why I left the `Solution` part empty :)

**Comment by LarsSjogreen** [comment]
Good. (I was just adding the question to make sure that it isn't missed.)

**Comment by iperdomo** [comment]
> * how to integrate Lumens current setup with one "master" database with a table containing tenants (jdbc string with different passwords) and akvo-maps current approach with host// to dispatch based on db.

Can you explain the problem? Right now there one _sample_ way of connecting to a db, nothing prevents to change those DB connection properties dynamically.

> * the underlaying table name for a dataset changes on things like transformations, undo and in the future probably updates. How does this work when the map editor generates sql and send to the tiler. Can the map config be updated based on an existing map token?

No, a map token is _unique_ to a MapConfig definition, it also expires. If you SQL statement changes, your token changes too. Think of if as a `JSON.stringify(mapConfig)`.

https://github.com/CartoDB/Windshaft/blob/3.2.1/lib/windshaft/storages/mapstore.js#L138
https://github.com/CartoDB/Windshaft/blob/3.2.1/lib/windshaft/models/mapconfig.js#L48-L56

Quick idea: If you want _stable_ table names you could simulate a file system symbolic link (`ln -s`) using a database view, a known not-changing view name, but it changes the underlying `SELECT * FROM dataset_table_version`. Not sure if is needed though.

> * the map token returned from the tiler; is that used as a hash for caching of tiles, if so what happens when data updates (maybe this is not how it works)?

There is a documentation on how to invalidate data. Basically part of your token is the last-update-timestamp of the table you're querying.
https://github.com/akvo/akvo-maps/blob/master/images/tiler/doc/MapServiceCaching.txt

**Comment by iperdomo** [comment]
> How do we allow the client to talk to the tiler while we still protect the tiler endpoint that accepts SQL queries?

There is distinction between `POST` and `GET` requests. Only `POST` requests are allowed to include SQL statements within a `MapConfig` definition. A `POST` must be checked by the Clojure backend (auth, authz), `GET` requests should be sent directly to Windshaft HTTP service

**Comment by iperdomo** [comment]
After a conversation with @peeb we're going to divide the work in smaller tasks:

- [ ] Pure data transformation from _Lumen Map spec_ to a Windshaft [MapConfig](https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.6.0.md) - @peeb 
 - Lat/lon - to geometry
 - Data driven styles
- [ ] Docker container with Windshaft+Redis to be used in a Lumen deployment (no multi-tenant) - @iperdomo
- [ ] Hook-and-use the docker container to get tokens from Windshaft (Authn|Authz required) - @peeb 
- [ ] Work on multi-tenant Windshaft container - @iperdomo
- [ ] Modify deployment to use the new container as part of the _pod_
- [ ] Modify the client to start use the new maps API using Leaflet - @peeb 

## Open questions
- An implementation detail: the _geom_ column required by Windshaft is the execution of the PostGIS functions ` ST_SetSRID(ST_MakePoint(longitude_column, latitude_column), 4326)` which should be pre-computed for performance reasons. This value gets stored in a new column, e.g. `the_geom`. We need to define _when_ we'll add this column and compute the value.

**Comment by iperdomo** [comment]
Relevant function - http://postgis.net/docs/AddGeometryColumn.html

**Comment by peeb** [comment]
Lumen mapspec doc needs to be updated to reflect current reality - as per #963

**Comment by peeb** [comment]
# Update

After a conversation with @peeb we're going to divide the work in smaller tasks:

- [x] Pure data transformation from _Lumen Map spec_ to a Windshaft [MapConfig] (https://github.com/CartoDB/Windshaft/blob/master/doc/MapConfig-1.6.0.md) - @peeb 
 - Lat/lon - to geometry - #967 
 - Data driven CartoCSS styles
 - See issues: #967, #972 
- [ ] Docker container with Windshaft+Redis to be used in a Lumen deployment (no multi-tenant) - @dlebrero 
- [ ] Hook-and-use the docker container to get tokens from Windshaft (Authn|Authz required) - @peeb 
- [ ] Work on multi-tenant Windshaft container - @iperdomo
- [ ] Modify deployment to use the new container as part of the _pod_
- [ ] Modify the client to start use the new maps API using Leaflet - @peeb + @gabemart 

## Open questions
- An implementation detail: the _geom_ column required by Windshaft is the execution of the PostGIS functions ` ST_SetSRID(ST_MakePoint(longitude_column, latitude_column), 4326)` which should be pre-computed for performance reasons. This value gets stored in a new column, e.g. `the_geom`. We need to define _when_ we'll add this column and compute the value.

**Comment by kardan** [comment]
Example on how to decrypt message from Lumen
https://github.com/akvo/akvo-lumen/issues/1006#issuecomment-329373437
