### ISSUE TITLE
Name visualizations & dashboards within editors

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#920]
# Context
Visualizations comprise of a number of things: title, axis labels, visual elements, etc. It may be more intuitive to edit the title from the visualization container, also if axis labels are also editable from within.

Dashboard: the assumption is that a text editor like canvas would be a starting point for the canvas; where the first row is reserved for the editor only e.g.
![image](https://user-images.githubusercontent.com/12692444/27730580-657a7d1a-5d92-11e7-8130-9e329e914886.png)

This enables us to keep the title in the editor, where the users get a good idea on the WYSIWYG. i.e. how the dashboard will appear when published

# Proposal
- provide title editing functionality within the respective editors
- use the top as a 'page title' (untitled visualization / untitled dashboard) 
- change page title, when asset title is changed

**Comment by Kiarii** [comment]
the ability to directly edit chart title and axis labels has also been requested by one of our early access users..

**Comment by janagombitova** [comment]
Editing the names is possible already in the editor, so this issue is resolved. On renaming labels we have a separate issue to handle it
