### ISSUE TITLE
Long visualisation titles appear cut off

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#931]
# Context
With the new design in place, some longer visualisation titles appear cut off:

<img width="1267" alt="screen shot 2017-07-03 at 13 37 08" src="https://user-images.githubusercontent.com/21127166/27791699-a5a41a8e-5ff6-11e7-8919-5261d633eb62.png">

# Problem or idea

A few issues here:

- People tend to give long titles to their visualisations. Looks like they use title to explain what the visualisation is about. An example: "Relationship between Household Income and Access to Handwashing Facility_Jigmy". Do we need a separate field for Description?
- how to deal with long strings across Lumen in a coherent way?

# Solution or next step
How could we solve it?

**Comment by Kiarii** [comment]
+ we can use smaller font size here and the two lines to accommodate long titles
+ perhaps soon we need to consider a character limit for titles?
+ imho a description/caption here is not necessary; the visualization shd somehow describe itself; in the dashboard that may be a different story altogether depending on what msg a presenter is driving at..

**Comment by loicsans** [comment]
Since the title appears on top of the visualisation. I suggest we do not touch the font-size, which will create unconsistency with other h1 across lumen, but we just trunk it to fit the max container width.
