### ISSUE TITLE
Hide buttons and actions that are not implemented yet

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-lumen#932]
# Context
Why do we add this issue?
We have several buttons dropped as placeholder in the UI

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?
Use display: none;

**Comment by Kiarii** [comment]
+ hide library/collection filter menu until further notice/review; some confusion between the asset creation and filter options have been noted

**Comment by loicsans** [comment]
the asset screen is now temporary looking like this:
![screen shot 2017-07-31 at 16 04 23](https://user-images.githubusercontent.com/1717219/28778923-02ba0a3e-760a-11e7-8dd2-1bce9c6d0b6f.png)

**Comment by Kiarii** [comment]
the filters have been found confusing by some users because of the proximity and appearance of duplicity of the filter options and the [+ Asset] buttons.
The filters need to be looked into with more detail so alleviate the said confusion.
