### ISSUE TITLE
Create static landing page

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#933]
# Context
Why do we add this issue?

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by Kiarii** [comment]
based on the storymap: https://app.mural.ly/t/akvo8194/m/akvo8194/1494319296733, here are the lumen lander wireframes: https://invis.io/PVBNA1DGW

**Comment by loicsans** [comment]
It turns out that it's not technically possible to support multi tenancy at the moment, making this unuseful for the moment.

**Comment by Kiarii** [comment]
the mockup actually addressed both use cases: a) single tenancy and b) multi-tenancy. This means that in the case of (a) the logging works directly to a single instance; the instance selection page is ignored..

**Comment by jonase** [comment]
> It turns out that it's not technically possible to support multi tenancy at the moment

@loicsans could you describe why this is the case? During the user story mapping sessions we tried to figure out what can and can't be shown if the user is logged in or not

**Comment by loicsans** [comment]
After discussion with Nadia, we decided that the way forward is to akvo brand the keycloak login page with a message conveying the one login to all akvo products idea. The message can be something like that: "One way to access all akvo services". 
Several steps are then necessary, have a next page that give option to select the tenacy you want to connect to and going further lets you choose the akvo service you want to connect to.

**Comment by nadiagorchakova** [comment]
Closing this as akvo brand keycloak login page has been implemented. we can return to the use case of multi-tenancy (see Kiarii's mockup) later.
