### ISSUE TITLE
Canvas: make into WYSIWYG

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#943]
# Context
WYSIWYG: what you see is what you get; in other words, the edit view shd at the same time be a preview for the reading view.

# idea
- switch canvas border & background colors: the viewing uses white as background
- users have a good feel of how their dashboard will look like - without having to open a separate tab to see it
- Textboxes, when deselected, do not necessarily need borders; on the view mode the interface is cleaner without borders for text..
- Auto-resize textbox e.g. when a piece of text larger than size is pasted in
- Empty spaces between objects should be removed in viewing mode; e.g. 

<img width="928" alt="screen shot 2017-07-06 at 16 06 34" src="https://user-images.githubusercontent.com/12692444/27912320-1e0bdabe-6265-11e7-9028-829ded8bef64.png">

**Comment by janagombitova** [comment]
Most of the points mentioned here are resolved. So closing this issue for now and if we find more improvement to make on the canvas, we will add them as separate issues
