### ISSUE TITLE
Option to display value labels in visualisations

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#945]
# Context

Currently value labels in visualisations are visible on hover.
When someone does a screenshot of a visualisaiton or, in the future, downloads it in jpeg or pdf format, the value labels are lost. 
Loosing value labels might be a problem as in some cases it's difficult to visually assess the size of a data sample:

Example:
<img width="350" alt="screen shot 2017-07-06 at 14 30 43" src="https://user-images.githubusercontent.com/21127166/27910976-bbfdd190-6257-11e7-96ff-c5b342161ea2.png">

In other cases, however, it might not work to display all of the value labels, for instance when there are hundreds of data points on a scatter plot.

# Problem or idea

Perhaps making it a option in visualisation editor to display or hide value labels. 
Users should decide where it's reasonable to display them.

# Solution or next step

**Comment by janagombitova** [comment]
We have decided with @finnfiddle and @nadiagorchakova and @gabemart to start with adding the option to display values -Show values - for pie charts first. The 2nd candidate is stacked bar charts where we see this as a valuable addition to the visualisations. For the other ones we do not see it adding more value to Jerome when viewing the visuals. 

The pie charts change is handled here: https://github.com/akvo/akvo-lumen/issues/1494
