### ISSUE TITLE
Support for Caddisfly data (basic implementation)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#946]
# Context
Currently Caddisfly data is not displayed in Lumen when imported directly from Flow.

# Problem or idea
Thomas needs to have some basic support for Caddisfly data by Stockholm Water Week as he wants to demo this integration.

The basic implementation of support for Caddisfly data means:
Present data as JSON blobs and then use derived column functionality to split it into columns.

A document with Caddisfly test types https://docs.google.com/document/d/1KRdUp59T3_heDksx9l2GV8UUUQixZiAuAB-Rl-l8d6k/edit#

Note to self: Lars asked for this transformation involving derived column to be documented in [Transformations Cookbook](https://docs.google.com/document/d/1QQCzOibsC2s906IZLbyCkVK1NPGcsH7KWC_OJPXRJ28/edit) for other partners to see.

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
A typical caddisfly response looks something like this:

```json
{
  "type": "caddisfly",
  "name": "Water - Electrical Conductivity",
  "uuid": "f88237b7-be3d-4fac-bbee-ab328eefcd14",
  "result": [
    {
      "name": "Electrical Conductivity",
      "unit": "\u03bcS\/cm",
      "id": 1,
      "value": "738.8"
    },
    {
      "name": "Temperature",
      "unit": "\u00b0Celsius",
      "id": 2,
      "value": "27.3"
    }
  ],
  "testDate": "2017-05-08 14:44",
  "user": {
    "backDropDetection": true,
    "language": "en"
  },
  "app": {
    "appVersion": "Version 1.0.0 Beta 8.5",
    "language": "en"
  },
  "device": {
    "model": "SM-G550FY",
    "product": "o5proltedd",
    "manufacturer": "samsung",
    "os": "Android - 6.0.1 (23)",
    "country": "GB",
    "language": "en"
  }
}
```

For the purpose of a visualisation, we are almost always interested in one of the `value`s inside the `result` array.

Using a derived column expression, this value can be extracted with the expression (setting the resulting column type to `number`): 
```javascript
parseFloat(JSON.parse(row['col name']).result[0].value)
```

If you're interested in the temperature instead of the conductivity, just change the array index to `1` instead of `0`.
