### ISSUE TITLE
Updating existing datasets with new data

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#947]
# Context
The data for some data sources evolves over time with new or modified data.  

# Problem or idea
We should be able to update the lumen datasets with the latest data from the data source and (if the update is successful) reuse all existing transformations, visualisations and dashboards.

# Solution or next step
As a first implementation the updating will be "manual". A user will request an update from the Lumen UI. 

A future feature will be for the user to schedule periodic updates.

**Comment by Kiarii** [comment]
we have settled to handle the following phases in an update process as illustrated in the wireframes: https://projects.invisionapp.com/share/VBCKKSN2D#/screens/243560664
- initiating the process
- acknowledging or confirming the initiation of the process
- process failure; various scenarios
- process success
- process prevention / postponing (/scheduling* - tbd in the future)

This also brings into mind the Activity log on which the user can view system events, whose notifications they do not see for various reasons. Hopefully we can in the near future also follow up on this implementation..
