### ISSUE TITLE
Visualization metadata: show parent dataset

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#949]
## Context:
Show as part of a visualization's metadata; its parent dataset:

possible use cases:
- When sharing a visualization someone might want to know what the source dataset is
- when viewing a visualization (within lumen) it might help
- when adding visualizations to a dashboard (this could partly be covered by a search or filter for visualizations from a specific dataset)

## Proposal 
Lets catch up on this one and see how it could work, there might be situations when the parent dataset needs to be hidden for a visualization, so we need to figure if and how to work them

**Comment by nadiagorchakova** [comment]
Related to that, I think we should also think about captions for visualisations, as discussed earlier. A source dataset can be mentioned in a caption, for example
