### ISSUE TITLE
Context menu occludes item name

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#950]
# Context
Why do we add this issue?
- The user needs to be able to see the title when selecting an action to perform on a respective item;

<img width="562" alt="screen shot 2017-07-12 at 15 47 18" src="https://user-images.githubusercontent.com/12692444/28118427-a0f8d1d0-6719-11e7-8e1b-51f3e3ab26f3.png">

# proposal
- place the context menu in a way that it leaves the the item name in view e.g.
<img width="414" alt="screen shot 2017-07-12 at 15 51 31" src="https://user-images.githubusercontent.com/12692444/28118536-1252129c-671a-11e7-8393-d4ba42e44c54.png">

**Comment by janagombitova** [comment]
Issue is resolved. The menu appears under the item
