### ISSUE TITLE
Colour picker in visualisations

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#951]
# Context

In our current implementation visualisations are built with default colour scheme e.g.
<img width="705" alt="screen shot 2017-07-12 at 15 59 55" src="https://user-images.githubusercontent.com/21127166/28121389-3aed48b0-671b-11e7-842f-b9a612fe4555.png">

Functioning hand pumps are by default shown in red.

# Problem or idea
Colour has certain symbolism. In the case above, it would be more intuitive to represent non-functioning hand pumps in red.

Some partners, apparently, use specific colour schemes for working with visualisations and maps. UNICEF, according to Luuk, use 'traffic light' colour scheme (red/yellow/green) in their data visualisations.

Additionally, when different graphs and maps are combined in one dashboard, it's important that colours mean the same thing in every visualisation. 

# Solution or next step
Enabling custom colours in visualisations might solve the colour inconsistency issue

**Comment by janagombitova** [comment]
Issue resolved with new visualisations library that enables Salim to choose which colour he wants for which value
