### ISSUE TITLE
Download option for visualisations and dashboards

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#952]
# Context

In some cases, sharing a visualisation/dashboard via a public link is not enough.
A few partners and partner team members inquired about the 'download' option. 

Use cases:
- sharing a graph/dashboard in paper format with people who don't have internet access
- using a a graph/dashboard in a printable report

As a workaround, it is possible to do a screen grab or to print a web page as a pdf, however, not everyone is happy with it. Apparently it's not easy to do on some devices.

A menu ribbon in visualisations and dashboards has a place holder for download option:
<img width="302" alt="screen shot 2017-07-12 at 16 27 43" src="https://user-images.githubusercontent.com/21127166/28122979-129ffd44-6720-11e7-82d5-a8bf92e68bcd.png">

**Comment by janagombitova** [comment]
Today we discussed with @finnfiddle and @Kiarii this issue. For more notes check the mural board here: 
https://app.mural.co/t/akvo8194/m/akvo8194/1530179115317/37ab92510e4b61e456fbbc02ff9cfe5f63684dc3

# Why
As mentioned in the description above, the reason to allow users to download their visualisation or dashboard is to allow them to use the visualisation or dashboard offline, in their report to a donor, in their project report or presentation, to add to a poster and showcase. 

Currently users use screen grabbing to get an image of their visualisation or dashboard. This approach is not ideal as not every user is familiar with screen grabbing and you cannot always see the values (resolved for pie charts in a separate issue and will create another issue for stacked bar charts). 

# Idea 
We will enable Jerome to **download** his visualisation or dashboard from the editor. He hits download where we give him the option to download a svg or png file. Each download will have a default file size and name (the title of the visualisation). Once he selects the file type the download will start automatically in the browser. Each downloaded file will hold 'Built with Akvo Lumen' in the bottom right corner. 

For downloading dashboards the workflow is the same. When downloading Jerome downloads the entire thing. The difference is in the file types: png or pdf. 

<img width="798" alt="screen shot 2018-07-09 at 16 08 35" src="https://user-images.githubusercontent.com/12456965/42455370-5a7a2330-8392-11e8-9a0b-2051b241cf53.png">

@Kiarii will share details on where the download option should live and how should it behave. 

## Issue of file size
We discussed how to handle the file size. We considered three alternatives: 
- provide a default size that take the width of an A4
- at download create a zip file with three files of different sizes 
- allow Jerome to set the size of the file. 

We have decided for the 1st option as it requires no user decisions. Once the 1st implementation is out we will gather some feedback to see if we need to change this approach.

**Comment by Kiarii** [comment]
![image](https://user-images.githubusercontent.com/12692444/42458125-efebe7b4-83a1-11e8-9506-7e9cbd38dd47.png)

**Comment by Kiarii** [comment]
for the dashboard we would have PNG & PDF options

**Comment by janagombitova** [comment]
@finnfiddle would it be possible to show also the **name/title** of the dashboards in the export? Right now you export what shows in the editor, so no name.

![testing issues](https://user-images.githubusercontent.com/12456965/46660807-2c276380-cbb8-11e8-88e4-a7be1ff21175.png)

When sharing the dashboard via the url the name shows as a title and I can expect users will want that in the exports too. Often the dashboard name serves indeed as a title and then the next item in the dashboard is text explaining the visualisations below.

**Comment by kardan** [comment]
Closing issue since we have the Epic issue (https://github.com/akvo/akvo-lumen/issues/2013)
