### ISSUE TITLE
Refer to user by name instead of email

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#955]
# Context
<img width="229" alt="screen shot 2017-07-13 at 12 41 25" src="https://user-images.githubusercontent.com/12692444/28161055-b84ca0c6-67ca-11e7-8af0-509dea4c14dd.png">

Do we have a scenario for which the user needs to see their email in the lib view or where they need to be referred to by email rather by name in Lumen? 
If not, or if only in edge cases, it might improve things for lumen to refer to the user by their name - it gives a similar feeling as when referred by name in real life

# proposal
- Use name: "First Last" in place of email
- Use user initials e.g. FL 
- Not sure what the limitation is around Keycloak but using a profile pic would even be better
- In their profile (keycloak) users can in any case view their email

**Comment by janagombitova** [comment]
Handled with the recent changes implemented with Auth0
