### ISSUE TITLE
Enforce uniqueness in titles

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#959]
# Context

It's possible to give the same title to several datasets - uniqueness of titles is not checked at the moment

<img width="857" alt="screen shot 2017-07-14 at 11 51 54" src="https://user-images.githubusercontent.com/21127166/28207889-8dba4450-688b-11e7-9b4b-99ec1710f412.png">

# Problem or idea
Since data in originally identical datasets can be transformed, we should enforce uniqueness of dataset titles. Otherwise, it can become confusing to differentiate between them when creating a visualisation. 

Since datasets can contain different information (e.g. one dataset was cleaned, the other one not), users should be able to differentiate between them.

The same goes for visualisation and dashboard titles

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
Ideally, we should add the uniqueness constraint at the database layer (as we now do for collections).

This means we need to resolve any existing conflicts before migrating
