### ISSUE TITLE
Empty values in Sort: Descending

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#960]
# Context

When I tried to sort a numeric column by descending order, I got empty values at the top

<img width="515" alt="screen shot 2017-07-14 at 12 23 41" src="https://user-images.githubusercontent.com/21127166/28208841-0b5cbc22-6890-11e7-99ad-792d91cdff4a.png">

# Problem or idea

It seems counter-intuitive to display empty values at the top when sorting in descending order.
I had quite a few empty values in the 'Enter year' column, so I had to scroll down a lot to see some values. 

My first impression was that sorting in descending order failed. But maybe it's subjective.

# Solution or next step
How could we solve it?

**Comment by jonase** [comment]
It's an easy change to make the empty values appear last instead :+1:

In sql, we'll just have to add `NULL LAST` as specified in https://www.postgresql.org/docs/current/static/queries-order.html
