### ISSUE TITLE
Overlapping strings in side panel

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#961]
# Context

Another example of UI difficulties with long strings..

<img width="527" alt="screen shot 2017-07-14 at 12 17 47" src="https://user-images.githubusercontent.com/21127166/28208928-85ea443c-6890-11e7-8a35-08a22bd50a40.png">

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by Kiarii** [comment]
<img width="835" alt="screen shot 2017-07-14 at 12 37 33" src="https://user-images.githubusercontent.com/12692444/28209180-149d364a-689a-11e7-8f55-52d579b35a9b.png">

**Comment by Kiarii** [comment]
@nadiagorchakova this also brings to mind the issue of renaming columns or using (flow) question ids as the column names - are we plan for these?

**Comment by nadiagorchakova** [comment]
Hi @Kiarii, yep it's already possible to rename a column in a dataset. As to question IDs, there is a related issue about giving user a choice btw using Flow question ID or the full survey question text: https://github.com/akvo/akvo-lumen/issues/964
