### ISSUE TITLE
Client interface for geo data transformation

### ISSUE THREAD

**Issue by peeb** [akvo/akvo-lumen#972]
# Context
Following on from #967.

# Problem or idea
Geo data transformation is available in the Lumen backend, but there is no client interface yet.

# Solution or next step
Add a client interface to enable generating geo data from user-selected latitude and longitude column data.

**Comment by peeb** [comment]
Per discussion with @gabemart - will new geometry PostgreGIS column *replace* existing lat/long columns simply add another column? i.e. do we preserve the original data columns from the import?

@gabemart @jonase @nadiagorchakova @Kiarii

**Comment by peeb** [comment]
New client type: `geoPoint` - a 2 member array `[ latitude, longitude ]`
Backend: a PostGIS geometry blob which can be reified using, for example, https://postgis.net/docs/ST_AsLatLonText.html

**Comment by nadiagorchakova** [comment]
Apart from user-facing geo data transformations, we should probably make changes to the map editor interface as well, where users currently have to select lat and long columns:

<img width="389" alt="screen shot 2017-07-25 at 11 47 24" src="https://user-images.githubusercontent.com/21127166/28566384-48584496-712f-11e7-9873-1fbe3177ae2a.png">

And re your question @peeb, I cannot think of any cases why we would preserve the 'old' lat/long columns... But I'm curious to hear what others say.

**Comment by peeb** [comment]
Thanks @nadiagorchakova 👍

**Comment by Kiarii** [comment]
imho we should drop the lat, lon cols and just have the geo-loc col instead, it simplifies the workflow for use cases involving geo-locs.. 

apart from the map, we also need to see how a geo-loc data type col header looks and determine the workflow for converting a lat + lon cols to geo-loc and respective options

**Comment by peeb** [comment]
Thanks @Kiarii

**Comment by Kiarii** [comment]
for the map editor, the geo-loc field may be presented as follows:
![image](https://user-images.githubusercontent.com/12692444/28778749-558cbf28-7609-11e7-8a50-7306f440bbdf.png)

to consider: is it agreed that we refer to the col as Geo-location?

**Comment by Kiarii** [comment]
@peeb, @jonase, @loicsans do we have answers to the following prerequisites for geo-col conversion (these are necessary to make the respective sketches): 

What would be the workflow for converting lat-lon to geo-loc?
1. Lumen does this auto-magically (requires recognizing cols at import, is it possible?)
2. User derives a geo-loc col; requires a specifying derive-able col types (e.g. derive col > geo-location)
3 both?

Error handling
1. what options are provided for empty, invalid values and error handling e.g. n/a, empty?
2. Would this transform be undoable?

Etc

**Comment by Kiarii** [comment]
If the dataset doesnt contain a geopoint column: 
+ disable dropdown
+ notify the user

![image](https://user-images.githubusercontent.com/12692444/28874147-3eefde9e-7799-11e7-8819-e6bacc1402c5.png)

nb: onwards "Geopoint" refers to the field/column with the geo-location data

**Comment by peeb** [comment]
I like this a lot ^^ @Kiarii

**Comment by jonase** [comment]
@Kiarii 

> Lumen does this auto-magically (requires recognizing cols at import, is it possible?) - This will happen for Flow data, but not for other types of import

For data sources where we know what properties (or columns) are geolocations we can do this when we initially import the data. So this is possible for Flow and probably impossible for generic csv files

> User derives a geo-loc col; requires a specifying derive-able col types (e.g. derive col > geo-location)

I'm not sure what the UI will look like but the user must somehow pick two numeric columns, which will be treated as latitude and longitude when calculating the new geo column

> what options are provided for empty, invalid values and error handling e.g. n/a, empty?

I think we can set the value to empty in this case (@peeb `NULL` at the db level). I don't think a "default value" makes sense for this transformation.

> Would this transform be undoable

All transformations are automatically undoable (unless there are implementation bugs of course).

**Comment by peeb** [comment]
See #1047 for work on refinements to this UI/UX.

Closing this issue to continue work there.
