### ISSUE TITLE
Date specificity, aggregation and display

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-lumen#979]
# Context
"Date" is an important data type that is used throughout Lumen

# Problem or idea
Our current handling of dates is limited, too tightly coupled with how we handle dates technically, and not very user friendly.

We store dates as second-precise values.

Currently, we also present and display dates *to the user* as second-precise values, which is confusing and hard to work with in many circumstances (e.g. #723).

Here are some common tasks that are hard to do in Lumen currently with dates:

* Aggregate on a date column by days, weeks, months, quarters or years. (This will be hard to get right because of time zones etc. but it seems quite important). An example of this might be a visualisation of "mean doctor visits per week" or "max fluoride ppm by month" etc

* In visualisations that operate on unique values in a column (e.g. pivot table), the user might want to aggregate on a date column and have the "unique values" be day, week, month, etc

* Choose how dates are displayed in the dataset editor or in a published visualisation (e.g. "13/01/2005" or "January 2005" or "Week 2, 2005" or "Q1 2005" etc etc

# Solution or next step
I think the solution needs considerable thought and design. We need to decide I) how and where the user chooses how dates are cleaned, formatted and aggregated, ii) how and where the system can best do this work, and iii) to what extent the system can aid the user, suggest common operations etc

As a first step I think we need to gather more data on the needs of the users in regards to dates. The examples I have given above are meant only to illustrate part of the problem.

@Kiarii @loicsans @nadiagorchakova thoughts?

**Comment by gabemart** [comment]
From @bjelkeman in #723 

# Context
Date on the X axis in a area chart (probably others too) are displayed with precision to the second.

# Problem or idea
It is very rare that you want dates displayed with that precision. 
Example: https://demo.akvolumen.org/visualisation/59145131-82e9-4c86-b024-bf47a09b7e84
https://demo.akvolumen.org/s/VrZLYMlHPiY

# Solution or next step
You want a date display to be configurable, to at least: YYYY, YYYY-MM, YYYY-MMM, YYYY-MMM-DD

**Comment by gabemart** [comment]
From @Kiarii in #860 

# Context
Months are easily identified with their text abbreviation Jan, Feb, etc. When dates are presented as 2017 03 01 it becomes tricky to id the month from the day. Additionally the date abbreviations 1st, 2nd, 3rd, are unnecessary; 2017 Mar 01, or 2017 03 Jan is explicit by itself. 

- Lib: Jan 3rd 2017
- Dashboard: 2017-06-01

# Proposal 
Id and unify all date instance where used in lumen to: 
- Jan 03 2017

This also implies the same in datasets: Jan 03 2017 is less confusing than 01 03 2017; which would have different interpretations depending on Jerome's locale or computer set region

**Comment by loicsans** [comment]
One problem with that is the translation. In French you do not cut off Months names, so you can end up with truncated dates.
