### ISSUE TITLE
Support (suggestive) typing in col picker field in the viz editor

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#983]
# Context
For datasets with many cols, picking a col of interest requires scrolling effort & time; as there is no alternative or shortcut to picking a col of interest
<img width="443" alt="screen shot 2017-07-31 at 15 10 47" src="https://user-images.githubusercontent.com/12692444/28777164-b645f28c-7602-11e7-94fd-0f0a72ee2de6.png">

# idea: reduce time & effort to col selection 
+ by enabling suggestive typing into the field
+ one user has also suggested that there be a possibility to order the cols alphabetically so that it is easier to scan col names

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
To keep this change as small as possible the expectation is: 
* [ ] allow suggestive typing in the column picker in all visualisation editors 
* [ ] allow suggestive typing for dataset picker in all visualisation editors 

Note: if this change does not trickle down to all column pickers (also in the Transformations) then create a separate issue to handle those.

**Comment by tangrammer** [comment]
Indeed this is the purpose of this ready to review PR => https://github.com/akvo/akvo-lumen/pull/2454 😄

**Comment by janagombitova** [comment]
@muloem once these changes are done in and production make sure to stress it in the Data platform updates page as it is a seemingly small change but it makes a world of a difference so we should shout it out as loud as we can ;)
