### ISSUE TITLE
Show visualizations' mouseover tips on dashboard

### ISSUE THREAD

**Issue by Kiarii** [akvo/akvo-lumen#985]
# Context | idea
In the language of the dashboard editor - WYSIWYG - we need to show visualizations' mouseover tips so users have a good feel of the functionality their dashboards will support when published

# Solution or next step
How could we solve it?

**Comment by janagombitova** [comment]
Can you please specify this issue @Kiarii or close it?

**Comment by Kiarii** [comment]
Wow, if I remember right, this was about providing the mouseover functionality on visualilzations in a dashboard.. so the editor can actually see how they appear on a published dashboard
