### ISSUE TITLE
A few ideas on improving CSV uploads

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-lumen#990]
# Context
Many csv files that users try to upload to lumen are "almost" correct. Could we try to support non-valid csv files in some cases? I believe slightly broken csv files will be a common support request. 

# Problem or idea
From what I've seen lately:

* The file contains blank lines. Either in the beginning of the file, at the end or in the middle
* The file is not comma separated. Common separators that we should support are tabs and semicolons. I'm not sure if we can safely auto-detect the separator or if the user needs to select it. I think often the user will not know what the separator is, so perhaps one approach would be to try to auto-detect if the user does not explicitly set the separator when importing.

**Comment by jonase** [comment]
@nadiagorchakova What are you're thoughts on this?

**Comment by nadiagorchakova** [comment]
@jonase I like the idea of improving user experience for csv file upload.
I've noticed that quite a few people from the partner team (and probably some partners using Lumen as well) have hard time understanding what's wrong with their csv files. Often it seems that Windows running on a Mac is a culprit. Often indeed it has a other separator than a comma.. 

If we decide to loosen our criteria for csv file upload, perhpas we need to enable deletion of rows first? To deal with blank lines and other messy rows. What do you think?

**Comment by nadiagorchakova** [comment]
I suggest to reopen this issue as a few partners continue to experience problems with csv file import. Quite often partners struggle with separators other than ',' (e.g. ;) and they don't understand what went wrong

**Comment by LarsSjogreen** [comment]
I found a good heuristic technique for auto-detection of CSV separation character.
The idea is to count the number of appearances of a separation character per row. The one that has the same number of appearances on every row is the correct one. Of course, you will also have to be careful with quoted and escaped characters and disregard these from the count.

Filtering a file for extra row breaks should be trivial.

**Comment by janagombitova** [comment]
Created via Reamaze:

Link: /admin/conversations/akvolumen-support-request-number-199845-from-geert-at-akvo-dot-org
