### ISSUE TITLE
Document decisions on Stackdriver as monitoring solution

### ISSUE THREAD

**Issue by LarsSjogreen** [akvo/akvo-lumen#992]
# Context
Why do we add this issue?

After a discussion a preliminary decision was made to use Stackdriver as a monitoring back end for Windshaft. There are a few prerequisites for this and some context that needs to be documented and reviewed before the decision can be made final.

# Problem or idea
What is the cause?
Care needs  to be taken for us to avoid vendor lock in, inadvertent sharing of any customer tool usage data to a vendor's system and to make the solution possible to switch off or exchange for another one when the need arises.

# Solution or next step
How could we solve it?
Lars writes ADR 007 documenting the decision and asks for review.

**Comment by janagombitova** [comment]
@kardan What should we do about this one?
