### ISSUE TITLE
double scroll bar appearing on windows.

### ISSUE THREAD

**Issue by loicsans** [akvo/akvo-lumen#999]
# Context
Why do we add this issue?
https://files.slack.com/files-pri/T044V5F9W-F6MQ3AV8X/pasted_image_at_2017_08_10_10_06_am.png

# Problem or idea
What is the cause?

# Solution or next step
How could we solve it?

**Comment by iperdomo** [comment]
Hi,
The double scroll bars are present again Firefox on Linux and Windows



![2019-10-08_1277x384_scrot](https://user-images.githubusercontent.com/178474/66390141-53329400-e9ca-11e9-8db5-0d3b072d49f2.png)

![2019-10-08_1917x405_scrot](https://user-images.githubusercontent.com/178474/66390162-5cbbfc00-e9ca-11e9-92b1-6455ee7929ad.png)
